### ISSUE TITLE
Generated dashboards throwing undefined method permit error

### ISSUE THREAD

**Issue by timsatterfield** [thoughtbot/administrate#1011]
Ver: 0.8.1
Rails ver: 4.2.8
Ruby ver: 2.4.1

Seeing this error when rendering generated dashboards.  Somewhere a strong_params object is expected, but just a hash is present.  Or at least something that responds to `:permit`.

```
ActionView::Template::Error (undefined method `permit' for {"controller"=>"admin/customer_configs", "action"=>"index"}:Hash):
    16:                             resource: resource_name) %>"
    17:          value="<%= search_term %>">
    18: 
    19:   <%= link_to clear_search_params, class: "search__clear-link" do %>
    20:     <svg class="search__clear-icon" role="img">
    21:       <title><%= t("administrate.search.clear") %></title>
    22:       <use xlink:href="#icon-cancel" />
```

There is some inconstancies: some dashboards throw this error as-is, but others work as-is until the attributes lists are customized.

**Comment by timsatterfield** [comment]
The offending line is here
https://github.com/thoughtbot/administrate/blob/master/app/helpers/administrate/application_helper.rb#L39

You can workaround this issue by generating and editing /views/admin/application_search.html.erb to omit this call.

**Comment by nickcharlton** [comment]
Oh that's a fun one.

You mention that some dashboards throw this, but others don't. Would you be able to provide an example where this is happening and one where it isn't? It'll help dig into it and work out what a long-term solution could be.

**Comment by timsatterfield** [comment]
I dont have a ready example I can post somewhere as its biz specific.  The call to `params.except(:search, :page)` is returning an object that does not respond to `permit`.  If you can think of why that could be, then the solution might be obvious.

**Comment by nickcharlton** [comment]
I'm afraid I don't have much of a suggestion without an example to work with. 

I'm going to close this for now, but if you're able to provide that then I'd be more than happy to take a look.
