### ISSUE TITLE
List plugins in repo?

### ISSUE THREAD

**Issue by coreyward** [thoughtbot/administrate#1015]
It would be really useful if this repo had either a link to a list of plugins or had a `PLUGINS.md` list of some kind.

I had no idea that Administrate had a bunch of plugins, much less [officially supported ones](https://github.com/thoughtbot/administrate-field-image). I've been building my own fields for most things. I only now know because I stumbled across references in other Issues while searching for something unrelated.

**Comment by nickcharlton** [comment]
I'd absolutely love to see this!

I personally find them by doing a dependency look up on Ruby Gems: https://rubygems.org/gems/administrate/reverse_dependencies

Do you think you'd be able to contribute a PR which added this to the `/docs`?

**Comment by coreyward** [comment]
I had no idea there was a reverse dependency lookup! That's awesome. I'll put together a PR.

**Comment by pmackay** [comment]
Is there a reason this project doesnt have a wiki? Would that be a useful place for a list of plugins @coreyward?

**Comment by nickcharlton** [comment]
No, not really. It might be a better place for plugins, as people wouldn't need to open up a PR each time (to add or remove). I can add this now, and look at adding a few later in the week!

**Comment by nickcharlton** [comment]
I've created this page: https://github.com/thoughtbot/administrate/wiki/List-of-Plugins

I don't have a strong opinion on how it should be formatted, but I'm expecting that we might want to end up having something like a table in the future (e.g.: https://github.com/omniauth/omniauth/wiki/List-of-Strategies).

I'm going to close this for now, as this feels like a good way of solving this problem.
