### ISSUE TITLE
Running the install generator after initial install should pick up new models.

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#1019]
Currently, when you run `rails g administrate:install` after administrate has already been installed, new models won't be picked up because the routes generator doesn't create the resources necessary.

The [install generator][2] protects against running the routes twice, because [the routes generator][1] blindly re-adds the full `:admin` namespace of models when it doesn't need to.

We should be able to run `administrate:install` multiple times, in a way that picks up new models without breaking the existing functionality.

This originally comes from #1003 where the documentation (addressed in #1018) suggested you could rerun it multiple times. And is related to #720, which describes the dashboard generator not updating routes when called directly.

[1]: https://github.com/thoughtbot/administrate/blob/967506a3694037b2451d67f4efa6c73ef7c2f2a0/lib/generators/administrate/routes/routes_generator.rb#L11
[2]: https://github.com/thoughtbot/administrate/blob/967506a3694037b2451d67f4efa6c73ef7c2f2a0/lib/generators/administrate/install/install_generator.rb#L12

**Comment by purinkle** [comment]
@nickcharlton, is this still an issue for you?
