### ISSUE TITLE
with_options for Field::BelongsTo?

### ISSUE THREAD

**Issue by alookatommorow** [thoughtbot/administrate#1023]
Thank you for the great work on this gem!

I was looking at these [administrate docs](https://github.com/thoughtbot/administrate/blob/master/docs/customizing_dashboards.md) and they say you can order the dropdown field on a `Field::BelongsTo` using the `with_options` method and and pass it `:order`. However, [these docs](https://administrate-prototype.herokuapp.com/customizing_dashboards) don't say anything about it. I am attempting to do this in an application of mine like so:

```
#random_model_dashboard.rb

ATTRIBUTE_TYPES = {
  user: Field::BelongsTo.with_options(order: 'id'),
  ...
}
```

This should order the users by id on the user dropdown on the new `random_model` form. But it doesn't work. I've tried all kinds of syntax varieties. Is this still supported? Because who wants to sift through a list of hundreds of user IDs to find the right one?

I've looked through the code base and everything suggests that this should work. What am I doing wrong?

**Comment by nickcharlton** [comment]
Hi @alookatommorow!

The difference in the docs is that the hosted version is pinned against the [last release which was 0.8.1](https://github.com/thoughtbot/administrate/releases/tag/v0.8.1). This functionality was introduced in #939, which hasn't yet gone out.

If you're comfortable with it, I'd recommend [pinning against current master (or something similar)](https://bundler.io/v1.16/guides/git.html):

```ruby
gem "administrate", github: "thoughtbot/administrate"
```

I'd like to get this out in a release soon, but I can't yet say when that might be.
