### ISSUE TITLE
Filters in search?

### ISSUE THREAD

**Issue by bvv218** [thoughtbot/administrate#1024]
I am new to administrate and I am wondering if there is a way to set up filters in search. For example, I need to filter by two columns where one boolean is true and one is false. Is it possible to set up with administrate?

**Comment by nickcharlton** [comment]
There have been a few search suggestions and/or PRs that I'm aware of, but I don't know which of those would help you do what you're trying to achieve. In general, I'd punted complex search until post 1.0 (e.g.: #947).

It sounds to me like you'd need some sort of predicate-based searching for this? e.g.:

```
bob admin=false expired_member=true
```

…where `bob` is a search string, `admin` and `expired_member` boolean fields.

Is that what you're thinking of?

**Comment by asecondwill** [comment]
@nickcharlton - not sure what the OP was thinking but for me, being able to add fields in the search interface so users can explicitly tick for expired members,  choose a category etc.  I guess a bit like active admins sidebar.  or is that a no no?  Search in a single text field is definitely way cooler, but would need good ux hints to enable non devs to be able to work it.

**Comment by nickcharlton** [comment]
Yeah, something like that might be nice.

My thinking is that a single search bar allows us to be much less specific with regards to the data, but you're right, it's a more difficult UX problem.

**Comment by pablobm** [comment]
I'm going to close this as it hasn't had activity in a long time, and the topic of Search is one that I think is particularly tricky, and for which I provide at opinion at: https://github.com/thoughtbot/administrate/pull/1218#issuecomment-821292428
