### ISSUE TITLE
Adding a newly-migrated attribute to the dashboard

### ISSUE THREAD

**Issue by vcavallo** [thoughtbot/administrate#1025]
Apologies if this is explained somewhere. I googled a bunch, read through the docs and searched open & closed issues and didn't see anything...

I've already installed Administrate and everything is working great. I've now added an attribute to one of my models and am looking for the best way to include this field on administrate's dashboards. I know I can add it in manually in the Dashboard file, but I opted to re-run `rails g administrate:install` - even though it was a bit cumbersome to skip/diff/Y/N various files.

What is the recommended way to do this?
Thanks!

**Comment by nickcharlton** [comment]
Hi @vcavallo!

I think you could probably do either of what you'd suggested. Personally, I'd probably lean towards adding it manually to the Dashboard (such as in a PR which introduced this new attribute).

It'd be great to be able to pick them up automatically with a generator, but this is pretty difficult to do.

To help others in future, what do you think about adding a mention of this to the docs?

**Comment by vcavallo** [comment]
@nickcharlton ! 

How does this look? https://github.com/thoughtbot/administrate/pull/1040

**Comment by nickcharlton** [comment]
Closing as we solved this!
