### ISSUE TITLE
DRY on admin_user_dashboard.rb

### ISSUE THREAD

**Issue by ldco2016** [thoughtbot/administrate#1030]
Greetings, 

I have been tinkering with your code to make it work on an application I am working on. I have had to do something like this:

require "administrate/base_dashboard"

```
class AdminUserDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    posts: Field::HasMany.with_options(searchable: false),
    id: Field::Number.with_options(searchable: false),
    email: Field::String.with_options(searchable: true),
    password: Field::String.with_options(searchable: false),
    sign_in_count: Field::Number.with_options(searchable: false),
    current_sign_in_at: Field::DateTime.with_options(searchable: false),
    last_sign_in_at: Field::DateTime.with_options(searchable: false),
    current_sign_in_ip: Field::String.with_options(searchable: false),
    last_sign_in_ip: Field::String.with_options(searchable: false),
    first_name: Field::String.with_options(searchable: false),
    last_name: Field::String.with_options(searchable: false),
    created_at: Field::DateTime.with_options(searchable: false),
    updated_at: Field::DateTime.with_options(searchable: false),
    type: Field::String.with_options(searchable: false),
  }.freeze
```
in order to get a search engine that functions properly. At the risk of stating the obvious there is a lot of duplicate code here.

I was thinking perhaps you guys can do something like this in a future release:

```
SEARCH_ATTRIBUTES = [
     :email,
     :id
]
```
and this would override all of that code I have above. Technically, I could just do that for myself, but right now I do not have the time.

**Comment by nickcharlton** [comment]
Hi @ldco2016!

Yep, I definitely agree! There's a lot going on here.

There's a fun balance here between ensuring that we're able to add additional features (the original design wouldn't have had `with_options`, for example!) but also ensure it's easy for others to expand on and understand.

I'd be more than happy to see an example of how this might be better. If you'd be able to show an example of how this might be improved in a PR, I'd be more than happy to look at it!
