### ISSUE TITLE
HasMany index partial passes an already-pluralized field name to pluralize helper

### ISSUE THREAD

**Issue by tbroadley** [thoughtbot/administrate#1042]
[The HasMany index partial](https://github.com/thoughtbot/administrate/blob/6661889711edd688c8768e48602fa4a25b82d7bf/app/views/fields/has_many/_index.html.erb) includes one line of code:

```erb
<%= pluralize(field.data.size, field.attribute.to_s.humanize.downcase) %>
```

In this partial, `field` is an instance of `Administrate::Field::HasMany`, so `field.attribute` returns the pluralized name of a model, e.g. "teams". When `field.data.size == 1`, the partial renders `pluralize(1, 'teams')` which equals `'1 teams'`, instead of `'1 team'` which is what I would expect.

To fix this, I would suggest using the following as the body of the partial instead:

```erb
<%= pluralize(field.data.size, field.attribute.to_s.humanize.downcase.singularize) %>
```

**Comment by nickcharlton** [comment]
Hi @tbroadley!

Thanks for opening this issue. Would you be able to open a PR making the change you suggested?

**Comment by tbroadley** [comment]
@nickcharlton Sure, I can do that!
