### ISSUE TITLE
Decorate model instance with custom attributes in administration?

### ISSUE THREAD

**Issue by schovi** [thoughtbot/administrate#1044]
Hi,

Is there any way, how to add custom attributes to model in Administrate scoped source code? What I mean is that I dont want to add methods to model just because I want them in administration. I want to somehow decorate model instance just for Administration purposes.

I know how to render already existing methods, but I dont know if there is any way to declare them just in scope of `class MyModelDashboard < Administrate::BaseDashboard`.

Any suggestions?

**Comment by pustomytnyk** [comment]
@schovi Hi, maybe this branch #843 would suit your need.

**Comment by nickcharlton** [comment]
I'm going to close this as I can see you'd commented on #843. I hope we'll get that merged in soon!
