### ISSUE TITLE
Custom /admin route?

### ISSUE THREAD

**Issue by Corstiaan84** [thoughtbot/administrate#1047]
Hi there,

How do I set a custom route for the admin pages instead of `/admin`?

**Comment by nickcharlton** [comment]
HI @Corstiaan84!

It's not gone out in a release yet, but #956 adds an option for changing the namespace which might help you here.

**Comment by mactkg** [comment]
this issue can be closed. @nickcharlton 

Finally we can set a custom route using `--namespace` option.
