### ISSUE TITLE
Eager load: uninitialized constant Administrate::Punditize::Pundit (NameError)

### ISSUE THREAD

**Issue by kesha-antonov** [thoughtbot/administrate#1048]
Hello!

In production (which eager load classes) I see this error:
```
uninitialized constant Administrate::Punditize::Pundit (NameError)
```

How to fix it?

Thanks!

**Comment by nickcharlton** [comment]
Ah, that's interesting!

This is potentially related to us merging #971. Are you installing from `master`?

**Comment by kesha-antonov** [comment]
Yes, from master @nickcharlton

**Comment by kesha-antonov** [comment]
As a temp solution:
```
gem 'pundit', '~> 1.1.0'
```

**Comment by GeekOnCoffee** [comment]
We've also run into this (in Production only). Confirmed that adding the gem to the Gemfile works as a temp solution.

**Comment by nickcharlton** [comment]
I've opened #1068 as a potential solution here.

/cc @pedantic-git

**Comment by pedantic-git** [comment]
Sorry for this! I genuinely didn't think about eager loading in production. Nick's fix looks perfect to me.

**Comment by nickcharlton** [comment]
No worries! I'd not considered it either. I'm going to merge the other, which'll close this.

**Comment by alex-benoit** [comment]
I just encountered this issue...
