### ISSUE TITLE
Custom controller causes ActionController::UrlGenerationError in Admin::Users#edit

### ISSUE THREAD

**Issue by MiralDesai** [thoughtbot/administrate#1049]
My `routes.rb`:

    namespace :admin do
        resources :users do
          resource :user_times # not a model or administrate dashboard
        end
    end

I have a dashboard for users, under the admin namespace as you do, but a user can have user_times, which does not have a model, but requires a controller to input data via a form and save the data on the user.

So I've created the views for that(custom views not in admin folder, no dashboard), created the controller, and I'm getting the error below. It seems everything under the admin namespace requires a model and a dashboard? Is this correct or am I doing doing something wrong?

First I had an error in the `_navgiation.html.erb partial`, but I generated that and put in my own fix:

`<% next if resource.resource == 'user_times' %>`

That at least let me able to see the rest of my dashboard under /admin. So now when I try and edit a User, where I have added a link to `new_admin_users_user_times_path` I get the error below:

`
ActionController::UrlGenerationError in Admin::Users#edit
No route matches {:action=>"new", :controller=>"admin/user_times", :id=>"1"}, missing required keys: [:user_id]
`

Is it possible for me to namespace user_times under users without having to involve administrate? If so, what have I done wrong.

Thanks.

**Comment by G-Rath** [comment]
@MiralDesai Given that you closed this issue, did you ever get this resolved? I'm interested in doing the same thing

**Comment by MiralDesai** [comment]
It's been about 6 months since i've worked on the project that needed this or administrate. From what I remember I think the generated the users show page, and added a custom button which routed to my custom form, and then went back to the user show page on save, with the data shown there.
