### ISSUE TITLE
Field::BelongsTo show link issue

### ISSUE THREAD

**Issue by DevinFrenze** [thoughtbot/administrate#1050]
the `_show` view for the BelongsTo field (https://github.com/thoughtbot/administrate/blob/master/app/views/fields/belongs_to/_show.html.erb) creates the `link_to` based on `valid_action?(:show, field.attribute)`. this means that if the attribute name is different from the class name, a link will not be created (i think).

in my own project, i worked around this by making a custom BelongsToField using `BelongsToField.with_options(class_name: CLASS)` in the dashboard, making `associated_class_name` a public method, and then using `valid_action?(:show, field.associated_class_name)` in the `_show` view. but that might be the best solution for the project as a whole.

ps happy to help if i can, i really appreciate the administrate tool and would love to give back

**Comment by nickcharlton** [comment]
Hi @DevinFrenze!

If you feel like you'd be able to make a PR that'd help others in the same situation, I'd very much appreciate it!

**Comment by DevinFrenze** [comment]
hey @nickcharlton, working on it !

**Comment by DevinFrenze** [comment]
@nickcharlton can you check out the above PR ?

**Comment by pablobm** [comment]
Looks like this is fixed? Let us know if not!
