### ISSUE TITLE
invalid date error

### ISSUE THREAD

**Issue by ldco2016** [thoughtbot/administrate#1058]
I have been working on developing a Ruby on Rails application utilizing the Administrate gem for an admin section with a couple of links to users, posts and admin within the admin section: `localhost:3000/admin`

However, when I go to posts `localhost:3000/admin/posts` I get the following error:
![](https://i.stack.imgur.com/tKBAJ.png)
 I am unsure what went wrong here

If I look at the trace it's saying that the issue is in the administrate code. It sounds like there is data that isn't in a date format, so where Adminstrate tries to parse data like a date, it breaks. And if I run the Ruby code in the Rails console, I would get the same error. So it seems like its a data related issue.

I don't think I am storing strings as dates. So I queried the records in the rails console that shows me how the data is being stored.

```
Running via Spring preloader in process 11232
Loading development environment (Rails 4.2.10)
2.3.3 :001 > Post.all
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.
You should use PG::Connection, PG::Result, and PG::Error instead, respectively.
Called from /Users/danale/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
  Post Load (1.1ms)  SELECT "posts".* FROM "posts"
 => #<ActiveRecord::Relation [#<Post id: 2, date: "2017-12-02", rationale: "1 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 3, date: "2017-12-02", rationale: "2 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 4, date: "2017-12-02", rationale: "3 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 5, date: "2017-12-02", rationale: "4 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 6, date: "2017-12-02", rationale: "5 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 7, date: "2017-12-02", rationale: "6 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 8, date: "2017-12-02", rationale: "7 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 9, date: "2017-12-02", rationale: "8 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 10, date: "2017-12-02", rationale: "9 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, #<Post id: 11, date: "2017-12-02", rationale: "10 rationale content", created_at: "2017-12-02 18:10:27", updated_at: "2017-12-02 18:10:27", user_id: 1, status: 0>, ...]>
```

So it looks like I am storing the dates as string, because that is what outputted above. How would I correct this became my next question.

But it cannot be that I would have to redo the entire column data type to use the date datatype because I am already using the date datatype. Here is my schema.rb file:

```
ActiveRecord::Schema.define(version: 20171202011809) do
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

create_table "posts", force: :cascade do |t|
    t.date     "date"
    t.text     "rationale"
    t.datetime "created_at",             null: false
    t.datetime "updated_at",             null: false
    t.integer  "user_id"
    t.integer  "status",     default: 0
  end
  add_index "posts", ["user_id"], name: "index_posts_on_user_id", using: :btree
  create_table "users", force: :cascade do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "type"
    t.datetime "created_at",                          null: false
    t.datetime "updated_at",                          null: false
  end
  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree
  add_foreign_key "posts", "users"
end
```

The error is saying I have `"12/13/2012".to_date` somewhere in my code. I know for sure I did not add this myself. So I am wondering if this is an issue with Administrate gem or if it could be a typo somewhere. It sure would help to know where Rails is seeing this: `"12/13/2012".to_date`

My sample data was created via seeds.rb:

```
100.times do |post|
  Post.create!(date: Date.today, rationale: "#{post} rationale content", user_id: @user.id)
end

puts "100 Posts have been created"
```

Also, I don't know if this helps you help me, but I only have this problem when I am signed in as `AdminUser` and I go to `localhost:3000/admin/posts`

I don't get that error when I sign in as `@user` and I go to `http://localhost:3000/posts`

Someone else had opened an issue with the same exact problem, but they later closed it saying that it was a typo somewhere, unfortunately, he did not provide details that could help me and avoid having yet another person open the same issue. So any help would be appreciated.

**Comment by robinvdijk** [comment]
The error doesn't say you have `"12/13/2012".to_date` in your code, but I think it is showing the comment within `conversion.rb`, as seen [here](https://github.com/rails/rails/blob/bb075e3839d9eea2be5cb0cbed50dafa2c14bb37/activesupport/lib/active_support/core_ext/string/conversions.rb#L42).

**Comment by nickcharlton** [comment]
Hi @ldco2016!

It's been a while since you'd originally opened this issue. Is this still a problem?

If it is, would you be able to provide an example app we could this happen?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time since the last response; if you're still facing this then please re-open!
