### ISSUE TITLE
Access Method on model

### ISSUE THREAD

**Issue by udahari** [thoughtbot/administrate#1062]
Hello, I'm new with this gems, can I access method on model like this method on model user ??

```ruby
class User < ApplicationRecord
  def verify_pin(entered_pin)
    update(phone_verified: true) if self.pin == entered_pin
  end

  def is_active_host
    !self.merchant_id.blank?
  end
end
```

**Comment by nickcharlton** [comment]
At which point are you trying to access the method? Is it when you're trying to update a record?

**Comment by nickcharlton** [comment]
#706 should provide a solution to this problem, so I'm going to close this. Please open another issue if this isn't the case!
