### ISSUE TITLE
rails generate administrate:install fails

### ISSUE THREAD

**Issue by bitcoiners** [thoughtbot/administrate#1071]
I created a rails app with suspenders template
https://github.com/thoughtbot/suspenders
and tried to add administrate but it fails

```
rails generate administrate:install

WARNING: Unable to generate a dashboard for Delayed::Backend::ActiveRecord::Job.
         Administrate does not yet support namespaced models.
WARNING: Unable to generate a dashboard for Delayed::Backend::ActiveRecord::Job.
         It is not connected to a database table.
         Make sure your database migrations are up to date.
```

**Comment by nickcharlton** [comment]
Hi @bitcoiners!

Does your app have models apart from `Delayed::Backend::ActiveRecord::Job`?

**Comment by bitcoiners** [comment]
I have not created any models yet, just generated new app from that template.

**Comment by nickcharlton** [comment]
That'll be why. The generator can't create any (useful) Dashboards without having a model in place.

Ideally, it should be exiting with an error or warning, but that's not currently implemented.

**Comment by nickcharlton** [comment]
I'm going to close this for now, but if you have any other issues please open new issues!
