### ISSUE TITLE
rails generate administrate:install --> const_get': uninitialized constant Welcome (NameError)

### ISSUE THREAD

**Issue by ck2000** [thoughtbot/administrate#1080]
Having trouble installing administrate

rails generate administrate:install
      create  app/controllers/admin/application_controller.rb
 ....rvm/gems/ruby-2.3.1/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant Welcome (NameError)
from .../.rvm/gems/ruby-2.3.1/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `klass'
	from ....rvm/gems/ruby-2.3.1/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
	from .../.rvm/gems/ruby-2.3.1/gems/administrate-0.8.1/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
	from .../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from .../.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
     ...

I have removed the fullpath of my hdd.

**Comment by nickcharlton** [comment]
Administrate tries to build dashboards according to the models you have defined. In previous cases where we've seen things like this, it's a problem with your models.

Could you show what those look like? Or, even better, show an example which I could try out where this fails?

**Comment by ragesoss** [comment]
I got a similar error, `uninitialized constant CoursesUser (NameError)`.

Here's the app: https://github.com/WikiEducationFoundation/WikiEduDashboard

The actual model is `CoursesUsers`, but it's trying to create `courses_user_dashboard.rb`. Any hints for working around that plural model name?

**Comment by yiyuanc** [comment]
@ck2000 hi, how have you solved this? thanks a lot!

**Comment by ck2000** [comment]
I decided not to use this gem...

**Comment by maokomioko** [comment]
Ended up with the same problem. 
A solution would be to write a custom inflection:
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.singular 'brfdata_file_logs', 'brfdata_file_log'
end
```

**Comment by nickcharlton** [comment]
The right solution here is custom inflections, which explains what you were seeing. There's other open issues addressing this so I'm going to close this.
