### ISSUE TITLE
dashboard for model inside a Gem

### ISSUE THREAD

**Issue by sloppycoder** [thoughtbot/administrate#1082]
Is there anyway to generate a dashboard for some model that is packaged inside a third party Gem?

**Comment by nickcharlton** [comment]
Are you thinking about using models inside another Rails Engine?

I can't think of a reason why that wouldn't work, but I don't think administrate's generators would be able to see that they existed. Most likely, I'd look at creating the dashboard manually.

Does that help?

**Comment by pablobm** [comment]
See related: https://github.com/thoughtbot/administrate/issues/1128

**Comment by pablobm** [comment]
Closed due to lack of activity. Let us know if we are missing something!

**Comment by pablobm** [comment]
Closed as I think the original question is answered. Let us know if not!
