### ISSUE TITLE
Add a way to show JSON column 

### ISSUE THREAD

**Issue by ecleel** [thoughtbot/administrate#1084]
It would be great to be able to show simple JSON column (one level of JSON) to represent in a small table. 
<img width="753" alt="screen shot 2018-02-03 at 20 04 39" src="https://user-images.githubusercontent.com/25447/35769531-8cf656d4-091d-11e8-9f8c-b2267ce8a9e2.png">

**Comment by ecleel** [comment]
I'll close the issue. I used [custom field](https://administrate-prototype.herokuapp.com/adding_custom_field_types) and it worked perfectly. It might be good Idea to have global JSON field but it's hard to figure out with all JSON structures (array of hashes, plain hash)
<img width="1279" alt="screen shot 2018-02-03 at 21 01 51" src="https://user-images.githubusercontent.com/25447/35770041-80342798-0925-11e8-801e-6767cb258996.png">

**Comment by volkov-sergey** [comment]
For all, who find this issue, here is a gem to display your json like at https://jsoneditoronline.org

https://github.com/codica2/administrate-field-jsonb

![show](https://user-images.githubusercontent.com/16163520/65867058-76cc5d80-e37e-11e9-9d0c-88d79ab2217b.png)
