### ISSUE TITLE
support globalize gem?

### ISSUE THREAD

**Issue by arlydemo** [thoughtbot/administrate#1086]
It will have the error when rails generate administrate:install :
Unable to generate a dashboard for Product::HABTM_Taxons

**Comment by nickcharlton** [comment]
Hi @arlydemo!

Support for `globalize` is something that's come up previously (in #423), but isn't something we've done anything more significant about yet. Looking at that PR, it looks like you'd be missing some translations anyway.

Could you provide some more detail on the error you're seeing?

**Comment by bikramwp** [comment]
Ping @arlydemo

**Comment by nickcharlton** [comment]
I'm going to close this as the original commentator hasn't replied in quite a while.

Please open another issue if there's a specific error you're seeing.

**Comment by dagumak** [comment]
Just wanted to see if there were any additional plans to support this

**Comment by sedubois** [comment]
I got Administrate + Globalize to agree with each other using the following incantations:
https://github.com/thoughtbot/administrate/issues/1291#issuecomment-545054789
