### ISSUE TITLE
Adminstrate with devise_invitable (Not an issue, Just a query)

### ISSUE THREAD

**Issue by rafayet-monon** [thoughtbot/administrate#1088]
I have two devise model 'admin_user' and 'user'. And I want to use devise invitable to invite 'user' by 'admin_user'. Have been struggling with this for some time. How that can be done?

**Comment by nickcharlton** [comment]
Would you be able to provide a more detailed example? It'll help me point you in the right direction!

**Comment by rafayet-monon** [comment]
@nickcharlton Sorry, I couldn't prepare a example for you as I don't know how it can be done. But I found this gist
[](https://gist.github.com/mikeatlas/5628317) where it shows how it can be done with active admin. Will this be helpful?

**Comment by FanaHOVA** [comment]
@rafayet-monon I set this up today for my app. Overriding UsersController#create should do the trick for you too:

```
def create
   User.invite!(resource_params)
   redirect_to admin_users_path
end
```

**Comment by rafayet-monon** [comment]
@FanaHOVA Thanks a lot for your time and it worked :100:
