### ISSUE TITLE
PG::UndefinedFunction: ERROR:  function lower(date) does not exist LINE 1: SELECT  "posts".* FROM "posts" WHERE (lower("posts"."date") ...

### ISSUE THREAD

**Issue by KickButtowski80** [thoughtbot/administrate#1089]
date: Field::DateTime.with_options(searchable: true ), and did not work and throw the error.
After that,I was told to changed it to
date: Field::Date.with_options(searchable: false),
yet the same error has inspire again
Could anyone help me ?
my code snippet: 
```
  ATTRIBUTE_TYPES = {
    user: Field::BelongsTo.with_options(searchable: false),
    id: Field::Number.with_options(searchable: false),
    date: Field::Text.with_options(searchable: true),<-------
    rationale: Field::Text.with_options(searchable: false),
    created_at: Field::DateTime.with_options(searchable: false),
    updated_at: Field::DateTime,
  }.freeze
```
note: I was told to move here from [here](https://github.com/thoughtbot/administrate/issues/1029#issuecomment-363482586)

![lookupdate](https://user-images.githubusercontent.com/18540566/35871364-e46ec980-0b18-11e8-8746-7d7598f18593.png)

**Comment by nickcharlton** [comment]
In your snippet there, you're showing `date: Field::Text.with_options(searchable: true)`. Would you be able to share what the model/schema looks like?

**Comment by fercreek** [comment]
I have the same error :( when I'm using `searchable: true`

**Comment by fercreek** [comment]
@KickButtowski80  My workaround was using the default index controller, I replaced this code `resources = Administrate::Search.new(scoped_resource, dashboard_class, search_term).run`. Instead, I had to use `LIKE`and `CAST`. 

Here is my example.

```rb
search_term = params[:search].to_s.strip
resources = User.where(
  'CAST(users.created_at AS text) LIKE :search_term OR
  CAST(users.last_sign_in_at AS text) LIKE :search_term',
  search_term: "%#{search_term}%".downcase
)
```

**Comment by KickButtowski80** [comment]
@fercreek  where your sample is gonna reside?

**Comment by nacengineer** [comment]
note this is probably an issue with your associated model's scope. You need to specify the table name in it. e.g. scope :some_scope, -> { order('table_name.created_at desc') } vs scope :some_scope, -> { order('created_at desc') }

**Comment by nickcharlton** [comment]
I suspect @nacengineer's solution here is likely true, but without a more detailed example it's always hard to tell.

This is quite old, so I'm going to close it for now. But feel free to re-open if you're still getting a similar problem.
