### ISSUE TITLE
PG case sensitivity

### ISSUE THREAD

**Issue by frpascal** [thoughtbot/administrate#1091]
Hello,

Here is the URL:

http://127.0.0.1:3000/admin/customers?direction=asc&order=LastName

Here is the error:

```
SELECT  "Customers".* FROM "Customers"  ORDER BY LastName asc LIMIT 10 OFFSET 0

ActionView::Template::Error (PG::UndefinedColumn: ERROR:  the column "lastname" doesn't exist
```

If I replace (in /administrate/order.rb):

      return relation.reorder("#{attribute} #{direction}") if
        relation.columns_hash.keys.include?(attribute.to_s)

by:

      return relation.reorder(attribute => direction) if
        relation.columns_hash.keys.include?(attribute.to_s)
		
everything works well:

```
SELECT  "Customers".* FROM "Customers"  ORDER BY "Customers"."LastName" ASC LIMIT 10 OFFSET 0
```

So, is it possible to revert #926 ?

Thx

**Comment by nickcharlton** [comment]
It's not likely that we'd go about reverting #926 as that provides support for custom ordering.

Rails conventions usually have columns in lower case, split by underscores. What are you doing such that that isn't the case?

**Comment by nickcharlton** [comment]
I'm going to close this, as it's been a long time and without an example app it's not going to be possible for me to understand what's going on.
