### ISSUE TITLE
Change basic authentication documentation

### ISSUE THREAD

**Issue by dare05** [thoughtbot/administrate#1092]
I'm using the latest version of Rails & Administrate, and try to implement basic authentication, as described here: https://github.com/thoughtbot/administrate/blob/master/docs/authentication.md

```
class Admin::ApplicationController < Administrate::ApplicationController
  http_basic_authenticate_with(
    name: ENV.fetch("ADMIN_NAME"),
    password: ENV.fetch("ADMIN_PASSWORD")
  )
end
```

What I get, however, is NoMethodError (undefined method `http_basic_authenticate_with' for #<Admin::UsersController:0x52f2c60>)

So I figured that this is a class method and the way you invoke it is:

`self.class.basic_http_authenticate_with`.

Correct me if I'm wrong.

**Comment by pustomytnyk** [comment]
> `self.class.basic_http_authenticate_with`

this mean you call it in context of an instance instead of a class?

**Comment by nickcharlton** [comment]
Huh, that's curious. This is where it originates from, and this hasn't changed (as far as I can see): http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html

From your snippet, I don't think there's anything you're doing wrong there. Would you be able to provide a more detailed example that I might be able to try out and run?

**Comment by kadru** [comment]
Any news on this?,  I have the same problem but the error manifest when I move `basic_http_authenticate_with` to a concern

**Comment by nickcharlton** [comment]
That sounds unrelated to the issue reported above, which I'm not sure I can comment on a solution for it without a bigger example.

With your issue, it'll be that inside a concern `basic_http_authenticate_with` will be out of scope. Can you provide an example of what you're doing here?

**Comment by nickcharlton** [comment]
I'm going to close this, as I have since done the same thing from the docs and it worked fine. I'd suggest opening an issue upstream if this is still an issue.

**Comment by caljess599** [comment]
I have no idea why, but I have this issue as well... it _could_ be a function of having an API ruby app? (Thus this login constitutes a separate authentication from the normal "front end" site that accesses the API.)

All I can say is, the suggestion works--and without using self.class, I get the method undefined error...

```ruby
# from application_controller.rb

  class ApplicationController < Administrate::ApplicationController
    
    before_action :authenticate_admin

    def authenticate_admin
      self.class.http_basic_authenticate_with(
        name: "name",
        password: "password!"
      )
    end
  end
```

**Comment by pablobm** [comment]
@caljess599 - Would you be able to provide a backtrace?

I had a look at your theory that this could be related to the app being API-only. Initially it makes sense, since it looks like `ActionController::API` does not load the HTTP authentication mixins, whereas `ActionController::Base` does.

However, your admin controllers inherit from `Administrate::ApplicationController`, which in turn does inherit from `ActionController::Base`. Therefore I would expect them to support the http auth methods.

In addition to the backtrace, could you please try something? Add this to your `Admin::ApplicationController`:

```
include ActionController::HttpAuthentication::Basic::ControllerMethods
```
