### ISSUE TITLE
Search is broken in MySQL

### ISSUE THREAD

**Issue by ineu** [thoughtbot/administrate#1101]
Due to https://github.com/thoughtbot/administrate/blob/v0.9.0/lib/administrate/search.rb#L27 Administrate 0.9 doesn't work with MySQL (tried MariaDB 10.1 and Oracle 5.7.21). The `TEXT()` method seems to be Postgres-specific.

**Comment by nickcharlton** [comment]
Ah, dammit. This isn't something we actively test against so I'm not so surprised it wasn't caught.

Do you think you'd be able to open a PR to help us bring back support?

**Comment by ineu** [comment]
Here it is: https://github.com/thoughtbot/administrate/pull/1103

I have a weird floating failure on spec/features/search_spec.rb:30 though, cannot reliably reproduce. I suspect some kind of race condition between FactoryGirl and DatabaseCleaner.

**Comment by ineu** [comment]
The PR is fixed now

**Comment by ineu** [comment]
Closing in favor of https://github.com/thoughtbot/administrate/pull/1103
