### ISSUE TITLE
Allow for custom attributes on PageCollection

### ISSUE THREAD

**Issue by badosu** [thoughtbot/administrate#1108]
This will allow fixing https://github.com/nickcharlton/administrate-field-nested_has_many/issues/12 and improving `NestedHasMany` capabilities.

Let me know if there are any restraints on this change or if there are alternative methods. If it's okay, I can go ahead and work on this.

**Comment by nickcharlton** [comment]
Hi @badosu!

I'm not aware of anything, nor do any alternative methods spring to mind. It'd be great if you'd be able to open a PR for this!

**Comment by badosu** [comment]
@nickcharlton Thanks, I'll take a stab at it.

**Comment by badosu** [comment]
@jmmastey I noticed you sent a PR to address this issue.

Let me know if you intend to fix the PR for merging, or else I can send a PR to your own branch to fix those issues as well.

Thanks!

**Comment by purinkle** [comment]
@badosu, is this still an issue for you?

**Comment by badosu** [comment]
@purinkle I am not using administrate in current projects, feel free to close if necessary
