### ISSUE TITLE
alternate field set for displaying has_many on show page

### ISSUE THREAD

**Issue by jmmastey** [thoughtbot/administrate#1109]
Hey, running into an issue with a client and I wanted to see if y'all would be interested in a PR for either of these potential solutions.

I have a record Company that has_many Users. I also have a users dashboard, with five or six columns defined on `UserController#COLLECTION_ATTRIBUTES`. My problem is that showing a Company causes all six attributes to be displayed, which in the constrained space looks really poor:

![screen shot 2018-03-07 at 8 13 05 am](https://user-images.githubusercontent.com/302011/37096797-6cd9697e-21df-11e8-853a-2189648d463a.png)

Two solutions I'd be willing to implement and I think could work to fix this issue:

1. Allow users to define an optional `EMBEDDED_COLLECTION_ATTRIBUTES` on UserDashboard, which the has_many partial can read to get the appropriate columns.
2. Allow some way to configure a max desired number of columns to show in the embedded collection.

Thanks! Really like the project.

**Comment by badosu** [comment]
@jmmastey I posted https://github.com/thoughtbot/administrate/issues/1108 to handle cases like this, in particular to remove the parent model from the columns of the children.

When that is achieved it would be really straightforward to allow `Fields::HasMany` to receive a list of attribute names for each action.

**Comment by jmmastey** [comment]
@badosu cool, I think I missed it because I don't see PageCollection in the source. If it solves the issue, I'm game. Do you have an example of how that would be defined in the dashboard class?

**Comment by badosu** [comment]
Could be as simple as:

```ruby
# user_dashboard.rb
users: Fields::HasMany.with_options(show: %i[name email role])
```

```ruby
# app/views/fields/has_many/_show.html.erb
  <%= render(
    "collection",
    collection_presenter: field.associated_collection.with_attribute_names(attribute_names_for_resource_and_action),
    resources: field.resources(params[field.name]),
    table_title: field.name
  ) %>

Where `#with_attribute_names` returns a duplicate of the original presenter with the custom attribute names from the field options or the default ones.
```

**Comment by nickcharlton** [comment]
I think @badosu's potential solution makes a lot of sense here. It avoids us trying to guess, and we can default to providing all fields that a user can adjust if it's breaking the UI.

Would one of you like to open a PR for this?
