### ISSUE TITLE
automatically remove models from sidebar that are inaccessible?

### ISSUE THREAD

**Issue by jmmastey** [thoughtbot/administrate#1111]
I have an administrate install with two types of users (`admin` and `staff`), authorized via Pundit.

Staff are not able to edit the record `Neighborhoods`, admins are. Example part of the policy:

```
class NeighborhoodPolicy
  def index?
    @user.admin?
  end
end
```

Really, staff can't do _anything_ with neighborhoods, so I'd like to remove that link from the left navigation entirely. Would y'all be amenable to a PR that changes `Administrate::Namespace.resources` to check authorization of the index action and conditionally drop that from navigation?

**Comment by nickcharlton** [comment]
Yes, that'd be great!

**Comment by jmmastey** [comment]
@nickcharlton submitted!
