### ISSUE TITLE
Randomly failing test in show_page_spec.rb:5

### ISSUE THREAD

**Issue by pustomytnyk** [thoughtbot/administrate#1114]
@pablobm, it seem the `rspec ./spec/features/show_page_spec.rb:5` test from #1078 has some random issue not related to the ordering https://circleci.com/gh/thoughtbot/administrate/2983. I was unable to reproduce it and don't know what can be a possible cause.

**Comment by pablobm** [comment]
@pustomytnyk Thank you for pointing out. After some playing with it, I think what must be happening is that we don't specify a sorting order, and therefore the DB doesn't necessarily return orders always in the expected order. In some occasions, this would result in the DB returning the same orders for the first and the second page, which I think is what happened at https://circleci.com/gh/thoughtbot/administrate/2983.

I'm creating a PR to ensure a consistent sorting order. Let's see if we see the same problem again.
