### ISSUE TITLE
No possibility to override stylesheets and javascripts through Webpacker assets

### ISSUE THREAD

**Issue by JacopoGobbi** [thoughtbot/administrate#1118]
Hi, I have created a rails 5.1 app, however I want to use vue to manage my front end assets, I noticed that I can override them through a generator but they get generated in the assets folder that should be loaded through sprockets.
Is there any way to get the css and js to be loaded (and overridden) from webpacker folder? It is very nice to have hot page reloading and I don't see any dependency over sprockets when using this gem, so what about being able to set the path in a config from which reloading the assets or find a way to load them through webpacker if available or even, what about both?
I started by forking this repo and maybe will also try to find a solution myself, but any help or suggestion would be highly appreciated.

Thanks!!

**Comment by archonic** [comment]
I would also appreciate a way to configure it so we could use our own assets. I've closed off the admin section with a routes constraint and right now this is hitting the users table just to serve the same asset files that my app has.

**Comment by nickcharlton** [comment]
I'd definitely be open to anything you can come up with regarding this! I've not personally had a chance to try out `webpacker` and `administrate`.

**Comment by SleeplessByte** [comment]
@nickcharlton I've added a wiki page [how to set this up](https://github.com/thoughtbot/administrate/wiki/Rails-6-&-Webpacker) with Rails 6, but should also work for Rails 5!

We're using it in production :)

**Comment by pablobm** [comment]
Since this is now documented, I think it can be closed. Thank you @SleeplessByte!

**Comment by SleeplessByte** [comment]
You're welcome!

**Comment by dansteele** [comment]
@SleeplessByte Thank you for the guide!

I'm currently trying to make webpacker happily compile the CSS too, but my issue is that my scss pack doesn't have visibility of the required administrate CSS. Given you've got this running, could you clarify what you used to import the CSS please?

I've tried about 50 variants of
```scss
@import '~administrate/app/assets/stylesheets/administrate/application';
```

I've tried various ways of adding administrate to my webpacker resolved_paths. No matter what I try I always end up with some variant of:
```bash
File to import not found or unreadable: ~administrate/app/assets/stylesheets/administrate/application.
```

Your help would be massively appreciated 🙏

**Comment by SleeplessByte** [comment]
@dansteele it won't work this way. The steps to make this work with webpacker are [the same as described in my Wiki Page](https://github.com/thoughtbot/administrate/wiki/Rails-6-&-Webpacker#update-stylesheet).

1. use the generator to generate the stylesheets. 
2. open `app/assets/stylesheets/administrate/application.scss`
3. follow the wiki
4. create a new css pack, and move over the entire administrate directory. Same steps as above but then for the stylesheet 💯

Here is how we have it set-up:

- `app/frontend` is our webpacker dir
- in `packs` there is a file `admin.js`
- The first line is `import '../stylesheets/admin/index.scss'`
- `app/stylesheets/admin/index.scss` is the file mentioned under step 2 above.

![image](https://user-images.githubusercontent.com/1964376/76632341-603c4c00-6543-11ea-886f-58a9c898553d.png)
