### ISSUE TITLE
should handle namespaced in field/associative

### ISSUE THREAD

**Issue by namiwang** [thoughtbot/administrate#1125]
Say we've got some models like

```
module OneModule
  class OneModel < ApplicationRecord
    belongs_to :another_model, class_name: 'AnotherModel', foreign_id: 'another_model_id'
  end
end
```

While Rails is ok about it, administrate needs `class_name` to be `OneModule::AnotherModel` instead of just `AnotherModel` to work properly.

Guess the related methods is `associated_class_name` in `field/associative`.

**Comment by pablobm** [comment]
I think this should be irrelevant now that we have automatic associations (https://github.com/thoughtbot/administrate/pull/1633). If someone is having still this issue, please let us know and we can reopen.
