### ISSUE TITLE
How to Create Job Dashboard?

### ISSUE THREAD

**Issue by uurcankaya** [thoughtbot/administrate#1128]
Is there a way to create a Dashboard for DelayedJobs table?

**Comment by Knack** [comment]
A simple way to do it is to create a model in your app that inherits from `Delayed::Job`

> app/models/background_job.rb
```ruby
class BackgroundJob < Delayed::Job
end
```

And then you can generate a Dashboard, etc. for your new model in the usual way

**Comment by nickcharlton** [comment]
Yeah, I'd expect making your own model like that to work. In theory, it should be possible to use the `Delayed::Job` model directly now we have support for namespaced models, but I've not tried it.

It does beg an additional question: Could we perhaps build a plugin which could provide a basic abstraction for other job dashboards? Whilst Resque, Sidekiq, etc have their own Dashboards it'd be nice to have something in one place. What do you think?

**Comment by pablobm** [comment]
I think the original question is now answered. Let us know if not!
