### ISSUE TITLE
Dependency issues with rails 5.2.0 on bundle install

### ISSUE THREAD

**Issue by frostini** [thoughtbot/administrate#1133]
**Expected:**
Should be able to add administrate gem to Rails 5.2.0 project.

**Actual**
Error resolving dependencies and could not run `bundle install`.

**Steps to Reproduce**
1. Add administrate gem to a 5.2.0 rails app Gemfile via `gem 'administrate', '~> 0.9.0'`
2. run `bundle install` in console

**Error Message**
```
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    administrate (~> 0.9.0) was resolved to 0.9.0, which depends on
      actionpack (< 5.2, >= 4.2)

    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      actionpack (= 5.2.0)
```

**Suggested fix**
Set actionpack dependency to `actionpack (~> 5.2.0, >= 4.2)`

**Isolated Issue**
I added administrate gem to a 5.1.6 rails app and dependencies were resolved and `bundle install` ran successfully

PS. Thank you for being awesome and all the work you do thoughtbot team :) !

**Comment by nickcharlton** [comment]
Thank you for opening this! I've merged in #1148 so we now have support for Rails 5.2 in `master`. I'm planning to cut a release so that we support this for everyone in the next day or so.
