### ISSUE TITLE
Discussion: How to change fields' visibility in a form using Pundit's `permitted_attributes_for#{action}`?

### ISSUE THREAD

**Issue by mactkg** [thoughtbot/administrate#1137]
My app has two types of users(e.g. `staff` and `admin`), and authorize with Pundit.
I want to change fields' visibility in a form by user types and actions, for example, admin can read and edit status of an application form but staff can only read.

Fields in forms are defined in a dashboard file(e.g. `apps/dashboards/foobar_dashboard.rb` in your app), and used [here(administrate/page/form.rb)](https://github.com/thoughtbot/administrate/blob/a6a8f7eee1de0d8f58595e41b24fde4a41375ad9/lib/administrate/page/form.rb#L13-L17).

I want to use Pundit's `permitted_attributes_for_#{action}`([document](https://github.com/varvet/pundit#strong-parameters)), but administrate's controller can pass only a dashboard to a form object and dashboard doesn't know information about authorize.

How implement this? I don't have a good idea now.

Thanks.

**Comment by nickcharlton** [comment]
Are you able to use anything from [Further Limiting Scope](https://github.com/thoughtbot/administrate/blob/master/docs/authorization.md#further-limiting-scope) in the docs?

**Comment by mactkg** [comment]
@nickcharlton 
Scope limits what **record** will be shown, not **field**, so [Further Limiting Scope](https://github.com/thoughtbot/administrate/blob/master/docs/authorization.md#further-limiting-scope) doesn't fill my requirement.
I didn't use Pundit's function, but I succeed implement what I want.

```ruby
# controllers/admin/application_controller.rb
# (snip)
def filter_form_attributes(attributes)
  attributes
end
helper_method :filter_form_attributes
```

```erb
# views/admin/application/_form.html.erb
# (snip)
<% filter_form_attributes(page.attributes).each do |attribute| -%>
  <div class="field-unit field-unit--<%= attribute.html_class %>">
    <%= render_field attribute, f: f %>
  </div>
<% end -%>
```

```ruby
# controller/admin/document_controller.rb
# (snip)
def filter_form_attributes(attributes)
  return attributes if current_user&.is_boss?
  attributes.reject { |attr| attr.attribute == :super_confidential_field }
end
```

and override `create` and `edit` method to control parameters.

* * *

After writing, I noticed my approach to control fields' visibility using Pundit is not fine. What action can an user do are coded to Pundit's documents, and what field can an user do are coded to Administrate's dashboard documents.

If take my first approach(limit with Pundit), the latter information are also coded to Pundit's document. I think it is better to gather same information to same file or module.

Anyway, I already implemented what I want, I'll close this issue.
