### ISSUE TITLE
`.byebug_history` and `gemfiles/.bundle/` not in .gitignore

### ISSUE THREAD

**Issue by shvetsovdm** [thoughtbot/administrate#1139]
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.byebug_history
	gemfiles/.bundle/
```

This files have not been added to .gitignore intentionally? I think `.byebug_history` should be included. Not sure about `gemfiles/.bundle/config` should be ignored or included in the repo.

**Comment by nickcharlton** [comment]
Thanks for raising this! I probably have it in my global `.gitignore` so I've never seen them.
