### ISSUE TITLE
issue with gem "administrate"

### ISSUE THREAD

**Issue by yossepbb** [thoughtbot/administrate#1141]
Hi everybody,
It's a pleasure to be here  and share we the largest community of dev in the world.
I am working on this project and  i want to create a new dashboard for e-commerce shop but i can't , I get stuck. 
I made some researches and i found a gem "administrate" 
First i just copy this line in my Gemfile <<  gem "administrate" >> then I bundle command on my terminal to install all the dependencies.

`
 dashboard_ajax git:(master) ✗ bundle      
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies.......
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 5.2.0)

  In Gemfile:
    administrate was resolved to 0.7.0, which depends on
      actionpack (< 5.1, >= 4.2)

    rails (~> 5.2.0) was resolved to 5.2.0, which depends on
      actionpack (= 5.2.0)

    rails (~> 5.2.0) was resolved to 5.2.0, which depends on
      sprockets-rails (>= 2.0.0) was resolved to 3.2.1, which depends on
        actionpack (>= 4.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.2.0)

  In Gemfile:
    rails (~> 5.2.0)

    administrate was resolved to 0.2.2, which depends on
      rails (~> 4.2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
`

Thank you for your help.

**Comment by mactkg** [comment]
@yossepbb Can you paste Gemfile and Gemfile.lock?
Pro Tip: You can paste some code snippets nicely surrounding the snippet with ```

**Comment by nickcharlton** [comment]
Hi @yossepbb!

It sounds like you're trying to install `administrate` onto a Rails 5.2 app which wasn't supported until #1148 was merged in.

There's not a release out yet (but might be when you read this). I'm going to do that in the next day or so.

I'd not recommend this for the long term, but you may which to install `administrate` from the git repo to work around this sooner:

```
gem "administrate", github: "thoughtbot/administrate"
```

If you have any other problems getting going with `administrate`, please open a new issue!
