### ISSUE TITLE
HasOne with a HasOne attribute shows object.to_s

### ISSUE THREAD

**Issue by hcarreras** [thoughtbot/administrate#1142]
Hi there,

On the show view of a HasOne association, the attributes of the association are being shown:
![](https://cl.ly/0o1q1j2l0F1j/Image%202018-04-13%20at%2012.10.24%20PM.png)

Because some of the attributes are HasOne associations as well, the object it's just converted to string.

Locally, I've fixed this by checking if the attribute has an associated resource:

app/views/fields/has_one/_show.html.erb
```
<% if field.data %>
  <fieldset class="attribute--nested">
    <legend>
      <%= link_to(
              field.display_associated_resource,
              [namespace, field.data],
          ) %>
    </legend>
    <% field.nested_form.attributes.each do |attribute| -%>
      <div>
        <dt class="attribute-label">
          <%= t(
                  "helpers.label.#{resource_name}.#{attribute.name}",
                  default: attribute.name.titleize,
              ) %>
        </dt>
        <dd class="attribute-data attribute-data--<%= attribute.html_class %>">
          <% if attribute.methods.include? :display_associated_resource  %>
            <%= link_to(
                    attribute.display_associated_resource,
                    [namespace, attribute.data],
                ) %>
          <% else %>
            <%= attribute.data %>
          <% end %>
        </dd>
      </div>
    <% end -%>
  </fieldset>
<% end %>
```

I think the result looks nicer since it allows a simple navigation between models:
![](https://cl.ly/3F3E3h022k0S/Image%202018-04-13%20at%2012.13.03%20PM.png)

Would this be something you are interested to have? Should I make a PR?

**Comment by nickcharlton** [comment]
Yes! This would be a great addition.

Are you expecting that the values which are displayed would be something that is/should be configurable?

**Comment by hcarreras** [comment]
I don't think we should make this configurable. 
The view of a has_one association simply displays the values of the association. In the case of another has_one association this should be its resource name. 
The link to the association it's just an added feature to improve the navigation.

**Comment by nickcharlton** [comment]
I'm going to close this because I think #1259 is the more ideal solution to this (showing some of the nested forms attributes) and it's been quite a while. Thanks for opening!
