### ISSUE TITLE
Support Sequel as a means for oracle database consumers.

### ISSUE THREAD

**Issue by serra92** [thoughtbot/administrate#1149]
Currently, Administrate does not support the use of search with Oracle Database (it is throwing errors of invalid SQL syntax). Is this going to be something that will be supported in the future?

This is the thrown error:

```
Java::JavaSql::SQLSyntaxErrorException: ORA-00904: "TEXT": invalid identifier
: 
              SELECT * FROM (
                SELECT raw_sql_.*, rownum raw_rnum_
                FROM (SELECT  "TEST_CASES".* FROM "TEST_CASES" WHERE 
(LOWER(TEXT("TEST_CASES"."ID")) LIKE '%teste%' OR LOWER(TEXT("TEST_CASES"."NAME")) LIKE
 '%teste%' OR LOWER(TEXT("TEST_CASES"."DESCRIPTION")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."PROJECT_NAME")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."WORK_AREA_NAME")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."TEST_PLAN_NAME")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."TEST_PLAN_ID")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."KIPER_ID")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."CREATED_BY")) LIKE '%teste%' OR 
LOWER(TEXT("TEST_CASES"."LAST_UPDATED_BY")) LIKE '%teste%') ) raw_sql_ WHERE rownum <=
 (:a1 + :a2) ) WHERE raw_rnum_ > :a1
```

**Comment by serra92** [comment]
Is it possible to construct the queries using arel tables instead of strings? Currently, for the application that I'm working on, I'm using them to build queries to a Oracle database and I haven't had any problems with it so far.

**Comment by nickcharlton** [comment]
I'm going to close this as (currently) the effort required to fully support another ORM and especially Oracle is quite high.

I'd support someone sponsoring a move in this direction though (either literally, or taking on the work to get it done).
