### ISSUE TITLE
Click to model tr (model#index view) didn't work at Firefox

### ISSUE THREAD

**Issue by ghost** [thoughtbot/administrate#1169]
Can't go to model#show view by clicking to model position at index view. Better check the gif to understand:
![](https://hsto.org/webt/e8/m_/hl/e8m_hls4t_tezanhcjsg4ggschg.gif)

Works as expected in Chrome, btw.

---

Firefox version: 60.0.1
Gem version: 0.10.0
Rails version 5.2

**Comment by nickcharlton** [comment]
Closing as this is working in Firefox 81.0. It _might_ have been a JavaScript related row issue which had come up before.
