### ISSUE TITLE
TextField works as BelongsTo

### ISSUE THREAD

**Issue by piotrpietrusewicz** [thoughtbot/administrate#1173]
Hi, 
I need TextField field type ( this would work with autocomplete) there I can choose only one option and I would like TextField should work as BelongsTo field. The option I choose will be assigned to RESOURCE_id. Is It possible to do ?

**Comment by pustomytnyk** [comment]
@piotrpietrusewicz maybe this would suit https://github.com/fishbrain/administrate-field-belongs_to_search

**Comment by piotrpietrusewicz** [comment]
@pustomytnyk It does not work for me. I need probably something custom.

**Comment by purinkle** [comment]
@piotrpietrusewicz, is this still an issue for you?
