### ISSUE TITLE
unable to install Administrate  rails 5.2

### ISSUE THREAD

**Issue by alvinsteph** [thoughtbot/administrate#1178]
hi still don't know how to install administrate , even trying to switch back to rails 4.2 didn't work this is the error message : 
Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 5.1.6)

  In Gemfile:
    rails (~> 4.2) x64-mingw32 was resolved to 4.2.0, which depends on
      actionpack (= 4.2.0) x64-mingw32

    sass-rails (~> 5.0) x64-mingw32 was resolved to 5.0.7, which depends on
railties (< 6, >= 4.0.0) x64-mingw32 was resolved to 5.1.6, which depends
on
        actionpack (= 5.1.6) x64-mingw32

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 4.2) x64-mingw32

Could not find gem 'rails (~> 4.2)' in any of the sources.

**Comment by pustomytnyk** [comment]
@alvinsteph `sass-rails (~> 5.0)`: maybe you can't have rails 4 and sass-rails 5. Just a guess. 
Administrate works on rails 5.2 for me.

**Comment by alvinsteph** [comment]
Hi really !!! It's strange I get an error message when I try to get to
localhost:3000/admin . thank you very for replying. I will send you a
capture of the message.

**Comment by splashinn** [comment]
@alvinsteph Administrate is working for me on Rails 5.2 as well. Looks like you (possibly) have an issue with gem versions being incompatible with one another in your Gemfile.

**Comment by purinkle** [comment]
@alvinsteph, is this still an issue for you?

**Comment by nickcharlton** [comment]
I'm going to close this as it's not had any activity for a while. If this is still an issue, please try with the latest Administrate release and open an issue if you're still having problems.
