### ISSUE TITLE
Rails 3.2 compatibility?

### ISSUE THREAD

**Issue by preist** [thoughtbot/administrate#1181]
How difficult would it be to make Administrate (at least partially) Rails 3.2 compatible? Are there special reasons why it can't work on versions lower than 4.2?

**Comment by nickcharlton** [comment]
I don't — of the top of my head — know of a strong reason other than when Administrate was started we'd started with a more recent version of Rails and no one has had a strong inclination to do something about that.

Generally, though, I wouldn't be willing to maintain support for a major Rails version that was released some 2 years ago. I'd be curious to understand your reasons to stick with 3.2 and what's keeping you investing in staying there, but I don't think it would be valuable for the project as a whole to extend the support.
