### ISSUE TITLE
Default `/admin` page when no models or dashboards exist

### ISSUE THREAD

**Issue by alvinsteph** [thoughtbot/administrate#1186]
hi administrate:install doesn't create everything i need to run administrate prpele this is what i get i my terminal:

alvin@alvin-virtual-machine:~/myapp$ rails g administrate:install
Running via Spring preloader in process 22931
 identical  app/controllers/admin/application_controller.rb

The command should create more files right ?????

on the wb browser this is what i get :+1: 

Routing Error
No route matches [GET] "/admin"

Rails.root: /home/alvin/myapp
Application Trace | Framework Trace | Full Trace

**Comment by computer045** [comment]
I have this problem on a clean install of ubuntu 18.04, ruby 2.5.1 and rails 5.2.
Only the `application_controller.rb` file is added. I can add the the views with a `rails g administrate:views`, but the routes are not added when running  `rails g administrate:routes`.

**Comment by thecalliopecrashed** [comment]
Hm, maybe we could set up a default `/admin` route when no dashboards are available?

It would be nice if people could bake in Administrate with a clean boot of Rails.

**Comment by thecalliopecrashed** [comment]
Conversation is still happening at #186!
