### ISSUE TITLE
Ordering BelongsTo's column alphabetically

### ISSUE THREAD

**Issue by thealiilman** [thoughtbot/administrate#1188]
Hallo. 😄 I need some help, as I've spent the past day or two digging through the repo's issues / PRs figuring out how to order a record's belongs_to association alphabetically in its collection.

These are the gems that I think are relevant to this issue.
```
administrate (0.10.0)
      actionpack (>= 4.2, < 6.0)
      actionview (>= 4.2, < 6.0)
      activerecord (>= 4.2, < 6.0)
      autoprefixer-rails (>= 6.0)
      datetime_picker_rails (~> 0.0.7)
      jquery-rails (>= 4.0)
      kaminari (>= 1.0)
      momentjs-rails (~> 2.8)
      sass-rails (~> 5.0)
      selectize-rails (~> 0.6)
    administrate-field-image (1.1.0)
      administrate (>= 0.2.0.rc1)
rails (5.0.7)
      actioncable (= 5.0.7)
      actionmailer (= 5.0.7)
      actionpack (= 5.0.7)
      actionview (= 5.0.7)
      activejob (= 5.0.7)
      activemodel (= 5.0.7)
      activerecord (= 5.0.7)
      activesupport (= 5.0.7)
      bundler (>= 1.3.0)
      railties (= 5.0.7)
      sprockets-rails (>= 2.0.0)
```

In my situation, I have a Dish model and a Restaurant model. Dish belongs to Restaurant and Restaurant has many dishes.
I noticed that when one clicks the `<th>` for Restaurant, it orders the column based on the restaurant's `id` and not the restaurant's name. I want to change it so that, it orders the column based on the restaurant's name and alphabetically.

Right now, it appears like so.
<img width="336" alt="screen shot 2018-07-06 at 15 42 48" src="https://user-images.githubusercontent.com/26957580/42366490-e88f6128-8133-11e8-9e63-d783538c11aa.png">

I've tried using the `order` option, but according to the docs, it's only for dropdown menu, not for a table.
Is there a way to let it be ordered alphabetically based on its name?

**Comment by splashinn** [comment]
@thealiilman What you'll want to do is generate the views for your resource: (`rails g administrate:views Restaurant`) 

In the `_collection.html.erb` file within the `app/views/admin/restaurants`, you'll see `resources.each do |resource|...`. 

Change that to `resources.order("name ASC").each do |resource|...` and that should list your restaurants alphabetically.

**Comment by thealiilman** [comment]
@splashinn Thank you for the suggestion! I forgot to mention that the `_collection` partial sits in the `dish` folder.

Your last sentence gave me an idea to join the `restaurant` model with the resource (`dish`) and order based on the restaurant's name, but I couldn't get the toggling to work in the view and through a controller action. So what I did was, I forked Administrate's repo and customised `administrate/order.rb`, like so.

```
def order_by_association(relation)
    return order_by_count(relation) if has_many_attribute?(relation)

    if belongs_to_attribute?(relation) && is_attribute_promoter(attribute)
        return order_by_id(relation)
    end

    return order_by_name(relation) if belongs_to_attribute?(relation)

    relation
end

def order_by_name(relation)
    relation.joins(attribute.to_sym).order("#{attribute.pluralize}.name #{direction}")
end

def is_attribute_promoter(attribute)
    attribute.eql?('promoter')
end
```

Not a pretty solution, but works for my case.

**Comment by jondkinney** [comment]
Here's a monkey patch that is a bit more flexible. I'll make a proper PR for it shortly.

```ruby
# Some dashboard that has user as a belongs_to association (Posts, for example)
ATTRIBUTE_TYPES = {
  user: Field::BelongsTo.with_options(
    order_by: 'first_name',
  ),
  # ...
}.freeze
```

```ruby
# lib/administrate/order.rb
# NOTE: Add a .with_options(order_by: 'something') to override sorting by id
module Administrate
  class Order
    def order_by_association(relation)
      return order_by_count(relation) if has_many_attribute?(relation)

      order_by_attribute =
        "#{relation.klass}Dashboard".constantize.send(:new)
          .attribute_types
          .fetch(attribute.to_sym)
          .options
          .fetch(:order_by, nil)

      if belongs_to_attribute?(relation)
        if order_by_attribute.present?
          return order_by_order_by_attribute(relation, order_by_attribute)
        else
          return order_by_id(relation)
        end
      end

      relation
    end

    def order_by_order_by_attribute(relation, order_by_attribute)
      relation
        .joins(attribute.to_sym)
        .order(
          attribute
          .titlecase
          .constantize
          .arel_table[order_by_attribute.to_s]
          .lower
          .send(direction.to_sym),
        )
    end
  end
end
```

**Comment by purinkle** [comment]
@thealiilman, is this still an issue for you?
