### ISSUE TITLE
Search fails in certain edge case with SQL error 

### ISSUE THREAD

**Issue by gouthamvel** [thoughtbot/administrate#1190]
This issue might be relating to #1179 

### Issue
Search gives a SQL error when searching in multiple association attributes linking to same foreign table.
Order (table: orders)
| -> Customer (table: customers)
| -> Seller (table: customers)

### How to reproduce
clone this https://github.com/gouthamvel/administrate/commit/45bc4187833910187f86bbfaff489aa6bb8e6d85 and run test.

### Note
I'm not sure if this is a issue with administrate or ActiveRecord. If you cloned my patch then 
`cd spec/example_app/ && bundle exec rails c` then run 

`Order.joins(:customer, :seller).includes(:customer, :seller).first` - This works fine `Order.joins(:customer, :seller).includes(:seller, :customer).first` - This won't

### Quick fix for anyone having this issue.
Change the order in which you define the ATTRIBUTE_TYPES or COLLECTION_ATTRIBUTES, this will in turn change the order in query and the issue should disappear.

**Comment by nickcharlton** [comment]
It seems like this one fell aside. I'm going to close this as it's been a long time, but please reopen if you're still facing it.
