### ISSUE TITLE
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

### ISSUE THREAD

**Issue by crispinheneise** [thoughtbot/administrate#1196]
Administrate depends on saas-rails, which depends on ruby-saas, which will be unmaintained in about a year. 

This is also discussed in the saas-rails issues, here:  https://github.com/rails/sass-rails/issues/420, but I wanted to make this community aware of it as well. 

```
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811

```

**Comment by nickcharlton** [comment]
Thanks for raising this! I saw this myself today as I was fixing something else.

It sounds like we can do a direct switch to `sassc-rails`. I opened #1197 for that. I'd love it if you (or anyone else!) could take a look.

**Comment by ignatiusreza** [comment]
would love to get this fixed.. this issue also block us from using sprockets 4, since v5 of sass-rails lock sprockets at `(>= 2.8, < 4.0)`..

**Comment by crispinheneise** [comment]
Thanks for upgrading. Forgive my ignorance, but what is Appraisals?

**Comment by nickcharlton** [comment]
[appraisal](https://github.com/thoughtbot/appraisal) lets us test against lots of different dependency versions. On administrate, it’s mostly used for testing different Rails versions but some other dependencies have caused problems in the past so we test against those specifically, too.

**Comment by crispinheneise** [comment]
TIL... thanks!
