### ISSUE TITLE
getting error that says  undefined local variable or method `resource_includes'

### ISSUE THREAD

**Issue by vasuchawla** [thoughtbot/administrate#1201]
My App works on the staging environment but on the development environment, when ever i open any of the `/admin` page, it gives me this error: `undefined local variable or method 'resource_includes'`

Any help would be appreciated. I have no idea why it gives this error.

**Comment by vasuchawla** [comment]
reverting to v0.9.0 worked.

**Comment by Murty0** [comment]
@vasuchawla You need to change this line: https://github.com/thoughtbot/administrate/blob/4eaef9e8589b505eb548715d053f9289f0e40059/app/controllers/administrate/application_controller.rb#L10
