### ISSUE TITLE
New page title should not be pluralized

### ISSUE THREAD

**Issue by dvanderbeek** [thoughtbot/administrate#1205]
This:
https://github.com/thoughtbot/administrate/blob/2c54226aeaebc1ac5316ccd22e87d3080e3608ed/app/views/administrate/application/new.html.erb#L21

Should probably use the same logic as this:
https://github.com/thoughtbot/administrate/blob/2c54226aeaebc1ac5316ccd22e87d3080e3608ed/app/views/administrate/application/index.html.erb#L47

**Comment by vifreefly** [comment]
Yes, 
![](https://i.imgur.com/5jtbmke.png)

It shouldn't be like that. Correct will be New Link (singular model name, not plural)

**Comment by nickcharlton** [comment]
After spending some time looking at this today, I'm going to close this as I don't think it's needed now that we've made a bunch of other i18n changes. Thanks for opening this.
