### ISSUE TITLE
Feature Request: Clearing Search

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#121]
I'd love to be able to easily the clear search by (1) deleting the text or (2) clicking an (X). As of right now, a user needs to click the page link in the navbar or remove the params for the URL. The former is my preferred method, but let me know what you think.

**Comment by graysonwright** [comment]
Hey, @ACPK. Thanks for the feedback!

I like the "clicking an (X)" option.

I'm not sure I understand how the "deleting the text" option would work - could you give some detail there? Right now, if you delete the search term and hit enter, it'll also clear the search.

**Comment by ACPK** [comment]
@graysonwright - "Deleting the text" would use autocomplete. With autocomplete, you params automatically get changed when you add or remove characters. 

Example (see the default white page you get on Google when you remove ThoughtBot):

    https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=thoughtbot

**Comment by graysonwright** [comment]
oh, alright.

Automatically searching for the user would be a bit tricky - we would need to reload part of the page while keeping the search bar there. I imagine we could do this with turbolinks, but I'm hesitant to introduce that level of complexity. We would need to be careful that the interaction isn't confusing for people who aren't expecting it, and it would require making a bunch of server requests for each search.

I think an "X" will be the easiest and most effective way to solve this.

**Comment by ACPK** [comment]
@graysonwright - For now, I agree. Want to do or PR or I can work on it later this week?

**Comment by graysonwright** [comment]
@ACPK I've got it, no worries.

https://github.com/thoughtbot/administrate/pull/127
