### ISSUE TITLE
 PG::UndefinedTable: ERROR:  relation "read_marks" does not exist

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#122]
When I run:

    rails generate administrate:install

I get:

     postgresql_adapter.rb:596:in `async_exec': PG::UndefinedTable: ERROR:  relation "read_marks" does not exist (ActiveRecord::StatementInvalid)
    LINE 5:                WHERE a.attrelid = '"read_marks"'::regclass
                                              ^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                    FROM pg_attribute a LEFT JOIN pg_attrdef d
                      ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                   WHERE a.attrelid = '"read_marks"'::regclass
                     AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum

**Comment by graysonwright** [comment]
Interesting - is the repo you're working in public?

Here's the source for [the install generator]. It looks like it mistakenly thinks `read_marks` is a table in the database.

[the install generator]: https://github.com/thoughtbot/administrate/blob/master/administrate/lib/generators/administrate/install/install_generator.rb

Can you run `ActiveRecord::Base.descendants` in your rails console and paste the output?

**Comment by ACPK** [comment]
pry(main)> ActiveRecord::Base.descendants
    => [Delayed::Backend::ActiveRecord::Job (call 'Delayed::Backend::ActiveRecord::Job.connection' to establish a connection),
     ReadMark (call 'ReadMark.connection' to establish a connection),
     Merit::Score (call 'Merit::Score.connection' to establish a connection),
     Merit::ActivityLog (call 'Merit::ActivityLog.connection' to establish a connection),
     Merit::BadgesSash (call 'Merit::BadgesSash.connection' to establish a connection),
     Merit::Sash (call 'Merit::Sash.connection' to establish a connection),
     Merit::Score::Point (call 'Merit::Score::Point.connection' to establish a connection),
     User (call 'User.connection' to establish a connection)]

**Comment by graysonwright** [comment]
Yeah, no problem! I have a few more questions:

- Are you up to date with your database migrations?
- What are the tables in your database?
- Is the `ReadMark` table installed as part of a gem?
- What is the file path where `ReadMark` is defined?
- If possible, can you share the contents of the `ReadMark` class?

**Comment by ACPK** [comment]
@graysonwright 

1. All of my migrations are up to date.
2. ReadMark shows up twice in my app at the moment, and both files were generated by Administrative.
..* The first file is DashboardManifest.rb [see Gist](https://gist.github.com/ACPK/8cb5b2b0eb333da788ac).
...* The second is ReadMore Dashboard despite the fact that it isn't a model in my app. I'll delete it but am curious why the Administrative generator created it.

**Comment by graysonwright** [comment]
Hm... I think one of your gems may define a `ReadMark` class that subclasses from `ActiveRecord::Base`. Administrate believes it is one of your models, and expects there to be a database table for it.

Can you post the contents of your `Gemfile`? I can try to to reproduce the error locally.

**Comment by graysonwright** [comment]
Looks like you might be using [Unread](https://github.com/ledermann/unread) - I added it to my gemfile and got the same error.

I've put together a fix for it [here] - we should have that released in version `0.1.1`, which we hope will go out at the end of the week.

If you delete `app/dashboards/read_mark_dashboard.rb` and remove `read_marks` from your dashboard manifest, things should work as planned.

If you need to, you can generate dashboards for your models, one at a time, with `rails generate administrate:dashboard MyModelName`

[here]: https://github.com/thoughtbot/administrate/pull/124

**Comment by ACPK** [comment]
@graysonwright Thanks for your help, and hope you had a great week!
