### ISSUE TITLE
Sharing what worked for me concerning Hstore/Jsonb datatypes 

### ISSUE THREAD

**Issue by jtoliver** [thoughtbot/administrate#1224]
Not sure if this is the place for this. Sorry...I don't contribute often. I was looking for this in the issues pages and didn't find. 

The following below helped me with hstore/jsonb data types.

**app/view/json_field/_form.html.erb**
```
<% field.send(:options).each do |fk, ft| %>
  <% field = ft.new(fk, field.data[fk.to_s], field.page) %>
  <%= render_field field, f: f %>
<% end %>
```
**app/view/json_field/_show.html.erb**
```
<% field.send(:options).each do |fk, ft| %>
  <% field = ft.new(fk, field.data[fk.to_s], field.page) %>
  <dt class="attribute-label"><%= t(
      "helpers.label.#{resource_name}.#{fk.to_s}",
      default: fk.to_s.titleize,
    ) %>
  </dt>
  <dd class="attribute-data">
    <%= render_field field, page: field.page %>
  </dd>
<% end %>
```
**app/view/json_field/index.html.erb**

Didn't to anything here yet.

```
<%= field.to_s %>
```

**app/fields/json_field.rb**

```
require 'administrate/field/base'

class JsonField < Administrate::Field::Base
  def self.permitted_attribute(_attr, _options = nil)
    _options.map{ |k, v| k }
  end

  def to_s
    data
  end
end
```

Might have to do some tweaking to the self.permitted_attribute method to allow different properties.
For example I had a custom array field and need the output to look like `[:allowed_colors => [], :test_field, test_field2]`

My self.permitted_atribute method looked like

```
  def self.permitted_attribute(_attr, _options = nil)
    _options.map do |k, v|
      if v == ArrayField
        { k => [] }
      else
        k
      end
    end
  end
```

**Usage in dashboard**

Just pass in other fields in the with_options method. I'm also using the jsonb_accessor gem.

```
  ATTRIBUTE_TYPES = {
    settings: Field::JsonField.with_options(
      allowed_colors: Field::ArrayField
    )
  }.freeze
```

**Comment by angusfretwell** [comment]
Thanks for this!

I also needed to define a `store_accessor` on my model to make the form work, e.g.:

```ruby
store_accessor :settings, :allowed_colors
```

**Comment by bastianwegge** [comment]
@jtoliver thanks for sharing this information!
I'd love to help you make either a pull-request for this or create your own little repository to share this as a gem. Please contact me if you're interested.

Small proposal for `app/view/json_field/_show.html.erb`:
You're overwriting your `field` value in line 2 which will cause errors when using more than one field. You should rather rename `field` from line 2 to `field_to_render` and replace the usage in line 9 using that variable.

There are some more things to take note of when using this with multiple fields. Usually you'd render a `fields_for` and then as @angusfretwell mentioned, you wouldn't have to use `store_accessor`.

**Comment by volkov-sergey** [comment]
Hi mate @jtoliver, thanks for your idea! Feel free to contribute your code to this gem https://github.com/codica2/administrate-field-jsonb.

**Comment by nickcharlton** [comment]
I'm going to close this as there's [`administrate-field-jsonb`](https://github.com/codica2/administrate-field-jsonb) which should provide the best solution to this problem, but please open a new issue if this doesn't solve it for you!
