### ISSUE TITLE
Why Time doesn't have a option `:format` ?

### ISSUE THREAD

**Issue by rnitta** [thoughtbot/administrate#1227]
Like Datetime, Time should have `:format` option, too.

If this is acceptable, I will be code it, after https://github.com/thoughtbot/administrate/pull/1226 is dealt with.

**Comment by nickcharlton** [comment]
Hi @rnitta, it's obviously been a long time since #1226 but I've just merged that if this is something you'd like to pick up?

**Comment by nickcharlton** [comment]
Closing this as we merged in #2029.
