### ISSUE TITLE
Deal with Active Storage attachments.

### ISSUE THREAD

**Issue by alogach** [thoughtbot/administrate#1236]
rails - 5.2.1
Active Storage - installed

```
class Model < ApplicationRecord
  has_one_attached :logo
  has_many_attached :documents
  has_many_attached :pictures
end
```
get 
`uninitialized constant LogoAttachmentDashboard`
immediately after installation. 

<img width="797" alt="screenshot 2018-11-06 8 48 01" src="https://user-images.githubusercontent.com/3097387/48045282-bb686c80-e1a0-11e8-9cdd-f14aea7f9862.png">

**Comment by Tashows** [comment]
Here is what needs to be done to get this to work initially:

Add Attachment Dashboard

    # app/dashboards/attachment_dashboard.rb

    require "administrate/base_dashboard"
    
    class AttachmentDashboard < Administrate::BaseDashboard
      ATTRIBUTE_TYPES = {
        id: Field::Number,
        name: Field::String,
        record: Field::Polymorphic,
        blob: Field::BelongsTo,
        created_at: Field::DateTime,
      }.freeze
    
      COLLECTION_ATTRIBUTES = [
        :id,
        :name,
        :record,
        :blob,
        :created_at
      ].freeze
    
      SHOW_PAGE_ATTRIBUTES = [
        :id,
        :name,
        :record,
        :blob,
        :created_at,
      ].freeze
    
      FORM_ATTRIBUTES = [
        :name,
      ].freeze
    
    end

Add Attachment Model
    
    # app/models/attachment.rb

    class Attachment < ActiveStorage::Attachment
    end

Add Blob Dashboard

    # app/dashboards/blob_dashboard.rb

    require "administrate/base_dashboard"
    
    class BlobDashboard < Administrate::BaseDashboard
      
      ATTRIBUTE_TYPES = {
        filename: Field::String,
        key: Field::String
      }.freeze
    
      COLLECTION_ATTRIBUTES = [
        :filename,
        :key
      ].freeze
    
      SHOW_PAGE_ATTRIBUTES = [
        :filename,
        :key
      ].freeze
    
      FORM_ATTRIBUTES = [
        :filename,
        :key
      ].freeze
    
    end

Add blob model

    # app/models/blob.rb

    class Blob < ActiveStorage::Blob
    end

Also in your routes add these inside the admin namespace

    # config/routes.rb

    namespace :admin do
      ...
      resources :attachments
      resources :blobs
      ...

This will get you past the errors, but it still needs customization. Will try to post a more complete answer later.

**Comment by SashkaSh** [comment]
Hi! I'm having the same issue with Rails 5.2.2. 

@Tashows I did all these steps but seems does not work.

**Comment by SashkaSh** [comment]
`NameError at /admin/jobs
uninitialized constant LogoAttachmentDashboard`

**Comment by Tashows** [comment]
@SashkaSh I edited my answer with some changes that ended up working for me. Haven't had the time to fully work on that yet.

**Comment by RossKinsella** [comment]
My solution was to:

* Create a custom field for active storage files as per [docs](https://github.com/thoughtbot/administrate/blob/master/docs/adding_custom_field_types.md)
* Populate the attachment as per snippet below
* Define the Attachment class at the top of my dashboard file. I didn't want to clutter my models with a work around file

```
# app/fields/attachment_field.rb
require "administrate/field/base"

class AttachmentField < Administrate::Field::Base
  def to_s
    return "Not attached" unless attached?
    service_url
  end

  private

  def attached?
    data.record.send("#{data.name}").attached?
  end

  def service_url
    data.record.send("#{data.name}").service_url
  rescue => ex
    Raven.capture_exception(ex)
    "error"
  end
end
```

```
# app/dashboards/MODEL_WITH_ATTACHEMENTS

# workaround for active storage attachements as per
# https://github.com/thoughtbot/administrate/issues/1236
class Attachment < ActiveStorage::Attachment
end

# dashboard definition stuff
.
.
.
```

**Comment by SleeplessByte** [comment]
There is [this gem](https://github.com/Dreamersoul/administrate-field-active_storage)  and with the default settings it _Just Works™_ for me.

**Comment by RossKinsella** [comment]
> There is [this gem](https://github.com/Dreamersoul/administrate-field-active_storage) and with the default settings it _Just Works™_ for me.

That gem looks good alright. I opted against using it as I didn't need many of its features. 
My only concerns were:
* Is there an attachment
* What is its url

**Comment by SleeplessByte** [comment]
Yep, I actually like the preview -- which is the only real other functionality, but because it tries to handle videos, audio, images etc there is "a lot".

**Comment by nickcharlton** [comment]
I'm going to close this one to merge discussion of ActiveStorage to #1560, which digs into some more specific issues.

It seems like the suggestion of using the field plugin is likely the right move for most cases, and areas where that isn't working we can discuss that separately.
