### ISSUE TITLE
Field markup could benefit from a reference to attribute name

### ISSUE THREAD

**Issue by greatseth** [thoughtbot/administrate#1237]
The "container" elements surrounding labels and inputs could benefit from having the attribute they represent indicated in a class.

I got the basic idea going with this initializer:

```
require 'administrate/field/base'

module FieldHtmlClassExtension
  def html_class
    [super, attribute].join(' ')
  end
end

Administrate::Field::Base.class_eval do
  prepend FieldHtmlClassExtension
end
```

I presume something more BEM-compliant would be in order if this were to be made official. `field-unit--{attribute}` or some such? I'm new to BEM naming.

Anyway, having a hook like that let me do this to three name fields using CSS:

<img width="772" alt="screen shot 2018-11-06 at 10 53 35 am" src="https://user-images.githubusercontent.com/5200/48076110-88c76f80-e1b2-11e8-9dc5-307c34fb1fac.png">

Now, I just need a way to change that `LName` label, but that's another issue...

P.S. I was mulling that label issue over before I hit send, and I started considering custom fields that provide several inputs as part of a solution. It occurs to me that could be another way to approach the example shown here. I'm not sure if that's a shady practice or not. It seems like some hooks on the core field markup could be useful for a bunch of things like this either way.

**Comment by purinkle** [comment]
@greatseth, is this still an issue for you?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been quiet for a long time; please open a new issue if it's still a problem.
