### ISSUE TITLE
Feature Request: Interface to add helper modules

### ISSUE THREAD

**Issue by joallard** [thoughtbot/administrate#1238]
This is a feature request following issue #334: *Best way to include main app helper modules in administrate*, which is closed.

According to recent reports, the workaround which consists of injecting the module in `config/application.rb` comes with an important caveat: the module is not automagically reloaded when it changes.

> A copy of SomeHelper has been removed from the module tree but is still active!

This makes implementing helpers that might be a little hairy (this was my case just now - I needed to fiddle with some values and see what emerges) way more inconvenient. In my case, I ended up just duplicating the code in the view instead of going through the hassle.

If implemented, I expect to be able to name my helper in some Administrate-related modules, with it being reloaded normally. We should probably add something in docs as well. Another possible solution would be to have an option to include all helpers by default.

**Comment by nealshepherd** [comment]
I found a solution that appears to be working as needed:

Add `helper all_helpers_from_path "app/helpers"` to your `Admin::ApplicationController`
Reference: https://api.rubyonrails.org/classes/ActionController/Helpers/ClassMethods.html#method-i-all_helpers_from_path

Unless I'm overlooking an important consideration, the helper modules are reloaded per-request with any changes.

**Comment by nickcharlton** [comment]
The solution listed here seems like a good approach; I can imagine having a method that's optional to override might be a good way of dong this. Would either of you be keen on opening a PR for it?

**Comment by paulRbr** [comment]
> I found a solution that appears to be working as needed:
> 
> Add `helper all_helpers_from_path "app/helpers"` to your `Admin::ApplicationController`
> Reference: [api.rubyonrails.org/classes/ActionController/Helpers/ClassMethods.html#method-i-all_helpers_from_path](https://api.rubyonrails.org/classes/ActionController/Helpers/ClassMethods.html#method-i-all_helpers_from_path)
> 
> Unless I'm overlooking an important consideration, the helper modules are reloaded per-request with any changes.

Should this be the default of [Administrate's ApplicationController](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb)? 

I got bitten by this today thinking I would be able to use my Rails app helpers directly in custom administrate fields views. 

Do you see any issue of making this a default in Administrate?

**Comment by pablobm** [comment]
I just had a look. The problem with loading all of the host application's helpers by default is that these may conflict with those provided by Administrate and cause strange errors.

For example, these are Administrate's own helpers: https://github.com/thoughtbot/administrate/blob/master/app/helpers/administrate/application_helper.rb. You can see that one of them is called `render_field`. If the host app had its own `render_field` helper, it would override Administrate's own and break the app.

I think this is something that users of Administrate will have to override manually by using `helper` in their own admin controllers. I'm going to close as I don't think there's more that can be done, but feel free to comment.

**Comment by KjellMorgenstern** [comment]
I am using the same pattern as in administrate/application_controller.rb
```ruby
    helper_method :nav_link_state
    def nav_link_state(resource)
      underscore_resource = resource.to_s.split("/").join("__")
      resource_name.to_s.pluralize == underscore_resource ? :active : :inactive
     end
```

So I just add the helper method in my custom controller, and declare it with ```helper_method :symbol```
I think this pattern is great for the many cases were xy_helper.rb is empty or has just one or two relatively trivial methods.

For example (needed since show_action is deprecated and authorized_action doesn't fit the description anymore)
```ruby
class SupportsController < Admin::ApplicationController
    ...
   helper_method :possible_action?
   def possible_action?(_resource, _action)
      return _resource.status != 'spam' if _action == :confirm_spam
      return _resource.status == 'spam' if _action == :not_spam
   end
   ...
```
