### ISSUE TITLE
Ability to pass custom variables to a dashboard controller

### ISSUE THREAD

**Issue by jkcchan** [thoughtbot/administrate#1274]
Hi, happy new year!

I want to use the `:scope` field of a `Field::BelongsTo`, with a custom variable (`current_user` using Devise gem). This is incredibly useful as the model being created would need to only show values that relate to the `current_user`.

Is there any way to do this currently?

Specifically, in `application_controller.rb` when the new form is called (`Administrate::Page::Form.new(dashboard, resource)`). What I'm thinking is that it would be nice to pass in a parameter, OR have the resource field accessible in `ATTRIBUTE_TYPES` in `dashboards/model_dashboard.rb`.

**Comment by nickcharlton** [comment]
This is fairly similar to #1342, so I'm going to close this in favour of that …plus there's a solution there.

Sorry for not seeing this before!
