### ISSUE TITLE
deploy latests docs

### ISSUE THREAD

**Issue by rileytg** [thoughtbot/administrate#1281]
https://github.com/thoughtbot/administrate/blob/master/docs/customizing_dashboards.md contains a fix for this typo on docs site:

```
country: Field::BelongsTo.with_options(
    searchable: true,
    seachable_field: 'name',
  )
```

https://administrate-prototype.herokuapp.com/customizing_dashboards

**Comment by nickcharlton** [comment]
The docs are deployed with each release, so this will be deployed when a new release is made.

You can find the docs for `master` at: https://administrate-demo-prerelease.herokuapp.com/

This has been a work in progress, but it's starting to be documented with #1514.
