### ISSUE TITLE
Accept array or string for searchable_field

### ISSUE THREAD

**Issue by charly-palencia** [thoughtbot/administrate#1289]
Hi guys, 

I have a question / issue related to searchable_field, i'm trying to use two different search fields for my `BelongsTo` relation but seems that we are not supporting this right now or maybe it should be address in a different way and i have no idea about it, there is any way to do this? 

``` ruby
...
    product: Field::BelongsTo.with_options(
      searchable: true,
      searchable_field: ['product_name', 'item_number']
    ),

...

```

Thanks for your help

**Comment by charly-palencia** [comment]
Seems like someone tried to do it here but this PR contains some conflicts https://github.com/thoughtbot/administrate/pull/1203

**Comment by purinkle** [comment]
@charly-palencia, is this still an issue for you?

**Comment by charly-palencia** [comment]
Hye @purinkle  
Yeah, in fact, I've been waiting for a multiple searchable_field implementation from your side guys (or at least a quick check for the PR that an included in one of the comments above). 
Thanks!

**Comment by nickcharlton** [comment]
I'm going to close this as #1203 got merged a while back; if you still have this issue, please reopen!
