### ISSUE TITLE
Generate `SHOW_PAGE_ATTRIBUTES` as an explicit array

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#130]
Right now, `COLLECTION_ATTRIBUTES`, `SHOW_PAGE_ATTRIBUTES`, and `FORM_ATTRIBUTES` use `ATTRIBUTE_TYPES.keys` as a base set of attributes. It would follow, then, that in order to re-order fields that appear in a form or table, you re-order the keys in `ATTRIBUTE_TYPES`. However, this seems a little odd, because `ATTRIBUTE_TYPES` is a hash, and so the order of its keys should be irrelevant. (It just so happens that hashes in Ruby are now ordered, but they really shouldn't be, and we shouldn't be assuming they are.)

So here's a suggestion: introduce a `BASE_ATTRIBUTES` constant that all of the other `*_ATTRIBUTES` constants use. The dashboard generator would have to set this to an explicit array based on the columns the model has, but then we'd encourage people to modify this array instead of `ATTRIBUTE_TYPES`. While we're at it, it might be useful to place `ATTRIBUTE_TYPES` first.

So a dashboard class would look like this:

``` ruby
ATTRIBUTE_TYPES = {
  author: Field::BelongsTo.with_options(class_name: "User"),
  content: Field::Text,
  id: Field::Number,
  ...
}

BASE_ATTRIBUTES = [
  :author,
  :content,
  :id,
  ...
]

READ_ONLY_ATTRIBUTES = [
  :id,
  :created_at,
  :updated_at
]

TABLE_ATTRIBUTES = BASE_ATTRIBUTES.first(4)

SHOW_PAGE_ATTRIBUTES = BASE_ATTRIBUTES

FORM_ATTRIBUTES = BASE_ATTRIBUTES - READ_ONLY_ATTRIBUTES
```

**Comment by graysonwright** [comment]
hm... I originally moved away from a similar solution, with `ATTRIBUTE_TYPES.keys` and `READ_ONLY_ATTRIBUTES`, because I thought it would be confusing what was part of the API and what wasn't.

I do like how this solution has a single place to change the order, but I'm not sure if it'll make things difficult for new users.

That was in #111. What do you think?

**Comment by mcmire** [comment]
Two points about that:

* Since `SHOW_PAGE_ATTRIBUTES` uses the keys from `ATTRIBUTE_TYPES`, you're still abusing a hash and assuming its keys are ordered.
* Other than `SHOW_PAGE_ATTRIBUTES`, is `ATTRIBUTE_TYPES` now used at all? That's unclear from the changes.

**Comment by graysonwright** [comment]
@mcmire I agree about the hash.

All of the constants in that file are required by Administrate, so yes - `ATTRIBUTE_TYPES` is used by Administrate.

I think I'd prefer to spell out `SHOW_PAGE_ATTRIBUTES` as an array, similar to how `TABLE_ATTRIBUTES` and `FORM_ATTRIBUTES` are now.

Thoughts?

**Comment by mcmire** [comment]
I think that's fine. I think that the attributes are going to end up getting customized anyway and in order to do so it's best to have it as an array.
