### ISSUE TITLE
Add a way to customize order of options in select for `belongs_to`

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#131]
The field for a `belongs_to` column is a `select` box, whose options are the values of the associated model. It's helpful to see the options in a sorted order, especially if there are a lot of options. Perhaps the easiest thing to do is to sort by `to_s` now, and provide a way to customize the order later.

**Comment by carlosramireziii** [comment]
As of now, there is no way to customize the order of a `belongs_to` association field. 

You can, however, create a new type of `Field` which applies the sort order you want. You can inherit all of the standard behavior from `Field::BelongsTo` and just override the part which applies to the collection. 

What do you think about something like this?

```
# app/fields/belongs_to_ordered_field.rb
class BelongsToOrderedField < Administrate::Field::BelongsTo

  def candidate_resources
    associated_class.all.order(:name) # add your custom order here
  end

  # tell this field to use the views of the `Field::BelongsTo` parent class
  def to_partial_path
    "/fields/belongs_to/#{page}"
  end

end
```

**Comment by mcmire** [comment]
Okay. That seems like a reasonable solution for now.

**Comment by carlosramireziii** [comment]
Great! Thanks for the response. I'm going to close this issue up.
