### ISSUE TITLE
Choosing between HasOne or BelongsTo

### ISSUE THREAD

**Issue by Miftahunajat** [thoughtbot/administrate#1311]
Hi,

In the current version in Administrate. Administrate support two types of relation
`Field::BelongsTo` and `Field::HasOne`.

In the BelongsTo Relation i must've created record first then i've to select the record I created.
The problem is whenever i want to create a single record i must switching to multiple dashboard page for just create some data.

In the HasOne relation you can create a nested association for related record.
But it would be problem if you want to have the associating field has same value in the existing record in database.

Is there any solution regarding this issue ? if it isn't I want to make Pull Request according this issue.

**Comment by nickcharlton** [comment]
I would expect the field type you choose to match the underlying relation in this situation. A `belongs_to` being used on the model when you have the foreign key stored, for example.

Does that help at all? If not, could you create a sample app which demonstrates the problem you're trying to solve?

**Comment by Miftahunajat** [comment]
Okay I will try to demonstrate it, on this Issue

**Comment by nickcharlton** [comment]
Did you get anywhere with this one?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been active for a long time.
