### ISSUE TITLE
It is an error to open a Show page when ImageField is nil.

### ISSUE THREAD

**Issue by kaito0228** [thoughtbot/administrate#1313]
The part of ImageField is nullable in type string.
If I open the show page, an error will occur if it is nil.
If it is nil, I would like not to refer to the image.
![image](https://user-images.githubusercontent.com/39002408/56039304-f6358880-5d6e-11e9-9ba4-e94dd935c29e.png)

**Comment by TolichP** [comment]
The ImageField is your custom field, I guess? 
It relates to Rails' helper [image_tag](https://apidock.com/rails/ActionView/Helpers/AssetTagHelper/image_tag), just check if your `field.url` is nil or not, like this:

`<% image_tag field.url if field.url.present? %>`

**Comment by kaito0228** [comment]
Thanks!
