### ISSUE TITLE
Customize search field 

### ISSUE THREAD

**Issue by 8vius** [thoughtbot/administrate#1315]
Currently having an issue with my search field showing up like this:

<img width="344" alt="Screen Shot 2019-04-12 at 5 25 00 PM" src="https://user-images.githubusercontent.com/671929/56069302-fd956b80-5d47-11e9-822b-89a230856af7.png">

Was wondering if there was a way to generate the view for the search partial to modify it and see what's up with it.

**Comment by Afoster2** [comment]
I'm having the same issue as above.

**Comment by nacengineer** [comment]
Note you can add a partial in views / admin / application called _search.html.erb and that will be used. If you copy the info from this partial https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/_search.html.erb you'll get the default search bar.

**Comment by nickcharlton** [comment]
It's been a long time, so I'm going to assume the specific issue has been solved. We'll document this better in #1778 and onwards as for how you override things.
