### ISSUE TITLE
Authorization with Pundit doesn't allow Policy Namespacing

### ISSUE THREAD

**Issue by bhtabor** [thoughtbot/administrate#1332]
[Punditize](https://github.com/thoughtbot/administrate/blob/b85abcf965ecc843ee9b25e3a2ea65dfeb1b0b3c/app/controllers/concerns/administrate/punditize.rb) assumes that there is no Pundit [Policy Namespacing](https://github.com/varvet/pundit#policy-namespacing) being used. If we allow namespaces, we could even avoid the custom policy_scope_admin.

Quick work around is, instead of including Punditize, to use the following code:

```
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Pundit

    def policy_scope(scope)
      super([:admin, scope])
    end

    def authorize(record, query = nil)
      super([:admin, record], query)
    end

    def scoped_resource
      policy_scope super
    end

    def authorize_resource(resource)
      authorize resource
    end

    def show_action?(action, resource)
      Pundit.policy!(pundit_user, [:admin, resource]).send("#{action}?".to_sym)
    end

  end
end

```

**Comment by robinboening** [comment]
I had the same thoughts for namespacing after stumbling into an error because I like using Pundit's `verify_policy_scoped` to verify the use of `policy_scope`.

My approach for changing administrate's punditize is a bit different, though. I believe deprecating the `policy_scope_admin` and removing it on the next major version is the right way to go, not to build on top of it. I believe software should needs to get rid of legacy code if we agree on a better approach.

**Comment by bhtabor** [comment]
I agree @robinboening We should just depricate `resolve_admin`. The whole idea behind `policy_scope_admin` is stated in the comment below:
```
# Like the policy_scope method in stock Pundit, but allows the 'resolve'
# to be overridden by 'resolve_admin' for a different index scope in Admin
# controllers.
```
This is the problem. It is trying to do what Pundit already does with [Policy Namespacing](https://github.com/varvet/pundit#policy-namespacing). Admin scope is just like a Pundit Namespace.

We still need to allow Pundit Namespacing though, like I did in this pull request - https://github.com/thoughtbot/administrate/pull/1335. I kept the `resolve_admin` feature for backward compatibility only. But, it could also be used to even have an additional admin scope over a namespace.

**Comment by archonic** [comment]
I just hit this issue upgrading from 0.11 to 0.14 and I think @bhtabor's solution works perfectly. There's unreleased pundit stuff in the master branch but I think it would make sense to sort out all pundit stuff before releasing 0.15.

**Comment by sedubois** [comment]
@archonic you'll find a proposed solution in #1663, feel free to take over that one if you'd like to help it get merged!

**Comment by Holist** [comment]
I think this has to be closed (https://github.com/thoughtbot/administrate/pull/2379)
