### ISSUE TITLE
Differently Named Route Namespace

### ISSUE THREAD

**Issue by richjdsmith** [thoughtbot/administrate#1341]
Is it possible to use a different route namespace than */admin*? 

I went through the documentation but couldn't find it and am hoping I just missed something. I know I can change the module name and controller names in /app/controllers/admin/* but that seems pretty drastic and not very future update-friendly. 

Am I missing something here?

**Comment by GeoffAbtion** [comment]
Does #1379 answer your question?

**Comment by nickcharlton** [comment]
[Custom Namespaces](https://administrate-demo.herokuapp.com/getting_started) is the only current solution to this problem.

In the interests of simplicity, I'm not particularly excited about adding configuration options to make this differ.
