### ISSUE TITLE
arrays not handled during edit action

### ISSUE THREAD

**Issue by gesaleh** [thoughtbot/administrate#1346]
I'm having an issue i have 2 Fields as json, one is array **sensors** `["x","y","e"] `and another is array or arrays (polygone) **area** `[[a,b],[c,d]]`
administrate don't handle these value when i do edit and apply 
first array is good but i have spaces that are added  `["x"," y"," e"]`
second one is converted to string 
```
more app/dashboards/role_dashboard.rb 
require "administrate/base_dashboard"

class RoleDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    users: Field::HasMany,
    id: Field::Number,
    name: Field::String,

    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    sensors: Field::Text,
    default_sensor: Field::Text,
    area: Field::String.with_options(searchable: false),
  }.freeze

```
```
 [3] #<Role:0x00007f534ccd1d00> {
                    :id => 1,
                  :name => "default",
            :created_at => Sat, 11 May 2019 12:23:01 UTC +00:00,
            :updated_at => Tue, 14 May 2019 11:06:06 UTC +00:00,
               :sensors => [
            [0] "H2",
            [1] "  CO",
            [2] "  NO2",
            [3] "  temperature",
            [4] "  humidity",
            [5] "  pressure",
            [6] "  aqi"
        ],
        :default_sensor => "temperature",
                  :area => "[[84.7750424,82.0989244],[84.8110913, 82.0957251],[84.7898053,82.041611],[84.754443,82.0517962],[84.7740124,82.0992152]]"
    }
```
any feedback on this Thanks

**Comment by sedubois** [comment]
Here is what I found:
- `administrate-field-collection_select` might answer the first need (haven't tried it)
- there is also `administrate-field-jsonb` but has some [issues](https://github.com/codica2/administrate-field-jsonb/issues) with serialization and it also uses an all-purpose JSON editor which isn't very practical to just select a bunch of predefined elements

Personally I'm thinking of how to handle assigning a collection of tags to some resources, after having stored them as an array of strings I'm now thinking of trying a [polymorphic field](https://github.com/thoughtbot/administrate/pull/1020) (first time I'd try that).

**Comment by nickcharlton** [comment]
I'm going to close this as @sedubois has listed some possible solutions here; please re-open if this isn't working for you.
