### ISSUE TITLE
Punditize concern does not restrict index

### ISSUE THREAD

**Issue by ademars94** [thoughtbot/administrate#1348]
Expected Behavior:
In `application_policy.rb`, if `index?` returns false, the user should not be able to access the index page.

Some Code:
In `application_policy.rb`, I've defined my `index?` action to return `false`:

```ruby
def index?
    false
end
```

Actual Behavior:
User is able to access the index page.

Note:
Even if I set `show?` to return `false`, the index page in Administrate will still show empty cells with no data.  If I set `show?` to return `true`, the index page appears as it should (it shows the data).  No matter what though, the `index` action is never properly restricted.

**Comment by HHGB12** [comment]
Hi @ademars94.
Index action and pundit is one story.
All other actions and pundit are an other story.

```ruby
class Seller < ApplicationRecord
 # ...
 has_many :quotations
 # ...
end
```


have a look of an example I have for one of my controller => QuotationsController. 
```ruby 
class QuotationPolicy < ApplicationPolicy
  def index?
    true
  end

  def show?
    if user.class == Seller
      record.seller == user || user.admin
    else
      record.customer == user
    end
  end

  def create?
    true
  end

  def new?
    create?
  end

  def update?
    true
  end

  def edit?
    update?
  end

  def destroy?
    true
  end
  def create_quotation_pdf?
    true
  end
  class Scope < Scope
    def resolve
      scope.where(customer: user)
    end
    def resolve_admin
      if user.admin
        scope.all
      else
        # i need to display on index view only quotation that have been 
        # build by the current user (here current_seller) 
        # the relation is seller has_many quotations and quotation belongs to seller 
        # i agree it's simple but it's good to start...
        scope.where(seller: user)
      end
    end
  end
end
```

then have a look on this kind of user story 
Let say that sellers have many suppliers and suppliers have many seller ...
A join table have to exist between them...
```ruby
class Seller < ApplicationRecord
 # ...
 has_many :quotations
 has_many :seller_suppliers
 has_many :suppliers, through: :seller_suppliers
 # ...
end
```
```ruby
class Supplier < ApplicationRecord
 # ...
 has_many :seller_suppliers
 has_many :sellers, through: :seller_suppliers
 # ...
end
```
Let's say also that suppliers have many products....
```ruby
class Supplier < ApplicationRecord
 # ...
 has_many :seller_suppliers
 has_many :sellers, through: :seller_suppliers
 has_many :products
 # ...
end
```
Now let's say that sellers have many products through supplliers... (through their suppliers)
```ruby
class Seller < ApplicationRecord
 # ...
 has_many :quotations
 has_many :seller_suppliers
 has_many :suppliers, through: :seller_suppliers
 has_many :products, through: :suppliers
 # ...
end
```
What is the business logic when you are connected as seller ? 
What do you want to display on the index view from ProductsController?  
And...How make a filter through allowed products if the seller want to create a new quotation for instance ???

=> inside your ```app/policies/product_policy.rb````
 you have to build the scope ...

```ruby
class ProductPolicy < ApplicationPolicy
  def index?
    true
  end

  def show?
    # record.supplier.supplier_users.pluck(:user_id).include? user.id
    true
  end

  def create?
    user.admin
  end

  def new?
    create?
  end

  def update?
      true
  end

  def edit?
    update?
  end

  def destroy?
    true
  end

  class Scope < Scope
    def resolve
      scope.all
    end
    def resolve_admin
      if user.admin == true
        scope.all
      else
        # scope.all
        scope.joins(:supplier).includes(:seller_suppliers).where(seller_suppliers: { seller_id: user.id })

      end
      # def resolve_admin_custom
      #   Product.joins(:supplier).where("supplier_id" => 2)
      # end
    end
  end

end
```

For instance here when I create a quotation, connected as seller with id 1 I have only access to the products owned by supplier that seller 1 deal with   

![final_5cf8cc58f93dfd001368fa07_830653](https://user-images.githubusercontent.com/24680535/59019065-94157300-8847-11e9-86bb-9226c5cb7835.gif)

Let me know if that answer to your question

**Comment by nickcharlton** [comment]
I'm going to close this as it's been inactive for a long time, plus there's a solution which addresses the original problem mentioned.
