### ISSUE TITLE
DateTime fields blank out for values that are already set

### ISSUE THREAD

**Issue by jcutrell** [thoughtbot/administrate#135]
Fields set as `Field::DateTime` seem to be automatically emptied out (rather than retaining their on-load value). Assuming this has something to do with the datepicker js, as it flashes the value for a moment presumably before the javascript executes.

**Comment by graysonwright** [comment]
@jcutrell thanks for reporting this. Right now datepickers are one of the brittle areas of the codebase, so we're working on improving this.

If you'd like to disable the form picker for those fields until we have a fix, you can run:
`rails generate administrate:views:field DateTime`, and then remove the `class: "datetimepicker"` from the generated `app/views/fields/date_time/_form.html.erb`

**Comment by jcutrell** [comment]
Sure, graysonwright!

Looks like this is probably caused by the format of the date coming in. It can be fixed by changing [this line](https://github.com/thoughtbot/administrate/blob/master/administrate/app/assets/javascripts/administrate/components/date_time_picker.js#L2) to something like this:

```
$(".datetimepicker").datetimepicker({ format: "2015-11-14 14:51:35 UTC
YYYY-MM-DD HH:mm:ss zz" });
```

Or, of course, from the other side on the actual `date_time` form.

**Comment by prrrnd** [comment]
Also, the datepickers seem to pick date and time by default, even on date fields.

**Comment by mattgillooly** [comment]
This issue is blocking me from being able to replace an ActiveAdmin deployment with Administrate.

**Comment by graysonwright** [comment]
@jcutrell and @mattgillooly - there's a fix for this in review at #194 - it's part of the [0.1.1 milestone], so it will go out with the rest of those changes.

[0.1.1 milestone](https://github.com/thoughtbot/administrate/milestones/0.1.1)

**Comment by mattgillooly** [comment]
Thanks!  Just deployed my app with the new version.  Picker looks good on my DateTimes!

**Comment by graysonwright** [comment]
Great to hear!

**Comment by jcutrell** [comment]
👌

**Comment by airjoshb** [comment]
I am having this problem currently v. 0.3.0 on rails 4.2, making it very difficult to update records.
