### ISSUE TITLE
Selector for belongs_to needs include_blank: true if column is nullable

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#136]
If you have a foreign key on your model and it `belongs_to` another model, but the foreign key column is not defined with `null: false`, then the select box that's rendered for that attribute should not be set to a value from the second model by default, i.e., it needs be rendered with `include_blank: true`.

**Comment by carlosramireziii** [comment]
I believe this is fixed in `v0.3.0` as per [this commit](https://github.com/thoughtbot/administrate/commit/fcd3fc7da4f13b5c3d9b08bb4add1ed2510958fe#diff-26cf978258ebdcd49bfbab61d8d7eabc).

Let me know if you see otherwise. Thanks!

**Comment by mcmire** [comment]
Ah, could be. I notice I made this a while back. I don't recall having a problem like this recently.

**Comment by carlosramireziii** [comment]
Okay. If you see it come up again, feel free to re-open. Closing for now. Thanks!
