### ISSUE TITLE
Don't search my edit route for id

### ISSUE THREAD

**Issue by rodrigovirgilio** [thoughtbot/administrate#1368]
The route through the slug field and not id see:

![Screenshot 2019-06-26 16 18 51](https://user-images.githubusercontent.com/392677/60208254-2fd64580-982e-11e9-9125-ae8a0d8e83c4.png)

The correct would be:

`/admin/customers/1/edit`

My controller:

```ruby
module Admin
  class CustomersController < Admin::ApplicationController
  end
end
```

My dashboard:

```ruby
require "administrate/base_dashboard"

class CustomerDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    company: Field::BelongsTo,
    id: Field::Number,
    name: Field::String,
    slug: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    contract_start_at: Field::DateTime,
    contract_end_at: Field::DateTime,
    observation: Field::Text,
    logo: Field::String,
    cnpj: Field::String,
  }.freeze

  COLLECTION_ATTRIBUTES = [
    :company,
    :id,
    :name,
  ].freeze

  SHOW_PAGE_ATTRIBUTES = [
    :company,
    :id,
    :name,
    :slug,
    :created_at,
    :updated_at,
    :contract_start_at,
    :contract_end_at,
    :observation,
    :logo,
    :cnpj,
  ].freeze

  FORM_ATTRIBUTES = [
    :company,
    :name,
    :slug,
    :contract_start_at,
    :contract_end_at,
    :observation,
    :logo,
    :cnpj,
  ].freeze
end
```

Thak you for support.

**Comment by davidsilveira** [comment]
Probably you are using the FriendlyId gem.

Maybe you can solve this problem uncommenting the following code in your model:

# app/controllers/admin/your_model_controller.rb
# Define a custom finder by overriding the `find_resource` method: 
def find_resource(param) 
    YourModel.find_by!(slug: param) 
end

**Comment by rodrigovirgilio** [comment]
worked with:

```ruby
def find_resource(param)
  Customer.find_by!(slug: param)
end
```

thank you

**Comment by GeoffAbtion** [comment]
This issue can be closed?

**Comment by davidsilveira** [comment]
@GeoffAbtion Yeah, I think you can close this issue.  @rodrigovirgilio how about you?

**Comment by rodrigovirgilio** [comment]
Yes, you can close it.

**Comment by januszm** [comment]
`Customer.friendly.find(params[:id])` should allow both id and slug
