### ISSUE TITLE
Use Administrate with a separate namespace

### ISSUE THREAD

**Issue by cristianogregnanin** [thoughtbot/administrate#1375]
I want use Administrate with an other namespace (supervisor), something like this:

- app/controllers/supervisor/users_controller.rb
- app/dashboards/supervisor/user.rb
- app/model/user.rb
- app/views/supervisors/users 

I want to do this becouse I just have the admin namespace but the supervisor should manage different resources than the admin and he must see different views.

I have spent some hours in the Administrate's source code but I haven't found the solution.
It seems that the problem is due to the fact that there is no way to insert dashboards in namespaces.

**Comment by nickcharlton** [comment]
Hi @cristianogregnanin!

We do have this feature, but it's hidden away in the generators so I'd not expect you to find it very easily.

I opened #1379 to add some documentation for this, let me know there if it's clear enough!
