### ISSUE TITLE
Move sample Rails app to separate repo or folder

### ISSUE THREAD

**Issue by maclover7** [thoughtbot/administrate#138]
Currently the sample Rails application is taking up most of the root file path, and the administrate gem itself is nested under the administrate folder. It might make more sense if the gem itself took up the root file path, and if the sample app is moved to a separate repository, or to a "sample_app" directory.

**Comment by graysonwright** [comment]
@maclover7 yep - we just realized that it's impossible to point your Gemfile at the administrate master branch, so bringing the gem to the root of the repo is a top priority for us now.

@danbee is currently working on this [in a branch](https://github.com/thoughtbot/administrate/tree/swap-gem-and-test-app) - we should have it up by the end of the week.

**Comment by maclover7** [comment]
:+1:

**Comment by graysonwright** [comment]
@danbee on your branch, how did you get `.env` working? I'm getting failing tests with the message: 
```
Missing `secret_token` and `secret_key_base` for 'test' environment, set these values in `config/secrets.yml`
```

**Comment by danbee** [comment]
I think I had a leftover `.env` file in the `app` directory when I ran them. I'm still figuring out how it all fits together this way!

**Comment by graysonwright** [comment]
Closing this in favor of #144 - let's move the discussion over there.

Thanks!
