### ISSUE TITLE
Search query and MySQL

### ISSUE THREAD

**Issue by prrrnd** [thoughtbot/administrate#140]
Hi,

The search query uses ILIKE, which is not available when using a MySQL database.
Any support for MySQL planned? Should I create a PR?

See https://github.com/thoughtbot/administrate/blob/master/administrate/lib/administrate/search.rb#L21

**Comment by graysonwright** [comment]
@prrrnd the plan is to extract that database-specific logic into an `Administrate::DB::Postgres` class, and add adapters for different databases alongside it.

I don't think I'll get an opportunity to work on this until the weekend - if you want to start in on it, that would be great!

**Comment by prrrnd** [comment]
@graysonwright I see. I'll try to start on this before the weekend.

**Comment by croaky** [comment]
Interim solution at https://github.com/thoughtbot/administrate/pull/166

**Comment by graysonwright** [comment]
The interim solution should hold until we have a solution for #143.
