### ISSUE TITLE
Not able to install with rails 6.0.0

### ISSUE THREAD

**Issue by prateekkish** [thoughtbot/administrate#1401]
Trying to install administrate 0.11.0 with rails 6.0.0.
Actionpack compatibility fails.

Error:

```Bundler could not find compatible versions for gem "actionpack":
  In snapshot (Gemfile.lock):
    actionpack (= 6.0.0)

  In Gemfile:
    administrate (~> 0.11.0) was resolved to 0.11.0, which depends on
      actionpack (>= 4.2, < 6.0)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      actionpack (= 6.0.0)

    administrate (~> 0.11.0) was resolved to 0.11.0, which depends on
      sass-rails (~> 5.0) was resolved to 5.1.0, which depends on
        sprockets-rails (>= 2.0, < 4.0) was resolved to 3.2.1, which depends on
          actionpack (>= 4.0)

**Comment by rwojnarowski** [comment]
temp solution for this issue is using master branch for this gem:
`gem "administrate", git: "https://github.com/thoughtbot/administrate.git"`

**Comment by nickcharlton** [comment]
Thanks for reporting this!

We need to put out a release soon, and do some basic regression testing against Rails 6. I hope to do this this week (w/b: 2019-08-19).

**Comment by mattgaudio** [comment]
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    administrate was resolved to 0.6.0, which depends on
      actionpack (>= 4.2, < 5.1)

    rails (~> 6.0.0) was resolved to 6.0.0, which depends on
      actionpack (= 6.0.0)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 6.0.0)

    administrate was resolved to 0.2.2, which depends on
      rails (~> 4.2)

**Comment by prateekkish** [comment]
> Bundler could not find compatible versions for gem "actionpack":
> In Gemfile:
> administrate was resolved to 0.6.0, which depends on
> actionpack (>= 4.2, < 5.1)
> 
> ```
> rails (~> 6.0.0) was resolved to 6.0.0, which depends on
>   actionpack (= 6.0.0)
> ```
> 
> Bundler could not find compatible versions for gem "rails":
> In Gemfile:
> rails (~> 6.0.0)
> 
> ```
> administrate was resolved to 0.2.2, which depends on
>   rails (~> 4.2)
> ```

Check out @rwojnarowski 's comment. That works as a temporary solution till there's a new release that supports rails 6.0.

**Comment by prateekkish** [comment]
> Thanks for reporting this!
> 
> We need to put out a release soon, and do some basic regression testing against Rails 6. I hope to do this this week (w/b: 2019-08-19).

@nickcharlton Any updates on this?

**Comment by nickcharlton** [comment]
There's some problems with model loading (see: #1406) which is holding us back, this took up enough time that I didn't get much further in being ready for a release. It'll be during this week, though.

**Comment by prateekkish** [comment]
Are we waiting on a dependency to push out a release?

**Comment by nickcharlton** [comment]
Yes, and that dependency was me. 👀 

There was a bit more work I ended up doing, but [0.12.0](https://github.com/thoughtbot/administrate/releases/tag/v0.12.0) is out now.
