### ISSUE TITLE
Allow choosing attributes for rendering nested records instead of using FORM_ATTRIBUTES

### ISSUE THREAD

**Issue by robinboening** [thoughtbot/administrate#1414]
Lets talk about some imaginary models to show the issue: `User` has_one `Account`

```
# 
ATTRIBUTE_TYPES = {
  ...,
  account: Field::HasOne,
  ...
}
```

```
# dashboards/account_dashboard.rb
...
SHOW_PAGE_ATTRIBUTES = [:user, :number].freeze
FORM_ATTRIBUTES = [].freeze
```

## Actual behavior:

In the User#show view I see the user attributes. Though, for the `has_one` association I can only see the legend of the fieldset but no attributes.

Once I add an attribute to the list of `FORM_ATTRIBUTES` in `dashboards/account_dashboard.rb` they appear to be rendered in the fieldset for User#show.

## Expected behavior:

In the User#show view, for the nested has_one resource `account` I expect the attributes being taken from the `SHOW_PAGE_ATTRIBUTES` because I am currently looking at User#show.

## Notes

If you check the code of the has_one view https://github.com/thoughtbot/administrate/blob/master/app/views/fields/has_one/_show.html.erb#L26 you will see its calling the resource's attributes on `field.nested_form` which is an instance of `Page::Form` which therefore provides the attributes from the `FORM_ATTRIBUTES` array.

I suggest adding a method to `Field::HasOne`which basically does the same as `nested_form` but initialises a `Page::Show` object.

Cheers
Robin

**Comment by robinboening** [comment]
Earlier today I was thinking about this again and noticed neither `FORM_ATTRIBUTES` nor `SHOW_PAGE_ATTRIBUTES ` would show you exactly what you'd define the right or useful information in a nested table context.

Let me bring up two real life examples with this two models: Order has many Payments

When using `FORM_ATTRIBUTES` for nested tables:
Once a payment for an order is recorded by a `Payment` object it should never be deleted or updated again. I define my authorization rules to prohibit anyone from doing so. I also empty administrate's `FORM_ATTRIBUTES` array in `PaymentDashboard` to make this expressively clear. Now the effect is my nested payments table is not showing any data anymore.

When using `SHOW_PAGE_ATTRIBUTES` for nested tables:
In `Order#show` I want to see order details and related information. An order has many payments and therefore nests them in a table. That payments table most likely renders the reference to the order (probably `Order#id`) because it is very useful information in the context of `Payment#show` but it is redundant  information in the nested context since I am already looking at the details of this specific order.

So, I believe what I am saying is: Whatever existing attribute collection is presented in a nested resource, it might not be the exact right information. How about another Array like `SHOW_NESTED_ATTRIBUTES` so you are free to define what information is presented when rendering a nested resource?

Happy to discuss. 🤙

**Comment by nickcharlton** [comment]
@robinboening, it's obviously been quite a long time since you opened this but is this still something you'd like to work on? I'm thinking — re-reading it all now — that adding another constant would be a good idea as when something nested you might well want to show different attributes.

**Comment by nickcharlton** [comment]
As I'm walking through all of the issues, I noticed that #1559 (which has a potential solution in it) is talking about the same thing. I'm going to close this one to merge them together.
