### ISSUE TITLE
disable pagination for some models

### ISSUE THREAD

**Issue by aksharj** [thoughtbot/administrate#1423]
Hello All,

I want to disable pagination for a couple of models, can you please help as to what is the preferred way.

i am currently doing it using below code, bit not sure if its the preferred way

```
    def index
      params[:per_page] =  1000
    end
```

I also tried  this as suggested on kaminari wiki

```
class User < ActiveRecord::Base
  paginates_per 50
end
```

but the above does not work, any help on this would be really great. Thanks.

**Comment by pablobm** [comment]
That's an ok solution. Administrate also offers the hook `records_per_page`, as described in the generated `Admin::ApplicationController`. See it at https://github.com/thoughtbot/administrate/blob/master/lib/generators/administrate/install/templates/application_controller.rb.erb#L17

**Comment by pablobm** [comment]
I'm closing this, as I think that might be good enough. Happy to reopen if anyone disagrees.
