### ISSUE TITLE
Feature Request: Make it ORM-agnostic

### ISSUE THREAD

**Issue by mrbrdo** [thoughtbot/administrate#143]
We are using Sequel and are looking for a decent admin (which is a problem even if using ActiveRecord). Since this project still seems young and showing promise, it would be nice if you could extract ORM-specific operations into a separate module so they can more easily be changed for a different ORM.

I think the only difficult thing I found in respect to Sequel was assoc_ids getter/setter which does not exist in Sequel. But it's not that big of a deal as it is not too hard to implement (although it would be nicer if this could be handled in the controller instead of unconditionally offloading it to the model, which may not be able to handle it in some ORMs).

I got most of it working with these monkey-patches: https://gist.github.com/mrbrdo/56da0dd984b4191a7273

I would be willing to provide Sequel implementations for such a module.

Cheers

**Comment by graysonwright** [comment]
@mrbrdo thanks for your interest! I don't have much experience with Sequel, so I'd need to look into it a bit. Is there a good sample Rails application that uses Sequel that I could use to test with? I'd like to try out your monkeypatches to get a feel for how they would work.

I think we can change the Administrate API a bit to make it easier to implement Sequel support, without requiring as much monkeypatching. I'll pull you in when we have those conversations.

Thanks!

**Comment by mrbrdo** [comment]
Hey,

Not sure for sample apps, I was able to find this app which is using a recent version of Rails with Sequel:
https://github.com/nathanl/searchlight_demo

Other than that, https://github.com/TalentBox/sequel-rails is usually used for Rails integration (as in the above app).

Note that I just monkey-patched enough to get the thing going on our project (which is for a client so I can't disclose code, unfortunately). So I'm not claiming it makes everything work.

I really hope it will be possible to "adapterize" the ORM in administrate, as you probably know the choices in administration frameworks for Rails is not that great even when using ActiveRecord, but when using another ORM it's really a serious issue. So my wish is to have a flexible enough adapter system that people can implement adapters for various ORMs, even though of course it may not be possible to do it for all of them (if they are radically different).

As I said I will be happy to provide a Sequel adapter implementation.

PS: Initially I was going to mention https://github.com/ianwhite/orm_adapter but after taking a closer look it does not have that many features (e.g. no reflection support). One possibility, although a bit more time-consuming, would be to create a similar library with expanded functionality that is needed in Administrate. Maybe people would pick it up and cover other ORM features in the future. But this is just a tangent, it would always be possible to extract the adapter system out later if it seems like it could be used for other purposes.

**Comment by diddeb** [comment]
> Make it ORM-agnostic
:+1: 

We're on a highly custom domain model, using our own backend (not Sequel, not AR). If the internals of the API were a bit more general we could make our own adapters and make it work fine.

**Comment by graysonwright** [comment]
Good to know there's demand!

@diddeb - what operations would you need to be able to customize to get this working in your app? (e.g. finding all records, single-record lookup, looking up associated has_many/has_one objects, etc).

Phrased differently: Where does your domain model differ from ActiveRecord, from the perspective of the controller layer?

**Comment by mrbrdo** [comment]
Let me jump in and list a few that I know are an issue for Sequel:
- association reflection (and other reflection like column_types, attribute_names etc)
- assoc_ids getter/setter for "has_many"
- pagination
- looking up associated has_many/has_one objects (unless using `association_proxies` plugin)

**Comment by diddeb** [comment]
@graysonwright Of course @mrbrdo's thoughts above apply to my concerns as well. But in our particular case (and I am *not* saying it's a mainstream case) we pretty much deal with PORO's fetched and updated through an event bus via external systems.

Upon reviewing the codebase I believe the internals of the API could be a bit more relaxed and not assume AR (or any other ORM) straight off. But, with that said: I am fairly certain we can make it work right now using proxy objects and some real Freedom Patching™ by basically adding support for association fetching, mass ID alignments and such.

If you're open to the idea of "opening up" and perhaps modularizing the ORM support, let me know! I will gladly make sure the team here contributes with what we come up with.

And if I did not come across clearly: I am super-glad to see this project coming out onto the stage. It's long overdue something leveraging the Rails way of doing things. Thanks!

**Comment by graysonwright** [comment]
@diddeb thanks! I'm glad to see there's so much interest in it!

I definitely want to open up and modularize support for ORMs. If you find any points in the API where it's particularly bad to hack around things, let me know and we can open it up more. :smile: 

At the moment I'm focusing on stability, so this might get pushed off for a week or so. If you make any progress before then, let me know!

**Comment by diddeb** [comment]
@graysonwright You bet. Thanks for your efforts!

**Comment by mrbrdo** [comment]
```
At the moment I'm focusing on stability, so this might get pushed off for a week or so.
```
If you start working on this in "a week or so" that's much better than what I expected. Nice to see development is so active. :+1: Let us know when you got some idea how to tackle this, I'd be happy to provide input. My general feeling was proxy/adapter objects for model classes, model instances and relations (querying) would work pretty well and would not be too difficult to implement.

**Comment by diddeb** [comment]
:+1: to what @mrbrdo said.

**Comment by DamirSvrtan** [comment]
:+1: for sequel

**Comment by graysonwright** [comment]
@mrbrdo you're right, I was a bit ambitious on the timeline. :smile: 

we released `0.1.1` with bug fixes, and we'll follow it up with more fixes and stability issues in `0.1.2`. If all goes well, I'd like to define a standard plugin structure ( #123 ) by `0.1.3`, so I'm tentatively scheduling this for `0.1.4`.

**Comment by mrbrdo** [comment]
No worries. How is it looking now time-wise?

**Comment by graysonwright** [comment]
@mrbrdo I'm hoping that we can make strides on this by mid-December.

**Comment by graysonwright** [comment]
From #279: request for ActiveResource support.

**Comment by graysonwright** [comment]
From #240: requests for Mongoid and RethinkDB.

**Comment by mrbrdo** [comment]
@graysonwright now we're getting closer to my original estimate of how long this will take :)

**Comment by mrbrdo** [comment]
I'm working on this.

**Comment by mrbrdo** [comment]
https://github.com/mrbrdo/administrate/commits/orm_adapters
Something like this. It's not all the way there and I should also run the tests if something broke.
But we are testing this on our Sequel app now so I'll try to iron out any remaining bugs. I'm still using monkeypatches for *_ids methods and for kaminari.
The idea is that ORM-specific objects are always wrapped.

**Comment by mrbrdo** [comment]
I'm pretty much done with Sequel, seems to work well on our app. I still have to test if I broke anything with my AR refactor, will run specs and see.
I think I can PR early next week.

**Comment by bruzos** [comment]
do you have plans to support mongoldb??

**Comment by mrbrdo** [comment]
It should be possible with this system, but I don't have any plans myself to add an adapter for mongo.

**Comment by co-github** [comment]
@mrbrdo would it be possible for me to test your Sequel adapter?

**Comment by mrbrdo** [comment]
what do you mean? of course it's possible...
@graysonwright so...

**Comment by graysonwright** [comment]
@mrbrdo - Thanks for putting together #474! I haven't looked it over in detail yet, but from what I've seen it looks great.

There are a few refactorings that I think need to happen, and I'm not sure what the best order for them is. I'll update when I have an idea how to proceed. Thanks!

**Comment by pmackay** [comment]
@graysonwright what kinds of refactorings were you thinking about here? Might you be able to add them to the PR? Just wondering if this can move forward with @mrbrdo's work.

**Comment by thecalliopecrashed** [comment]
Alright, it seems like this thread petered out with a clear direction in mind.
I'll close it out so we can boot up discussion again on #474.

Thank you @mrbrdo!
