### ISSUE TITLE
Demo on Heroku does not work

### ISSUE THREAD

**Issue by diegotoral** [thoughtbot/administrate#1443]
* What were you trying to do?
Access the demo at https://administrate-prototype.herokuapp.com/admin

* What did you end up with (logs, or, even better, example apps are great!)?
Heroku's default error page

**Comment by nickcharlton** [comment]
Huh, interesting. I'm not seeing an error now. Could you try again?

I'm wondering if you were unlucky enough to hit the demo app when the scheduled cleaning job runs, or if Heroku was having problems.

**Comment by diegotoral** [comment]
hey @nickcharlton I think you are right. checked out and everything seems to be working just fine.

I tried to access the demo a couple of times before posting an issue though.

Thank you!
