### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by aksharj** [thoughtbot/administrate#1445]
Hello All,

I am trying to implement a bulk delete of users model where we can select multiple user records via checkbox and delete them at once.

Can anyone please point me in the right direction as to how best to achieve this, Thanks.

**Comment by nickcharlton** [comment]
There's not currently a way to go about this with Administrate as is. A solution here might be to extend the field to do it, but that doesn't sound very elegant.

I'm going to close this as #184 would provide a better place to discuss what an ideal solution to this might look like.

**Comment by andreibondarev** [comment]
@aksharj You can use https://github.com/SourceLabsLLC/administrate_batch_actions to pull in bulk user deletion.
