### ISSUE TITLE
issues with `rake routes`

### ISSUE THREAD

**Issue by astamm78** [thoughtbot/administrate#145]
Half the time when I run my `rake routes` command I get the following error:

RailsApp/config/routes.rb:26:in `block (2 levels) in <top (required)>': uninitialized constant DashboardManifest (NameError)

Other times my routes print correctly to the console, but there's no listing for my admin namespaced routes.

I've seen the `uninitialized constant DashboardManifest (NameError)` error pop up randomly when using generators as well, but the error doesn't seem to appear consistently.

**Comment by graysonwright** [comment]
@astamm78 If you've already run the `administrate:install` generator, it has added a block to your `config/routes.rb` that sets up routes for your admin interface.

If you've deleted your `DashboardManifest`, then the routing logic will fail with the `uninitialized constant` error. Rails generators load in the routes file, so you're in a bit of a chicken-and-egg situation: you can't re-generate the `DashboardManifest` without valid routes, and your routes aren't valid without the `DashboardManifest`.

Try deleting these generated lines from your `config/routes.rb`, then re-run `rails generate administrate:install`.

```ruby
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end
```

**Comment by astamm78** [comment]
I hadn't deleted my DashboardManifest file, I did edit it a little, reordered some of the models

I tried your advice above, but then hit this error:

/Users/andrewstamm/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:in `const_get': wrong constant name #<class:0x007fcef5181b38> (NameError)

**Comment by graysonwright** [comment]
Hm, can you post the contents of your `DashboardManifest`?

Also, can you run `ActiveRecord::Base.descendants` in your rails console, and paste the output?

**Comment by astamm78** [comment]
Contents of `DashboardManifest`

# DashboardManifest tells Administrate which dashboards to display
class DashboardManifest
  # `DASHBOARDS`
  # a list of dashboards to display in the side navigation menu
  #
  # These are all of the rails models that we found in your database
  # at the time you installed Administrate.
  #
  # To show or hide dashboards, add or remove the model name from this list.
  # Dashboards returned from this method must be Rails models for Administrate
  # to work correctly.
  DASHBOARDS = [
    :users,
    :admin_users,
    :travel_books,
    :travel_pages,
    :color_themes,
    :comments,
    :followings,
    :regions,
    :specialties
  ]

  # `ROOT_DASHBOARD`
  # the name of the dashboard that will be displayed
  # at "http://your_site.com/admin"
  #
  # This dashboard will likely be the first page that admins see
  # when they log into the dashboard.
  ROOT_DASHBOARD = DASHBOARDS.first
end

Output of `ActiveRecord::Base.descendants`

[#<Class:0x007fcef5181b38>(travel_book_id: integer, region_id: integer), #<Class:0x007fcef51b75a8>(travel_book_id: integer, specialty_id: integer), #<Class:0x007fcef51d4888>(travel_book_id: integer, travel_page_id: integer), #<Class:0x007fcef850aea0>(user_id: integer, specialty_id: integer), #<Class:0x007fcef6fb4970>(user_id: integer, specialty_id: integer), #<Class:0x007fcef445fe28>(user_id: integer, specialty_id: integer), #<Class:0x007fcef9c9b8a8>(user_id: integer, specialty_id: integer), #<Class:0x007fcef6eeb980>(user_id: integer, specialty_id: integer), #<Class:0x007fcef869db50>(user_id: integer, specialty_id: integer), #<Class:0x007fcef83e5980>(user_id: integer, specialty_id: integer), #<Class:0x007fcef81a83e8>(user_id: integer, specialty_id: integer), #<Class:0x007fcef525f028>(user_id: integer, specialty_id: integer), AdminUser(id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: inet, last_sign_in_ip: inet, created_at: datetime, updated_at: datetime), User(id: integer, name: string, dob: date, gender: string, location: string, ta_record_number: string, agency_name: string, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: inet, last_sign_in_ip: inet, created_at: datetime, updated_at: datetime, api_token: string, access_token: string, access_provider: string, access_uid: string, image: string, color_theme_id: integer), User::HABTM_Specialties(user_id: integer, specialty_id: integer), ColorTheme(id: integer, color_1: string, color_2: string, color_3: string), TravelBook(id: integer, name: string, user_id: integer, published: boolean, created_at: datetime, updated_at: datetime), TravelBook::HABTM_Regions(travel_book_id: integer, region_id: integer), TravelBook::HABTM_Specialties(travel_book_id: integer, specialty_id: integer), TravelBook::HABTM_TravelPages(travel_book_id: integer, travel_page_id: integer)]

**Comment by graysonwright** [comment]
Ah, @astamm78  - I think it's having trouble with the models nested under the `TravelBook` module.

We currently don't support namespaced models like that, but it's on our roadmap.

**Comment by astamm78** [comment]
You mean Model relations like this?

`  has_many :created_travel_pages, class_name: "TravelPage", inverse_of: :primary_travel_book`

**Comment by graysonwright** [comment]
That kind of relationship should be fine. I think it's hitting an error with the dynamically generated classes in your application (in the `ActiveRecord::Base.descendants`, those are the classes like `#<Class:0x007fcef5181b38>`).

Is your codebase open-source? It might be easier to debug if I can poke around a bit.

If not, can you post your `Gemfile` and `Gemfile.lock`?

**Comment by astamm78** [comment]
So, I tore out my previous installation of the administrate gem and started from scratch… I'm still running into the `uninitialized constant DashboardManifest (NameError)` error despite a clean install with no customization.

I re-ran `ActiveRecord::Base.descendants` and got different output this time:

[#<Class:0x007f9b3a3e8320>(travel_book_id: integer, region_id: integer), #<Class:0x007f9b3a51e820>(travel_book_id: integer, specialty_id: integer), #<Class:0x007f9b3a52c470>(travel_book_id: integer, travel_page_id: integer), #<Class:0x007f9b3a346200>(user_id: integer, specialty_id: integer), ColorTheme(id: integer, color_1: string, color_2: string, color_3: string), TravelBook(id: integer, name: string, user_id: integer, published: boolean, created_at: datetime, updated_at: datetime), TravelBook::HABTM_Regions(travel_book_id: integer, region_id: integer), TravelBook::HABTM_Specialties(travel_book_id: integer, specialty_id: integer), TravelBook::HABTM_TravelPages(travel_book_id: integer, travel_page_id: integer), User(id: integer, name: string, dob: date, gender: string, location: string, ta_record_number: string, agency_name: string, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: inet, last_sign_in_ip: inet, created_at: datetime, updated_at: datetime, api_token: string, access_token: string, access_provider: string, access_uid: string, image: string, color_theme_id: integer), User::HABTM_Specialties(user_id: integer, specialty_id: integer)]

`Gemfile`

source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'active_model_serializers', '~>0.9.0'
gem 'administrate'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'carrierwave'
gem 'carrierwave_backgrounder'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'fog', '~> 1.20', require: 'fog/aws/storage'
gem 'haml-rails', '~> 0.9'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mini_magick'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sidekiq'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0'
  gem 'shoulda-matchers'
end

group :development do
  gem 'faker'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

`Gemfile.lock`

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.2)
    actionmailer (4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.4)
      actionview (= 4.2.4)
      activesupport (= 4.2.4)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    activejob (4.2.4)
      activesupport (= 4.2.4)
      globalid (>= 0.3.0)
    activemodel (4.2.4)
      activesupport (= 4.2.4)
      builder (~> 3.1)
    activerecord (4.2.4)
      activemodel (= 4.2.4)
      activesupport (= 4.2.4)
      arel (~> 6.0)
    activesupport (4.2.4)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    administrate (0.1.0)
      autoprefixer-rails (~> 6.0)
      datetime_picker_rails (~> 0.0.5)
      inline_svg (~> 0.6)
      kaminari (~> 0.16)
      momentjs-rails (~> 2.8)
      neat (~> 1.1)
      normalize-rails (~> 3.0)
      rails (~> 4.2)
      sass (~> 3.4)
      selectize-rails (~> 0.6)
    arel (6.0.3)
    autoprefixer-rails (6.0.3)
      execjs
      json
    bcrypt (3.1.10)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-sass (3.2.0.2)
      sass (~> 3.2)
    bourbon (4.2.6)
      sass (~> 3.4)
      thor (~> 0.19)
    builder (3.2.2)
    byebug (6.0.2)
    carrierwave (0.10.0)
      activemodel (>= 3.2.0)
      activesupport (>= 3.2.0)
      json (>= 1.7)
      mime-types (>= 1.16)
    carrierwave_backgrounder (0.4.2)
      carrierwave (~> 0.5)
    celluloid (0.17.2)
      celluloid-essentials
      celluloid-extras
      celluloid-fsm
      celluloid-pool
      celluloid-supervision
      timers (>= 4.1.1)
    celluloid-essentials (0.20.5)
      timers (>= 4.1.1)
    celluloid-extras (0.20.5)
      timers (>= 4.1.1)
    celluloid-fsm (0.20.5)
      timers (>= 4.1.1)
    celluloid-pool (0.20.5)
      timers (>= 4.1.1)
    celluloid-supervision (0.20.5)
      timers (>= 4.1.1)
    coffee-rails (4.1.0)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.9.1.1)
    connection_pool (2.2.0)
    database_cleaner (1.5.1)
    datetime_picker_rails (0.0.5)
      momentjs-rails (>= 2.8.1)
    debug_inspector (0.0.2)
    devise (3.5.2)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    devise-bootstrap-views (0.0.6)
    diff-lcs (1.2.5)
    erubis (2.7.0)
    excon (0.45.4)
    execjs (2.6.0)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.5.0)
      i18n (~> 0.5)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.35.0)
      fog-aliyun
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (>= 0.1.1)
      fog-json
      fog-local
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      nokogiri
    fog-aliyun (0.0.10)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.7.6)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.9.0)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-core (1.32.1)
      builder
      excon (~> 0.45)
      formatador (~> 0.2)
      mime-types
      net-scp (~> 1.1)
      net-ssh (>= 2.1.3)
    fog-dynect (0.0.2)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.1)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.2.1)
      fog-core (~> 1.27)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-radosgw (0.0.4)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.3.3)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.0.1)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-xenserver (0.2.2)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    haml (4.0.7)
      tilt
    haml-rails (0.9.0)
      actionpack (>= 4.0.1)
      activesupport (>= 4.0.1)
      haml (>= 4.0.6, < 5.0)
      html2haml (>= 1.0.1)
      railties (>= 4.0.1)
    hitimes (1.2.3)
    html2haml (2.0.0)
      erubis (~> 2.7.0)
      haml (~> 4.0.0)
      nokogiri (~> 1.6.0)
      ruby_parser (~> 3.5)
    i18n (0.7.0)
    inflecto (0.0.2)
    inline_svg (0.6.1)
      activesupport (>= 4.0.4)
      loofah (>= 2.0)
      nokogiri (~> 1.6)
    ipaddress (0.8.0)
    jbuilder (2.3.2)
      activesupport (>= 3.0.0, < 5)
      multi_json (~> 1.2)
    jquery-rails (4.0.5)
      rails-dom-testing (~> 1.0)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    kaminari (0.16.3)
      actionpack (>= 3.0.0)
      activesupport (>= 3.0.0)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mime-types (2.6.2)
    mini_magick (4.3.6)
    mini_portile (0.6.2)
    minitest (5.8.1)
    momentjs-rails (2.10.6)
      railties (>= 3.1)
    multi_json (1.11.2)
    neat (1.7.2)
      bourbon (>= 4.0)
      sass (>= 3.3)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (3.0.1)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    normalize-rails (3.0.3)
    orm_adapter (0.5.0)
    pg (0.18.3)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.4)
      actionmailer (= 4.2.4)
      actionpack (= 4.2.4)
      actionview (= 4.2.4)
      activejob (= 4.2.4)
      activemodel (= 4.2.4)
      activerecord (= 4.2.4)
      activesupport (= 4.2.4)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.4)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.2)
      loofah (~> 2.0)
    railties (4.2.4)
      actionpack (= 4.2.4)
      activesupport (= 4.2.4)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    rdoc (4.2.0)
    redis (3.2.1)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    responders (2.1.0)
      railties (>= 4.2.0, < 5)
    rspec-core (3.3.2)
      rspec-support (~> 3.3.0)
    rspec-expectations (3.3.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-mocks (3.3.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.3.0)
    rspec-rails (3.3.3)
      actionpack (>= 3.0, < 4.3)
      activesupport (>= 3.0, < 4.3)
      railties (>= 3.0, < 4.3)
      rspec-core (~> 3.3.0)
      rspec-expectations (~> 3.3.0)
      rspec-mocks (~> 3.3.0)
      rspec-support (~> 3.3.0)
    rspec-support (3.3.0)
    ruby_parser (3.7.1)
      sexp_processor (~> 4.1)
    sass (3.4.19)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    selectize-rails (0.12.1)
    sexp_processor (4.6.0)
    shoulda-matchers (3.0.0)
      activesupport (>= 4.0.0)
    sidekiq (3.5.2)
      celluloid (~> 0.17.2)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    spring (1.4.0)
    sprockets (3.4.0)
      rack (> 1, < 3)
    sprockets-rails (2.3.3)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.1)
    timers (4.1.1)
      hitimes
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.3)
      rack (>= 1.0)
    web-console (2.2.1)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    xml-simple (1.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers (~> 0.9.0)
  administrate
  bootstrap-sass (~> 3.2.0)
  byebug
  carrierwave
  carrierwave_backgrounder
  coffee-rails (~> 4.1.0)
  database_cleaner
  devise
  devise-bootstrap-views
  factory_girl_rails
  faker
  fog (~> 1.20)
  haml-rails (~> 0.9)
  jbuilder (~> 2.0)
  jquery-rails
  mini_magick
  pg
  rails (= 4.2.4)
  rspec-rails (~> 3.0)
  sass-rails (~> 5.0)
  sdoc (~> 0.4.0)
  shoulda-matchers
  sidekiq
  spring
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

BUNDLED WITH
   1.10.6

**Comment by graysonwright** [comment]
Alright - I should have a chance to look at this more tonight, but it's rather strange to see elements in the `ActiveRecord::Base.descendants` array that don't have a constant class name.

Is your codebase open source? If not, could you grant me read access to help debug?

**Comment by astamm78** [comment]
I'll grant you read access, thanks!

**Comment by graysonwright** [comment]
@sgrif mind if I loop you in?

We're looking into an issue where there are subclasses of `ActiveRecord::Base` that aren't named constants:

```ruby
[5] pry(main)> ActiveRecord::Base.descendants
=> [#<Class:0x007fe0dfa262d8> (call '#<Class:0x007fe0dfa262d8>.connection' to establish a connection),
 #<Class:0x007fe0df9fff98> (call '#<Class:0x007fe0df9fff98>.connection' to establish a connection),
 #<Class:0x007fe0df9dc840> (call '#<Class:0x007fe0df9dc840>.connection' to establish a connection),
 #<Class:0x007fe0df8b0ea8> (call '#<Class:0x007fe0df8b0ea8>.connection' to establish a connection),
 #<Class:0x007fe0da440058> (call '#<Class:0x007fe0da440058>.connection' to establish a connection),
 AdminUser (call 'AdminUser.connection' to establish a connection),
 User (call 'User.connection' to establish a connection),
 User::HABTM_Specialties (call 'User::HABTM_Specialties.connection' to establish a connection),
 ColorTheme (call 'ColorTheme.connection' to establish a connection),
 TravelBook (call 'TravelBook.connection' to establish a connection),
 TravelBook::HABTM_Regions (call 'TravelBook::HABTM_Regions.connection' to establish a connection),
 TravelBook::HABTM_Specialties (call 'TravelBook::HABTM_Specialties.connection' to establish a connection),
 TravelBook::HABTM_TravelPages (call 'TravelBook::HABTM_TravelPages.connection' to establish a connection),
 Region (call 'Region.connection' to establish a connection),
 Region::HABTM_TravelBooks (call 'Region::HABTM_TravelBooks.connection' to establish a connection),
 Specialty (call 'Specialty.connection' to establish a connection),
 Specialty::HABTM_TravelBooks (call 'Specialty::HABTM_TravelBooks.connection' to establish a connection),
 Specialty::HABTM_Users (call 'Specialty::HABTM_Users.connection' to establish a connection),
 TravelPage (call 'TravelPage.connection' to establish a connection),
 TravelPage::HABTM_TravelBooks (call 'TravelPage::HABTM_TravelBooks.connection' to establish a connection)]
```

When I ran `ActiveRecord::Base.descendants.map(&:table_name)`, I got:

```ruby
["regions_travel_books",
 "specialties_travel_books",
 "travel_books_pages",
 "specialties_users",
 "specialties_users",
 "admin_users",
 "users",
 "specialties_users",
 "color_themes",
 "travel_books",
 "regions_travel_books",
 "specialties_travel_books",
 "travel_books_pages",
 "regions",
 "regions_travel_books",
 "specialties",
 "specialties_travel_books",
 "specialties_users",
 "travel_pages",
 "travel_books_pages"]
```

Is there some ActiveRecord magic going on here around HABTM?
If so, is there a way to detect and ignore those un-named classes?

**Comment by sgrif** [comment]
Not sure where those are coming from, but it shouldn't be Active Record. We don't assign the join model from HABTM to a constant, but we do give it a name. Can you give me an isolated script to reproduce?

**Comment by graysonwright** [comment]
yeah, I'll work on that - it might be a couple days, though - lot of issues to get through.

Thanks!

**Comment by astamm78** [comment]
I found the issue tended to only happen if I had `rails server` running, I made changes to my administrate setup and then would try to run `rake routes` … if I stopped/restarted the server then I wouldn't have the issue.

Hope this helps

**Comment by mrbrdo** [comment]
I just wanted to point out, if these classes are not being generated by ActiveRecord itself, an adapter system like we are discussing in #143 would probably make it pretty easy for the user to override this (if nothing else, monkey-patching the appropriate method of the administrate *AR adapter* would be easy and reliable).

**Comment by matthaliski** [comment]
Stopping the `rails server` from running fixed a similar problem I was having trying to generate a model. I would also get the `uninitialized constant DashboardManifest (NameError)`. All is good as long as that server isn't running.

**Comment by Rodrigora** [comment]
I'm getting this error too. Seems to be intermittent.

When it happens, I run the command again and it works!

**Comment by graysonwright** [comment]
Cool - I'm working on a fix for it now! There's also discussion in #219.

@Rodrigora by any chance, do you have `has_and_belongs_to_many` relationships in your app?

**Comment by Rodrigora** [comment]
@graysonwright thanks for the quick response.

Yes, I have a `has_and_belongs_to_many` relationship and it seems to be the problem. I commented it and the error stopped.

**Comment by graysonwright** [comment]
@sgrif looks like it is caused by `HABTM`:

```ruby
2.2.3 debug/trexa_rails (master) ✔  r r 'pp ActiveRecord::Base.descendants'
[#<Class:0x007fddea1bdf08> (call '#<Class:0x007fddea1bdf08>.connection' to establish a connection),
 #<Class:0x007fddea1a7280> (call '#<Class:0x007fddea1a7280>.connection' to establish a connection),
 #<Class:0x007fddea17f668> (call '#<Class:0x007fddea17f668>.connection' to establish a connection),
 #<Class:0x007fdde15c0a78> (call '#<Class:0x007fdde15c0a78>.connection' to establish a connection),
 AdminUser (call 'AdminUser.connection' to establish a connection),
 User (call 'User.connection' to establish a connection),
 User::HABTM_Specialties (call 'User::HABTM_Specialties.connection' to establish a connection),
 ColorTheme (call 'ColorTheme.connection' to establish a connection),
 TravelBook (call 'TravelBook.connection' to establish a connection),
 TravelBook::HABTM_Regions (call 'TravelBook::HABTM_Regions.connection' to establish a connection),
 TravelBook::HABTM_Specialties (call 'TravelBook::HABTM_Specialties.connection' to establish a connection),
 TravelBook::HABTM_TravelPages (call 'TravelBook::HABTM_TravelPages.connection' to establish a connection)]
2.2.3 debug/trexa_rails (master) ✔  r r 'pp ActiveRecord::Base.descendants.map(&:name)'
["HABTM_Regions",
 "HABTM_Specialties",
 "HABTM_TravelPages",
 "HABTM_Specialties",
 "AdminUser",
 "User",
 "HABTM_Specialties",
 "ColorTheme",
 "TravelBook",
 "HABTM_Regions",
 "HABTM_Specialties",
 "HABTM_TravelPages"]
```

I'm trying to re-create the error in my test suite, but I can't nail it down. The un-constantized models only show up intermittently.

So far, both Gemfiles have `spring` in there, so it may be related to that. :confused:

**Comment by Rodrigora** [comment]
@graysonwright maybe it can help:

inside `rails console`, calling the `reload!` method always raises the error

**Comment by graysonwright** [comment]
cool, thanks!

I figured out what's causing this, and I'm opening up a PR now. :smile:

**Comment by graysonwright** [comment]
@Rodrigora, check out https://github.com/thoughtbot/administrate/pull/259.
