### ISSUE TITLE
Turbolinks back button broken

### ISSUE THREAD

**Issue by btrewern** [thoughtbot/administrate#1454]
I have a rails app with turbolinks enabled and I'm trying to integrate administrate.
Ruby 2.6.4
Rails 6.0
Administrate 0.12.0

If i access the administrate dashboards (through a link on the app) I can move around between dashboards using links and the back button but the back button will not bring me back to the actual application.

Is this by design?  Thanks for any information.

**Comment by nickcharlton** [comment]
We don't, out of the box, include Turbolinks. There's a solution in #200 that'll allow you to pull this in.
