### ISSUE TITLE
uninitialized constant DashboardManifest (NameError)

### ISSUE THREAD

**Issue by astamm78** [thoughtbot/administrate#146]
Half the time when I run my `rake routes` command I get the following error:

RailsApp/config/routes.rb:26:in `block (2 levels) in <top (required)>': uninitialized constant DashboardManifest (NameError)

I've seen the `uninitialized constant DashboardManifest (NameError)` error pop up randomly when using generators as well, but the error doesn't seem to appear consistently.

**Comment by graysonwright** [comment]
This seems like a duplicate of #145 - I'm closing so we can keep the discussion in one place.
