### ISSUE TITLE
An user submitting a form should be able to see what fields are required.

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#1489]
When rendering a field, a user should be able to see what fields are required. Has anyone else implemented this as I'd be happy to do a PR?

**Comment by pablobm** [comment]
Hello @ACPK. I'm not aware of any work on this. I'd be happy to see a PR.

What do you have in mind? Happy to discuss before providing code too.

**Comment by davitapajos-cm42** [comment]
Hey!
What you guys think about it?

![Captura de Tela 2020-01-09 às 17 20 38](https://user-images.githubusercontent.com/54637230/72102053-d4b8fb80-3304-11ea-9ae2-d359ed1c9b8f.png)

```erb
<% page.attributes.each do |attribute| -%>
  <div class="field-unit field-unit--<%= attribute.html_class %> <%= required_field?(attribute) %>">
    <%= render_field attribute, f: f %>
  </div>
<% end -%>
```

```ruby
def required_field?(field)
  'required' if field.resource.class.validators_on(field.attribute).map(&:class).include?(ActiveRecord::Validations::PresenceValidator)
end
```

**Comment by pablobm** [comment]
Fixed at https://github.com/thoughtbot/administrate/pull/1521
