### ISSUE TITLE
Please change the example e-mail addresses to end in @example.com

### ISSUE THREAD

**Issue by lorenzk** [thoughtbot/administrate#149]
Your demo has realistic looking e-mail addresses. A lot of those probably are real. Those will get picked up by crawlers and receive spam.

Please change the demo addresses to end in @example.com, that way nobody receives those spam mails.

P.S.: That's also a good idea for all local testing you ever do. If you ever accidentally configure your dev setup with the real e-mail server, nothing bad happens.

**Comment by graysonwright** [comment]
@lorenzk Great call, thanks. I'll swap them out tonight.

**Comment by graysonwright** [comment]
Just re-ran the seeds so the app has `example.com` addresses. Thanks again for this catch!
