### ISSUE TITLE
BUG: Custom fields are not included in Search

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#1490]
Administrative searches records via a SQL query that uses the code below.

    OR Lower(Cast("public"."post"."deadline" AS CHAR(256))) 
     LIKE 
     '%scholarship%' 

If a custom Field Type is being used (i.e. changes Field::Text to RequiredRequiredField), Administrative does not include the custom field in the search query above.

The temporary fix:

Change: 

    ATTRIBUTE_TYPES = {
      id: Field::Number,
      name: RequiredStringField,
    }

To:

    ATTRIBUTE_TYPES = {
      id: Field::Number,
      name: RequiredStringField.with_options(searchable: true, searchable_field: 'name'),
    }

**Comment by pablobm** [comment]
Thank you for raising this @ACPK.

Does your custom field class implement `.searchable?`? Does making this return `true` fix the problem? It might be that implementing this, either explicitly or by inheriting from `Field::String` helps.

Let me know,

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time without a response; but please re-open if you're still struggling with this.
