### ISSUE TITLE
How can I run demo on my windows？

### ISSUE THREAD

**Issue by qq1012827513** [thoughtbot/administrate#1492]

**Comment by pablobm** [comment]
Hello @qq1012827513. I don't understand.

1. You can run the online demo on any platform by visiting https://administrate-prototype.herokuapp.com/admin/
2. You can deploy your own demo. For example to Heroku (this is where the official demo is hosted).
3. It should be possible to run the demo using Foreman, as described at https://github.com/thoughtbot/administrate/blob/master/CONTRIBUTING.md#start-application-in-development. I haven't tried on Windows though, so I'm not 100% it will work. If it doesn't work, I'm happy to accept a fix.

Please let us know if it is one of the above, or something else.

**Comment by qq1012827513** [comment]
I did it !
![a5cc6aee-3408-11e7-8bcb-c62bb7addf40](https://user-images.githubusercontent.com/29473978/70885022-96d0fc00-2012-11ea-8cee-70149f6c35bb.png)
