### ISSUE TITLE
How can I convert my properties in ‘show page‘?

### ISSUE THREAD

**Issue by qq1012827513** [thoughtbot/administrate#1499]
for example
![a5cc6aee-3408-11e7-8bcb-c62bb7addf40](https://user-images.githubusercontent.com/29473978/70981114-82166600-20ef-11ea-97a0-4ad09bc90b23.png)
and I tried
`def render_field(field, locals = {})
      case field.resource[:state] # a_variable is the variable we want to compare
      when '0'
        field.resource[:state]='未检测'
      when '1'
        field.resource[:state]='测试通过'
      when '-1'
        field.resource[:state]='测试未通过'
      when '2'
        field.resource[:state]='虚拟机测试'
      else
        field.resource[:state]='无效'
      end
      p field.resource
      locals.merge!(field: field)
      render locals: locals, partial: field.to_partial_path
    end`

its not work T_T

**Comment by qq1012827513** [comment]
I edit application_helper.rb
![image](https://user-images.githubusercontent.com/29473978/70981330-eafdde00-20ef-11ea-9004-b151e00d792d.png)

**Comment by pablobm** [comment]
Create a method in your model, with value derived from "state":

```ruby
def special_field
  case state
  when '0'
    '未检测'
  when '1'
    # ...
  end
end
```

Then use that as an attribute in your dashboard:

```ruby
special_field: Field::String,
```

Thank you for your interest in Administrate! Can I please ask you to post these questions on StackOverflow instead? Use the tag `administrate` and I'll see it and will be able to answer them: https://stackoverflow.com/questions/tagged/administrate
