### ISSUE TITLE
Enum attribute type

### ISSUE THREAD

**Issue by davit-khaburdzania** [thoughtbot/administrate#150]
it's seems like i'm unable to set enum field type

**Comment by mgrachev** [comment]
You can generate field type for enum:
```
$ rails generate administrate:field enum
  create  app/fields/enum_field.rb
  create  app/views/fields/enum_field/_show.html.erb
  create  app/views/fields/enum_field/_index.html.erb
  create  app/views/fields/enum_field/_form.html.erb
```

For enum would only need to modify the file `form.html.erb`:

```erb
<%= f.label field.attribute %>
<%= f.collection_select(
        field.attribute,
        f.object.class.public_send(field.attribute.to_s.pluralize),
        :first,
        :first,
        {},
        { multiple: false },
    )
%>
```

Then open the file dashboard and replace the `Field :: Number` on` EnumField `. Everything should work.

**Comment by graysonwright** [comment]
@mgrachev thanks! Looks like I missed this issue.

@davit-khaburdzania - if that works for you, feel free to close the issue!

**Comment by davit-khaburdzania** [comment]
@mgrachev checked it and everything seems to be works. Thanks a lot

**Comment by graysonwright** [comment]
:tada:

**Comment by pkrefta** [comment]
@graysonwright What do you think about adding Field::Enum into built-in field list ? :smiley:

**Comment by graysonwright** [comment]
@pkrefta I like the idea, added to the to-do list.

**Comment by akrisanov** [comment]
**Enum field with humanized text**

*enum_field*:
```
require 'administrate/fields/base'

class EnumField < Administrate::Field::Base
  def to_s
    data.humanize
  end
end
```

*_form.html.erb:*
```
<%= f.label field.attribute %>
<%= f.select(
  field.attribute,
  options_for_select(
    f.object.class.public_send(field.attribute.to_s.pluralize)
      .map { |k, v| [k.humanize.capitalize, k] },
      f.object.public_send(field.attribute.to_s)),
  include_blank: false) %>
```

**Comment by BillyParadise** [comment]
This breaks with current version (0.1.3) - no administrate / fields / base

**Comment by graysonwright** [comment]
@BillyParadise - sorry about that. There were breaking changes in the most recent version. Here are the release notes: https://github.com/thoughtbot/administrate/releases/tag/v0.1.4

In this case, here's the fix:

```ruby
# Change any instances of this...
require "administrate/fields/base"
# ...to this:
require "administrate/field/base"
```

**Comment by BillyParadise** [comment]
appreciated!

**Comment by balbinas** [comment]
If you guys are still having trouble with the Enum type I made it a gem, feedback is appreciated 😊. https://rubygems.org/gems/administrate-field-enum

**Comment by shreya19888** [comment]
Thanks Balbina,It worked perfectly for me!
