### ISSUE TITLE
HasOne without association routes shouldn't create link

### ISSUE THREAD

**Issue by bekicot** [thoughtbot/administrate#1517]
* What were you trying to do?
Showing `HasOne` `association` in Index page. Where `association` doesn't have the corresponding path.
e.g:
`User` has_one `Profile`. But `profile` doesn't have an admin page. 
* What did you end up with (logs, or, even better, example apps are great!)?
It raises undefined method error like `Undefined method admin_profile_path`
* What versions are you running?
  - Rails 6.0
  - Administrate 12.0

I'd like to make a fix on this. If no one has.

Labels:
`bug`, `fields`

**Comment by pablobm** [comment]
@bekicot - good spot! I can reproduce it indeed.

If you provide a fix, I'll be happy to review it. It'll probably involve using `valid_action?(:show, resource)` in the right place. I'm happy to answer questions if anything is not clear.

**Comment by bekicot** [comment]
@pablobm Sure, please assign this to me, I will work on it tommorow night. Pretty occupied today.

**Comment by pablobm** [comment]
No rush!

**Comment by nickcharlton** [comment]
@bekicot, is this something we ended up solving? I just walked through the other PRs but I can't quite be sure.

**Comment by pablobm** [comment]
I think this should have been fixed by https://github.com/thoughtbot/administrate/pull/1941 Happy to reopen if that's not the case
