### ISSUE TITLE
How to export dashboards as excel（xls xlsx）

### ISSUE THREAD

**Issue by qq1012827513** [thoughtbot/administrate#1520]

**Comment by nickcharlton** [comment]
This isn't currently something which is supported, but #1120 is looking into handling `CSV` export.

As the data would otherwise be raw, I'd expect that to cover this use case as a `CSV` can be imported into more applications than `xls`/`xlsx` can.

**Comment by andreibondarev** [comment]
Adding Excel support to this CSV exporting plugin should be relatively straight-forward: https://github.com/SourceLabsLLC/administrate_exportable
