### ISSUE TITLE
Customizing page views - missing view generators?

### ISSUE THREAD

**Issue by johnmeehan** [thoughtbot/administrate#155]
Following the documentation after a new set up.
RE:   https://administrate-docs.herokuapp.com/customizing_page_views

Following fresh set up on an existing app. running:
```
✗ rails generate administrate:views:index     
Could not find generator 'administrate:views:index'. Maybe you meant 'administrate:install', 'administrate:dashboard' or 'kaminari:views'
```
and
```
✗ rails generate administrate:views:index User
Could not find generator 'administrate:views:index'. Maybe you meant 'administrate:install', 'administrate:dashboard' or 'kaminari:views'
Run `rails generate --help` for more options.
```

**Comment by johnmeehan** [comment]
oops....
installing with just gem 'administrate' pulled me down version 0.0.4 

updating to gem 'administrate', '~> 0.1.0'
got me going.

**Comment by graysonwright** [comment]
@johnmeehan cool, glad you're set. Let us know if you run into any more issues.

Anyone else finding this issue - the current version can be found at https://rubygems.org/gems/administrate.
