### ISSUE TITLE
Can't set Nullable Fields to null

### ISSUE THREAD

**Issue by TheNeikos** [thoughtbot/administrate#1553]
* What would you like to be able to do? Can you provide some examples?

I have a boolean field on my model that can have 3 values, "not set" -> `NULL`, "true" and "false. Right now, I can only switch between true/false but not `NULL.

* How could we go about implementing that?

One could add a new option to `Field::Boolean` like 'nullable'. Although, this could be applied to all fields. 

* Can you think of other approaches to the problem?

Not really in this case

**Comment by pablobm** [comment]
The problem with implementing this with a checkbox is that a checkbox only has two states. There's no way to express the three states you require.

Instead, you could create a custom field type that shows something else, perhaps three radio buttons. These would send values `null`, `true` or `false`, and a controller that knows how to use it, perhaps by overriding `Administrate::ApplicationController#resource_params`.

A similar conversation was had recently at https://github.com/thoughtbot/administrate/pull/1478

If you are not sure of how to do this, ask on StackOverflow and I'll try to answer there (use the tag "administrate").
