### ISSUE TITLE
Should we drop Rails <5 support?

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#1588]
This would mean removing the Rails 4.2 Appraisal. But are there other things we could also remove?

Are any of you still/stuck on Rails lower than 5?

This originally came up in #1581, as it's a feature that's not possible to do yet.

**Comment by nickcharlton** [comment]
Another reason: Bundler 2 and Rails 4.2 are causing problems with Appriasal: https://github.com/thoughtbot/appraisal/pull/168, which in-turn is related to our own #1548 and #1549.

**Comment by deivid-rodriguez** [comment]
Note that the underlying issue with ruby 2.7 is that Rails 4.2 is not compatible with Ruby 2.7 because it uses a `bigdecimal` 1.x interface, but `bigdecimal` 2.0.0 is provided by default on `ruby 2.7`.

My recommendation would be to:

* Upgrade to bundler 2.1, which fixes the other issue you're having when testing against ruby 2.7.
* Remove the ruby 2.7 + Rails 4.2 from the CI matrix.

**Comment by deivid-rodriguez** [comment]
I mean, I'd probably drop support for old Rails versions too, but that sounds like a separate discussion and not a requirement to start testing against ruby 2.7.

**Comment by composerinteralia** [comment]
factory_bot and factory_bot_rails are dropping support for Rails 4.2 in the next major release (they might still work with 4.2, but I will not be running the tests with that version anymore). I was having similar fights with Rails 4.2 locking to bundler < 2.

Rails 4.2 is no longer being maintained, so if there is additional maintenance burden to support it here I think we should drop support.

**Comment by nickcharlton** [comment]
Yeah — we're going to do the same (I realise I didn't actually write this on this issue). Administrate 1.0.0 (which will be it) won't support Rails 4.2.

**Comment by nickcharlton** [comment]
I've opened #1740, which removes support for everything below Rails 5.0.
