### ISSUE TITLE
Custom field types not work

### ISSUE THREAD

**Issue by nyrf** [thoughtbot/administrate#159]
http://administrate-docs.herokuapp.com/adding_custom_field_types, i followed this, but got error:

```ruby
require "administrate/base_dashboard"
# lib/administrate/fields/gravatar.rb
# (location of the file does not matter)
# require 'digest/md5'


class PostDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    title: Field::Gravatar,
    body: Field::Text,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = [
    :id,
    :title,
    :body,
    :created_at,
  ]

  # SHOW_PAGE_ATTRIBUTES
  # an array of attributes that will be displayed on the model's show page.
  SHOW_PAGE_ATTRIBUTES = ATTRIBUTE_TYPES.keys

  # FORM_ATTRIBUTES
  # an array of attributes that will be displayed
  # on the model's form (`new` and `edit`) pages.
  FORM_ATTRIBUTES = [
    :title,
    :body,
    :updated_at
  ]
end
```

```
uninitialized constant Administrate::Field::Gravatar
```

**Comment by graysonwright** [comment]
@nyrf - it looks like that documentation's a little bit out of date. Can you try running `rails generate administrate:field gravatar`, and using that as a starting point for your custom field?

I'll update the documentation to reflect the new instructions.

**Comment by graysonwright** [comment]
@nyrf check out the updated instructions:
http://administrate-docs.herokuapp.com/adding_custom_field_types

Let me know if you run into any more problems!

**Comment by nyrf** [comment]
@graysonwright Thanks, but it still not work, got same error.

**Comment by nyrf** [comment]
@graysonwright Sorry, my misstake, it works well. thanks.

**Comment by graysonwright** [comment]
@nyrf glad you figured it out, I hope the new docs helped. Let me know if you have any other trouble!

**Comment by picandocodigo** [comment]
@graysonwright I tried creating a field with the generator and am having the same issue:
```
$ rails generate administrate:field paperclip
```
I added some logic to `app/fields/paperclip_field.rb`, modified the views, but still getting:

```
uninitialized constant Administrate::Field::Paperclip
```

Do we have to manually load the fields?

**Comment by graysonwright** [comment]
@picandocodigo - it looks like in one of your dashboards' `ATTRIBUTE_TYPES` array, you've specified:

```ruby
some_attribute: Field::Paperclip
```

If you change that to:

```ruby
some_attribute: PaperclipField
```
then does it work? Also, if I misinterpreted the problem, let me know.

**Comment by picandocodigo** [comment]
Indeed, that's exactly what was wrong, thank you very much! I have Paperclip integration working flawlessly with Administrate now :)

**Comment by murdoch** [comment]
I was having the same problem with my CkEditor field, because I was doing `body: Field::CkEditorField` in my dashboard file. Your instructions helped me fix the problem... Thanks.

**Comment by graysonwright** [comment]
ok - it seems like I should add a note to the documentation. Thanks for the feedback!

**Comment by Perpherior** [comment]
@graysonwright hey, I meet the same error here.
I used the command  `rails generate administrate:field gravatar` to generate gravatar field
Then call it in the dashboard file.
```
require "administrate/base_dashboard"

class FamilyTagDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
      id: Field::Number,
      name: Field::String,
      approved: Field::Boolean,
      user_tags: GravatarField
  }

  ATTRIBUTES = [
      :id,
      :name,
      :approved,
      :user_tags
  ]

  def display_resource(tag)
    tag.name
  end

  COLLECTION_ATTRIBUTES = ATTRIBUTES
  SHOW_PAGE_ATTRIBUTES = ATTRIBUTES
  FORM_ATTRIBUTES = ATTRIBUTES
end

```
But by using `user_tags: GravatarField`, it will raise error `uninitialized constant FamilyTagDashboard::GravatarField`. If using `Field::Gravatar`, then will raise `uninitialized constant Administrate::Field::Gravatar`. Any idea?

**Comment by Xosmond** [comment]
I have a strange case of this, the custom field that i created only works with one dashboard, but others crash, it says that the custom field doesn't exist. Any help?

**Comment by anasyo10** [comment]
I am using the same method to for custom feild but I am getting data as nil :/ does anyone know why?
```
subscription_plan: SubscriptionPlanField
```
```
require "administrate/field/base"

class SubscriptionPlanField < Administrate::Field::Base
  def subscription_plan
    subscription = data.subscription
    subscription = SubscriptionDecorator.decorate(subscription)
    subscription.pay_interval
  end
end

```
This is what am doing.
