### ISSUE TITLE
Live dashboard

### ISSUE THREAD

**Issue by petrachi** [thoughtbot/administrate#1590]
Is it possible to have a live dashboard with administrate ? Where the user doesn't have to reload the page to see new or updated records ?

Maybe this could work with rails action cable ?

**Comment by nickcharlton** [comment]
In theory we could yes and ActionCable would be the preferred way to do it.

What problem are you trying to solve, though?

**Comment by petrachi** [comment]
Hi,
We have our customers support service who uses the admin to do some actions when they need to help a user. 
But they also follow the activity there is on the service, as they will call users if, for example, the waiting time for the service is too long. For that they uses a live dashboard using metabase, to see live each new order, etc.

The problem is that it is really not practical to uses two differents tools for them. So we would want to "merge" the admin actions (update an user, etc), and the live dashboard view, where they can see every new request.

**Comment by nickcharlton** [comment]
Ah, I understand!

I think the best approach here would be to create a [Dashboard without a model][1] (this isn't released yet, but won't be too long and so I'd suggest bundling from `master` for now), then connect ActionCable up to give the live stats. How does that sound?

[1]: https://github.com/thoughtbot/administrate/pull/1579

**Comment by petrachi** [comment]
Yes sounds like a good idea. I will give it a try.

**Comment by nickcharlton** [comment]
I'm going to close this as it's been inactive for a while and it sounds like we solved the problem — thanks for using Administrate!
