### ISSUE TITLE
Getting session's information from administrate dashboard or field?

### ISSUE THREAD

**Issue by bekicot** [thoughtbot/administrate#1593]
* What would you like to be able to do? Can you provide some examples?
```ruby
institutions: Field::Select.with_options(collections: -> {
  Pundit.authorize(?user?, Institution.where(pic_id: ?user?.id), :show, policy_class: InstitutionPolicy)
} )
```
* How could we go about implementing that?
I don't how to implement it.
Is this already available? 
* Can you think of other approaches to the problem?
I cannot think of alternative

The proc feature on `Field::Select` is introduced in #1535

**Comment by pablobm** [comment]
I think you are right, and there isn't a good way to implement this currently. It looks to me like a design issue with Administrate. I do think it should be fixed, but it won't be trivial.

Fortunately, I think there's a workaround. It's ugly, but it should work: use `Thread.current` to store the current user, and read it from the proc. Like this:

```ruby
# app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user! # This line will depend on your authentication library
    before_action :store_current_user

    private

    def store_current_user
      Thread.current[:current_user] = current_user
    end
  end
end
```

```ruby
# In your dashboard
institutions: Field::Select.with_options(collections: -> {
  Pundit.authorize(Thread.current[:current_user], Institution.where(pic_id: Thread.current[:current_user].id), :show, policy_class: InstitutionPolicy)
} )
```

For more information on `Thread.current` and its risks, be sure to read https://stackoverflow.com/questions/7896298/safety-of-thread-current-usage-in-rails.

I'm going to keep this open, in order to come back to it in the future.

**Comment by bekicot** [comment]
Thank you for taking the time to make the solution. It somehow reminds me of Rails 5's `Current`.
https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

Which is also considered harmful by Radar,
https://ryanbigg.com/2017/06/current-considered-harmful .

**Comment by bekicot** [comment]
I think we can expose session and other information (such as request params) to the
Administrate Instance variable, and from there we can pass it to Field.
WDYT @pablobm ? If you are confident with this, I can make a PR for it.

It will, of course, make administrate instances harder to instantiate. But, we already expect administrate to be instantiated from a controller instance.

**Comment by pablobm** [comment]
I forgot about `Current`. Yeah, I agree it's not a great solution.

Ideally the PR you propose would be good. However, I'm currently working on changes across all fields, so perhaps it'll be better to wait for that. Specifically, I'm working on this: https://github.com/thoughtbot/administrate/issues/1597 It may cause a bunch of conflicts...

What do you think?

**Comment by bekicot** [comment]
The workaround works fine for me. I will wait until you finished with #1597. 
It seems like a tedious task considering the amount of tests broken. Good luck, can't wait to remove the association's repetitive config on our dashboards.

**Comment by pablobm** [comment]
@bekicot - #1597 has been merged for a while (sorry, I forgot to ping here), so perhaps you may want to look into this issue? It's been a long time, so I understand if you have moved on to other things.

**Comment by pablobm** [comment]
Duplicated at https://github.com/thoughtbot/administrate/issues/2051

**Comment by bekicot** [comment]
@pablobm hi, yes I've been moved to other things now ;) . I don't have the time to help implement this feature as you suggested. So this is still free for someone who want to contribute :)

I'm thinking Current attribute is okay as a work around and not harmful in this case.

**Comment by nickcharlton** [comment]
I'm going to close this, as we've got a possible solution. We can revisit it in future if it becomes a more common situation.
