### ISSUE TITLE
Preloading instance dependent scopes is not supported

### ISSUE THREAD

**Issue by matteo-rossi-wise** [thoughtbot/administrate#1599]
* What were you trying to do?

I am trying to access my `/admin` page after setting up an `has_many` association as follows:

```ruby
has_many :bookings,
  ->(user) { unscope(where: :user_id).where("#{user.role}_id" => user.id) }
```

but browsing the index of my model from Administrate i get the following error:

```
Preloading instance dependent scopes is not supported
```

* What versions are you running?
  - Rails: 6.0.2.2
  - administrate: 0.13.0

**Comment by nickcharlton** [comment]
This is not a problem with Administrate (we don't have that error message), it's being caused by the removal of a deprecated feature in Rails itself: https://github.com/rails/rails/commit/4ed97979d14c5e92eb212b1a629da0a214084078

**Comment by trushkevich** [comment]
would it be an option not to preload instance dependent scopes ? it's possible to determine e.g. via
```ruby
Model.reflect_on_association(:assoc_name).scope.arity
```
