### ISSUE TITLE
We should bring community plugins into the docs

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#1600]
In #1535, @sedubois writes:

> - people can create their own plugins and share them on the [list of plugins wiki page](https://github.com/thoughtbot/administrate/wiki/List-of-Plugins), but that information tends to be outdated or not verified and so the quality information gets diluted;
> - external plugins might not be as stable as Administrate itself, because people are basically on their own and e.g. cannot ask for their PRs to be reviewed by other Administrate users (and the wiki page itself is not subject to a review process), and conversely the maintainer him/herself might not be available any more (as my example above shows);
> - various users (such as myself) might have functional custom administrate fields in their own private systems but have no clue how to turn that into a gem (although I'm not a good example because I could just have forked the outdated one; but then what should I put on the wiki page? Keep the outdated one, replace with my own, keep both?);
> - even if one finds an external plugin that is functional, it does not benefit from a clear API documentation like the ["official" API documentation](http://administrate-prototype.herokuapp.com/);
> - the documentation of these external plugins is fragmented (not available from the same central place);
> - we might also end up in situations where an external plugin already addresses a need, but due to lack of visibility then we partially try to address the need internally (as in this PR), which defeats a bit the purpose of supporting external plugins.
> 
> I don't know what is the solution. Maybe the documentation system could integrate external plugins as well...

The [intention of the wiki page was to reduce friction for people adding their plugins][1], but in practice that's just split the source of information.

I now think it'd be better to have a specific plugin listing page in the docs, with a section for Community Plugins _plus_ an invitation for people to add theirs. This should add a bit of feedback too, which hopefully answers the other points.

[1]: https://github.com/thoughtbot/administrate/issues/1015

**Comment by bekicot** [comment]
> I now think it'd be better to have a specific plugin listing page in the docs, with a section for Community Plugins plus an invitation for people to add theirs. This should add a bit of feedback too, which hopefully answers the other points.

What kind of information do you want to be put on the plugin listing page? Maybe some standard like:
1. Github Page
2. Documentation Page
3. Dependencies (E.g Administrate 0.12, Rails 6)

or it is just a list of plugin name, with link to their respective homepage.

**Comment by nickcharlton** [comment]
That sounds about right, something like:

* Plugin Name (Docs)

…where plugin name is a link to the GitHub page and documentation if relevant (i.e.: there's not much point if it's just the README)

**Comment by ghn** [comment]
I would love to see this too, instead of crawling google..

**Comment by pablobm** [comment]
An even better list is this one: https://rubygems.org/gems/administrate/reverse_dependencies. It will capture also some plugins that do not have the words "administrate-field" in them :-)

**Comment by pablobm** [comment]
I had a first stab at this at https://github.com/thoughtbot/administrate/pull/1899

**Comment by nickcharlton** [comment]
I'm going to close this now I've merged #1899 — I don't think this is an issue that will really ever be done but if people would like to add theirs to docs I'd welcome a PR!
