### ISSUE TITLE
Problem to get started

### ISSUE THREAD

**Issue by kurukuruk** [thoughtbot/administrate#1623]
I'm trying the administrate gem but after rails administrate:install when i go to "localhost:3000/admin" i'm meeting a problem who says:
"undefined local variable or method `root_url'"
What i need configure ?

**Comment by sedubois** [comment]
This is fixed if you use the master version of the gem: #1574

**Comment by kurukuruk** [comment]
Oh thanks you ! It's ok now sorry for that :)
