### ISSUE TITLE
Enum fields should be generated as Field::Select instead of Field::String

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/administrate#1629]
* What were you trying to do?
  Run generator for a ActiveRecord model with an enum column.
* What did you end up with (logs, or, even better, example apps are great!)?
  Dashboard with Field::String
* What versions are you running?
  - Rails: 6.0
  - administrate: master

The generated field should be like this

```ruby
enum_attribute: Field::Select.with_options(collection: Model.enum_attributes.keys)
```

With Field::String submitting to the update action with invalid value results in a Server Error of ArgumentError in Admin::ModelController#update

**Comment by pablobm** [comment]
This might be a matter of changing this mapping:

https://github.com/thoughtbot/administrate/blob/15c49a619995c653ddd0bfa2d9ea4110c5c0fc0d/lib/generators/administrate/dashboard/dashboard_generator.rb#L3-L16

Not 100% sure though. @betelgeuse, do you think you could try a PR?
