### ISSUE TITLE
Sort by function in line item doesn't work in `quantity` and `unit price`

### ISSUE THREAD

**Issue by leomao10** [thoughtbot/administrate#163]
Here is the link I tried:
https://administrate-prototype.herokuapp.com/admin/line_items?direction=asc&order=quantity

**Comment by graysonwright** [comment]
@leomao10 I suspect this is related to the project reorganization we did in #144, and this might be related to #162. I'll be able to troubleshoot it this evening, around 6 PST. Thanks for the heads-up!

**Comment by graysonwright** [comment]
Yep - looks like this was caused by the same error in #144. I deleted the offending record and it's working now - I'm going to add safeguards against that happening in the future.

**Comment by leomao10** [comment]
:+1:
