### ISSUE TITLE
undefined method `new' for nil:NilClass on custom attribute

### ISSUE THREAD

**Issue by estiens** [thoughtbot/administrate#164]
Every time I try to add a custom attribute to the show page, I get the following error from this code

    def attribute_field(dashboard, resource, attribute_name, page)
        value = get_attribute_value(resource, attribute_name)

        dashboard.
          attribute_types[attribute_name].
          new(attribute_name, value, page)
    end

I used the gravatar example as a base.

I am trying to display a standard paperclip `model.attachment.url(:thumb)`

**Comment by graysonwright** [comment]
@estiens - it looks like you might need to add your attribute to the dashboard, under the `RESOURCE_TYPES` constant. I just realized that that part is missing from [the docs](https://administrate-docs.herokuapp.com/adding_custom_field_types).

It should look something like this - I'm assuming you're trying to add the gravatar to the `User` model's `email` field, and that your generated field class is called `GravatarField`.

```ruby
class UserDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
    name: Field::String,
    email: GravatarField,    # Update this email to use your new field class
  }
end
```

Let me know if that works!

**Comment by estiens** [comment]
This works well, thanks! Maybe make a note to add to docs.
