### ISSUE TITLE
Always render flashes div so you can insert HTML via Javascript

### ISSUE THREAD

**Issue by stevenbuccini** [thoughtbot/administrate#1661]
### Scenario
Within my table row, I have a button that fires an asynchronous JS request. I want to be able to notify the user about the result of this request. 

Currently, this div is only rendered into the DOM when flashes exist. However, you might have a scenario in which no flash messages are sent down from the server but you still would like to prompt flashes programmatically from the frontend.

### Proposal
Always render in the flash partial into the DOM. When empty, it doesn't seem to affect the page layout at all so even conditionally adding `display: none` based on flash message absence shouldn't be necessary. Clients can then hook into this to insert their own HTML flashes as desired.

Happy to submit a PR for this if you're okay with this change.

**Comment by pablobm** [comment]
I think your use case is valid. I wonder though: would it be possible to do this by providing your own `app/views/administrate/application/_flashes.html.erb`? (I haven't tried; just asking to probe the usability of different approaches).

**Comment by stevenbuccini** [comment]
It's totally possible. I'm currently using that work around right now. My thinking was that that it seemed like overkill to generate an `application.html.erb` layout just to insert this empty div when one was already (sometimes) available in the layout. Additionally, putting flashes in the same place would allow for styling consistency. Agree it's a minor nit in the grand scheme of things which is why I wanted to see what other folks thought.

**Comment by pablobm** [comment]
Oh, right. I think it's not necessary to generate the whole thing. Try provide only a `app/views/administrate/application/_flashes.html.erb`. No need for the other files if you only want to change the flash partial. I just had a quick look and was able to make it work.

Please let us know if this works for you.

**Comment by stevenbuccini** [comment]
That's a fair solution. Thanks.

**Comment by pablobm** [comment]
I think that the docs could explain this a bit better. I have created a PR to address this: https://github.com/thoughtbot/administrate/pull/1679
