### ISSUE TITLE
Using "administrate" as custom namespace throws exception

### ISSUE THREAD

**Issue by marckohlbrugge** [thoughtbot/administrate#1669]
```
bin/rails generate administrate:install --namespace=administrate
```

Seems to work fine, but ends up creating a controller like this:

```ruby
# app/controllers/administrate/application_controller.rb
module Administrate
  class ApplicationController < Administrate::ApplicationController
    # …
  end
end
```

Which of course throws `RuntimeError: Circular dependency detected while autoloading constant Administrate::ApplicationController`, because we're defining `Administrate::ApplicationController` which inherits from `Administrate::ApplicationController`.

I expect Administrate to either support the "administrate" custom namespace (most user-friendly, but harder to implement) or throw an error when running `rails generate administrate:install --namespace=administrate` (easier to implement, but slightly annoying).

**Comment by pablobm** [comment]
Uh, interesting edge case. I think it's possible to do it at the moment, by telling the namespace to use a different module name:

```ruby
namespace :administrate, module: "admin" do
  resources :posts
  # ...
end
```

Then the controllers, etc will be assumed to be called `Admin::PostsController`, etc.

Would you be able to check this? If this works, making the generator aware of this corner case may become rather simple.

**Comment by marckohlbrugge** [comment]
I wanted to use "administrate" because I already use the "admin" namespace for something else. So this workaround wouldn't work in my particular case.

I think the easiest "fix" would be to just warn people not to use "administrate" as a namespace when installing. Not being able to use it is fine, as long as people are aware of it.

**Comment by pablobm** [comment]
Oh, I'm using `module: "admin"` just as an example. It could be `module: "foobar"`, as long as you put your dahsboards and controllers under the namespace `Foobar::`.

**Comment by pablobm** [comment]
Closing as I think my solution would work here. Please let us know if not.
