### ISSUE TITLE
Generators trip over irregular inflections

### ISSUE THREAD

**Issue by hayesgm** [thoughtbot/administrate#167]
When running `rails generate administrate:install` in an app with acronyms, the following error occurs:

``` ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'SKU'
end
```

``` bash
/Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:in `const_get': uninitialized constant SkU (NameError)
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:87:in `klass'
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/administrate-0.1.0/lib/generators/administrate/dashboard/dashboard_generator.rb:40:in `attributes'
  from (erb):11:in `template'
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/2.2.0/erb.rb:863:in `eval'
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/2.2.0/erb.rb:863:in `result'
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:116:in `block in template'
  from /Users/user/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/actions/create_file.rb:53:in `call'
```

The generators should check the inflectors when generating files.

**Comment by graysonwright** [comment]
Interesting, I haven't worked with acronyms in Rails before.

What happens if you run this? `rails generate administrate:dashboard SKU`

**Comment by tute** [comment]
I have an issue which might be related: a `Feedback` model (with an inflection rule so that the pluralized version looks the same) breaks the route generation for the link to index in the dashboard. It tries to go to `/admin/feedback/5`, and neither that nor without that weird 5 work.

**Comment by graysonwright** [comment]
@tute - can you give me a sample app to work with? I haven't used model inflections or acronyms before, so I'm not quite sure what the errors look like.

Thanks!

**Comment by tute** [comment]
> @tute - can you give me a sample app to work with?

If it's in administrate better, I hope! Check out my `tc-inflections` branch. If you boot up the app, you'll see:

```
ActionView::Template::Error (No route matches {:action=>"show", :controller=>"admin/feedback"} missing required keys: [:id]):
    10: <ul class="sidebar__list">
    11:   <% DashboardManifest::DASHBOARDS.each do |resource| %>
    12:     <li>
    13:       <%= link_to(
    14:         display_resource_name(resource),
    15:         [Administrate::NAMESPACE, resource],
    16:         class: "sidebar__link sidebar__link--#{nav_link_state(resource)}"
  actionpack (4.2.2) lib/action_dispatch/journey/formatter.rb:46:in `generate'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:727:in `generate'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:758:in `generate'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:801:in `url_for'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:280:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:223:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:345:in `block (2 levels) in define_url_helper'
  actionpack (4.2.2) lib/action_dispatch/routing/polymorphic_routes.rb:220:in `polymorphic_method'
  actionpack (4.2.2) lib/action_dispatch/routing/polymorphic_routes.rb:134:in `polymorphic_path'
  actionview (4.2.2) lib/action_view/routing_url_for.rb:99:in `url_for'
  actionview (4.2.2) lib/action_view/helpers/url_helper.rb:181:in `link_to'
  /Users/tute/Sites/thoughtbot/administrate/app/views/administrate/application/_sidebar.html.erb:13:in `block in ___sers_tute__ites_thoughtbot_administrate_app_views_administrate_application__sidebar_html_erb__3197254418321929445_70131938131900'
  /Users/tute/Sites/thoughtbot/administrate/app/views/administrate/application/_sidebar.html.erb:11:in `each'
  /Users/tute/Sites/thoughtbot/administrate/app/views/administrate/application/_sidebar.html.erb:11:in `___sers_tute__ites_thoughtbot_administrate_app_views_administrate_application__sidebar_html_erb__3197254418321929445_70131938131900'
  actionview (4.2.2) lib/action_view/template.rb:145:in `block in render'
 ```

Thank you, Grayson!

**Comment by tute** [comment]
https://github.com/thoughtbot/administrate/tree/tc-inflections

**Comment by mdkirby** [comment]
This has to do with the most terse rails path helpers not handling singular and plural model names being the same, a potential fix is to use the more verbose index path helper for the sidebar
this isn't pretty, but if line 15 looked like below, I think it would work:
`Rails.application.routes.url_helpers.send("#{Administrate::NAMESPACE}_#{resource}_index_path")`

**Comment by tmecklem** [comment]
It's possible this is similar to #400 and might be fixed by PR #414

**Comment by tute** [comment]
> It's possible this is similar to #400 and might be fixed by PR #414

Indeed it is. Should we close thi issue as duplicate?

**Comment by hayesgm** [comment]
I haven't tested this against PR 414, but this definitely does not appear to be a duplicate. This is from lack of inflections on `rails g administrate:install`.

**Comment by tmecklem** [comment]
#414 does not fix this issue. It only addresses the sidebar link_to index.

**Comment by thecalliopecrashed** [comment]
I followed the trail of issues a bit, and landed on #934, which was merged in July 2017.

That issue explicitly fixes the sidebar links only, so it is not clear if there is still an error during the `rails generate administrate:install` command.

I'll label this so we can follow up with an investigation.

**Comment by thecalliopecrashed** [comment]
@jalberto mentioned #559 as a potential fix for this issue.

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a while since the last activity and it sounds like there's a solution. Please open a new issue if you're still having problems.
