### ISSUE TITLE
Belongs to label does not follow the Internationalisation

### ISSUE THREAD

**Issue by huylocit14054** [thoughtbot/administrate#1681]
This issue will be a bit similar to the issue #451 . As HasMany field which already been resolve, belongs to does not use the label in Internationalisation file. 

Here is some of my code: 
<img width="290" alt="Screen Shot 2020-06-22 at 14 36 38" src="https://user-images.githubusercontent.com/28186870/85261077-ded74c80-b495-11ea-9a07-a74759d77897.png">
<img width="520" alt="Screen Shot 2020-06-22 at 14 36 46" src="https://user-images.githubusercontent.com/28186870/85261078-df6fe300-b495-11ea-89b5-68a2be820008.png">

<img width="935" alt="Screen Shot 2020-06-22 at 14 36 12" src="https://user-images.githubusercontent.com/28186870/85261068-dc74f280-b495-11ea-9d28-292e499b482f.png">

**Comment by nickcharlton** [comment]
Ah, nice catch. Do you think you'd be able to open a PR for this?

**Comment by huylocit14054** [comment]
@nickcharlton sr I am currently busy with another project

**Comment by KOlofinmoyin** [comment]
Hiya @huylocit14054 ,

1. Is the app where you observed the behaviour public? Or would you be able to share an example app?

2. Otherwise, how best would you suggest we reproduce the behaviour against a generic app?
cheers

**Comment by huylocit14054** [comment]
Hi @KOlofinmoyin , sr for my late response. Unfortunately, I cannot share that code here but I will show you how to re-produce it.  
You just need to create a `belongs_to` field in your dashboard. Then, you change its label in the `en.yml` file. The expected behavior is that the label will be the string you edited in the `en.yml`, however, it will be the `class name` of the field instead.

For my picture above, has a model named `sub_function` which belongs to `function`. I want to change its name to `practice coverage`. But as you can see, it does not change when I go to the `edit function`.

**Comment by SeedyROM** [comment]
Going to try to look into this, *let's see how it goes?*

**Comment by SeedyROM** [comment]
Can't replicate this locally, actually. Turns out I had a typo in my locale YAML, @huylocit14054 Maybe you could share a truncated version of your locale?

**Comment by huylocit14054** [comment]
I don't know if the newest version already fixes my problem. Mine was 0.13.0.
I do not have access to the repo anymore but as I remember it is something like this:

A `sub_function` has many `recruiter` and vise versa. This bug will happen when I create a `sub_function_recruiter` relationship record. In the create screen, the label is not correct. 
My en.yml has already changed the `sub_function` into `Practice` but it still shows as `sub_function`

@SeedyROM sr if this is not clear for u :(

**Comment by SeedyROM** [comment]
Here's what worked for me, I'm using `0.16.0`:
```
en:
  helpers:
    label:
      work: # Name of the model
        organizer: "Seller" # Name of the field
```

**Comment by huylocit14054** [comment]
Yeah I think newer version have already fixed this issue. I will close this one.
