### ISSUE TITLE
Destroy button not fit on the page when Layout is Responsive

### ISSUE THREAD

**Issue by edimossilva** [thoughtbot/administrate#1699]
* Scenario
  - On show resource page, when the layout is responsive and the column labels have many letters

* Issue
  - Destroy button not fit on the page.
  
* Example
  - ![image](https://user-images.githubusercontent.com/6463001/86587586-0114b280-bfde-11ea-97a3-5fde6528e39c.png)

* Proposal
  - Increase the min-width to .main-content 

* What versions are you running?
  - Rails - 6.0.0
  - administrate - 0.14.0

**Comment by nickcharlton** [comment]
Administrate's layout doesn't try to be responsive to different browser widths and so far it's not been something that's been prioritised above other work.

…however it is something I'd like to get fixed, so thanks for opening this!

Do you think you'd be able to open a PR with your suggested fix?

**Comment by edimossilva** [comment]
Hi @nickcharlton, yes, I will create a PR.
