### ISSUE TITLE
Order of items in navigation sidebar

### ISSUE THREAD

**Issue by mvanh** [thoughtbot/administrate#1706]
rails 6.0.3.2 administrate 0.13.0

I was trying to change the order of items in the navigation sidebar (effectively items in the DASHBOARDS array in dashboard_manifest.rb

Changing the order of the items in the array did nothing

Changing the order of when each of the respective controllers were mentioned in routes.rb was the only way to change the order.

**Comment by sedubois** [comment]
@mvanh indeed the order of the left-side navigation is controlled by changing the order of your resources in routes.rb. Does that pose an issue?

**Comment by mvanh** [comment]
@sedubois It seems odd. Route order has a function of it's own (precedence, specificity, and frequency of use) and i don't see why that should in any way be linked to the display layer. 

Eg. i may have a view of customers & transactions, and want transactions to be the first route for efficiency reasons, but want customers to show up higher on the navigation sidebar for ease of use/UX.

Would make more sense to use the order of the array in Dashboard Manifest.

**Comment by sedubois** [comment]
I was not aware of this dashboard_manifest but I see it is mentioned in the git history, probably something that was used in the past? My app runs without it, and so does the [example app](https://github.com/thoughtbot/administrate/tree/master/spec/example_app/app/dashboards).

Personally I am happy that there is a single place to configure the dashboard order. I understand the main question here is about performance, however that sounds like a feature request. Do you have an idea of the concerned performance impact?

**Comment by pablobm** [comment]
I wasn't aware of this manifest either. I agree it's most likely a legacy file from an older version.

Regarding efficiency, I'd be very surprised if the order of routes made any measurable impact. Is this something you have experienced?

**Comment by nickcharlton** [comment]
I'm going to close this, in part because order of routes — whilst important in their own right — shouldn't generally be a big issue with an Admin dashboard, because providing some sort of look up table for ordering would unnecessarily add complexity and because it's been inactive for a while.
