### ISSUE TITLE
Is there a workaround for a model named "Page"?

### ISSUE THREAD

**Issue by milkfarm** [thoughtbot/administrate#1709]
I didn't find any documentation about reserved names for the administrate gem. Is there a workaround for a model named `Page`? When I create a standard dashboard (`rails g administrate:dashboard Page`), I encounter a variety of errors. For example, when trying to access the pagination links on the `index` view.

```
NoMethodError in Admin::PagesController#index
undefined method `fetch' for "2":String

def order
  @order ||= Administrate::Order.new(
    params.fetch(resource_name, {}).fetch(:order, "created_at"),
    params.fetch(resource_name, {}).fetch(:direction, "desc")
  )
end
```

The issue relates to the paging/sorting information being stored under the same param key as the resource.

Rails: 6.0.3.2
administrate: 0.13.0

**Comment by pablobm** [comment]
Uh, that's indeed a bug. I have put together some code that might help. Mind trying out branch https://github.com/thoughtbot/administrate/compare/master...pablobm:fix-page and tell us how it went? Thank you.

**Comment by milkfarm** [comment]
The paging links for unsorted results now work. Clicking a table column header to sort records, however, generates the following error message: 

```
NoMethodError in Admin::PagesController#index
undefined method `to_i' for #<ActionController::Parameters:0x00007fec239ddbd8> Did you mean? to_s to_h

Extracted source (around line #17):

15  def self.#{Kaminari.config.page_method_name}(num = nil)
16    per_page = max_per_page && (default_per_page > max_per_page) ? max_per_page : default_per_page
17    limit(per_page).offset(per_page * ((num = num.to_i - 1) < 0 ? 0 : num)).extending do
18      include Kaminari::ActiveRecordRelationMethods
19      include Kaminari::PageScopeMethods
20  end
```

I'm ok renaming my model if you don't think this can be remedied in an elegant manner. I'm also here to help if you'd like to continue investigating. In any regard, thanks!

**Comment by pablobm** [comment]
Thank you again for that diagnosis. I have pushed a new change to that branch. Would you have time to try it out?

The bug should definitely be fixed, and I don't expect it to be a particularly difficult fix.

**Comment by milkfarm** [comment]
You've squashed another part it -- well done. The only problem I see is the paging when the records are sorted. I don't encounter an exception but the behavior isn't correct. The paging links don't retain the sorting. I didn't look at the code but I imagine the "page[:order]" and "page[:direction]" are being overwritten by the "page" param that contains the page number.

Example:
* I click the ID column header to sort the records. The resultant URL is:
  * http://localhost:3000/admin/pages?page%5Bdirection%5D=desc&page%5Border%5D=id
* The paging links, however, are:
  * http://localhost:3000/admin/pages?page=2
  * http://localhost:3000/admin/pages?page=3
  * etc

Note: The "page%5Bdirection%5D=desc&page%5Border%5D=id" are missing.

**Comment by pablobm** [comment]
Uh, that's strange. I'm not able to reproduce.

There's something odd about the URLs you show though: the query param should be called `_page` now, but you show it as `page`. Perhaps Spring is playing us, and the version of the code you are running is not quite correct? Would you be able to check again, running `./bin/sprint stop` before running the server, just in case?

**Comment by milkfarm** [comment]
You're right, it's my setup. Sorry for the confusion. Thanks for all your help. 👏

**Comment by pablobm** [comment]
Actually, I'm reopening because the bug does still exist. I should create a PR from my branch above, which should fix it properly.

**Comment by rohmanitsavirus** [comment]
> You're right, it's my setup. Sorry for the confusion. Thanks for all your help.

How to solve this issue?

**Comment by rohmanitsavirus** [comment]
> > You're right, it's my setup. Sorry for the confusion. Thanks for all your help.
> 
> How to solve this issue?
> What's wrong with your setup?
> I get this error and get stuck

I updated the administrate version to 0.15 and fix this error.

**Comment by pablobm** [comment]
If anyone else is having an issue with this, see the following for a potential solution: https://github.com/thoughtbot/administrate/issues/2359#issuecomment-1516002382
