### ISSUE TITLE
Need to cast `params[:per_page]` to Int; seems like it should be handled by the gem?

### ISSUE THREAD

**Issue by connor** [thoughtbot/administrate#1714]
* What were you trying to do?
Customize the number of results of a model on an index page.

* What did you end up with (logs, or, even better, example apps are great!)?

I updated my `admin/application_controller.rb` to have the following:

```rb
def records_per_page
     params[:per_page] || 50
end
```

Then, going to http://localhost:3000/admin/foo?per_page=5

```
ActionView::Template::Error (comparison of Integer with String failed):
    62:     table_title: "page-title"
    63:   ) %>
    64:
    65:   <%= paginate resources %>
    66: </section>
```

If we update the code to the following, though:

```rb
def records_per_page
    per_page = params[:per_page] || 50
    per_page.to_i
end
```
The issue is fixed.

I feel like this should be handled by administrate (or lower in the stack)?

* What versions are you running?
  - Rails
`Rails 6.0.3.2`
  - administrate
`0.14.0`

**Comment by pablobm** [comment]
That makes sense. Would you be able to put together a PR, with a spec?

**Comment by connor** [comment]
Yes, can do!

**Comment by connor** [comment]
I can no longer reproduce this; closing out.
