### ISSUE TITLE
Edit directly in the collection view

### ISSUE THREAD

**Issue by Pasta** [thoughtbot/administrate#1716]
It would be awesome to be able to edit fields directly in the collection view. 
That would allow for fast mass editing.
Maybe there is an  actual  way to do this now I just didn't find it.

**Comment by pablobm** [comment]
There isn't a way to do this at the moment indeed. It's not a feature we have in the horizon either, as it'd be tricky to do, particularly in a way that is generic and works across different setups.

It's possible to implement on your own though. You can add custom JS to your Administrate app. This could bind event handlers to rows in collection views, and use the existing `Adminitrate::ApplicationController#update` action to send data via Ajax. Does that make sense?

It might be that there are hooks or similar that we could add that helps implementing something like this. We'd be more open to adding these than to adding the whole functionality, as we prefer to make Administrate easy to extend, as opposed to full-featured.

**Comment by Pasta** [comment]
Thanks for the fast answer, will look into what you described and will report back =)
