### ISSUE TITLE
How do I change the resource #show links?

### ISSUE THREAD

**Issue by connor** [thoughtbot/administrate#1717]
I've got a dashboard for a `User`. A `User` has a unique `username`. I'd like to use that to lookup instead of their ID.

I understand I can customize the logic in the `find_resource` method for the controller, but... how do I change all of the links to the #show method of that resource? They are all currently (`/admin/users/{id}`). Do I have to generate my own view to customize this, or is there a more built-in way to handle this?

Thank you! Please let me know if I can provide more information.

**Comment by sedubois** [comment]
You can add this to `app/models/user.rb`:

```rb
def to_param
   username
end
```

**Comment by connor** [comment]
Excellent. Thank you! I'll submit a PR that updates documentation to include this.
