### ISSUE TITLE
Search by string field does not work

### ISSUE THREAD

**Issue by luiseugenio** [thoughtbot/administrate#1719]
* What were you trying to do?
Search by a string field. 

* Dashboard
```ruby
ATTRIBUTE_TYPES = {
    name: Field::String,
}.freeze

COLLECTION_ATTRIBUTES = [
    :name
].freeze
```
* Steps to reproduce:
 1. Go to `http://localhost:3000/admin/foos?search=another`
 2. Got the error:
```ruby
undefined method `match?' for "another":String
```
* What did you end up with (logs, or, even better, example apps are great!)?
I created a monkey patch for `Administrate::Search::Query` to have the following:
```ruby
private

def filter?(word)
   word.match(/^\w+:$/)
end
```

* What versions are you running?
  - Rails
`Rails 5.2.0`
  - administrate
`administrate (0.14.0)`

**Comment by sedubois** [comment]
I run administrate 0.14.0 and don't encounter this error when visiting my app at http://localhost:3000/admin/users?search=test (and it correctly yields users with `email` attribute containing `test`).

Maybe `name` has a special meaning in Administrate, could you try changing it to something else?

**Comment by luiseugenio** [comment]
> I run administrate 0.14.0 and don't encounter this error when visiting my app at http://localhost:3000/admin/users?search=test (and it correctly yields users with `email` attribute containing `test`).
> 
> Maybe `name` has a special meaning in Administrate, could you try changing it to something else (although I have doubts)?

I left only one attribute (named `id`) `Number`. But I still have the same problem.

**Comment by pablobm** [comment]
The method `String#match?` (as opposed to `String#match` without question mark) was added in Ruby 2.4[1], which is also the minimum version of Ruby supported by Administrate. If you are seeing this error, it's probably because you are using a previous version of Ruby.

I'll close this issue. Let me know if I'm mistaken.

[1] https://rubyreferences.github.io/rubychanges/2.4.html#match-method
