### ISSUE TITLE
Can't access models/order.rb from order_dashboard.rb

### ISSUE THREAD

**Issue by kesha-antonov** [thoughtbot/administrate#1720]
Hi!

```
class OrderDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    state: SelectField.with_options(options: ApplicationRecord::Order.aasm(:state).states.map(&:name).map{|x| [I18n.t("orders.state.#{x}"), x]}, include_blank: true),
```

I can't access Order from OrderDashboard. Because if I use Order without ```ApplicationRecord::``` it uses Order.rb from administrate. But ```ApplicationRecord::``` doesn't work either.

Can you help me please get access to Order from models?

* What versions are you running?
  - Rails 5.1.4
  - administrate 0.14.0

**Comment by sedubois** [comment]
Seems like a similar issue to #1709?

**Comment by kesha-antonov** [comment]
@sedubois yeah, I think

Now I use ```::Order```. It helped to use Order from models/order.rb

**Comment by pablobm** [comment]
It's not the same as #1709. Using `::Order` is the correct fix here. It's a common issue when working with similarly-named modules in Ruby.

I think this solves it, so I'll close. Let me know if you think otherwise.
