### ISSUE TITLE
Height of attribute list section is incorrect  

### ISSUE THREAD

**Issue by artplan1** [thoughtbot/administrate#1722]
Height of this list section is broke because of float usage

![image](https://user-images.githubusercontent.com/9060346/88535102-0cbe2c80-d012-11ea-97df-8758d549c1bc.png)

This issue makes it hard to add content below this list

It can be fixed using flexbox (I can provide PR if this change is ok)

```
.main-content__body > dl {
    display: flex;
    flex-flow: row wrap;
}
```

**Comment by pablobm** [comment]
I agree it's a bit weird. What do you mean by adding content below the list? Can you show an example?

**Comment by artplan1** [comment]
sure
for example I want to add something below attributes list in `show` page by modifying `show` page for resource


```html
<section class="main-content__body">
  <dl>
    here is default attributes loop
  </dl>

  <%= render partial: 'admin/audit/log', locals: { log_data: page.resource.log_data } %>
</section>
```

generated html

```html
<section class="main-content__body">
  <dl>
      list....
  </dl>

  <div>
    <h3>Log</h3>

    <div class="table-container is-fullwidth">
       <table class="table is-vertically-aligned">
          .........
       </table>
    </div>
  </div>
</section>
```

without fix it looks like this - `Log` header is incorrectly placed

![image](https://user-images.githubusercontent.com/9060346/88904882-50a57180-d25e-11ea-841f-6b8dc85e60af.png)

![image](https://user-images.githubusercontent.com/9060346/88905290-ca3d5f80-d25e-11ea-9c48-7e6d9f6f4bf0.png)

same happens when I place my new section **out of `content__body`, below it**

with fix

![image](https://user-images.githubusercontent.com/9060346/88905189-b2fe7200-d25e-11ea-9d85-93c2b19fee37.png)

![image](https://user-images.githubusercontent.com/9060346/88905328-d32e3100-d25e-11ea-8a47-6a762c8f8d32.png)

**Comment by pablobm** [comment]
Thank you for the example. There has been some discussion around making the layout more responsive, and that would help here. Unfortunately it's been a low priority.

I think that we could try solve this in small increments. For example, if you provided a PR that integrated flexbox in this specific setting, it would be a step in the right direction.

Regarding your proposed solution, I would prefer if you used a semantic class name there, instead of targeting tag names like `> dl`.

**Comment by pablobm** [comment]
Closing in favour of https://github.com/thoughtbot/administrate/issues/128.
