### ISSUE TITLE
Implicit dependencies on the Rails Asset Pipeline

### ISSUE THREAD

**Issue by maxkwallace** [thoughtbot/administrate#173]
When I added Administrate to my Rails app, things were broken out of the box. My app is designed to be an API backend only, and didn't include Sprockets or several other necessary Rails Asset Pipeline gems.

I'm not a Rails expert, so I can't speak to how this issue should be handled in general. But you might find it worthwhile to make these dependencies explicit within Administrate.

For reference, I was able to load the Administrate dashboard after adding the following to my `Gemfile`

```
gem 'sprockets-rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
```
(EDIT: this list is neither minimal nor exhaustive-- I just copy/pasted from the Rails Guides. As grayson mentioned below, the `'coffee-rails'` gem shouldn't be needed.)

and uncommenting the line

```
gem 'sprockets-rails'
```

in `/config/application.rb`.

**Comment by graysonwright** [comment]
@maxkwallace good point - we can fix that. Give me a couple minutes and I can have a PR up.

**Comment by graysonwright** [comment]
@maxkwallace can you narrow that list down a little more? For example, Administrate doesn't use any CoffeeScript. If you remove that from the list, does the app still error out?

**Comment by graysonwright** [comment]
I've opened up #174, which hopefully fixes this. Can you try pointing your Gemfile at:

```
gem "administrate", github: "thoughtbot/administrate", branch: "gw-explicit-asset-dependencies"
```

and see if it works?

**Comment by maxkwallace** [comment]
@graysonwright Gladly-- I'll give that a shot. Your question above is well-warrented btw... I just copied those gems from the Rails guides, so the list is neither minimal nor exhaustive. I should have clarified that in my original post.

**Comment by maxkwallace** [comment]
@graysonwright Here's the steps I followed:

- Created a new branch off of `master` in my app
- Added `gem "administrate", github: "thoughtbot/administrate", branch: "gw-explicit-asset-dependencies"` to my `Gemfile`
- Ran `rails generate administrate:install`
- Saw the following error (same as before):

```
mkw@user-computer:~/sw/shearwater/rails$ rails generate administrate:install
/home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg.rb:25:in `asset_finder=': Asset Finder should implement the #find_asset method (InlineSvg::Configuration::Invalid)
  from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:15:in `block (2 levels) in <class:Railtie>'
  from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg.rb:55:in `configure'
  from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:12:in `block in <class:Railtie>'
  from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/activesupport-4.2.4/lib/active_support/lazy_load_hooks.rb:36:in `call'
...
```
- Uncommented `require "sprockets/railtie"` in my `config/application.rb`
- Re-ran `rails generate administrate:install`
- Started my server-- everything looks good!

I'm not sure if it would make sense to handle the `'sprockets/railtie'` require in your generator, but you'll probably want to add a comment about that to the docs, at least.

**Comment by graysonwright** [comment]
oh, cool. mind trying one more time for me? I think we can get it if I add that `require` statement to the Administrate engine file – [like this](https://github.com/thoughtbot/administrate/commit/bfb43f43f5955cbb1c4c0026a8554e8960699ccc).

**Comment by maxkwallace** [comment]
@graysonwright Not at all! I'll give it another shot.

**Comment by tomgatzgates** [comment]
Hey, jumping here because I'm in a very similar situation to @maxkwallace. 

I'm getting the following as my error now. 

```ruby
Could not load generator "generators/administrate/install/install_generator". Error: undefined method `+' for nil:NilClass.
```

FYI also working on change our rails 4 api app to an engine and mounting it inside a host app running admin. The reason being using Administrate will be temporary for now until we get the resource for a custom front-end, api driven admin system.

**Comment by tomgatzgates** [comment]
Worked for me but only with require "sprockets/railtie" in my config/application.rb

Sorry to butt in, I'm in a very similar situation to @maxkwallace

**Comment by maxkwallace** [comment]
@graysonwright I'm trying to test this but having trouble verifying that bundler is downloading the updated branch after your [recent commit](https://github.com/thoughtbot/administrate/commit/bfb43f43f5955cbb1c4c0026a8554e8960699ccc)

Following the same steps as before didn't work (same error as the one I posted above), but I suspect that I might just not have the updated version of the gem. I tried

```
gem "administrate", github: "thoughtbot/administrate", branch: "gw-explicit-asset-dependencies", ref: 'bfb43f43f5955cbb1c4c0026a8554e8960699ccc'
```

and then ran `gem unpack administrate` in an attempt to inspect my local copy of the source. I still don't see the line
```
require "sprockets/railtie"
```
in my unpacked copy of `lib/administrate/engine.rb`.

**Comment by graysonwright** [comment]
hmm, maybe `bundle update administrate` ?

**Comment by graysonwright** [comment]
it might be that your Gemfile.lock has it locked on the previous commit.

**Comment by graysonwright** [comment]
if that doesn't work, I'd try `gem uninstall administrate`, delete your `Gemfile.lock`, and then try to do a fresh `bundle install`.

**Comment by tomgatzgates** [comment]
A secondary issue i've noticed from this implantation route (API app)

```ruby
NoMethodError in Admin::UsersController#index

undefined method `paginate' for #<User::ActiveRecord_Relation:0x...


@resources = User.all.paginate(10, params[:page])
```

**Comment by graysonwright** [comment]
oh, interesting. @tomgatzgates are you using any pagination gems in your app that might be conflicting with Kaminari?

**Comment by graysonwright** [comment]
also, I think I might need to start up an API-only app to test this with. Did you start from [rails-api](https://github.com/rails-api/rails-api)?

**Comment by graysonwright** [comment]
@tomgatzgates - you might want to check out #158 for the `paginate` issue. Sounds similar to something we found before.

**Comment by tomgatzgates** [comment]
@graysonwright Thanks, I'll take a look. 
Using grape-kaminari so perhaps that. I'll update if I find anything new

**Comment by maxkwallace** [comment]
@graysonwright On a fresh branch:
- `gem uninstall administrate`
- `rm Gemfile.lock`
- `bundle install`
- Added `gem "administrate", github: "thoughtbot/administrate", branch: "gw-explicit-asset-dependencies"` to my Gemfile.
- `bundle install`
- ` rails generate administrate:install`

I still see the error:
```
/home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg.rb:25:in `asset_finder=': Asset Finder should implement the #find_asset method (InlineSvg::Configuration::Invalid)
	from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg/railtie.rb:15:in `block (2 levels) in <class:Railtie>'
	from /home/mkw/.rvm/gems/ruby-2.2.3@shearwater/gems/inline_svg-0.6.1/lib/inline_svg.rb:55:in `configure'
...
```

**Comment by graysonwright** [comment]
ok - I'll create my own repo to play around with and see if I can get it working. Thanks for helping debug this!

**Comment by maxkwallace** [comment]
Glad to help-- thanks for the prompt replies!

**Comment by graysonwright** [comment]
anytime. :smile:

**Comment by rayfix** [comment]
Hello.  I am hitting the error during rake assets:precompile on heroku (can't reproduce in development)
InlineSvg::Configuration::Invalid: Asset Finder should implement the #find_asset method

I am using will_paginate and first ran into  the problem #158 and fixed that by customizing my index as that issue suggested.

rails 4.2.5 app, using 0.1.2 administrate.  (Project actually includes all the gems listed above. Latest versions of pretty much everything.)

Any hints?

**Comment by rayfix** [comment]
Sorry my bad.  In the process of trying to solve #158 I updated some gem dependencies.  (A newer version of sprockets is getting me I think.)  Anyway, that appears to have been the source of this problem and resemblance to this issue was just coincidence.  PS: Thank you for this great tool.

**Comment by QuintinAdam** [comment]
@rayfix I am also getting this error when pushing to heroku. Did you get this fixed? 

sprockets version 3.5.2

**Comment by zamith** [comment]
This also fails for me on the same sprockets version.

**Comment by BillyParadise** [comment]
confirmed. I had sprockets-rails 3.0.0 in my gemfile.lock. Rolling it back to 2.3.3 solved the issue for me in production.

**Comment by tquill** [comment]
Changing to 2.3.3 worked for me too.  Thanks.

**Comment by Johnsalzarulo** [comment]
Changing to 2.3.3 solved this same issue for me as well.

**Comment by hajpoj** [comment]
related to https://github.com/jamesmartin/inline_svg/issues/25 . which is still open (right now). Quick fix of 2.3.3 works for me too. Thanks!

**Comment by MaxPleaner** [comment]
me, too.

**Comment by yago580** [comment]
:+1: for `2.3.3`

**Comment by graysonwright** [comment]
Alright, this should be taken care of in #365. Thanks, everyone!
