### ISSUE TITLE
How do I use a polymorphic relationship with Carrierwave?

### ISSUE THREAD

**Issue by ortonomy** [thoughtbot/administrate#1730]
I'm really sorry if this is not appropriate here, but I'm lost as to how to set this up.

To save time, I have multiple models which accept a CarrierWave upload, so I made a polymorhpic relationship `Upload` as `:uploadable` , mounting carrierwave as `:file`. 

I'm trying to add the ability to change / edit / view this in an administrate dashboard, but if I set `Field::Polymorphic` I get an error when editing:

`undefined method `to_global_id' for #<ActiveRecord::Associations::CollectionProxy []>`

Where am I going wrong? I know that the CarrierWave field is NOT the responsibility of the Administrate maintainers, but I can't find an appropriate place to put this question

**Comment by pablobm** [comment]
It might be an Administrate bug. It's strange because `to_global_id` is only applied to model instances, so it shouldn't be complaining that it got applied to `#<ActiveRecord::Associations::CollectionProxy []>` instead.

Would you be able to show the full exception trace, and your version of Rails?

**Comment by ortonomy** [comment]
@pablobm -- thanks for replying, and thanks for helping me try to fix this...

So, I managed to get the carrierwave field to display, like this...

`user.rb`

```
class User < ApplicationRecord
  has_one :avatar, -> { where(upload_type: 'avatar') }, as: :uploadable, class_name: 'Upload'
end
```

and `upload.rb`

```
class Upload < ApplicationRecord
  belongs_to :uploadable, polymorphic: true

  mount_base64_uploader :file, MediaUploader, file_name: ->(_) { SecureRandom.uuid }

  def self.work_attachments
    where(upload_type: 'work_attachment')
  end

  def self.avatars
    where(upload_type: 'avatar')
  end
end
```

and `upload_migration.rb`

```
class CreateUploads < ActiveRecord::Migration[5.2]
  def change
    create_table :uploads do |t|
      t.references :uploadable, polymorphic: true
      t.string :file
      t.string :upload_type
      t.timestamps
    end
  end
end
```

and `user_dashboard.rb`

```
require 'administrate/base_dashboard'

class UserDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    first_name: Field::String,
    last_name: Field::String,
    ...,
    avatar,
    ...
  }.freeze

... 

end
```


and the `upload_dashboard.rb`

```
require 'administrate/base_dashboard'

class UploadDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    uploadable: Field::Polymorphic,
    id: Field::Number,
    file: Field::Carrierwave.with_options(
      image: :standard,
      multiple: false,
      remove: false,
      remote_url: false
    ),
    upload_type: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime
  }.freeze

... 

end
```

but I can't seem to save anything to the DB... logs say 'COMMIT', but I can't work out why it's not saving...

**Comment by ortonomy** [comment]
@pablobm -- realised it was a strong parameters error, so added:

`accepts_nested_attributes_for :avatar, reject_if: ->(attributes) { attributes['upload_type'].blank? }, allow_destroy: true`

to my user model and now it displays the fields correctly! 

but now my 'show' is broken 🤣...

![image](https://user-images.githubusercontent.com/6688676/89541151-92bb4e00-d830-11ea-8156-46a903c628fc.png)

thoughts?

**Comment by ortonomy** [comment]
Fixed it... had to add `show` for uploads to routes for `upload`!
