### ISSUE TITLE
autoprefixer-rails is deprecated

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#1733]
As of today (2020-08-03), [autoprefixer-rails is deprecated][1].

The suggested upgrade path is to move it into frontend dependencies (which would assume we were using webpacker everywhere, [ala the frontend-pipeline group of issues][2]). But, I wonder if we can just remove it and inline any prefixes?

[1]: https://github.com/ai/autoprefixer-rails/wiki/Deprecated
[2]: https://github.com/thoughtbot/administrate/issues?q=is%3Aopen+is%3Aissue+label%3Afrontend-pipeline

**Comment by sedubois** [comment]
autoprefixer-rails [has been un-deprecated](https://github.com/ai/autoprefixer-rails/pull/177).

**Comment by pablobm** [comment]
Re: the "un-deprecation" - You have to be kidding me! :laughing: 

Still, it's a dependency that had very little use, so I think it will save us trouble in the future if we just remove it, as we just did.
