### ISSUE TITLE
Make nested has_many respect `scoped_resource`?

### ISSUE THREAD

**Issue by connor** [thoughtbot/administrate#1734]
Let's say I have three models — `Post`, `Author` and `Tag`.

And on the `Post` admin controller, I have a custom `scoped_resource` that only shows posts by the current author (which is tied to the authentication mechanism).

However, when viewing a specific `Tag`, I want the `articles` field on that page to only show the articles by that author. Right now that's not the case.

Is there any way to do this right now? If not, any guidance would be much appreciated, and I'll work on submitting a PR to address this.

Thank you!

**Comment by connor** [comment]
I figured out how to hack around this — passing the `current_user` from the view to the controller method and doing filtering there.

It's definitely janky. I feel like there should be a `where` I can pass in to the `HasManyField` as an option.

Thoughts on that?

**Comment by pablobm** [comment]
I'm not sure, but this sounds like it may need using nested routes? Like this:

```ruby
Rails.application.routes.draw do
  namespace :admin do
    resources :tag do
      resources :articles
    end
  end
end
```

Then in the `ArticlesController` you should be able to retrieve articles by `:tag_id` and by `current_user`. Would that work?

**Comment by connor** [comment]
Ah, figured it out. Thank you!

It wasn't quite a nested resource issue. Basically I added logic in the custom fields I'm using to filter.
