### ISSUE TITLE
Field type: Array resource_params getting called twice. 

### ISSUE THREAD

**Issue by shilpi230** [thoughtbot/administrate#1735]
I am trying to permit an extra array field which is coming as hash in params like this followed this [issue](https://github.com/thoughtbot/administrate/issues/705)

```
  def resource_params
    params["book"]["pages"] = params["book"]["pages"].try(:keys) || []
    params.require("book").permit(*dashboard.permitted_attributes, pages: [])
  end
```
This is working fine with update action but for create action `resource_params` is getting called just before in enters the create action and thus already fetching array value from params["book"]["pages"] and setting the value as an array. So, when create action actually calls the resource_params now params["book"]["pages"] doesn't have any hash, instead an array and it sets the `params["book"]["pages"] = []` setting in db as nil.

**Comment by pablobm** [comment]
Hello @shilpi230, thank you for taking the time to file this issue. I'm trying to reproduce it, but I have been unsuccessful so far. When you say that "`resource_params` is getting called just before in enters the create action", what do you mean? The only place where it should be called is from within the `create` action. Specifically in line 44 here:

https://github.com/thoughtbot/administrate/blob/a320be4cf11f833aa77b919172857f8c67cc838e/app/controllers/administrate/application_controller.rb#L43-L57

So for a test, if you put some debugging code in your version of `resource_params`, are you able to identify where it's being called from? For example, you could use `Kernel#caller` like follows, and paste here the stack traces you see:

```ruby
  def resource_params
    pp caller
    params["book"]["pages"] = params["book"]["pages"].try(:keys) || []
    params.require("book").permit(*dashboard.permitted_attributes, pages: [])
  end
```

From here we should be able to tell why this is being called twice.

**Comment by shilpi230** [comment]
Hey @pablobm thanks for looking at it. I found the issue I was using cancan in my application and had this `load_and_authorize_resource` in before action and that was causing the issue. But its weird that for update it doesn't go there for create alone it happens. If you know why it might be happening and if there is any way to fix that. Please let me know. Thank you so much. Else we can close this bug.

**Comment by pablobm** [comment]
It appears that CanCan has its own `resource_params`:

https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L216-L223

This appears to be called by `load_and_authorize` resource on create. This would be the sequence:

1. `load_and_authorize_resource`: https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L24
1. `load_resource`: https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L29
1. `load_resource_instance`: https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L64
1. `build_resource`: https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_resource.rb#L84
1. And from there to `resource_params`.

So this appears to be an incompatibility that I'm not sure can be resolved fully. I don't know what other unintended effects will it have, the fact that we are completely interfering with CanCan. The safest route action would be not to use CanCan, I'm afraid. I recommend using Pundit instead, which is tested with Administrate: https://administrate-prototype.herokuapp.com/authorization

Having said that... perhaps whatever it breaks is not important and you can still live with it. In this case, I advise that you rewrite your version of `resource_params` to be immutable. In fact I would very much recommend that you never mutate `params`.

But even in that case, CanCan may be malfunctioning in some way. Be careful that it's not creating you a security issue.

I'm going to close for now, as it appears to be beyond our reach. Feel free to ask more questions.

**Comment by shilpi230** [comment]
Thanks! @pablobm
