### ISSUE TITLE
How to customize the displayed text for an associated model?

### ISSUE THREAD

**Issue by maxkwallace** [thoughtbot/administrate#175]
At https://administrate-prototype.herokuapp.com/admin/orders it looks like each order belongs to a Customer. This association is rendered nicely as:

![prototype](https://cloud.githubusercontent.com/assets/3249377/10998243/c0420a80-8461-11e5-8b52-8a5d528dbdf7.png)

Within my own app, I have a similar relationship: Student belongs to School. After setting up Administrate within my own app, I see the following out-of-the-box:

![my prototype](https://cloud.githubusercontent.com/assets/3249377/10998265/ed16b128-8461-11e5-9a79-1a549e79da63.png)

Instead of displaying `#<School:0x0000000aa98080>` or similar, I want to customize the link text based on the attributes of that school model (similar to the prototype, which uses the Customer's full name). How can I do this? The docs at http://administrate-docs.herokuapp.com/ don't seem to cover this.

**Comment by graysonwright** [comment]
@maxkwallace you're right - we need to add that to our docs. Right now, every model is displayed using its `to_s` method - you can define `School#to_s` to display whatever you like there.

**Comment by graysonwright** [comment]
I'm going to close this issue for now - it overlaps a fair bit with #129. If you have any more questions around it, feel free to open it back up!

**Comment by maxkwallace** [comment]
@graysonwright Sounds good. Thanks for the tip!

**Comment by tquill** [comment]
Thank you.  I had this question too.
