### ISSUE TITLE
why update request is post action?

### ISSUE THREAD

**Issue by anklos** [thoughtbot/administrate#1755]
Update resource request sends a http `POST` rather than `PUT` or `PATCH`. 

Not quite sure why it is that? On my local it throws no route error when update any resource. (version is 0.14.0)

I also took a screenshot of the submit button in demo app from README, which shows the http method is `POST`

![image](https://user-images.githubusercontent.com/530145/92119451-25083f00-ee3b-11ea-953d-dff4899f0160.png)

Thanks.

**Comment by sedubois** [comment]
If you check the code you can see a hidden field with name `_method` and value `patch`.

> ## 2.4 How do forms with PATCH, PUT, or DELETE methods work?

> The Rails framework encourages RESTful design of your applications, which means you'll be making a lot of "PATCH", "PUT", and "DELETE" requests (besides "GET" and "POST"). However, most browsers don't support methods other than "GET" and "POST" when it comes to submitting forms.

> Rails works around this issue by emulating other methods over POST with a hidden input named "_method", which is set to reflect the desired method

https://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark

**Comment by pablobm** [comment]
@anklos - Can you paste the error you are seeing? It's probably related to something else, as @sedubois has already explained.

**Comment by anklos** [comment]
@sedubois thanks for the guide

@pablobm 

```
I, [2020-09-03T23:06:20.335002 #29983]  INFO -- : Started POST "/admin/user_profiles/13" for 124.170.161.7 at 2020-09-03 23:06:20 +0000
F, [2020-09-03T23:06:20.336302 #29983] FATAL -- :
F, [2020-09-03T23:06:20.336432 #29983] FATAL -- : ActionController::RoutingError (No route matches [POST] "/admin/user_profiles/13"):
```

if I manually change the form action from `post` to `put`, it has no routing error.

I use Rails 5 API, with the middleware config as:

```
   config.middleware.use ActionDispatch::Flash
   config.session_store :cookie_store
   config.api_only = true
```

**Comment by anklos** [comment]
@sedubois also it seems that most browser support `PUT` and `DELETE` nowadays? not like the doc claims that most don't support.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

**Comment by sedubois** [comment]
@anklos I don't know. But this does not seem like an Administrate issue? Maybe try to isolate the issue and/or ask in the Rails forum. Unless @pablobm has suggestions.

**Comment by anklos** [comment]
I guess probably some middleware i should add in the config that parses the hidden `_method` action, as I use Rails API not Rails full stack

**Comment by sedubois** [comment]
You could create a freshly scaffolded Rails app to confirm that the issue does not occur there, then progressively simplify your own app until you find what modification causes the issue.

**Comment by anklos** [comment]
just added `config.middleware.use ::Rack::MethodOverride` and it worked.

https://www.rubydoc.info/gems/rack/Rack/MethodOverride it reads `_method` param.

This middleware was mentioned in the doc https://administrate-prototype.herokuapp.com/rails_api, however I didn't realize it is a must and ignored it.
