### ISSUE TITLE
Any plan to support json type?

### ISSUE THREAD

**Issue by anklos** [thoughtbot/administrate#1759]
* What would you like to be able to do? Can you provide some examples?
* How could we go about implementing that?
* Can you think of other approaches to the problem?

Currently the library does not support json type fields. We could work around by using some plugin like `administrate-field-jsonb`, however they are not quite perfect (i.e it does not work with administrate generator to generate json fields)

I wonder is there any plan to officially introduce json field type in this gem, or any other thoughts?

Thanks.

**Comment by sedubois** [comment]
I did try to use that JSONB field at some point (you might notice the issues I opened), but then realized I didn't really need JSON but something more specific like an "array of strings" type (that is stored in a Postgresql JSONB column), which I implemented with this [`CollectionSelect`](https://github.com/thoughtbot/administrate/pull/1603). So my first question would be what is your use case exactly?

**Comment by anklos** [comment]
thanks @sedubois 

a gem in the codebase (https://github.com/lynndylanhurley/devise_token_auth) that introduce json type column: https://github.com/lynndylanhurley/devise_token_auth/blob/master/lib/generators/devise_token_auth/templates/devise_token_auth_create_users.rb.erb#L38

we could change the column to `text`, but would be good it just works without extra changes.

**Comment by sedubois** [comment]
The code `t.json :tokens` seems to suggest this field does store a collection of (unpredictable) strings. Does the field need to be editable or only viewed? What does it currently look like with the default dashboard config?

**Comment by anklos** [comment]
it only needs to be viewed in admin panel. however if I update any other field in the object, the gem would still do some condition check on the `tokens` based on the json type, which would cause exception because admin panel passes the field as string.

**Comment by anklos** [comment]
currently administrate generates the `tokens` field as `tokens: Field::String.with_options(searchable: false)` in dashboard

**Comment by sedubois** [comment]
So it seems you need a select field with `multiple: true` which only accepts the existing token data as options. Or should it be possible to enter new tokens manually as well?

I tested and it seems that the CollectionSelect I proposed in this PR should work:
https://github.com/thoughtbot/administrate/issues/1535

Except that I had to modify `lib/administrate/field/collection_select.rb` as follows:
```diff
      def collection
-       @collection ||= options.fetch(:collection, proc { [] })
+       @collection ||= proc { data }
      end
```

It would be better to specify this through the field's options but I'm not sure what would be the API for this (just passing the option `collection: proc { data }` wouldn't work as `data` is undefined in the context of the dashboard).

**Comment by nickcharlton** [comment]
The general strategy for Administrate is to cover a set of basic fields only and delegate more complex data structures to plugins. I don't believe that there's a restriction on plugins providing custom generators (perhaps we just don't have an example?), but if there's work we need to do to facilitate this I'd be happy to see an issue about it.

I'm going to close this as @sedubois has shown a reasonable solution to this problem, but if we're missing something, please open a new issue!
