### ISSUE TITLE
How do I customise the page title?

### ISSUE THREAD

**Issue by tomgatzgates** [thoughtbot/administrate#177]
Currently my page title looks like `#<User:0x007fafae315280>`
I'm struggling to find where I can overwrite that.

**Comment by maxkwallace** [comment]
@tomgatzgates I assume you're referring to the page titles for individual models? Take a look at the following issues:

https://github.com/thoughtbot/administrate/issues/129
https://github.com/thoughtbot/administrate/issues/175

**Comment by tomgatzgates** [comment]
Fantastic, thanks!
