### ISSUE TITLE
Field::ActiveStorage MULTIPLE ITEMS is not well imlemented

### ISSUE THREAD

**Issue by pulgamecanica** [thoughtbot/administrate#1780]
I have an application and when I try to add into the product dashboard "images: Field::ActiveStorage" administrate only accepts one submission for the documents... I can't upload one by one or add because it will erase the previous documents....

**Comment by pablobm** [comment]
You may want to file an issue at https://github.com/Dreamersoul/administrate-field-active_storage, as it's a separate project.

**Comment by pulgamecanica** [comment]
> You may want to file an issue at https://github.com/Dreamersoul/administrate-field-active_storage, as it's a separate project.

you're right! Thanks for the guidance
