### ISSUE TITLE
Unpermitted parameters: :password, :password_confirmation remain unsolved

### ISSUE THREAD

**Issue by halkichi0308** [thoughtbot/administrate#1793]
Hi,
I got an error when push [Create User] from New Users which screen was created by administrate(default)
```
Unpermitted parameters: :password, :password_confirmation
   (0.4ms)  BEGIN
  ↳ app/controllers/admin/users_controller.rb:52
  User Exists (0.5ms)  SELECT  1 AS one FROM `users` WHERE `users`.`email` = BINARY 'admin5@example.com' LIMIT 1
  ↳ app/controllers/admin/users_controller.rb:52
   (0.3ms)  ROLLBACK
....
```
Although I was looking for how to solve this problem, I couldn't find it.

and I tried below the following methods.

``` ruby
[app/controllers/admin/users_controller.rb]
module Admin
  class UsersController < Admin::ApplicationController
    before_action :configure_permitted_parameters, :permitted_attributes, if: :devise_controller?

    def create
      super
    end

    protected
    def permitted_attributes
      dashboard.permitted_attributes << %w(password password_confirmation)
    end
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:create, keys: [:password,:password_confirmation])
    end
```

I also tried below code instead of `devise_parameter_sanitizer`
```
x params.require(:user).permit(:email, :password, :password_confirmation)
x params.permit(user:[])
```

Who has solution for this problem?

**Comment by pablobm** [comment]
Three things spring to mind:

1. Those two attributes may not be listed as `FORM_ATTRIBUTES` in your dashboard. Would you be able to show us your `UserDashboard`?

2. There isn't a method `permitted_attributes` in `Administrate::ApplicationController`. Perhaps you mean [`resource_params`](https://github.com/thoughtbot/administrate/blob/e71ebd8c5be2fa3d900ba1111db98f99199ee3dc/app/controllers/administrate/application_controller.rb#L151)?

3. You refer to Devise in your code, for example with `if: :devise_controller?`. Is your `Admin::UsersController` a Devise controller? I haven't used Devise in a while, but I seem to remember that it works with inheritance, so you shouldn't be able to have a `Administrate::ApplicationController` that is also a Devise controller... but I might be wrong on this one.

**Comment by halkichi0308** [comment]
Thanks your tips
Each way can't solve my Issue.
However your third mind reminded me that more easier workaround for this issue.

My solution:
``` ruby
# I've omitted some of the source code below
module Admin
  class UsersController < Admin::ApplicationController
~~
    def create
      # To avoid devise function(Strong Parameters)
      # https://github.com/heartcombo/devise#strong-parameters
      user = User.new()
      user.email = params[:user][:email]
      user.role = params[:user][:role]
      user.password = params[:user][:password]
      user.password_confirmation = params[:user][:password_confirmation]
      user.id=User.maximum(:id)+1
      user.save
      redirect_to admin_user_path(id: user.id), notice: 'User was successfully created.'
    end
~~
end
```
That problem has plagued me for a long time.
Thanks a lot.

**Comment by pablobm** [comment]
I'm glad you fixed it. A couple of notes:

1. I don't think that `before_action :configure_permitted_parameters, :permitted_attributes, if: :devise_controller?` is doing anything there. The controller is not a Devise controller (I think?) so the condition will always be `false`.
2. You shouldn't need to `user.id=User.maximum(:id)+1`. It should be automatically handled by Rails or the underlying database. Unless you have an unconventional setup?
