### ISSUE TITLE
AssetNotPrecompiled after clean install

### ISSUE THREAD

**Issue by stephenson** [thoughtbot/administrate#1802]
* What were you trying to do?
I have just installed the administrate gem on a fresh Rails 6.0.3 and ran `rails generate administrate:install`, when visiting localhost:3000/admin I get `Sprockets::Rails::Helper::AssetNotPrecompiled in Admin::Contents#index`.

* What did you end up with (logs, or, even better, example apps are great!)?
Logs: https://gist.github.com/stephenson/ced9164b4c60b43b051ff60747dd78e6

* What versions are you running?
  - Rails 6.0.3
  - administrate 0.14.0

**Comment by kareemgrant** [comment]
@stephenson Try adding the following to `app/assets/config/manifest.js`

```
//= link administrate/application.css
//= link administrate/application.js

```
It's mentioned here: https://github.com/thoughtbot/administrate#getting-started

**Comment by stephenson** [comment]
> @stephenson Try adding the following to `app/assets/config/manifest.js`
> 
> ```
> //= link administrate/application.css
> //= link administrate/application.js
> ```
> 
> It's mentioned here: https://github.com/thoughtbot/administrate#getting-started

Awesome, that worked! Sorry I did not see that section, I followed the guide on http://administrate-prototype.herokuapp.com/getting_started where that part is not included 👍

**Comment by glenpike** [comment]
This is still potentially an issue as I was looking at the 'Getting Started' page in the Doc's and had not realised that there was a shorter version of Getting Started on the 'Home Page' - the information about the CSS is missing from the former...
