### ISSUE TITLE
Unify "getting started" documentation

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/administrate#1806]
We have two pieces of documentation that describe installation and first steps:

* The "Getting Started" section of the documentation at http://administrate-prototype.herokuapp.com/getting_started
* The "Getting Started" section of the README at https://github.com/thoughtbot/administrate#getting-started

They don't have the same information, which is confusing to users as evidenced by https://github.com/thoughtbot/administrate/issues/1802

Perhaps we should lose the one in the README, and make sure that the docs have the additional information?

**Comment by nickcharlton** [comment]
I think we should lose the one in the README and point towards the main documentation.
