### ISSUE TITLE
Updating from 0.10.0 to 0.14.0

### ISSUE THREAD

**Issue by aksharj** [thoughtbot/administrate#1809]
Hi,

Thanks for a gem of a gem :) 

I am trying to update from 0.10.0 to 0.14.0 and see a few places giving exceptions.

1) undefined local variable or method `page' 

```
undefined local variable or method `page' for #<#<Class:0x00007fea1173fa20>:0x00007fea135f0c80> excluded from capture: DSN not set
  
ActionView::Template::Error (undefined local variable or method `page' for #<#<Class:0x00007fea1173fa20>:0x00007fea135f0c80>):
    25:     "collection",
    26:     collection_presenter: field.associated_collection(order),
    27:     collection_field_name: field.name,
    28:     page: page,
    29:     resources: field.resources(page_number, order),
    30:     table_title: field.name,
    31:   ) %>

```

i fixed this by passing page to `render_field attribute`, like this `render_field attribute, page: page`

2) wrong number of arguments (given 0, expected 2) to `sanitized_order_params`

```
ActionView::Template::Error (wrong number of arguments (given 0, expected 2)):
    28:         scope="col"
    29:         role="columnheader"
    30:         aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
    31:         <%= link_to(sanitized_order_params.merge(
    32:           collection_presenter.order_params_for(attr_name)
    33:         )) do %>
    34:         <%= t(
  
app/views/admin/application/_collection.html.erb:31:in `block in _app_views_admin_application__collection_html_erb___1979491327543919911_70321646233460'
app/views/admin/application/_collection.html.erb:24:in `each'
app/views/admin/application/_collection.html.erb:24:in `_app_views_admin_application__collection_html_erb___1979491327543919911_70321646233460'
app/views/admin/application/index.html.erb:56:in `_app_views_admin_application_index_html_erb___3549165793792612575_70321649542120'
```

I fixed this by passing `collection_presenter` & `attr_name` to `sanitized_order_params`  like this `sanitized_order_params(collection_presenter, attr_name)`

Can anyone please confirm if this would be the correct way to fix the above two issues. Many thanks in advance.

**Comment by pablobm** [comment]
Both look correct to me. It looks like you are using custom views in both cases, am I correct? In general, when you upgrade Administrate, you should regenerate the custom views with `rails generate administrate:views`, and see what's changed and needs to be integrated with your custom changes.

I'm going to close this as I don't think it's a bug, but feel free to comment if you have more relevant information.
