### ISSUE TITLE
Feature Request: Override Default Templates

### ISSUE THREAD

**Issue by estiens** [thoughtbot/administrate#181]
You can override the default views, but you can't override the application layout to customize the sidebar.

**Comment by gpinkham** [comment]
you can copy the _sidebar.html.erb file to app/views/administrate/application/ and then customize it (would be nice the the gem did it for you though)

**Comment by estiens** [comment]
Is it possible to override javascript files the same way?

**Comment by graysonwright** [comment]
@estiens yep! you can copy over the JS files. We're discussing how to support this more officially in #187.

Also, we do plan to have a generator for the page layouts - that's a likely 0.1.2 feature.

**Comment by estiens** [comment]
Great. thanks!

**Comment by graysonwright** [comment]
Should be fixed by #269!

**Comment by graysonwright** [comment]
The fix will go out in `0.1.3`.
