### ISSUE TITLE
Docs sites do not load

### ISSUE THREAD

**Issue by niedfelj** [thoughtbot/administrate#1814]
* What were you trying to do?
* What did you end up with (logs, or, even better, example apps are great!)?
* What versions are you running?
  - Rails
  - administrate

**Comment by nickcharlton** [comment]
Which doc sites? What error are you getting?

**Comment by niedfelj** [comment]
Looks like @pablobm updated the readme to point https://administrate-demo.herokuapp.com/docs, but I get an error saying it doesn't exist.

<img width="820" alt="Captura de Tela 2020-10-29 às 18 51 42" src="https://user-images.githubusercontent.com/294487/97636452-e72d2e80-1a17-11eb-9f4d-788799cdc42d.png">

**Comment by niedfelj** [comment]
@nickcharlton 🤞

**Comment by nickcharlton** [comment]
Oh I see! That's because there isn't a `/docs`, the pages in the directory `/docs/` render relative to the root.

There was a change I made to the README which introduce them, it seems. I'll push up a fix.
