### ISSUE TITLE
Webpacker issue when using database replicas as read source.

### ISSUE THREAD

**Issue by rajahafify** [thoughtbot/administrate#1818]
I'm trying to hook administrate with write: primary <> read: replica database. 
I was following the guide here:
https://guides.rubyonrails.org/active_record_multiple_databases.html

When we deploy to our staging server. We run into 500 error. 

```ruby
def handle_missing_entry(name)
    raise Webpacker::Manifest::MissingEntryError, missing_file_from_manifest_error(name)
end
```

> Webpacker::Manifest::MissingEntryError
> Webpacker can't find administrate in /web/public/packs/manifest.json. Possible causes:
> 1. You want to set webpacker.yml value of compile to true for your environment
>    unless you are using the `webpack -w` or the webpack-dev-server.
> 2. webpack has not yet re-run to reflect updates.
> 3. You have misconfigured Webpacker's config/webpacker.yml file.
> 4. Your webpack configuration is not creating a manifest.
> Your manifest contains:
> {
> }

More info here: https://sentry.io/share/issue/0589c522604340ff97d17abddf95b60c/

The problem doesn't happen to our main deployment (non-admin). Once we reverted the deployment, the problem is gone. 

Our gem versions: 

```ruby
gem 'rails', '~> 6.0.3.1'
gem 'administrate', git: 'https://github.com/thoughtbot/administrate'
gem 'administrate-field-active_storage'
gem 'administrate-field-nested_has_many'
gem 'administrate-field-simple_markdown', '~> 0.5.0'
```

**Comment by pablobm** [comment]
Uh, this is weird. In theory Webpacker should not know anything about databases. In practice... who knows what's going on.

Are you able to explain a bit more about what the exact change was? Is it possible to provide a diff? I wonder if there's more to it than just DB-related changes.

**Comment by rajahafify** [comment]
<img width="966" alt="Screenshot 2020-11-05 at 6 34 51 PM" src="https://user-images.githubusercontent.com/924488/98230181-d50e3b80-1f95-11eb-8c45-8f72efe6d252.png">
<img width="964" alt="Screenshot 2020-11-05 at 6 35 06 PM" src="https://user-images.githubusercontent.com/924488/98230192-d8092c00-1f95-11eb-9090-869c9117fe33.png">
<img width="724" alt="Screenshot 2020-11-05 at 6 35 45 PM" src="https://user-images.githubusercontent.com/924488/98230205-db041c80-1f95-11eb-907e-4b85bfbf773e.png">

There's also a file change in k8s secrets where we set the value for DATABASE_REPLICA_URL and nothing else

**Comment by pablobm** [comment]
Hm... all I can think of is perhaps it's a problem with loading order, or something like that.

Here's a totally random idea. Your original code had that default value for database URL, which used `Rails.application.credentials.database.fetch(:url)`. Was this being triggered in your staging environment? I wonder if running this line activated some magic that ended up loading things in a different order.

This might be "just a Rails bug", but on the other hand I can't be sure as we do have our own Webpacker-related issues with Administrate. I don't have a multi-DB setup at hand to test right now unfortunately, so it's a bit tricky for me to debug. Would you be able to look into what Webpacker is doing? For example, looking at the code around here and see what the difference is between the two DB configurations:

https://github.com/rails/webpacker/blob/257df41cb17017ab29f1415cf856da494fd93cfc/lib/webpacker/manifest.rb#L48-L50

**Comment by rajahafify** [comment]
Loading order seems to be the problem @pablobm. The issue dissapper when i use Rails Credentials to get the database urls.
I guess its because we have this in our initializers:

```ruby
# config/initializers/administrate.rb
Administrate::Engine.add_stylesheet('selectize/dist/css/selectize')
```

I don't have time yet to check what webpacker are doing, but I assume, using Rails Credentials in `database.yml` force rails to autoload the initializers.

**Comment by pablobm** [comment]
Thank you for reporting back. That's useful to know :+1:

**Comment by pablobm** [comment]
I agree. Closing.
