### ISSUE TITLE
Resource name in flash messages is in camel case

### ISSUE THREAD

**Issue by orenyk** [thoughtbot/administrate#1819]
* What were you trying to do?
  * Set up a dashboard with a resource name that is two acronyms combined (e.g. `FOO BAR`), when both `FOO` and `BAR` are registered as acronyms with ActiveSupport (so that the path names work, e.g. `app/models/foo_bar.rb`). I expect that in flash messages that the name will be represented correctly (e.g. `FOO BAR was successfully created.`)
* What did you end up with (logs, or, even better, example apps are great!)?
  * The resource name in flash messages is the two acronyms combined without the space (e.g. `FOOBAR was successfully created.`). The root cause is [here](https://github.com/thoughtbot/administrate/blob/84084235463a6761f25108382cb81c13632d2052/lib/administrate/resource_resolver.rb#L34), where the ResourceResolver first converts the resource name to camel case, causing the space to be lost when it is subsequently converted to snake case in `#resource_name`.
* What versions are you running?
  - Rails
    - 6.0.3.4
  - administrate
    - 0.14.0

If anyone else is experiencing this, for the time being my workaround is to override `translate_with_resource` method in that specific resource's controller to hard-code the resource name with the space instead of relying on `ResourceResolver`.

Hope this helps! 

---

**EDIT 2020-11-05** I don't believe this is exclusive to resources whose names begin with an acronym, as I'm also seeing it with non-acronym resources. I'm not sure why the following lines aren't working (I checked that the `model_name.human` methods work in the Rails console, so maybe there's an issue with `resource_class`?):
https://github.com/thoughtbot/administrate/blob/84084235463a6761f25108382cb81c13632d2052/lib/administrate/resource_resolver.rb#L23-L25

**Comment by pablobm** [comment]
Thank you for filing this issue. In general the resolver is due an revision, and this is the sort of behaviour that we need to keep in mind.

**Comment by orenyk** [comment]
No problem! If I have some time I'll see if I can take a stab at a PR for at least this issue - it feels like it must be possible to leverage the same ActiveSupport mechanisms that allow acronyms to be registered to begin with. Thanks!

**Comment by orenyk** [comment]
Just as a follow-up, I was incorrect in my assumption that this was specific to acronyms; I'm seeing the same behavior with regular camel-cased resources (`FooBar`). I'll still try to take a look and investigate further.

**Comment by orenyk** [comment]
A little bit more info - I'm able to replicate this issue in the console and it's kinda weird:

```ruby
irb(main):011:0> Administrate::ResourceResolver.new('admin/foo_bars').resource_title
=> "FooBar"
irb(main):012:0> Administrate::ResourceResolver.new('admin/foo_bars').resource_class.model_name.human
=> "Foo bar"
```

**Comment by pablobm** [comment]
Good news! It looks like this is fixed in master. Not sure when, but I suspect it's due to #1633. Here's an illustration of 0.14 vs. master:

![Before: "FooBar was successfully created". After: "Foo bar was successfully created".](https://user-images.githubusercontent.com/36066/98447731-0c5c2400-211f-11eb-90f4-387ddbcc08c3.png).

I'm going to close this as I think that's it, but feel free to comment or provide other info if you see an issue. For example, I guess the capitalisation is up for debate, but I think that should be customisable via i18n.
