### ISSUE TITLE
Dashboard Manifest generator

### ISSUE THREAD

**Issue by astamm78** [thoughtbot/administrate#182]
Rather than running `rails generate administrate:install` and going through the overwrite prompts for each model, would it be possible to have a single-model generator for when new models get added to an application?

**Comment by gpinkham** [comment]
rails generate administrate:dashboard Foo

**Comment by astamm78** [comment]
Perfect. Missed that in the docs

**Comment by zamith** [comment]
What about for projects that start using administrate pretty late in the game, when they already have dozens of models, but only want dashboards for some? Is that a solution as well?

**Comment by graysonwright** [comment]
@zamith - you could take a couple approaches there.

1. Run `rails generate administrate:install`, and delete the dashboards you don't want
2. Run `rails generate administrate:dashboard ModelName` for each dashboard you do want.

If you go with option 2, you'll also need to define a `DashboardManifest` class [that follows this structure][manifest].

[manifest]: https://github.com/thoughtbot/administrate/blob/master/spec/example_app/app/dashboards/dashboard_manifest.rb

**Comment by zamith** [comment]
@graysonwright Right, I was wondering about the manifest. I think I'll take number 2. Any interest/ideas to improve the flow in this situation, or is this not a regular use case at all?

**Comment by graysonwright** [comment]
At the moment we don't have a generator for creating only a blank manifest - we could add that in as part of our generator push.

Thanks for the suggestion!

**Comment by zamith** [comment]
That would be cool. Thanks.

**Comment by zamith** [comment]
@graysonwright Btw, is there a way to specify the directory administrate uses? I already have an `admin` directory for other things, I would like to change it.

**Comment by zamith** [comment]
It seems you also need an `Admin::ApplicationController`, or to change the inheritance to something else.

**Comment by graysonwright** [comment]
@zamith at the moment, `admin` is hard-coded. We'd like to change that, but haven't gotten to it yet. There's discussion in https://github.com/thoughtbot/administrate/issues/281.

**Comment by graysonwright** [comment]
follow-up to the `admin` namespace discussion in #339, #332.

**Comment by graysonwright** [comment]
This should be fixed by #362.
