### ISSUE TITLE
"Un-deprecate

### ISSUE THREAD

**Issue by orenyk** [thoughtbot/administrate#1820]
* What would you like to be able to do? Can you provide some examples?
* How could we go about implementing that?
* Can you think of other approaches to the problem?

**Comment by nickcharlton** [comment]
Did you mean to open this? Could you add some more detail?

**Comment by orenyk** [comment]
Huh, there was a weird bug with GitHub when I submitted #1821 so I think it somehow submitted this at the same time? Sorry about the noise!
