### ISSUE TITLE
Order fields on the nested attributes edit form by id 

### ISSUE THREAD

**Issue by aksharj** [thoughtbot/administrate#1833]
Hi All,

I have a dashboard which loads a nested attributes form and `ATTRIBUTE_TYPES` is defined as
```
use_case_workflow_steps: Field::NestedHasMany.with_options(skip: :use_case_workflow_filter, sort_by: :id_column)
```

But this seems to sort the view on show page, how do I sort the nested forms records on the edit form. Any help on this would be really great.

Thanks.

**Comment by pablobm** [comment]
This appears to be an issue with https://github.com/nickcharlton/administrate-field-nested_has_many, rather than Administrate proper. I think you should file it there.
