### ISSUE TITLE
Possibility to have two or more instances of administrate in same rails app

### ISSUE THREAD

**Issue by inem** [thoughtbot/administrate#1847]
I have several roles in my app. And instead of implementing permissions system I am considering to simply add multiple instances of administrate with different sets of functionality. For repeating logic I'd just reuse some service layer logic.

Currently [documentation for generators looks](https://administrate-demo-prerelease.herokuapp.com/customizing_page_views) like only one instance of administrate is possible. But maybe I am wrong.

**Comment by liang3404814** [comment]
potential duplicate https://github.com/thoughtbot/administrate/issues/1764

**Comment by pablobm** [comment]
I agree that this is a duplicate of https://github.com/thoughtbot/administrate/issues/1764. I'm closing, but please let us know if you think otherwise.
