### ISSUE TITLE
Improve default styling of validation messages

### ISSUE THREAD

**Issue by stefanwille** [thoughtbot/administrate#185]
If I edit a user, delete the name and click "Update", the resulting page has a broken layout. Please see my screenshot.

<img width="1299" alt="screenshot" src="https://cloud.githubusercontent.com/assets/331756/11014597/f613d224-853d-11e5-8b76-9804b84338a3.png">

**Comment by graysonwright** [comment]
oh, wow - that's pretty bad. Thanks for pointing this out!

**Comment by erdostom** [comment]
Should prob put this in flashes.
It would also be nice if required fields were asterixed

**Comment by tehfailsafe** [comment]
Any update on this? Client just ran into it...

**Comment by carlosramireziii** [comment]
![screen shot 2017-03-01 at 8 37 32 pm](https://cloud.githubusercontent.com/assets/362585/23489166/f6b459a0-febe-11e6-9d2b-df1e37d296fd.png)

Still seems to be an issue. 

@nickcharlton What's the best way to fix this one? Should we just add a little bit of styling to give a better default experience?

**Comment by nickcharlton** [comment]
I think we should style the default flash messages (or adjust the markup to fit right). There's a nice version in [Refills](http://refills.bourbon.io) we'll be able to use.

**Comment by nickcharlton** [comment]
I'm going to close this as it should be fixed with #760. Please open again if it doesn't!
