### ISSUE TITLE
Administrate doesn't read context on Model when load form for mandatory field

### ISSUE THREAD

**Issue by helmiItsavirus** [thoughtbot/administrate#1860]
* What were you trying to do?

When I define validation inside of the context on my Model, Administrate doesn't read the context. So, Mandatory appears on the form that should not appear because of the mandatory inside of the context.

* What did you end up with (logs, or, even better, example apps are great!)?

```
class User < ApplicationRecord
  with_options on: [:update_birth_date] do
    before_validation :age_is_old_enough
    validates_presence_of :birth_date
  end
end
```
         
* What versions are you running?

- ruby "2.6.6"
- gem "rails", "~> 6.0.3", ">= 6.0.3.2"
- gem "administrate", "~> 0.14.0"

**Comment by pablobm** [comment]
Thank you for your report. I don't entirely understand what your code block represents. Is it:

* A workaround?
* An example of code that doesn't work?

I'm trying to reproduce, but I'm not sure of what to do.

**Comment by helmiItsavirus** [comment]
Hi, @pablobm 

Thanks for your response. Actually, I had a problem when the validation e.g "validates_precense_of" inside the context.

Administrate make the field that has validation inside the context become mandatory when I see it in the form.

I think Administrate should not make the field become mandatory in form because of the validation inside the context.

**Comment by pablobm** [comment]
I see now. You are right, this is a bug. A fix is not entirely obvious as there are several ways to go about this. I have created a PR at https://github.com/thoughtbot/administrate/pull/1872. This will need a bit of discussion, and hopefully we'll be able to fix this.

**Comment by pablobm** [comment]
By the way @helmiItsavirus: I'm not sure if you are aware, so I'll explain here. In your code, the problem is not the `with_options` (which I think is what you mean as "context"). Your code is equivalent to the following:

```ruby
class User < ApplicationRecord
  validates_presence_of :birth_date, on: [:update_birth_date]
end
```

It is actually the `:on` option that Administrate has an issue with. The way you asked confused me a bit, so I thought I'd explain.

**Comment by helmiItsavirus** [comment]
@pablobm thanks for your correction with simple code, actually I'm using with_options to use the context even though too long looks like.
