### ISSUE TITLE
Check if an associated model's route exists before trying to link it

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/administrate#1861]
Over at StackOverflow, a user had an issue: https://stackoverflow.com/questions/65538115/administrate-gem-does-not-allow-to-view-user

I was able to reproduce it on the example app as follows:

1. Remove `resources :orders` from the routes file.
2. Visit the "show" page of a customer.

The page breaks because Administrate is trying to link to the orders of the customer. However orders do not have routes, so there's nothing to link.

Administrate is checking with `show_action?` before rendering the link, but that only checks for authorization. It should be checking with `valid_action?`, which does check for the existence of the route.

This brings a new question: should we have only one such helper, which checks for both authorization and existence?

**Comment by nickcharlton** [comment]
Heh, I saw this problem recently myself. One helper would work well, I think: if you're allowed to view something that's sort of moot if it doesn't exist in the first place!
