### ISSUE TITLE
Could not find generator 'administrate:install'. Maybe you meant "administrate:field"?

### ISSUE THREAD

**Issue by aguynamedben** [thoughtbot/administrate#1873]
I'm trying administrate out for the first time and getting an error when running `rails generate administrate:install` (see below). I'm a pretty experienced Rails engineer, and this is a pretty vanilla app, so I'm not sure what's wrong. This is my first experience with administrate so I'm not sure where to look.

Thanks for making this project and supporting it. I'm looking forward to using this instead of rails_admin. 🙏 

---

* What were you trying to do?
Install administrate on my pretty vanilla Rails app

* What did you end up with (logs, or, even better, example apps are great!)?
An error on running `rails generate administrate:install`
![image](https://user-images.githubusercontent.com/107841/105644406-44cfec00-5e4a-11eb-8462-8f58d6045ed5.png)

* What versions are you running?
  - Rails 6.1.1 (also happened on Rails 6.0.x)
  - administrate 35a21cf (also happened on 0.14.0)
  - Ruby 2.7.2

**Comment by aguynamedben** [comment]
List of administrate generators in my environment:
![image](https://user-images.githubusercontent.com/107841/105644681-aba1d500-5e4b-11eb-9853-2130d5193972.png)

**Comment by aguynamedben** [comment]
As far as I know, I don't use spring. But it does seem to be installed.
```
falcon!ben:/Users/ben/code/mammoth$ which spring
/Users/ben/.rbenv/shims/spring
falcon!ben:/Users/ben/code/mammoth$ spring stop
Spring is not running```

**Comment by sedubois** [comment]
It seems related to `clientconfig_controller.rb` (`Error: superclass must be a class (module given)`). How is it defined?

**Comment by aguynamedben** [comment]
Ahhh, I think this fixes it... we had some bad controller definitions 🤦‍♂️ 

This must be it... I'll give it a go again soon. Thanks @sedubois I was digging through the backtrace but missed the error at the top and the fact that it was related to the line under it. 🙏 

![image](https://user-images.githubusercontent.com/107841/105827866-595dd280-5f77-11eb-8163-bae4a58717a1.png)

**Comment by Iccr** [comment]
this is still an issue in 0.15, is there any updates for this.

**Comment by pablobm** [comment]
@Iccr - The original issue was due to a problem in the user's own setup. It was not a bug. If you are experiencing something similar, we are going to need some more information. Can you provide a backtrace and some context? Thank you in advance.
