### ISSUE TITLE
Add translations to kaminari pagination labels 

### ISSUE THREAD

**Issue by edimossilva** [thoughtbot/administrate#1888]
* What would you like to be able to do? Can you provide some examples?
  I would like to have labels from kaminari like "first",  "last", "previous" and others translated to other languages.

* How could we go about implementing that?
 As previously discussed in #1622, I could create a file named `kaminari.pt-BR.yml` with the translations.

* Can you think of other approaches to the problem?
No

Can I create a PR for it?

**Comment by pablobm** [comment]
Yeah, go for it :+1:

**Comment by edimossilva** [comment]
Ops, it was fixed by https://github.com/thoughtbot/administrate/pull/1777 I think you should close it

**Comment by pablobm** [comment]
Cool. Let's see if we can get a new version published soon that includes this :crossed_fingers:
