### ISSUE TITLE
No route matches [POST] "/admin/users/22"

### ISSUE THREAD

**Issue by tomgatzgates** [thoughtbot/administrate#189]
I'm running into an issue when I try to edit any of my models that I get a no route matches error. Has anyone else run into the same thing?

**Comment by tomgatzgates** [comment]
Rails-api gem causing issues. Ignore

**Comment by jrnk** [comment]
For other people running into this, or `flash` related problems when using the `administrate` gem with `rails-api`. Add the following two middleware in `application.rb` 

```
config.middleware.use ActionDispatch::Flash
config.middleware.use Rack::MethodOverride
```

**Comment by graysonwright** [comment]
@tomgatzgates is that the same workaround you used? If not, can you post your solution as well for others who might run into it?

Thanks!

**Comment by vokecodes** [comment]
Visiting the edit page I get the below error 

`No route matches [GET] "/admin/3/edit"`

I encounter this after I updated my app to use ruby '2.7.4'
