### ISSUE TITLE
How to use a modal form?

### ISSUE THREAD

**Issue by webdev36** [thoughtbot/administrate#1890]
Hi guys, I'm so happy to use this gem so I want to say thanks.
Just I'd like to use the CSV import button on the index page as a modal form for selecting a CSV file.
But here is no way to use the modal form.
Could you please help me?

**Comment by pablobm** [comment]
Hello @webdev36. I don't understand what you are asking. At the moment, there isn't any functionality in Administrate to import from CSV files, and there aren't any modals.

If you are asking how to implement such functionality, I think you can do the following:

1. Copy the template https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/index.html.erb into your app.
2. Change it to include a feature for importing CSV.
3. Add a new action in one of your controllers, which would deal with the upload.

I'm going to close this issue, as I don't think you are describing a problem with Administrate, but rather a feature that you need, and can be implemented as described. Let us know if you need more info.
