### ISSUE TITLE
Demo source code

### ISSUE THREAD

**Issue by daveit** [thoughtbot/administrate#190]
I've had a brief play, but have a few questions.
I'm sure the demo source code will answer most of them, but darned if I can find it ?
Thanks, Dave

**Comment by graysonwright** [comment]
@daveit - the demo app is hosted in the same repository as the rest of administrate, in the `spec/example_app` subdirectory. Here's a link: https://github.com/thoughtbot/administrate/tree/master/spec/example_app

Cheers! Reopen this if you have any other questions about the demo app.

**Comment by HHGB12** [comment]
Hi, i know that it's an old topic, sorry
I'm looking to get the full source code of the demo, as a launchable app, the link https://github.com/thoughtbot/administrate/tree/master/spec/example_app is not really an app ... is there someone who tried to duplicate the demo and so perfect to grab it 😎 ????

**Comment by nickcharlton** [comment]
The [Repository Structure](https://github.com/thoughtbot/administrate/blob/master/README.md#repository-structure) section should provide what you need.

What's in `spec/example_app` is what's running on Heroku and providing the demo.

If you have more specific questions, I'd recommend opening a new issue.
