### ISSUE TITLE
Trying to render a collection field with a PaperTrail versions key throws an exception

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#1911]
If you have something like this:

```ruby
# COLLECTION_ATTRIBUTES
# an array of attributes that will be displayed on the model's index page.
#
# By default, it's limited to four items to reduce clutter on index pages.
# Feel free to add, remove, or rearrange items.
COLLECTION_ATTRIBUTES = %i[
  versions
].freeze
```

You'll get an exception early on like:

```ruby
undefined method `first' for nil:NilClass
```

thrown from: `owner = owners_by_key[convert_key(record[association_key_name])].first` in `activerecord (6.0.3.2) lib/active_record/associations/preloader/association.rb:105:in `block in records_for'`

My feeling is that you'd likely not _want_ `versions` on your collection attributes in the first place but it'd be nice if Administrate knew this could go wrong and pointed you to what's going on.

I'd be interested to hear if this can be triggered by other configurations, too.

---
* What versions are you running?
  - Rails: 6.0.3.2
  - administrate: > 0.14.0 (current `master` as of 2021-02-16)

**Comment by pablobm** [comment]
I just tried with Rails 6.0.3.5 and it worked for me. What field type do you have in `ATTRIBUTE_TYPES`?

This is what I have:

```
require "administrate/base_dashboard"

class DeviceDashboard < Administrate::BaseDashboard
  # ATTRIBUTE_TYPES
  # a hash that describes the type of each of the model's fields.
  #
  # Each different type represents an Administrate::Field object,
  # which determines how the attribute is displayed
  # on pages throughout the dashboard.
  ATTRIBUTE_TYPES = {
    id: Field::Number,
    name: Field::String,
    code: Field::String,
    versions: Field::HasMany,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze

  # COLLECTION_ATTRIBUTES
  # an array of attributes that will be displayed on the model's index page.
  #
  # By default, it's limited to four items to reduce clutter on index pages.
  # Feel free to add, remove, or rearrange items.
  COLLECTION_ATTRIBUTES = %i[
    id
    name
    code
    versions
    created_at
  ].freeze

  # ...
end
```

And I get a count as it's a default with `HasMany` fields in the index page:

![Example index page with column value of "2 versions" for PaperTrail field](https://user-images.githubusercontent.com/36066/110826140-af1edd80-828c-11eb-9611-0d345681d11c.png).

I haven't explored others pages (eg: show pages) for now.

**Comment by nickcharlton** [comment]
Hmm, interesting. I'm going to close this for now on the assumption that it's a bit more complex than perhaps I found, but also that just having a record in an issue should be good enough to suggest what might be going wrong if someone else sees this.

If anyone else is able to reliably replicate this, feel free to comment!
