### ISSUE TITLE
customize edit and destroy links

### ISSUE THREAD

**Issue by dvodvo** [thoughtbot/administrate#1917]
* What were you trying to do?
 
  Present an index without an edit or destroy link for a specific class

   administrate/app/views/administrate/application/_collection.html.erb 

is the partial that generates these links, however the manual provides no indication
    https://administrate-demo.herokuapp.com/customizing_page_views
as to how to generates a customized views *without* such links 

Is there any shortcut to do so?  Otherwise how can this be accomplished on a per-model basis?

* What versions are you running?

  - Rails  6.0
  - administrate 0.14.0

**Comment by sedubois** [comment]
This works in my app using Pundit policies and  [`Administrate::Punditize`](http://administrate-demo.herokuapp.com/authorization). I have a `destroy?` method, if it returns false then the destroy links are not present.

**Comment by dvodvo** [comment]
That can be helpful as pundit is already installed.  
However:

```
include Administrate::Punditize
module Admin
  class ApplicationController < Administrate::ApplicationController
 
[card_policy.rb]
  def destroy?
    false
  end


```
still leaves the link present unless I_ve_got_something_wrong.


But that would only deal with the destroy link.  Is there any idea with the edit link?

**Comment by sedubois** [comment]
`Administrate::Punditize` has a method `authorize_resource`. You could set a breakpoint there and in your destroy? method to see if they are called properly. If you have trouble putting a breakpoint in a third-party lib you could copy the authorize_resource code in your own application controller.

For edit, the same should work using `edit?`.

**Comment by dvodvo** [comment]
I guess I did not  scan the documentation properly enough  [the customizable controller actions page] (https://administrate-prototype.herokuapp.com/customizing_controller_actions) has a perfect pointer. For a per class basis:
```
    def valid_action?(name, resource = resource_class)
      %w[edit destroy].exclude?(name.to_s) && super
    end
```
Having `def scope`already established in scope policies, there was conflict in using `Administrate::Punditize` inclusion. The one-liner definition addresses the issue directly in the most succinct manner.
