### ISSUE TITLE
dashboard for namespaced model (eg. audited:audits)?

### ISSUE THREAD

**Issue by df1228** [thoughtbot/administrate#1919]
* What would you like to be able to do? Can you provide some examples?

i'm using audited for tracking database changes, the model is audited:audit and the table is audits, how to add a dashboard model for this ?

* How could we go about implementing that?
* Can you think of other approaches to the problem?

**Comment by sedubois** [comment]
You can normally generate namespaced dashboards with some workarounds which I described here:
http://gist.github.com/70955

I was able to use this system for dashboards such as PaperTrail::Version, ActiveStorage::Blob, etc.

There is also apparently a proper fix being worked on in https://github.com/thoughtbot/administrate/pull/1812.

**Comment by dfang** [comment]
thanks !

**Comment by df1228** [comment]
thanks !

**Comment by df1228** [comment]
https://github.com/thoughtbot/administrate/issues/1291
