### ISSUE TITLE
customize redirect_url after update a resource

### ISSUE THREAD

**Issue by df1228** [thoughtbot/administrate#1920]
* What would you like to be able to do? Can you provide some examples?
redirect to index action after an resource

* How could we go about implementing that?

```
add a redirect_url_for_update method
```

* Can you think of other approaches to the problem?

**Comment by sedubois** [comment]
If you need some special behaviour when updating a resource, I guess you could override the update method in your controller?

**Comment by df1228** [comment]
hi @sedubois, this is the update method from administrate gem

```
    def update
      if requested_resource.update(resource_params)
        redirect_to(
          [namespace, requested_resource],
          notice: translate_with_resource("update.success"),
        )
      else
        render :edit, locals: {
          page: Administrate::Page::Form.new(dashboard, requested_resource),
        }
      end
    end
```

what is the path for index action ?

thanks !

**Comment by sedubois** [comment]
I guess it would be `[namespace, requested_resource.class]`.

**Comment by pablobm** [comment]
Thank you @sedubois for helping out!
