### ISSUE TITLE
Nested resources in admin namespace 

### ISSUE THREAD

**Issue by AliRodri1992** [thoughtbot/administrate#1946]
I get  uninitialized constant Admin::AddressesController: with the below setup

```
# routes.rb
namespace :admin do
    resources :agents do
      resources :addresses
    end
end

module Admin
  class Agents::AddressesController < Admin::ApplicationController
    def index
      @addresses = Address.where(agent_id: params[:agent_id])
    end
  end
end
```

**Comment by sedubois** [comment]
In your routes, `addresses` is defined within the `admin`namespace, which I guess is why you get that error.

**Comment by pablobm** [comment]
There are two problems here. The first one is that, currently, Administrate doesn't deal will with namespaced resources. This is a known problem.

The second thing is that you are providing your own `index` route. The `index` template supplied by Administrate is going to miss several variables that it will normally expect.

**Comment by pablobm** [comment]
Closing as I think this is not an issue any more. Happy to reopen if you think otherwise.

**Comment by thebravoman** [comment]
> Closing as I think this is not an issue any more. Happy to reopen if you think otherwise.

Does this mean that administrate can now handle nested resources?

**Comment by pablobm** [comment]
Hopefully yes! :slightly_smiling_face:
