### ISSUE TITLE
Field::Select using hash as a collection (can use key and value)

### ISSUE THREAD

**Issue by helmiItsavirus** [thoughtbot/administrate#1947]
I have a problem when I try to implement **Field::Select** using hash as a collection.

## Current Feature
Field::Select.with_options(collection: [:name1, :name2]),

## Request Feature
Field::Select.with_options(collection: [{key1: :product1},{key2: :product2}]),

## Expectation
```
<select>
     <option value="key1"> product1</option>
     <option value="key2"> product2</option>
</select>
```

**Comment by sedubois** [comment]
PR #1603 might help, configured using `text_method` and `value_method`.

**Comment by pablobm** [comment]
Does it work if you do the following instead?

```
Field::Select.with_options(collection: [[:key1. :product1], [:key2: :product2]]),
```

**Comment by helmiItsavirus** [comment]
@pablobm yeah it works!
