### ISSUE TITLE
Add example of file upload 

### ISSUE THREAD

**Issue by alvarowolfx** [thoughtbot/administrate#195]
Will be good to have a example of how to integrate some form of file upload to people follow. By the way, really nice work on this gem.

**Comment by nickmjones** [comment]
+1 would be nice specifically to know how to integrate paperclip. And yes, this is a really excellent gem.

**Comment by picandocodigo** [comment]
I managed to integrate Paperclip pretty easily. It was already working on my project so I just generated a new field.

```
rails generate administrate:field paperclip
```

The code for `app/fields/paperclip_field.rb`;
```ruby
class PaperclipField < Administrate::Field::Base
  def url
    data.url
  end

  def thumbnail
    data.url(:thumbnail)
  end

  def to_s
    data
  end
end
```

**VIEWS**

```
# app/views/fields/paperclip_field/_form.html.erb
<%= f.label field.attribute %>
<%= f.file_field field.attribute %>

# app/views/fields/paperclip_field/_index.html.erb
<%= image_tag field.thumbnail %>

# app/views/fields/paperclip_field/_show.html.erb
<%= image_tag field.url %>
```

I have a User model with `avatar` as an attached file. So in my User dashboard, I added the new field to the ATTRIBUTE_TYPES hash (and removed the other `avatar` related fields):
```ruby
avatar: PaperclipField
```

I am using it in my FORM_ATTRIBUTES and COLLECTION_ATTRIBUTES as any other field. Note that I created a `thumbnail` method because I defined a thumbnail size in the avatar's styles. But you can ignore that and just use `url` for the views.

I think that's it, if I didn't miss anything. I'm loving `administrate` :smiley:

**Comment by nickmjones** [comment]
@picandocodigo worked perfectly, thanks

**Comment by graysonwright** [comment]
@picandocodigo thanks, this looks great!

I'm working to extract the `image` field into a separate plugin. I might take your solution and package it up into an `administrate-paperclip` gem, if that's cool with you.

**Comment by picandocodigo** [comment]
@graysonwright of course, feel free to use it :+1:

**Comment by graysonwright** [comment]
Great! I'll give you a shoutout in the README.

**Comment by alvarowolfx** [comment]
Thanks @picandocodigo, I will use your solution.

**Comment by murdoch** [comment]
If anyone's interested, here's a similar setup for getting a CkEditor textarea:

`bin/rails g administrate:field ck_editor`

Then open up _app/fields/_form.html.erb_:

**Comment by picandocodigo** [comment]
@nickmjones @alvarowolfx Glad I could help :smiley: 

@graysonwright Looking again at the code, the `thumbnail` method could be parameterized or have just one `url` method with a `style` parameter. Since Paperclip allows for multiple styles, I was thinking of a way to have different styles for different views. For example display full size in the show view and thumbnails in the index view. The only way I found to do that was writing a `thumbnail` method on the model for the attachment and a new "field" called thumbnail which would receive the style in `with_options`. Just writing down my thoughts, but maybe there's a better way to make parameterized fields for different models.

If you're working on creating fields as plugins, I also added a "password" field to my app to have a password input. I can share that code if anyone needs it.

**Comment by graysonwright** [comment]
@picandocodigo wow, great!

I'll try to extract this into a plugin this weekend, and let you know if I have any questions. Cheers!

**Comment by tute** [comment]
@picandocodigo I just used your snippets, thanks for your comment!

**Comment by picandocodigo** [comment]
Awesome! Glad I could give something back. As I said, I'm loving the gem and I'm using it in a branch in a production project, hopefully will completely move away from rails_admin this week, merge to master and deploy.

Wish I could do more, I'd love to give a coding issue a try if you need any help. And let me know if you have any questions on how I'm using this stuff. Looking forward to implementing some plugins once they're defined :smile:

**Comment by taylorscollon** [comment]
Just wanted to say thanks for the nice solution. This was helpful for me.

**Comment by marcog** [comment]
Uploading with Carrierwave is pretty strait forward too, following @picandocodigo path:

```rails generate administrate:field carrierwave

**Comment by nando** [comment]
We're using Carrierwave in our project, thanks @marcog! And thanks @picandocodigo, @graysonwright and the rest of the people making possible to build this great tool :)

p.d.: @graysonwright you put a typo in the milestone version tag of this issue :(

**Comment by jrguenther** [comment]
Another use case you might want to consider is selecting multiple files. It requires you do two things:

* create a field that has the attribute `multiple: true`
* modify the controller to handle the array of image or file values

**Comment by knopfler81** [comment]
Hi there is there any tutorial to add carrievave with multiple images ?
I'm a newbie on rails and I don't understand (yet) how I could do :(
Cheers

**Comment by jrguenther** [comment]
I don't use carrierwave, so I don't know the specifics of how it works. In general, though, there are two ways you can add support for multiple images to your form. If you have a set number of images, you could add each of these fields to your model and add input fields to your administrate form using the techniques described in this thread and in the docs.

If want to allow a user to upload an unknown number of images via a single form file input, you will need to what I described above. Here's a more detailed explanation.

`$ rails generate administrate:field image_many`

Create an administrate field for the multiple files:
`app/fields/image_many_field`
```
require "administrate/fields/base"

class ImageManyField < Administrate::Field::Base
  def to_s
    data
  end
end
```

Modify the view:
`views/fields/image_many_fields/_form.html.erb`
```
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.file_field field.attribute, multiple: true %>
</div>
```
The `multiple: true` option is what makes it possible to update multiple files.

Then you need to update the controller for the resource you want to support multiple files with. By default, the params method used by the controller only allows you to create a single object at a time. You need to override the create action in the resource's admin controller to accept an array of images.

```
def create
      images = params[:photo][:image]

      success = true
      images.each do |img|
        resource = resource_class.new(image: img, event_id: resource_params[:event_id])  
        success &&= resource.save
      end

      if success
        redirect_to(
          admin_photos_path,
          notice: translate_with_resource("create.success"),
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource),
        }
      end
    end
```
Note this will allow you to use a single file input to create a number of objects.
You can see a working example in https://github.com/LoamStudios/sustainability-summit

**Comment by knopfler81** [comment]
Thanks for the very quick answer I will see what I can do :D
Many thanks

Nelly Duclos

**Comment by harismahmood89** [comment]
@picandocodigo oh man thanks so much! EXACTLY what i was looking for!!

**Comment by picandocodigo** [comment]
@harismahmood89 It's great to know I could help somehow :)

**Comment by esparkman** [comment]
How do you get by the permitted attributes for Paperclip and the controllers?

**Comment by jrguenther** [comment]
@esparkman I don't follow. Can you describe your situation in a little more detail, so we can help?

**Comment by esparkman** [comment]
I am using Administrate for an Inventory management application. It is has Vehicle objects which will require multiple images. I am using Paperclip to facilitate that need. The issue I am running into, when I add the custom field for uploading the image, is permitted_params for the Paperclip fields.

This gist should have all the relevant information.
https://gist.github.com/esparkman/6feee0a4d3f7a4f4ee7429765abf91fd

**Comment by jrguenther** [comment]
I think you need to override the `create` method in your `VehiclesController`. If you look at my example above, you'll see that I had re-implement it to so I could loop through the images passed in the single input.

**Comment by esparkman** [comment]
I tried that and still get the "Unpermitted paramater" error

**Comment by jrguenther** [comment]
It might be because you need to allow the parameter to be an array. See https://github.com/rails/strong_parameters#permitted-scalar-values

**Comment by balbinas** [comment]
Hey guys, came here looking for a file upload solution, I'm trying to get a text file uploaded temporarily and then read. I'm attempting to generate my own Field::File, but is there an existing solution for this? Thanks!

**Comment by Tongboy** [comment]
For anyone looking to use expiring URLs & S3 with paperclip - it is as simple as expected - just change the url def on @picandocodigo 's example
```
  def url
    data.expiring_url
  end
```

**Comment by knopfler81** [comment]
Hello,

I keep having the same error when I add carrierwave to my app with administrate

In my log I have an **Unpermitted parameter: images** error

Everything is set as carrierwave documentation for multiple image says...

As suggested I added a carrierwave_field with _form.html.slim
```ruby

= f.label :images
= f.file_field :images, multiple: true

```
my model looks like this:

```ruby
class Progress < ActiveRecord::Base
 default_scope ->{ order(created_at: :desc)}
 mount_uploaders :images, ImageUploader
end
```

my controller 
```ruby
class ProgressesController < ApplicationController

  def index
    @progresses = Progress.all
  end

  def show
    @progress = Progress.find(params[:id])
  end

  def new
    @progress = Progress.new
  end

  def edit
    @progress = Progress.find(params[:id])
  end

  def create
    @progress = Progress.new(progress_params)

    respond_to do |format|
      if @progress.save
        format.html { redirect_to @progress, notice: 'progress was successfully created.' }
        format.json { render :show, status: :created, location: @progress }
      else
        format.html { render :new }
        format.json { render json: @progress.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @progress = Progress.find(params[:id])
    if @progress.update(progress_params)
      redirect_to tour_path(@progress.id)
    else
    render :progress
    end
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def progress_params
    params.require(:progress).permit(:title, :date, :content, { :images []})
  end

end
```
 Is there a bug connecting Carrierwave and Administrate?
or am I doing wrong?  (I followed Carrierwave doc step by step tough)

**Comment by akestner** [comment]
Anyone have thoughts on how to best add the ability to _remove_ a Paperclip attachment?

**Comment by stoge** [comment]
hi all, thnx for your contribution on the subject. It really helped me.
But I quite seem not to understand how to make multiple image upload.

I have created two models: Gallery , Images
Gallery has_may Images, Image belongs_to Gallery
I have also created the administrate:field paperclip  //field (and implemented the views as mentioned by @picandocodigo  ,thnx btw)
but when I create a new Gallery, the images do not get saved.
I should mention that I have overridden the create action on Gallery.

`def create
      @gallery = Gallery.new(gallery_params)
        if @gallery.save
          if params[:images]
            #===== The magic is here ;)
            params[:images].each { |image|
              @gallery.images.create(image: image)
            }
          end
          flash[:notice] = "Gallery was successfully created."
          redirect_to admin_gallery_path(@gallery)
        else
          flash[:error] =  @gallery.errors.to_a.to_s.tr('[""]','')
          redirect_to new_admin_gallery_path
        end
    end

    private

    def gallery_params
      params.require(:gallery).permit(:descr,
                                      :name,
                                      :images
      )
    end`

I'm guessing that there is something going wrong on `@gallery.images.create(image: image)` line...

Could someone help walk me through it?
Thank you in advance :D
(sry I my question sounds dump, but I am not an experienced rails dev...)

**Comment by stoge** [comment]
![screen shot 2016-12-28 at 19 06 57](https://cloud.githubusercontent.com/assets/1492468/21527022/096cdf1e-cd31-11e6-9cb5-742830a3bbfa.png)
How is this possible? -_-'

**Comment by carlosramireziii** [comment]
Just following up on this thread.. It seems like the next steps were either to (1) add an example of a file upload field using Paperclip to the documentation and/or (2) create a new Administrate plugin to package up the snippet provided above.

**Comment by picandocodigo** [comment]
I've started working on turning the example code into a plugin here:
https://github.com/picandocodigo/administrate-field-paperclip

This is my first plugin so I might be missing something (other than tests for now :scream:). I based it off of [thoughtbot/administrate-field-image](administrate-field-image). I had one issue though, the views directory had to be named `paperclip_field` instead of just `paperclip` as the [template suggests](https://github.com/thoughtbot/administrate-field-image).

I tested it on a new Rails project with Administrate from git:

```ruby
gem 'administrate', git: 'https://github.com/thoughtbot/administrate.git'
gem 'administrate-field-paperclip', path: '/local/path/to/administrate-field-paperclip'
gem 'paperclip', '~> 5.0.0'
gem 'rails', '~> 5.0.1'
```

Please let me know what you think. Thanks!

**Comment by carlosramireziii** [comment]
Very cool! 

>  I had one issue though, the views directory had to be named paperclip_field instead of just paperclip as the template suggests.

I think this is because [you called the class](https://github.com/picandocodigo/administrate-field-paperclip/blob/master/lib/administrate/field/paperclip.rb#L6) `PaperclipField` instead of just `Paperclip`.

**Comment by picandocodigo** [comment]
Ah, makes sense! I should probably change it to "Paperclip" for consistency, right?

**Comment by pbmolini** [comment]
@akestner I have done it with `carrierwave` which has [the `remove_avatar` method](https://github.com/carrierwaveuploader/carrierwave#removing-uploaded-files). 
Basically to remove an avatar uploaded with `carrierwave` just add the `remove_avatar` field in the dashboard file:
```ruby
ATTRIBUTE_TYPES = {
    ...
    avatar: CarrierWaveField,
    remove_avatar: Field::Boolean,
    ...
  }.freeze

FORM_ATTRIBUTES = [
    ...
    :avatar,
    :remove_avatar,
    ...
  ].freeze
```
No need to filter the `params` in the controller.

**Comment by nickcharlton** [comment]
Thank you for all of your comments on this issue!

This contains some great solutions, so I'm going to close it for now. I suggest people use one of these here!
