### ISSUE TITLE
[housekeeping] change leading branch from `master` -> `main`

### ISSUE THREAD

**Issue by c4lliope** [thoughtbot/administrate#1958]
I imagine this is a simple change in `Settings`, alongside:

```bash
git checkout master
git branch -m main
git push origin main
```

**Comment by nickcharlton** [comment]
Yeah, I think it is something like that.

I'd been putting it off until GitHub did the redirect properly, but I don't have an excuse now 😅. I'm not going to get to this this week, but I'll make sure it's done next at the latest.

**Comment by nickcharlton** [comment]
I've done this now, thanks for reminding me!
