### ISSUE TITLE
CONTRIBUTING.md link gets a 404 on herokuapp

### ISSUE THREAD

**Issue by luilver** [thoughtbot/administrate#1959]
### Briefing

It should link to github instead of herokuapp or replace CONTRIBUTING.md by /contributing if the idea is to remain within herokuapp.

### Steps to reproduce

1. Visit Administate's [Home](https://administrate-demo.herokuapp.com/) 
2. Go to section Contribute
3. Click on "Please see [CONTRIBUTING.md](https://administrate-demo.herokuapp.com/CONTRIBUTING.md)."
4. Get a "The page you were looking for doesn't exist." error

**Comment by nickcharlton** [comment]
Thanks!

Yeah — we do the same with the LICENSE and should do here. I opened #1962 to solve this as it's such a quick thing.

(Note, you won't see the fix deployed until we release the next version.)
