### ISSUE TITLE
Search for user throwing error

### ISSUE THREAD

**Issue by sanchit121** [thoughtbot/administrate#1964]
![Screen Shot 2021-04-25 at 12 14 57 PM](https://user-images.githubusercontent.com/30828115/115983694-5a2af280-a5c0-11eb-8a20-bbf19d28eb38.png)

  - Rails 5.0.0
  - administrate 0.15.0

I tried to search for user in admin area and get error. Attached more details in screenshot. Thanks

**Comment by pablobm** [comment]
What does your `User` model look like? Eg: what attributes does it have? What does the dashboard look like?

I have a theory: I see that your user has `first_name` and `last_name`, but you are searching for `full_name`. Is it the case that `full_name` is a virtual attribute, generated with a method? If that's the case, it's unfortunately not possible to search by it at the moment. You'll have to mark it as `searchable: false`.

**Comment by sanchit121** [comment]
Thanks for the information. It was really helpful.
