### ISSUE TITLE
Generated dashboard files won't work without tweeking

### ISSUE THREAD

**Issue by johnmeehan** [thoughtbot/administrate#197]
Version: `gem 'administrate', '~> 0.1.0', github: 'thoughtbot/administrate'`

The dashboards that are generated with 
```bash
$ rails generate administrate:install
```
gives us:
```ruby
class DesignDashboard < Administrate::BaseDashboard
  def attribute_types
    {  
      id: :integer,
      name: :string,
      description: :string, 
    }
   ......

  end
end
```

But to get the pages to display without errors I have to implement as per the documentation (For the code to work it needs both ATTRIBUTE_TYPES and attribute_types! 
).
 
```ruby
ATTRIBUTE_TYPES =     {
        id: Field::Number,
        name: Field::String,
        description: Field::String,
}
```

looking at the gem in `/lib/administrate/base/dashboard.rb`
the code still wants to be provided with. 
ATTRIBUTES
ATTRIBUTE_TYPES
FORM_ATTRIBUTES
SHOW_PAGE_ATTRIBUTES
COLLECTION_ATTRIBUTES

Once given it works fine.

I am assuming there was a decision to move away from the constants to methods.

Either way the code will not work out of the box by simple running the generate command in the docs.

If it is simply a case of changing a few names in the code I can stick together a PR.

**Comment by graysonwright** [comment]
Hey, @johnmeehan - it looks like you might be using an older version of Administrate. Can you check your `Gemfile.lock` and make sure you're on `0.1.0`?

If you're on any `0.0.x` version, upgrading to `0.1.0` should take care of a lot of those problems.

**Comment by johnmeehan** [comment]
Yeah I seem to have originally installed it with an older version, ran the generator and then updated to 0.1.0 without changing my dashboard files contents. So thats where my confusion came from.  The generator in 0.1.0 creates the correct dashboard files needed.   Thanks for the response!

**Comment by graysonwright** [comment]
No problem, glad it's working!
