### ISSUE TITLE
Select witch visible attributes deppending Pundit or something

### ISSUE THREAD

**Issue by edimossilva** [thoughtbot/administrate#1983]
* What would you like to be able to do? Can you provide some examples?
  - `User` has `role` attribute
  - if `user` is `admin`, then the `role` attribute would be visible on the form
  - if `user` is not `admin`, then the `role` attribute would not be visible on the form

* How could we go about implementing that?
  something similar to https://github.com/thoughtbot/administrate/issues/1137 but using Pundit with something like `AttributesScope`. I could work on it.

* Can you think of other approaches to the problem?
  Not

**Comment by pablobm** [comment]
Unfortunately this is not supported at the moment. See https://github.com/thoughtbot/administrate/issues/1983

I'm going to close this as it is a duplicate.
