### ISSUE TITLE
Associations are displaying the object id in the select box

### ISSUE THREAD

**Issue by minimul** [thoughtbot/administrate#199]
This was after following the basic install install -> `bin/rails generate administrate:install`

![screen shot 2015-11-09 at 8 10 21 am](https://cloud.githubusercontent.com/assets/199862/11034518/209bc286-86ba-11e5-9fa3-6652af2a3f4f.png)

**Comment by rikkipitt** [comment]
#129 might help!

**Comment by minimul** [comment]
Thanks! Closing.
