### ISSUE TITLE
Example file upload through Administrate? Enable multipart/form-data ?

### ISSUE THREAD

**Issue by dtbaker** [thoughtbot/administrate#1997]
We have a custom field that is computed, not directly mapped to a model, it has these views:

```
views/fields/video_field/_form.html.erb
views/fields/video_field/_index.html.erb
views/fields/video_field/_show.html.erb
```

I'm able to retrieve data and display it in the Administrate index and show views just fine.

However now I'm trying to handle uploads, so inside `_form.html.erb` I've added an input field like: ` <input type="file" name="new_video_upload" />` 

I can see this passed through to the `create` and `update` methods in `admin/my_controller.rb`, however the param is just a string of the file name, not an actual uploaded file.

Is there a way we can easily enable `multipart/form-data` on the create/edit form so file uploads work correctly? Or am I missing another step somewhere? 

Thanks!

**Comment by dtbaker** [comment]
Ah, if I use 

```
  <%= f.file_field "new_video_upload" %>
```

it enables multipart/form-data on the parent form. Interesting... 

This produces an input field with the name `foo[new_video_upload]` which gives me a warning in the console: 

```
Unpermitted parameter: :new_video_upload
```

I can still access the uploaded file manually like so:

```
params[:foo][:new_video_upload]
```

Unsure if there's a better way around this, the `new_video_upload` field is not related to any DB model, we're shipping the file off to an S3 bucket.

**Comment by pablobm** [comment]
Have you implemented the method `permitted_attribute` in your custom field type? See how it's done in other field types: https://github.com/thoughtbot/administrate/tree/main/lib/administrate/field

If you are still having difficulty, would you be able to provide the source code of your custom type?

**Comment by pablobm** [comment]
I'm going to close this issue, as it appears to be solved:

* The original problem should be solved by implementing `permitted_attribute` as mentioned.
* A plugin gem exists that may solve the issue, or at least provide guidance on how to implement it.

But you may disagree or still have questions! :slightly_smiling_face: In which case please let us know here and we may want to reopen.

Thank you all!
