### ISSUE TITLE
Potential security vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [thoughtbot/administrate#1999]
Hi, @nickcharlton  @pablobm @gracewashere 

A security vulnerability has been submitted through huntr .
Plz validate them 
https://huntr.dev/bounties/1-thoughtbot/administrate
Report is only visible to repo-maintainer and reporter .

**Comment by nickcharlton** [comment]
Thanks for opening this. I'm going to close this issue as I'll reply elsewhere.
