### ISSUE TITLE
Option to generate with turbolinks enabled

### ISSUE THREAD

**Issue by minimul** [thoughtbot/administrate#200]

**Comment by graysonwright** [comment]
@minimul what's required to enable turbolinks?

**Comment by minimul** [comment]
Should be able to just: 

- `gem 'turbolinks', github: 'rails/turbolinks' # for turbolinks 3` 
- application.html.erb 
```
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %> 
<%= javascript_include_tag 'application', async: true, 'data-turbolinks-track' => true %> 
``` 
- application.js 
```
//= require turbolinks
```

Typically, when retrofitting turbolinks a problem can arise with incompatible
existing JavaScript that binds to
[`jQuery.ready()`](https://github.com/rails/turbolinks#jqueryturbolinks). 

However, it looks like the JS libraries Administrate is using are turoblinks compatible.

I will take a deeper dive/PR and report back. This could be a simple way to
make Adminstrate feel snappy and desktop-like for "free". Moreover, the views
look prime along with the gem philosophy (of letting the user override
defaults with standard tools such as plain Rails controllers and views) for
Turbolinks 3 partial replacement.

**Comment by nickcharlton** [comment]
As we've been trying to reduce the amount of things we depend on, I think this would be best solved in the docs.

Alternatively, if we could make the dependency optional and use it if it's available?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time since the last activity. This might make for a good documentation PR if someone wanted to do that.
