### ISSUE TITLE
Please don't titleize results of I18n calls

### ISSUE THREAD

**Issue by mvz** [thoughtbot/administrate#2014]
* What were you trying to do?

Trying to get the email address column to be labeled "E-mailadres" (in Dutch)

* What did you end up with (logs, or, even better, example apps are great!)?

The title becomes "E Mailadres" because titleize destroys dashes and applies English capitalization rules.

* What versions are you running?
  - Rails: 6.1.4
  - administrate: 0.16.0

**Comment by pablobm** [comment]
Fixed by #2280
