### ISSUE TITLE
Moment JS is in maintenance mode

### ISSUE THREAD

**Issue by sedubois** [thoughtbot/administrate#2016]
Moment.js is "a legacy project in maintenance mode. It is not dead, but it is indeed done".
https://momentjs.com/docs/

Recommended alternatives:
https://momentjs.com/docs/#/-project-status/recommendations/

For example Day.js "is a minimalist JavaScript library ... for modern browsers with a largely Moment.js-compatible API":
https://day.js.org/

Administrate 0.16.0

**Comment by nickcharlton** [comment]
Closing as we removed Moment in #2136.
