### ISSUE TITLE
Is it possible to create a separate dashboard for a subset of a collection

### ISSUE THREAD

**Issue by DavidGeismarLtd** [thoughtbot/administrate#2022]
* What would you like to be able to do? Can you provide some examples?

Let's say i have a table `Users` with a `role` attribute that can be `customer` or `admin`.
I want to handle my customers and my admins in two different dashboards. What is the correct way to achieve that ?

**Comment by pablobm** [comment]
A way to do this might be to model them with Single Table Inheritance. You create new models for each, both stored in the `users` table, then create separate controllers/dashboards to handle them differently.

I can't remember from the top of my head how to do this, but I think you'd start by defining the models like this:

```ruby
class User
  self.inheritance_column = "role"
end

class Customer < User; end
class Admin < User; end
```

I'm going to close this issue for now, but do ask again if this doesn't solve your problem.
