### ISSUE TITLE
polymorphic route arguments issue on update route

### ISSUE THREAD

**Issue by remy727** [thoughtbot/administrate#2038]
### Steps to reproduce
Upgrade rails version from `5.2.4.3` to `5.2.4.6`

### Expected behavior
`Show` page needs to be shown after `Update`.

### Actual behavior
When update, it doesn't redirect to show page and this error is showing.
```
ArgumentError in Admin::ProductsController#update
Please use symbols for polymorphic route arguments.
```

### System configuration
Ruby version: `2.4.0`
Rails version: `5.2.4.6`

### Thoughts
I think [this line](https://github.com/thoughtbot/administrate/blob/4b394898ebf4e457b7ed720ae94a94670e2ae579/app/controllers/administrate/application_controller.rb#L93) needs to be updated.
```ruby
# current
def after_resource_updated_path(requested_resource)
   [namespace, requested_resource]
end

# new
def after_resource_updated_path(requested_resource)
   [namespace.to_sym, requested_resource]
end
```

**Comment by pablobm** [comment]
Fixed by https://github.com/thoughtbot/administrate/pull/1972
