### ISSUE TITLE
When can we expect a new gem version?

### ISSUE THREAD

**Issue by DawidCwiek** [thoughtbot/administrate#2044]
First of all, thank you very much for a great job! 🚀 
Administration gem keeps getting better! 🥇 

However, I have one question: When can we expect a new gem version?
In particular, I care about `Customizing Redirects after actions`.
It would simplify my code a lot and save a lot of time. 

Regards, Dawid

**Comment by pablobm** [comment]
Thank you for your appreciation. I'm not sure when a new gem will be released. For now, would it work for you to pull the code from master?

```
gem "administrate", git: "https://github.com/thoughtbot/administrate.git", branch: "master"
```
