### ISSUE TITLE
Tables should have an explicit link to each resource

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#205]
Currently, if you are writing a feature test that involves navigating to a specific resource by going to its table view and then clicking on a row within that table, you need to run that test using a JavaScript driver. This is because the whole row is clickable, and that behavior is added via JavaScript. I'd like to not always have to use a JavaScript driver, so what do you think about adding some kind of link to the row so that tests can click this link instead?

Perhaps instead of "Edit" and "Destroy" links at the end of each row, there should be another button, "Show Details" or "View Details" that then links to the show page.

**Comment by 5minpause** [comment]
Is this meant only for testing purposes or do you need this for actual using administrate as well?

**Comment by mcmire** [comment]
No, this is really only meant for testing purposes.

**Comment by graysonwright** [comment]
@mcmire I'd rather not add user-facing changes for the sole reason of making tests easier. If people find the navigation model confusing, or would rather click on a link instead of the whole table row, then I'd be more willing to add it.

What do you think? What are the benefits of removing the `js` dependency from tests?

**Comment by mcmire** [comment]
@graysonwright The benefits of not using a JavaScript driver is that the tests run a lot faster and don't require a window environment to run.

**Comment by graysonwright** [comment]
I don't think those benefits are compelling enough to add an explicit link. Sorry!
