### ISSUE TITLE
Edit page times out when there's a large number of has_many relations

### ISSUE THREAD

**Issue by getaaron** [thoughtbot/administrate#2059]
* What were you trying to do?

My `User` model `has_many` `book_audits`. An average user on my system has 60,000 or so of them. For example:

```
SELECT COUNT(*) FROM book_audits WHERE deleted_at IS NULL AND user_id=267;
 count
-------
 62889
```

My `user_dashboard.rb` contains this has_many relationships (and a few other of similar size), e.g.:

```
FORM_ATTRIBUTES = %i[
    first_name
    last_name
    book_audits
    …
```

I am trying to load the page `http://localhost:3000/admin/users/267/edit`. I expect to see a form page load relatively quickly.

* What did you end up with (logs, or, even better, example apps are great!)?

The request times out every time. You can see it loads from the DB quickly (113.7ms) and then takes 448,016.8ms to render for just this field:

```
  BookAudit Load (113.7ms)  SELECT "book_audits".* FROM "book_audits" WHERE "book_audits"."deleted_at" IS NULL AND "book_audits"."user_id" = $1 /*application:LA,controller:users,action:edit*/  [["user_id", 267]]
  Rendered /Users/aaron/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/administrate-9e462f7179f4/app/views/fields/has_many/_form.html.erb (448016.8ms)
```

* What versions are you running?
  - Rails 5.0.7.2
  - administrate 9e462f7179f47151d1b91aab59291e6884870dab (latest on `main`, also reproduces with 0.16.0 release)

**Comment by vokecodes** [comment]
Visiting the edit page I get the below error

`No route matches [GET] "/admin/3/edit"`

**Comment by nickcharlton** [comment]
I think this is an already known performance issue: recently in #2088, but also in #1697 which potentially has a solution. I'm going to close this one, for now, to keep the discussion in one place.
