### ISSUE TITLE
Create dependent model from show page

### ISSUE THREAD

**Issue by getaaron** [thoughtbot/administrate#2061]
* What would you like to be able to do? Can you provide some examples?

For a `has_many` relationship, I'd like easy UI to create a dependent model. For example, if I'm viewing the Show page for an Author, who has a new Book, I'd like to be able to click "Add Book" to take me to the "Add Book" page with author_id already populated.

* How could we go about implementing that? 

I assume adding the link is easy enough, not sure if URL query params or other approach to prefill author_id would work

* Can you think of other approaches to the problem?

Not at the moment.

**Comment by nickcharlton** [comment]
I think a query param, as you say, would be a good solution to this. Do you think you'd be able to explore a possible solution for that?

**Comment by matteomelotti** [comment]
@nickcharlton Hi! Can I try with this issue? Is it possible to discuss with someone a possible solution and/or issue during the development?

**Comment by matteomelotti** [comment]
@pablobm @nickcharlton is this similar to this? [https://github.com/thoughtbot/administrate/issues/1987](url)

**Comment by getaaron** [comment]
@matteomelotti Yea I think #1987 is a duplicate of this issue, sorry I didn't see it!

I'm not working on the project this was for any more so feel free to take a pass at it. I probably won't work on it myself but I'd be happy to review a PR or something if you need help

**Comment by pablobm** [comment]
@matteomelotti - If you had a go at it, it would be great :slightly_smiling_face: For now, I'm going to close this issue as it's a duplicate as mentioned.
