### ISSUE TITLE
Defining different attributes for `new`/`create` or `edit`/`update` actions without defining `FORM_ATTRIBUTES` makes it crash

### ISSUE THREAD

**Issue by pjmartorell** [thoughtbot/administrate#2066]
* What were you trying to do?
Upgraded from `0.13` to `main` (9e462f7179f47151d1b91aab59291e6884870dab). I tried to define different attributes for new/create or edit/update actions as stated here: https://github.com/thoughtbot/administrate/blob/main/docs/customizing_dashboards.md#form-attributes

  When trying to `update` or `create` a record in the dashboard, there is a crash. This is because, when validating permitted attributes, it's trying to get these attributes from `self.class::FORM_ATTRIBUTES` but it should get them from `"FORM_ATTRIBUTES_#{action.upcase}"` as `FORM_ATTRIBUTES` is not defined anymore. `specific_form_attributes_for(action)` is returning `nil` because `action` is not being passed in `permitted_attributes`. So the solution is to pass the `action_name` when checking permitted attributes.

* What did you end up with (logs, or, even better, example apps are great!)?
The affected code is related with https://github.com/thoughtbot/administrate/pull/1991
**Logs:**
  <img width="1065" alt="Screenshot_2021-11-23_at_12_43_43" src="https://user-images.githubusercontent.com/345520/143021057-fbc9225d-3421-4b75-89e8-92a78b996401.png">

  **My workaround:**
  In my `UserDashboard` added the following overrides:

  ```ruby
  def permitted_attributes(action)
    action =
      case action
      when "update" then "edit"
      when "create" then "new"
      else action
      end

    form_attributes(action).map do |attr|
      attribute_types[attr].permitted_attribute(
        attr,
        resource_class: self.class.model
      )
    end.uniq
  end

  def form_attributes(action = nil)
    specific_form_attributes_for(action) || self.class::FORM_ATTRIBUTES
  end

  def specific_form_attributes_for(action)
    return unless action

    cname = "FORM_ATTRIBUTES_#{action.upcase}"

    self.class.const_get(cname) if self.class.const_defined?(cname)
  end
  ```
  In my `Admin::UsersController` add the following override:

  ```ruby
  def resource_params
    params.require(resource_class.model_name.param_key)
          .permit(dashboard.permitted_attributes(action_name))
          .transform_values { |v| read_param_value(v) }
  end
  ```

* What versions are you running?
  - Rails: 6.1.3.1
  - administrate (9e462f7179f47151d1b91aab59291e6884870dab)

**Comment by pablobm** [comment]
Thank you for the report @pjmartorell. It looks like we could have used a feature spec there. Do you think you'd be able to provide a PR?

**Comment by pjmartorell** [comment]
yes, now that I'm on holidays I'll probably have time to do a PR 😅👍

**Comment by jordan-brough** [comment]
@pjmartorell do you still plan on making a PR? I might be up for making one if not.

**Comment by nunocarvalhog** [comment]
@jordan-brough that would be great 👍  I just run into this issue too.

**Comment by pablobm** [comment]
@jordan-brough - Go for it! :rocket:

**Comment by pablobm** [comment]
fixed by https://github.com/thoughtbot/administrate/issues/2352
