### ISSUE TITLE
Adding field name to table header class

### ISSUE THREAD

**Issue by shouichi** [thoughtbot/administrate#2068]
### Background

We want to customize table column width e.g., enlarge certain fields. Currently, we use CSS nth-child selector to accomplish this. But it is fragile because of the field order dependency. We could also use a custom view but it seems an overkill just to add a few lines.

### Suggestion

Expose field name as an HTML attribute e.g.,

```
<thead>
	<tr>
		<th class="user_name">Name</th>
	</tr>
</thead>
```

**Comment by getaaron** [comment]
I love this, could also be used to use smaller text for created_at/updated_at timestamps which take up a lot of width

**Comment by pablobm** [comment]
Hello there. The fields names are rendered via an i18n label: `helpers.label.$RESOURCE_NAME`. See:

https://github.com/thoughtbot/administrate/blob/ceae954efb721c4fc6a98552eca65bfc88f4fa8f/app/views/administrate/application/_collection.html.erb#L34-37

Admittedly, the i18n code in Administrate needs a lot of work, but would this be enough for you for now?

**Comment by shouichi** [comment]
Hi @pablobm, thanks for the reply! The original title was somewhat misleading. What I meant was to add field name as HTML attribute e.g., `<th class="user_name">Name</th>`. This should make our life easier when we want to add custom css.

**Comment by pablobm** [comment]
Oh, of course. Sorry, I didn't read that very well.

Perhaps we could add something. We have some classes `cell-label--*` for other things, but I wonder if we should add it as a data attribute instead, like `data-administrate-field-name="user_name"` or something like that. What do you think?

Would you be able to provide a PR?

**Comment by shouichi** [comment]
Yes, I also thought about using data attributes. It may be safer because adding classes can affect existing users who add custom css. The only concern I have is inconsistency. It seems that administrate mostly uses classes (the only usage is `table.js`?).

I'll open a PR.
