### ISSUE TITLE
Be able to search deeper in instance methods or model associations

### ISSUE THREAD

**Issue by raphael-allard** [thoughtbot/administrate#2076]
* What were you trying to do? Adding attribute types based on instance methods and be able to search through (or instance methods related to associations).
* What did you end up with (logs, or, even better, example apps are great!)? See below.
* What versions are you running?
  - Rails : 6.0.3.4
  - administrate : (0.14.0 0f8624c)

I have three different models: `Project`, `Client` & `Invoice`. `Invoice` & `Client` both belong to `Project`. Through my invoice search bar, I'd like to retrieve all of invoices when searching by client name.

In my `Invoice` model, I have an instance method:
```
def client_name
  self.project.client&.name
end
```

And in my `Project` model, another one:
```
def client_name
   self.client&.name
end
```

I added the first one to my `ATTRIBUTE_TYPES` hash as `client_name: Field::String.with_options(searchable: true)` to be able to search through it. When I'm searching a keyword through the administrate search bar, I get the following error: `PG::UndefinedColumn: ERROR:  column invoices.client_name does not exist`

I also tried to search client name through the `Project` model but it doesn't work as well:
`project: Field::BelongsTo.with_options(searchable: true, searchable_field: ["name", "client_name"])`. Error: `PG::UndefinedColumn: ERROR:  column projects.["name", "client_name"] does not exist`

Is there a way to handle it? Thanks for your help!

**Comment by pablobm** [comment]
Unfortunately, such a complex search is very difficult to automatise... but there's a way around this.

In general, Administrate tries to do as little magic as possible, and allow things to be overridden to provide for custom use cases, such as this one. In this case, you could override `Administrate::ApplicationController#index` to provide your own way to search.

Right now this is not very obvious, but I have just created a PR that will make it a bit simpler, as well as provide an example in the example app: https://github.com/thoughtbot/administrate/pull/2096

**Comment by pablobm** [comment]
https://github.com/thoughtbot/administrate/pull/2096 has been merged, offering a hook that can help here, along with an example.

I'm going to close this, as automating searches through instance methods is not possible. However the offered hook offers a way to implement it in a case-by-case basis.
