### ISSUE TITLE
Is it possible to get access to administrate demo source code http://administrate-demo.herokuapp.com?

### ISSUE THREAD

**Issue by denys-medynskyi** [thoughtbot/administrate#2086]
* What were you trying to do?
I want to update nested association in the sam way as on [Edit Product](https://administrate-demo.herokuapp.com/admin/products/the-logo-board-game/edit). It has `MetaTag` association and updates properly
* What did you end up with (logs, or, even better, example apps are great!)?
* What versions are you running?
  - Rails 6.1
  - administrate 0.16.0

**Summary**: Is it possible to get access to administrate demo source code?

**Comment by pablobm** [comment]
For future reference, the example app is provided with the source code. See https://github.com/thoughtbot/administrate/tree/main/spec/example_app. To see how to run it, see: https://github.com/thoughtbot/administrate/blob/main/CONTRIBUTING.md
