### ISSUE TITLE
Performance Problems Counting Associated records

### ISSUE THREAD

**Issue by jamie** [thoughtbot/administrate#2088]
* What were you trying to do?

So this has some overlap with #1697 but...

I'm attempting to make a vanilla admin for a work application, where we have one model with a large number of associated log records, but as time goes on we're starting to see excessively long request times from default-generated screens.

* What did you end up with (logs, or, even better, example apps are great!)?

[Example app](https://github.com/jamie/administrate-bug-repro/) has a fresh rails/administrate install, with two models. Setup steps are in the git commit messages. This gets me the following screen:

 ![Users - Bug Repro](https://user-images.githubusercontent.com/1093/146845075-d31e21ae-f218-45cb-b57e-5295ee1f79e1.png)

with the following queries via rails logs:

```
  User Load (0.1ms)  SELECT "users".* FROM "users" LIMIT ? OFFSET ?  [["LIMIT", 20], ["OFFSET", 0]]
  Message Load (85.3ms)  SELECT "messages".* FROM "messages" WHERE "messages"."user_id" = ?  [["user_id", 1]]
```

Loading all the associated messages when we just need a count is prohibitively slow once the model is of a decent size (even with this small 4-column table, there's a very measurable performance impact I believe due to ActiveRecord object creation). Running ab on a local dev server, so concurrency 1:

```
$ ab -n 100 http://localhost:3000/admin
Time per request:       28.603 [ms] (mean)    [with  0  messages]
Time per request:       214.491 [ms] (mean)   [with 10k messages]
Time per request:       416.564 [ms] (mean)   [with 20k messages]
```

All that to say: when generating a count of associated objects, I would expect Administrate to be running a `select count(*)` here for performance.

* What versions are you running?
  - Rails 7.0
  - administrate 0.16.0
  - ruby 2.7.2

**Comment by pablobm** [comment]
Thank you for this report. It provided a more focused example that helped me understand the issue much better. I have proposed a solution at https://github.com/thoughtbot/administrate/issues/1697#issuecomment-1004606731 PRs welcome :-)

**Comment by pablobm** [comment]
I'm going to close this in favour of #1697.
