### ISSUE TITLE
Using with Clearance

### ISSUE THREAD

**Issue by nickmjones** [thoughtbot/administrate#209]
I'm sure this is an easy thing to do, but I'm having trouble setting Administrate up with Clearance. Simply adding `before_action :require_login` to the admin controllers doesn't do the trick. Some documentation on setting up authentication would be welcomed.

**Comment by graysonwright** [comment]
@nickmjones, I think you also need to add `include Clearance::Controller` in your `Admin::ApplicationController`. In your main app, Clearance adds this for you automatically.

Give that a shot and let me know if it works.

**Comment by nickmjones** [comment]
That _sort of_ worked. I have a welcome view in my dashboard, and a user will get an auth screen everywhere *except* for that screen. So, it does what I want (keeping users out of the important parts of the dashboard) but it's not quite there yet. I'll keep at it. Thanks!

**Comment by graysonwright** [comment]
@nickmjones, how did you set up the welcome screen?

Does the controller behind that screen inherit from either `ApplicationController` or `Admin::ApplicationController`?

**Comment by nickmjones** [comment]
Ah ha. That did it! I now have 
`include Clearance::Controller
  before_action :require_login`
in each controller I want to force authentication on, and it's working great. Thanks!

**Comment by graysonwright** [comment]
yep, no problem! Glad it's working.
