### ISSUE TITLE
Generated forms aren't getting a 'form' class

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#212]
I used `rails g administrate:views:form` to generate a form and then add a class to that form, but was noticing that my class wasn't getting applied.

I believe this line in the `_form` partial:

``` erb
<%= form_for([Administrate::NAMESPACE, page.resource], class: "form") do |f| %>
```

needs to be replaced with this line:

``` erb
<%= form_for([Administrate::NAMESPACE, page.resource], html: { class: "form" }) do |f| %>
```

**Comment by graysonwright** [comment]
Good catch, thanks!

**Comment by 5minpause** [comment]
My pull request fixes this.
