### ISSUE TITLE
Support opening url in a new browser tab

### ISSUE THREAD

**Issue by shouichi** [thoughtbot/administrate#2134]
* What would you like to be able to do? Can you provide some examples?

By using `Field::Url` we can display URLs as links. In some cases, it would be convenient to open links in new browser tabs.

* How could we go about implementing that?

Though the implementation would be straightforward, we may want to add `rel="noopener"` or `rel="noreferrer`.

https://docs.rubocop.org/rubocop-rails/cops_rails.html#railslinktoblank

* Can you think of other approaches to the problem?

No.

**Comment by nickcharlton** [comment]
It's not something we currently support. I wondered if we'd exposed enough of the HTML options to do it, but apparently not. `content_tag` accepts a hash of options, so you could do similar things too. It'd be nice to be able to do this on all fields, I'd think, if you or someone was able to open a PR to do so.

You _could_ do something like this, but it'd mean overriding the partials in your project:

```ruby
# dashboard
ATTRIBUTE_TYPES = {
  image_url: Field::Url.with_options(target: "_blank"),
}
```

```erb
# field partial
<%= content_tag :a, href: field.data, target: field.options[:target] do %>
  <%= field.data %>
<% end %>
```
