### ISSUE TITLE
Adding destroy link to the show template

### ISSUE THREAD

**Issue by shouichi** [thoughtbot/administrate#2143]
* What would you like to be able to do? Can you provide some examples?

Adding destroy link to the show template (`app/views/administrate/application/show.html.erb`) just like the edit link.

Background: Because the index template is the only template that has destroy link, there's no way to destroy a resource when index route for the resource is not defined.

* How could we go about implementing that?

The implementation should be straightforward.

* Can you think of other approaches to the problem?

No.

**Comment by nickcharlton** [comment]
Sounds good! Would you be able to open for a PR for this?

**Comment by shouichi** [comment]
Sure! I'll open a PR soon :+1:
