### ISSUE TITLE
Dealing with booleans that require true or false

### ISSUE THREAD

**Issue by migu0** [thoughtbot/administrate#2155]
In the schema I have the following field:

`add_column :users, :some_value, :boolean, default: false, null: false`

And in the user model a corresponding validation:

```
class User < ApplicationRecord
    validates :denied_loans, presence: true
end
```

Then in the dashboard I use the corresponding field type:

```
ATTRIBUTE_TYPES = {
    some_value: Field::Boolean,
}.freeze
```

When I uncheck the field and want to save a record, I get this validation error:  `Some value can't be blank`

How can I customise the field to accept a `false` value by unchecking it?

Thank you

**Comment by pablobm** [comment]
Hello and thank you for filing this issue. I assume that the attribute in the second code block was meant to be `:some_value`, so I'll go with that :slightly_smiling_face: 

What you describe is strange. Administrate uses Rails's own `f.check_box` internally, which should result in `true`/`false` values. Let's see what might be changing this behaviour here...

First: do you have any customisations in your admin area? Dashboard, controller, templates, etc... All these work in unison to deliver the expected result. If any change, it may alter the result if not done carefully.

Second: let's see if the HTML is as expected. If you view the HTML source of the "edit" page (or use the inspector), the markup around the checkbox should look like this:

```html
<div class="field-unit__field">
  <input name="user[some_value]" type="hidden" value="0" autocomplete="off" />
  <input type="checkbox" value="1" name="user[some_value]" id="user_some_value" />
</div>
```

Not sure if you are familiar with this construct, so I'll describe it. You'll notice that `user[some_value]` is defined twice. First as `type=hidden` with `value="0"`, then as a `type="checkbox"` with `value="1"`. On submit, this is the behaviour of the browser:

* If the checkbox is ticked, it will "win" over the input value, as the last field wins when several fields have the same name. Therefore it sends a `user[some_value]=1`.
* If the checkbox is not ticked, the browser doesn't count it as existing when sending the data. Therefore it is as if only the hidden field is there, resulting in the server receiving `user[some_value]=0`.

So the controller receives `params[:user][:some_value]` as whichever value above. In the unchecked case, it receives a `"0"` (note that these values are always strings).

Administrate does a bit of transformation to this, but it should not affect boolean fields. The result is then given to ActiveRecord as `resource.update(update_params)`.

Finally, ActiveRecord interprets the value `"0"` in booleans as `false` (by default, anyway).

Which leads us to the third question: what does your code do when you give it the following?

```
u = User.find(1) # Just any arbitrary user
u.update(some_value: "0")
u.some_value # What's the value of this? It should be `false`
```

Let us know and we'll get to the bottom of this.

**Comment by migu0** [comment]
Thank you @pablobm. The problem only exists if I have this line in the model, not sure if it's ActiveModel issue, i.e. boolean "false" not validating as presence true:

`validates :some_value, presence: true`

Here's the console ouput

```
irb(main):001:0> u = User .last
  User Load (0.9ms)  SELECT "users".* FROM "users" ORDER BY "users"."created_at" DESC, "users"."id" DESC LIMIT $1  [["LIMIT", 1]]             
=> #<User id: "9f2c2e71-795f-4d4c-8347-66e97bbb3a48", email: "admin@test.com", created_at: "2022-03-06 00:22:08.297...
irb(main):002:0> u.some_value
=> true
irb(main):003:0> u.update(some_value: "0")
  TRANSACTION (0.2ms)  BEGIN
  User Exists? (0.7ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."id" != $2 LIMIT $3  [["email", "admin@test.com"], ["id", "9f2c2e71-795f-4d4c-8347-66e97bbb3a48"], ["LIMIT", 1]]
  User Exists? (0.2ms)  SELECT 1 AS one FROM "users" WHERE "users"."mobile" = $1 AND "users"."id" != $2 LIMIT $3  [["mobile", "+61491111333"], ["id", "9f2c2e71-795f-4d4c-8347-66e97bbb3a48"], ["LIMIT", 1]]
  TRANSACTION (0.4ms)  ROLLBACK                                            
=> false                                                                   
irb(main):004:0> u.valid?
  User Exists? (1.7ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 AND "users"."id" != $2 LIMIT $3  [["email", "admin@test.com"], ["id", "9f2c2e71-795f-4d4c-8347-66e97bbb3a48"], ["LIMIT", 1]]
  User Exists? (0.2ms)  SELECT 1 AS one FROM "users" WHERE "users"."mobile" = $1 AND "users"."id" != $2 LIMIT $3  [["mobile", "+61491111333"], ["id", "9f2c2e71-795f-4d4c-8347-66e97bbb3a48"], ["LIMIT", 1]]
=> false                                                                   
irb(main):005:0> u.errors
=> #<ActiveModel::Errors [#<ActiveModel::Error attribute=some_value, type=blank, options={}>]>
irb(main):006:0>
```

**Comment by pablobm** [comment]
Ah, I see now what's going on. Apologies for my previous message: it was a red herring. I had forgotten how the presence validator works.

You can't use the presence validator with boolean fields. Or at least not if you expect them to be true/false. Only true values will be valid. If you want to accept both true and false values, you should use `inclusion: { in: [true, false] }`.

This is nothing to do with Administrate, but instead it's about how Rails (to be precise ActiveModel) works. The presence validator tests for `blank?` and false values are indeed considered blank.

In fact your console example shows how `some_value: "0"` is not being accepted: the transaction fails, the `UPDATE` never takes place, and the subsequent `valid?` returns false. This is all Rails. Administrate is not involved in that sequence of events.

I'm going to close this :slightly_smiling_face: Do let us know if that doesn't solve the problem and we'll reopen.

**Comment by migu0** [comment]
Understood, thanks so much for your help @pablobm.
