### ISSUE TITLE
Is this necessary to keep unicorn setting in package?

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2168]
Question 

https://github.com/thoughtbot/administrate/blob/9fc3ce6323815fa66dd9d27df166fcd601c2365f/config/unicorn.rb#L1

**Comment by nickcharlton** [comment]
Yes, Administrate as well as being a gem is a self-hosting demo and this is there because Unicorn has always needed some configuration.

That might have changed, but that's the reason it's there. Hope this helps!

**Comment by jubilee2** [comment]
Thank you for explaining

**Comment by nickcharlton** [comment]
I think it would make maintenance a lot harder if we split it into two repositories. I've had similar thoughts about splitting out the translations into a different repository (similar to how we do so with [clearance-i18n](https://github.com/thoughtbot/clearance-i18n)).

**Comment by jubilee2** [comment]
https://github.com/jubilee2/administrate/commit/78d5446d5479f6826959efd94287e142b155c138
is this make sense to you?
by the way you can create sub repository to host i18n languages
