### ISSUE TITLE
Enum field support

### ISSUE THREAD

**Issue by Marthyn** [thoughtbot/administrate#218]
Currently something goes wrong with my Enum field. It's an integer of course so that's why i think something goes wrong. Is anyone working on this? Otherwise i'd gladly work on it.

```
invalid value for Float(): "super_admin"
```

**Comment by tjlivesey** [comment]
If you change the field type in ATTRIBUTE_TYPES for that attribute to `Field::String`, it is displayed as the enum string.

**Comment by graysonwright** [comment]
@Marthyn if @tjlivesey's solution doesn't work, it looks like some other users got enums working in #150. Let me know if that helps.

**Comment by Marthyn** [comment]
Okay good to know. I see it's in the to-do list too. So I'll see if i can fix that myself in a PR.

**Comment by phoet** [comment]
sorry, i looked around but i could not find that to-do list everybody is referencing...

**Comment by graysonwright** [comment]
@phoet - I'm also not sure what to-do list @Marthyn was referencing. Sorry for the confusion.
