### ISSUE TITLE
Dashboard does not identify class with namespaces.

### ISSUE THREAD

**Issue by pragatiwagh** [thoughtbot/administrate#2209]
* What were you trying to do?
I had some models inside a particular namespace. These models had some association outside the namespace.

* What did you end up with (logs, or, even better, example apps are great!)?
I had to define class_name in dashboard, but it keeps showing warning that the class_name option is deprecated.
* What versions are you running?
  - Rails - 7
  - administrate - latest

**Comment by pablobm** [comment]
Thank you for the report. We are discussing these issues at https://github.com/thoughtbot/administrate/issues/1978#issuecomment-1147267975.

There's currently a fix that I'm testing that may work for you. Would you be able to test the branch https://github.com/thoughtbot/administrate/compare/main...pablobm:namespaced-associations and let me know if it fixes your issue?

**Comment by pragatiwagh** [comment]
Thank you Pablo for your response. I will look into the solution and
get back to you.


Regards
Wagh Pragati Malhari

**Comment by SumOys** [comment]
I ran into this same issue recently. The patch on the above branched did work. I put this in `config/initializers/overrides.rb` for now

```
# Needed until the following bug is fixed
# https://github.com/thoughtbot/administrate/issues/2209
Administrate::Field::Associative.class_eval do
  def self.associated_class_name(resource_class, attr)
    associated_class(resource_class, attr).name
  end
end
```

**Comment by pragatiwagh** [comment]
@pablobm I tried the solution mentioned by @SumOys and it worked for me. Thank you @pablobm @SumOys

**Comment by pablobm** [comment]
Fixed by https://github.com/thoughtbot/administrate/pull/2235. Thank you all!
