### ISSUE TITLE
Would it be possible to cut a new release?

### ISSUE THREAD

**Issue by ericgross** [thoughtbot/administrate#2233]
I appreciate so many of the improvements to administrate since its last release - is there any chance a new version of administrate could be created? I know that we can reach into github via the `git` attribute in my `Gemfile` but we'd prefer otherwise.

**Comment by nickcharlton** [comment]
I've just [released v0.18.0](https://github.com/thoughtbot/administrate/releases/tag/v0.18.0). Have fun!
