### ISSUE TITLE
is this too much information for end-user?

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2246]
https://github.com/thoughtbot/administrate/blob/f10b5567916703a2ac242c2e9808cfafcfc7fbff/lib/administrate/not_authorized_error.rb#L9
![image](https://user-images.githubusercontent.com/5558405/184451016-eb6b637c-352e-4dca-bd48-ad042d04f1ff.png)

**Comment by pablobm** [comment]
Perhaps. In which circumstance do you see that error? I would think you should not see it if you use the provided interface, and it would only appear if you forged a request.

**Comment by jubilee2** [comment]
Yes out of the provided interface.

**Comment by pablobm** [comment]
This issue may actually have merit. The question is: would this reveal information useful to an attacker? For example, by doing this an attacker would be able to see details about what attributes are available for models. That would not be so good.

Perhaps we should give less information?

**Comment by jubilee2** [comment]
super("Not allowed to perform #{action.inspect} on #{resource.**name**}") 
we might need think about I18n for message

**Comment by jubilee2** [comment]
Thank you!
