### ISSUE TITLE
Custom Display Name in index table

### ISSUE THREAD

**Issue by joshfester** [thoughtbot/administrate#2254]
This may be possible but I haven't been able to find a solution

* What would you like to be able to do? Can you provide some examples?

On the index/collection page, I'd like to specify a field to display in the table cell for a relation field. Currently it shows class name + id

For example, I have a Deal model with belongs_to a Retailer model. On the deals#index page, it shows "Retailer #1" in the retailer column. 

The Retailer model has a title attribute that would make more sense to show here

* How could we go about implementing that?

I think the ideal solution would be to specify it in the fields list. Something like:

`.with_options(display_field: :title)`

* Can you think of other approaches to the problem?

Currently I'm doing it by adding a helper method and then overriding the collection template, but it doesn't seem like a great solution

**Comment by jubilee2** [comment]
override this method (display_resource) in dashboard, should solve your issue.
https://github.com/thoughtbot/administrate/blob/d5acc101fcb0ac3b18ed670771fe3627d3975974/lib/administrate/base_dashboard.rb#L88

**Comment by joshfester** [comment]
Ah thanks so much! I see now that it's even in the comments of the generated dashboard files
