### ISSUE TITLE
should we move javascript to html head

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2257]
Hi every one,

dose any reason we put the javascript under body but not head?

https://github.com/thoughtbot/administrate/blob/40a008c9a5a403b2564d26802c3319e414c4f4d4/app/views/layouts/administrate/application.html.erb#L40

**Comment by pablobm** [comment]
I think there was some reason regarding best practices, but I can't remember. We can revisit it.

Since you closed the issue, did you find an answer to this?

**Comment by jubilee2** [comment]
@pablobm I am ok with put JavaScript in the body, it's not hurt anything.

if you want to move JavaScript into html head, just need move all selectize call under a JavaScript call back of "ready turbolinks:load" event, that is mean execute the selectize code after html complete rendered.

```javaScript
$(document).on('ready turbolinks:load', function() {
  $('.field-unit--belongs-to select').selectize({});
  $(".field-unit--has-many select").selectize({});
  $('.field-unit--polymorphic select').selectize({});
});
```
