### ISSUE TITLE
Search filter with special characters

### ISSUE THREAD

**Issue by alebian** [thoughtbot/administrate#2265]
Hi everyone!

* What would you like to be able to do? Can you provide some examples?

If I store some special characters in a column and want to use a filter to search, the search term is not included because of the regexp [here](https://github.com/thoughtbot/administrate/blob/main/lib/administrate/search.rb#L34). For example in my project I have defined a filter called `sender` and an email field that I want to search. If I search `sender:test` it works but then when I do it like `sender:test@test.com` it does not. Debugging a little I found that line causing the issue.

* How could we go about implementing that?

Changing the regexp to allow more symbols like `@` and `.`: `/^#{filter}:[\w|@|\.]*$/`

* Can you think of other approaches to the problem?

It can be simplified as `valid_filters&.any? { |filter| word.starts_with?("#{filter}:") }`

If you think this approach is fine I can make a PR for it. I monkey patched that class with the first version and its the code I'm currently using.

Regards,
Alejandro

**Comment by pablobm** [comment]
Thank you for bringing this up :slightly_smiling_face: Something similar (not exactly the same thing) was raised at https://github.com/thoughtbot/administrate/issues/2228, but it appears to have gone dormant. If you create PR, I'll be happy to review it.

**Comment by pablobm** [comment]
I think we can close this after https://github.com/thoughtbot/administrate/pull/2260 :slightly_smiling_face:
