### ISSUE TITLE
Wire up i18n-spec

### ISSUE THREAD

**Issue by tute** [thoughtbot/administrate#227]
As a maintainer, it's good to know that the changes to locales in PRs coming in, or our edits in our main locale file, are always kept in sync. `i18n-tasks` can help with that.

Adding this as a low-priority note to ourselves.

**Comment by graysonwright** [comment]
A more appropriate title would be "Get i18n-tasks working again".

https://github.com/thoughtbot/administrate/blob/master/Gemfile#L14

**Comment by tute** [comment]
Title updated. We might want to follow a similar setup as in https://github.com/doorkeeper-gem/doorkeeper-i18n.

Actually, we might want to consider separating a locales repo from the main one à la doorkeeper. I have observed that this cleaned up the main repo's issue tracker, while keeping the extracted repo very focused, easy to manage, and with blazing fast tests (`i18n-tasks`).

**Comment by tute** [comment]
`i18n-spec`, I mean!

**Comment by graysonwright** [comment]
wow, that's an interesting idea. Would definitely clean up these github issues a bit.

**Comment by tordans** [comment]
Maybe consider creating a public https://www.localeapp.com/ project. This way there are some basic validations that translations with %{values} are in sync across languages and you can also easily see and filter how far behind one translation is. At the end you just "localeapp pull" the new translations and commit them.

**Comment by Marthyn** [comment]
The locale app project is a great idea, but not free.

Maybe related, i was also wondering why there are two locations with locales?
https://github.com/thoughtbot/administrate/tree/master/administrate/config/locales
https://github.com/thoughtbot/administrate/tree/master/config/locales

**Comment by graysonwright** [comment]
@Marthyn oh, wow. good catch.

The correct location is in `/config/locales`. Before v0.1.1, we were storing the code in `/administrate`. We switched the repository structure up in #144, but I think there were a few I18n PRs merged afterwards that were still referencing the original `administrate/config/locales` location.

**Comment by graysonwright** [comment]
I've opened up https://github.com/thoughtbot/administrate/pull/237 to move all locale files into the correct location.

**Comment by tute** [comment]
> The locale app project is a great idea, but not free.

I just tried it. I didn't like it. 4 years ago webtranslate.it felt better to me. Bare yaml files are very much ok for developers, I think.

**Comment by tordans** [comment]
@Marthyn actually it is free for public projects https://www.localeapp.com/projects/public

**Comment by buren** [comment]
I've used transifex.com in a few projects and have really liked it. They are also free for open source projects :) Discourse among others uses transifex.

Its really easy to configure multiple locale files etc. You configure by adding a file in the project root: `.tx/config`

Example integrations:

https://github.com/justarrived/just_match_api/blob/master/.tx/config
https://github.com/discourse/discourse/blob/master/.tx/config

**Comment by nickcharlton** [comment]
I've opened #876 as a fresher version of this issue. This has a more specific plan to keep our translations healthy, so I'm going to close this in favour of that. Thank you for all of your suggestions; I hope we'll get the full issue resolved in a not-too distant release!
