### ISSUE TITLE
Docs are offline

### ISSUE THREAD

**Issue by de-farias** [thoughtbot/administrate#2297]
The docs are offline. When I try to access them an error page from heroku is shown

![Screenshot from 2022-12-06 14-18-52](https://user-images.githubusercontent.com/12251182/205979029-36e6f63d-1a6f-45a6-aa5b-c57629a0d6a3.png)

**Comment by de-farias** [comment]
Not exactly a bug, maybe, but that was the less wrong (?) category I could find there...

**Comment by nickcharlton** [comment]
Oh, oops. Of course, it's database-backed on Heroku.

Thanks for reporting this — I'll fix this tomorrow my time as it's evening in the UK now.

**Comment by nickcharlton** [comment]
This is now working — I didn't personally do anything, but it looks like @cpytel picked it up for us instead. Thank you!
