### ISSUE TITLE
Has Many relationship, redirect to parent model

### ISSUE THREAD

**Issue by DavidGeismarLtd** [thoughtbot/administrate#2329]
* What would you like to be able to do? Can you provide some examples?

Let's say you have :
`Product has_many categories_products
``Product has_many categories through categories_products
`
In the product dashboard I have 
```
   ATTRIBUTE_TYPES = {
    categories_products: Field::HasMany,
  }
  SHOW_PAGE_ATTRIBUTES = %i[
    categories_products
  }
```
which will display a table with destroy action for categories_products on the products#show page
It's currently possible to redirect to the index of the products by setting the following in the `CategoriesProductsController` : 
```
  def after_resource_destroyed_path(_requested_resource)
      { action: :index, controller: :products }
    end
```

However I don't see anywhere the possibility to redirect to the parent product from which the destroy action was initiated.

* How could we go about implementing that?
I don't know
* Can you think of other approaches to the problem?
I don't know

**Comment by pablobm** [comment]
For future readers, it should be possible to achieve this by using the `_requested_resource` argument. This however may not work if the relationship is more complex than a simple `belongs_to`, as intermediate objects may have been deleted by the time you get there. In that case, you may want to override the `destroy` action, or do something potentially a bit more hacky like looking at the `params` or the `request` and figuring out the destination URL from there.
