### ISSUE TITLE
Sign in Count, etc.

### ISSUE THREAD

**Issue by gjackson12** [thoughtbot/administrate#234]
I know Rails Admin offers some pretty common features like: 'sign in count', last-sign-in, etc. Is that something that can be done in the context of administrate?

**Comment by picandocodigo** [comment]
I'm almost certain those features are offered by devise and not rails_admin. The app where I'm currently using administrate already had devise setup and I can show sign_in_count and other fields in the AdminUser dashboard with `sign_in_count: Field::Number` and these fields were automatically detected/generated.

**Comment by graysonwright** [comment]
@gjackson12 It sounds like those stats would be tracked in the database by your app's authentication system - I think [Devise] and several other authentication gems track those metrics.

If you're using Devise, then running:
`rails generate administrate:dashboard User`
should automatically add those stats to Administrate.

In short, sign in count, last sign in, etc. are the responsibility of authentication gems, not administration gems.

[Devise]: https://github.com/plataformatec/devise

**Comment by graysonwright** [comment]
I'm going to close this because I don't think it's an issue with Administrate. If you have questions, feel free to keep posting here.

**Comment by gjackson12** [comment]
Thanks! Mea culpa.
