### ISSUE TITLE
Have to repeatedly press confirm button

### ISSUE THREAD

**Issue by 54b7hr707h** [thoughtbot/administrate#2345]
* What were you trying to do?
Any typical delete link

* What versions are you running?
  - Rails 7.0.4
  - administrate 0.17.0

Also worth noting: if i refresh the page, it works fine. if i click around a bunch and then click destroy, i get prompted repeatedly. I'm guessing it has to do with turbo links somehow?

**Comment by pablobm** [comment]
Thank you for letting us know. Does upgrading to 0.18 help? Are you able to reproduce the issue in the example at app https://administrate-demo.herokuapp.com/admin/customers?

**Comment by 54b7hr707h** [comment]
I upgraded it to 0.18.0 now, same problem. I can't reproduce in that link, is the source for that somewhere? I can try to compare/reproduce based on that

**Comment by pablobm** [comment]
Yes, that's the same app that is bundled with the Administrate source code. You can run it with `bundle exec rails s` on the root of the project.

**Comment by 54b7hr707h** [comment]
Ok, thanks. The problem went away after I moved ` <%= render "javascript" %>` into `<head>`. Not sure why this fixes it for me, since this seems to be the default:
https://github.com/thoughtbot/administrate/blob/main/app/views/layouts/administrate/application.html.erb#L40
