### ISSUE TITLE
Error after running install generator

### ISSUE THREAD

**Issue by gjackson12** [thoughtbot/administrate#235]
After running the install generator I am receiving the following error: 

```
ActionController::RoutingError at /admin
uninitialized constant AdminController
```

**Comment by jasontwong** [comment]
You're getting this error because you have no dashboards in `app/dashboards/dashboard_manifest.rb`

```ruby
  DASHBOARDS = [
    :users
  ]
```

**Comment by carlosramireziii** [comment]
This appears to be a duplicate of the original issue reported in #186. The suggested solution is to create a "Getting Started" page.
