### ISSUE TITLE
the permitted_attributes may need pass current action

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2352]
https://github.com/thoughtbot/administrate/blob/062ea9f517b140ea04e2c6c4ff3a00a563bafcac/lib/generators/administrate/dashboard/templates/controller.rb.erb#L39

the permitted_attributes may need pass current action to support "FORM_ATTRIBUTES_NEW" and "FORM_ATTRIBUTES_EDIT". 

otherwise only go through "FORM_ATTRIBUTES" whatever edit or new action.

**Comment by pablobm** [comment]
Uh, I think you are right. Interestingly, `permitted_attributes` calls `form_attributes`, which does accept an `action`.

Would you be able to provide a PR?

**Comment by jubilee2** [comment]
related #2066
