### ISSUE TITLE
undefined method `all' for Administrate::Page:Module

### ISSUE THREAD

**Issue by 9mm** [thoughtbot/administrate#2359]
I'm running latest rails, latest administrate.

I have a polymorphic field called Attachment

```
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true
end

class Page < ApplicationRecord
  has_many :attachments, as: :attachable
end

#... more attachable classes
```

Here is the definition in `attachment_dashboard.rb`:

```
    attachable: Field::Polymorphic.with_options(
      classes: [User, Room, Company, Equipment, Page],
    ),
```

For whatever reason... `Page` is the only thing that generates this error. I have combed over it for like 2 hours trying to find what about it is different and i cant find anything :/

Is this a conflicting name or something with administrate?

```
ActionView::Template::Error (undefined method `all' for Administrate::Page:Module):
    23:   <div class="field-unit__field">
    24:     <%= pf.hidden_field(:type, value: field.class.name) %>
    25:     <%= pf.select(:value) do %>
    26:       <%= grouped_options_for_select(field.associated_resource_grouped_options, field.selected_global_id, prompt: true) %>
    27:     <% end %>
    28:   </div>
    29: <% end %>

  Rendered /Users/zesty/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/administrate-0.18.0/app/views/fields/polymorphic/_form.html.erb (Duration: 106.5ms | Allocations: 58066)
  Rendered /Users/zesty/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/administrate-0.18.0/app/views/administrate/application/_form.html.erb (Duration: 107.4ms | Allocations: 58349)
  Rendered /Users/zesty/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/administrate-0.18.0/app/views/administrate/application/new.html.erb within layouts/administrate/application (Duration: 108.4ms | Allocations: 58696)
  Rendered layout /Users/zesty/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/administrate-0.18.0/app/views/layouts/administrate/application.html.erb (Duration: 108.5ms | Allocations: 58763)
```

**Comment by 9mm** [comment]
More bugs leftover from this maybe?

https://github.com/thoughtbot/administrate/issues/1709

**Comment by pablobm** [comment]
As a workaround, can you try defining the field as follows?

```
    attachable: Field::Polymorphic.with_options(
      classes: [User, Room, Company, Equipment, ::Page],
    ),
```

The important part is the `::` prefix to `Page`.

Administrate has a class called `Administrate::Page`. I think that Ruby is resolving the wrong thing here. If you explicitly say `::Page`, it will know that it's the root-level one and not the one under `Administrate`.

**Comment by 9mm** [comment]
OOOoooo. I should have guessed to do that. Thanks so much. I suppose I'll close this because if the fix is that easy it's probably not worth prioritizing over other things, and someone can always find this issue. Thanks for your awesome work.

**Comment by pablobm** [comment]
Thank you for the prompt response!

**Comment by pablobm** [comment]
Hm, I don't understand what you describe :slightly_frowning_face: Would you be able to provide more info? I just went and tried to figure it out from the Rails Admin demo site, but it appears to be down...

**Comment by 9mm** [comment]
Haha yeah, everyone's demo site went down 🤣

Well actually I looked again at nested form and it looks like it can do it its just not really documented maybe.

Imagine you have an "user" and it belongs_to a "company", "account", "group"

I want to be able to create a user, and inline in the form it can be like:

```
New User
=======
Name
Email
[Company dropdown] [+ADD ONE] (opens modal or inline form)
[Account dropdown] [+ADD ONE] (opens modal or inline form)
[Group dropdown] [+ADD ONE] (opens modal or inline form)
```

The inline form plugin looks like i have to do it this way:

```
New Company
=======
Name
[Nested New User Form] 
```

But I suppose I'm misreading because they allude to nested fields, they just dont say how to do the other direction (on the belongs to). Maybe its NestedBelongsTo or something, I'll have to read their source code I guess

**Comment by pablobm** [comment]
Oh, I see. What you would need is a nested belongs_to with the ability to create. I guess it should be possible to create a custom BelongsTo that mostly copies the existing HasOne...? Perhaps copying a bit from the nested-has-many plugin in order to add the [+ADD ONE] options... That's how I would try go about it, but I haven't really tried.
