### ISSUE TITLE
Upgrading to 0.18.0 results in uninitialized constant Pundit::Authorization

### ISSUE THREAD

**Issue by fbuys** [thoughtbot/administrate#2378]
* What were you trying to do?
We are trying to upgrade from administrate 0.17.0 to 0.18.0

* What did you end up with (logs, or, even better, example apps are great!)?
Our Heroku build seems to fail because `Pundit::Authorization` is not available.

I believe a solution would be to specify that pundit 2.2.0 or higher should be used if pundit is added to the application.
We currently have pundit 2.1.0.

Alternatively a patch should be added to see if `Pundit::Authorization` is available.
[Pundit Changelogs](https://github.com/varvet/pundit/blob/dd53b6929946405438aab43564f14d630f2eb804/CHANGELOG.md#deprecated)

Here is a section from our heroku logs:
```
pid=2 tid=5iy WARN: NameError: uninitialized constant Pundit::Authorization
pid=2 tid=5iy WARN: /app/vendor/bundle/ruby/2.7.0/gems/administrate-0.18.0/app/controllers/concerns/administrate/punditize.rb:5:in `<module:Punditize>'
/app/vendor/bundle/ruby/2.7.0/gems/administrate-0.18.0/app/controllers/concerns/administrate/punditize.rb:2:in `<module:Administrate>'
/app/vendor/bundle/ruby/2.7.0/gems/administrate-0.18.0/app/controllers/concerns/administrate/punditize.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
```

* What versions are you running?
  - Rails: 6.0.3.6
  - administrate: 0.18.0 (during the upgrade process to 0.18.0)
  - pundit: 2.1.0

**Comment by pablobm** [comment]
Ooopsie, thanks for catching this. Would you be able to create a PR? Your idea of detecting `Pundit::Authorization` sounds good. We can then include one module or the other as appropriate.

**Comment by fbuys** [comment]
For sure, will add a PR. Thank you!
