### ISSUE TITLE
Destroy button sending GET request instead of Delete.

### ISSUE THREAD

**Issue by aliumairdev** [thoughtbot/administrate#2385]
* What were you trying to do?
<img width="284" alt="Screenshot 2023-05-26 at 6 08 16 PM" src="https://github.com/thoughtbot/administrate/assets/115366866/221d8a04-b5ec-4d42-8cd5-142fe775127e">
When I click on destroy button it goes to the show page. that means It's sending a GET request Instead of Delete. 
I'm using Rails 7 
gem "administrate", github: "excid3/administrate", branch: "jumpstart" # '~> 0.10.0'

<img width="571" alt="Screenshot 2023-05-26 at 6 07 17 PM" src="https://github.com/thoughtbot/administrate/assets/115366866/c7295728-7b0f-4cd8-a13f-eb1f379aad9b">

**Comment by pablobm** [comment]
You are using an non-official fork of Administrate. Please file issues only after having tested with the official version.

Having said that, I had a look and the version you use doesn't appear to differ much. Potential ideas: do you use some sort of JS blocker? Do you have warnings or errors in the JS console? The deletion action requires JS, so that could be the problem.

**Comment by pablobm** [comment]
Would it be possible to see your `Gemfile` and `package.json` files? I think that some other package is interfering there.

Also: how did you install Administrate? Did you use Jumpstart or something like that?

**Comment by aliumairdev** [comment]
I've shown my Gem file and package JSON file in this video.

https://www.loom.com/share/2bbacd53264647a9a8eb144ac2f72059

**Comment by aliumairdev** [comment]
@pablobm 
<img width="1101" alt="Screenshot 2023-05-31 at 3 41 17 PM" src="https://github.com/thoughtbot/administrate/assets/115366866/dedff860-aee5-419d-a2ba-ec432cef0ecc">


I think for the destroy button you are using link_to tag but in  Rails 7 Link_to not send the post or delete request unless we use the turbo-data in link_to or use the Button_to tag instead of link_to

**Comment by pablobm** [comment]
I guess you found a solution? For the future, @aliumairdev, when asked to share a file it's better to copy&paste it in a comment, as a video is difficult to both read and reproduce locally.
