### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by dmitrypol** [thoughtbot/administrate#240]
The gem looks really interesting and more flexible than RailsAdmin.  Any plans on adding Mongoid support?

**Comment by graysonwright** [comment]
@dmitrypol thanks for checking it out!

We'd love to add support for Mongoid and other ORMs. There's a bit of discussion around it in #143.

At the moment, we're focusing on ironing out some bugs and improving stability on a single database (ActiveRecord & postgres). Once we've gotten those issues out of the way, we'll work on improving the flexibility for other database adapters. Would love your input on the conversation!

**Comment by brandondrew** [comment]
Thanks for starting with Postgres!  If you're taking votes on non-ActiveRecord DBs to support, please add RethinkDB to the list.

**Comment by graysonwright** [comment]
Great! I'll add these as notes on #143 - once that's in, this should be pretty straightforward.

**Comment by dmitrypol** [comment]
Any updates on this?

**Comment by nickcharlton** [comment]
This is something that will be addressed post-1.0. I'd recommend seeing #143.
