### ISSUE TITLE
Tested  with rails7

### ISSUE THREAD

**Issue by waghanza** [thoughtbot/administrate#2424]
Hi,

I think there is a typo here
https://github.com/thoughtbot/administrate/blob/852b62c73080c78fe219704b45b7dff3ba6e2f94/Appraisals#L10

Can I upgrade to rails **7.0** (I'm still on 6.1) ?

Regards,

**Comment by pablobm** [comment]
Oopsie, that does look like a typo. Please feel free to create a PR to fix it.
