### ISSUE TITLE
DEPRECATION WARNING: The method `valid_action?` is deprecated 

### ISSUE THREAD

**Issue by vitality82** [thoughtbot/administrate#2456]
* What were you trying to do?
Run tests that cover also our dashboards that are build with administrate: bundle exec rspec
* What did you end up with (logs, or, even better, example apps are great!)?
RSpec runs with lots of warnings, example:
```
DEPRECATION WARNING: The method `valid_action?` is deprecated. Please use `accessible_action?` instead, or see the documentation for other options. (called from block (2 levels) in <top (required)> at /spec/requests/admin_dashboard_spec.rb:17)
DEPRECATION WARNING: The method `show_action?` is deprecated. Please use `accessible_action?` instead, or see the documentation for other options. (called from block (2 levels) in <top (required)> at /spec/requests/admin_dashboard_spec.rb:17)
```
When I search my project I have no usages of "valid_action" or "show_action". However I do see these calls in the administrate gem code and/or dependencies, example:
<img width="878" alt="image" src="https://github.com/thoughtbot/administrate/assets/3256598/9c0817e6-a3fc-41f1-89b7-62a3e5435ae6">

* What versions are you running?
  - Rails 3.1.4 (just upgraded from 3.0.4)
  - administrate (0.19.0)e
  -- administrate_exportable (0.6.3)

Is this a known issue? Should we ignore these warnings? Thanks!

**Comment by nickcharlton** [comment]
We don't currently have a plan to actually remove the deprecated method, so for now, you're okay. But I'd keep an eye out when upgrading at the CHANGELOG as it'll be mentioned there when it is removed in a new release.

As you mention using `administrate_exportable`, my expectation would be that the offending code is in that plugin, and I'd have a look and see if you can fix that there if possible!
