### ISSUE TITLE
Developer UX: better error for misspelled/missing attribute

### ISSUE THREAD

**Issue by monkbroc** [thoughtbot/administrate#246]
If a field in `COLLECTION_ATTRIBUTES` has no key in `ATTRIBUTE_TYPES` either because I misspelled it or I forget to add it to `ATTRIBUTE_TYPES` I will get a `undefined method new for nil:NilClass` in [`Page::Base`](https://github.com/thoughtbot/administrate/blob/04247d78196e692e668933390f8190ba1f4f8533/lib/administrate/page/base.rb#L21)

It would be nicer to see a custom exception `Attribute xyz not found in dashboard AbcDashboard`

This has already happened multiple times on my first day of using Administrate so I think this is worthwhile to fix.

**Comment by graysonwright** [comment]
:+1: good call, I think this would be super useful.

**Comment by 5minpause** [comment]
@graysonwright @monkbroc I gave a possible implementation a try. 
https://github.com/ikuseiGmbH/administrate/commit/62570b673bd43964db8d9dfc09b6fddb1ec7b8be

Could you provide feedback, please? I wasn't sure how to add a test for that. Any hints would be appreciated.
Also I don't know how Thoughtbot deals with HEREDOCS? Do you use indentation?

**Comment by monkbroc** [comment]
Thanks @5minpause. I commented on your commit.

**Comment by graysonwright** [comment]
@5minpause can you open a PR for that commit, so we can leave comments on it more effectively?

For HEREDOCs, I usually go with this:

```
  string = <<-SOMETHING.strip_heredoc
    If you use `<<-` instead of `<<`,
    it lets you indent the closing tag.
    The `strip_heredoc` removes leading indentation
    for the heredoc string.
  SOMETHING
```
