### ISSUE TITLE
Incompatibility with `importmap-rails`

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#2501]
Extracted from another issue, so we can track it better:

I tried to use https://github.com/thoughtbot/administrate/pull/2397 PR's gem version, unfortunately still get `An import map is added after module script load was triggered.` . But after page reload error disappears.
Please give example of how should I organize my overrided `_javascript.html.erb`?
Now it' like:

```ruby
<% Administrate::Engine.javascripts.each do |js_path| %>
  <%= javascript_include_tag js_path %>
<% end %>

<%= javascript_importmap_tags 'application' %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>
```

_Originally posted by @tagirahmad in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1900322774_
            
---

@tagirahmad, thank you for chipping in with your feedback. 🙌

Can you help me reproduce your issue? 🤔

Where do you see the error message you reported?

I created a new Rails app with Administrate and importmaps but had no problems. 🚀

Do you have an example Rails app we could look at? 🕵️‍♂️

_Originally posted by @purinkle in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1906283449_
            
---

> @tagirahmad, thank you for chipping in with your feedback. 🙌
> 
> Can you help me reproduce your issue? 🤔
> 
> Where do you see the error message you reported?
> 
> I created a new Rails app with Administrate and importmaps but had no problems. 🚀
> 
> Do you have an example Rails app we could look at? 🕵️‍♂️

Thank you for your desire to help! 😊

Here it is [the repo](https://github.com/tagirahmad/administrate_test/blob/main/app/views/admin/application/_javascript.html.erb)

_Originally posted by @tagirahmad in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1906603095_
            
---

@tagirahmad, thank you so much for sending through the example app. 🙏

It made debugging the issue much more straightforward.

After some investigation, this may be [a known issue][] with `importmap-rails` and Chrome extensions. 🕵️‍♂️

Try running your application in Incognito mode or a different browser. 🔄

Do you still see the error? 🤔

[a known issue]: https://github.com/rails/importmap-rails/issues/28

_Originally posted by @purinkle in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1910436837_
            
---

I tried Chrome, Firefox, Brave in both modes. I still do see the error.

Please look at the scenario @purinkle 
<details> 
<summary>Video</summary>
https://github.com/thoughtbot/administrate/assets/43289913/39c84bae-88b3-4f03-b288-f708970385cc
</details>

_Originally posted by @tagirahmad in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1913269026_
            
---

@tagirahmad , thank you for the video. 🙌

It helped me diagnose the issue and come up with a solution. 👩‍💻

Can you try something for me? 🤔

Can you move [the `<%= render "javascript" %>` line in your `application.html.erb` file][]?

Instead of having it at the bottom of the body, can you move it to the bottom of the head? 🚀

Using your sample application, you should end up with the following. 📝

```erb
<head>
  <meta charset="utf-8">
  <meta name="ROBOTS" content="NOODP">
  <meta name="viewport" content="initial-scale=1">
  <title>
    <%= content_for(:title) %> - <%= application_title %>
  </title>
  <%= render "stylesheet" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag if defined?(csp_meta_tag) %>
  <%= render "javascript" %>
</head>
```

[the `<%= render "javascript" %>` line in your `application.html.erb` file]: https://github.com/tagirahmad/administrate_test/blob/2d555311726e423d8ae972424a75753fab1498c6/app/views/layouts/admin/application.html.erb#L40

_Originally posted by @purinkle in https://github.com/thoughtbot/administrate/issues/2446#issuecomment-1915182280_

**Comment by tagirahmad** [comment]
Hi @purinkle! Tried. Unfortunately, it didn't help. Still need to reload the page to pull up the js.

**Comment by purinkle** [comment]
@tagirahmad, I will need your help to diagnose this issue further. 🛠️🔍

I created a fork of your test repository and tried to recreate the problem. 🔄

As you can see from the GIF below, everything is working okay for me. ✅👀

![2024-03-06 11 22 38](https://github.com/thoughtbot/administrate/assets/185321/a53d08f2-f015-4050-b0bf-016fb597bacd)

**Comment by tagirahmad** [comment]
@purinkle I suppose, no. I see on your gif, that there are some problems, layouts don't load fully.

![20240307-1923-07 8656110](https://github.com/thoughtbot/administrate/assets/43289913/2e22a2ab-86ac-44f0-a069-5fe1d2fe7b91)

**Comment by purinkle** [comment]
@tagirahmad, I also noticed that issue, but we can return to that. 💡💭

Can you confirm if the error is no longer visible in the console? 🛠️

Once we've got rid of that, we can move on to the next thing. 🚀

**Comment by tagirahmad** [comment]
@purinkle, Yes, the error is not visible now!

**Comment by purinkle** [comment]
@tagirahmad, excellent!

How would you feel about closing this issue and opening a new one to solve the problem with layouts?

I want to keep the scope tight so we can resolve different issues.

**Comment by tagirahmad** [comment]
Okay, let's close it and open a new one
