### ISSUE TITLE
Paginate has_many collections. 

### ISSUE THREAD

**Issue by tomgatzgates** [thoughtbot/administrate#254]
Has anyone tackled paginating has_many fields. For example a customer having many order. Currently it is limited to 5 but it would be nice to enable pagination. I'm just wondering if anyone else has tried/done this before I give it a go

**Comment by graysonwright** [comment]
@tomgatzgates A possible way to treat this would be adding a link below the `has_many` table that takes the user to the index page for the associated resource class, filtered down to the records associated with the original object.

It might take a little time to set that up, because we'd probably want to build it off of the filtering functionality proposed in #157.

What are your thoughts on that? Would it work for your use case? If not, I'm interested to see your approach!

**Comment by tomgatzgates** [comment]
That would definitely be an option, especially since in our particular implementation we've customised which dashboards appear in the side bar.

I'll have a go at linking to the index filtered by the associated object. I'll ignore #157 for the moment just to get it working in a very basic form then think about how it could fit in.

**Comment by tomgatzgates** [comment]
Currently a **very basic** 'hack' in my admin application controller. Pass in query params in the `link_to`.
i.e. for User with ID 122345,  `.../orders?query[][user_id]=12345`

```ruby
def index
    resources = find_resources
    resources = order.apply(resources)
    resources = resources.page(params[:page]).per(records_per_page)
    page = Administrate::Page::Collection.new(dashboard, order: order)

    render locals: {
      resources: resources.page(params[:page]).per(records_per_page),
      search_term: search_term,
      page: page,
    }
  end

...

private

def find_resources
    @_resources ||= if params[:query]
                      query = params[:query].first.symbolize_keys
                      resource_resolver.resource_class.where(query)
                    else
                      search_term = params[:search].to_s.strip
                      Administrate::Search.new(resource_resolver, search_term).run
                    end
  end
```

**Comment by jdell64** [comment]
what about setting  `resources` equal to `field.data[#{start_num}..#{end_num}]` ?

**Comment by avk** [comment]
This is sorely missing from administrate.

**Comment by pablobm** [comment]
I believe this is now fixed:

<img width="852" alt="association-pagination-administrate" src="https://user-images.githubusercontent.com/36066/68580412-39bfb480-046e-11ea-8e8d-a595371760b3.png">

Don't hesitate to reopen if I'm missing something.
