### ISSUE TITLE
Cannot see the value of most fields in edit forms unless you mouseover them (1.0.0.beta1)

### ISSUE THREAD

**Issue by louis-antonopoulos** [thoughtbot/administrate#2543]
* What were you trying to do?
  * Edit any record, both in a project that uses Administrate and in the [demo app](https://administrate-demo.herokuapp.com/admin/customers/40655/edit)

* What did you end up with?
  * The values in most field types in edit forms are not visible until you mouse over them. I replicated this using both the latest Firefox and latest Chrome.

https://github.com/thoughtbot/administrate/assets/19808194/60701a18-7e51-4306-ab3a-42e1b9c9e9ea

* What versions are you running?
  - Rails 7.1.3.2
  - administrate 1.0.0.beta1

This issue does not occur on Administrate 0.20.1.

**Comment by DoodlingDev** [comment]
I think this was fixed in [2512](https://github.com/thoughtbot/administrate/pull/2512) and is in main, so likely just wasn't in the `v1.0.0.beta1` that's deployed in the demo app and the version we saw it in Closeknit.
