### ISSUE TITLE
the has_one looks different in edit page

### ISSUE THREAD

**Issue by jubilee2** [thoughtbot/administrate#2555]
I do not sure is it expect or bug. the inputbox next row of label.
it was in the same row.

https://administrate-demo.herokuapp.com/admin/orders/121361/edit

currently look like
<img width="1326" alt="Screenshot 2024-03-22 at 12 57 50 PM" src="https://github.com/thoughtbot/administrate/assets/5558405/11439fca-42dc-4261-8b34-31727f8a1d43">

it was looks like i think
<img width="1342" alt="Screenshot 2024-03-22 at 12 58 54 PM" src="https://github.com/thoughtbot/administrate/assets/5558405/f671e4ae-9fc8-4722-9cd9-550a1b2f2aca">

**Comment by nickcharlton** [comment]
Thanks for spotting! Yeah, it should be like the second screenshot.
