### ISSUE TITLE
`missing required keys: [:id]` in dashboard for a model with CamelCase name

### ISSUE THREAD

**Issue by akrisanov** [thoughtbot/administrate#256]
Hello,

I tried to create a dashboard for a model with `CancellationPolicy` name. But always got `ActionController::UrlGenerationError in Admin::Offers#index` where current model belongs to `Offer`.

After renaming model `CancellationPolicy` to `Policy` (and file policy.rb), admin starts work.

**Comment by graysonwright** [comment]
@akrisanov Did you fix this issue? Can you share what was going wrong?
