### ISSUE TITLE
Admin layout generation?

### ISSUE THREAD

**Issue by nextekcarl** [thoughtbot/administrate#258]
I'm working on integrating the Cloudinary heroku addon and I need to get that gem to include the javascript files that it normally adds by adding:

//= require cloudinary

...to the application.js manifest, but it appears that's all ignored when I'm in the administrate Rails engine. Where does the layout live for Administrate? I don't see a way listed to generate that layout that Administrate uses so that I can make changes to it the same way I can with the resource specific views, etc.

And while I can use the content_for :javascripts helper to add the javascript for cloudinary things directly, I'm pretty sure that will break when I move it to Heroku due to the SHA that added during precompile, won't it? So where do I add the require statement above to get it to get it added to the asset pipeline used in Administrate?

**Comment by graysonwright** [comment]
Thanks, @nextekcarl! It looks like there's a bit of overlap with #187 here. We're hoping to add generators for SCSS and JS soon, but until then you should be able to overwrite a few files to get it working.

**Comment by nextekcarl** [comment]
Thanks, I looked at that but I guess I'm just not sure how I'd translate the manifest require statement into this formt and actually expect it to work:

**Comment by nextekcarl** [comment]
Sorry, comment was messed up there so I deleted to and I'll try again:

I guess I'm just not sure who I'd translate the work done by //= require cloudinary in the app manifest into a simple content for block and expect it to work wince this method doesn't add the SHAs:

<% content_for :javascript do %>
  <%= javascript_include_tag("jquery.ui.widget", "jquery.iframe-transport", 
                         "jquery.fileupload", "jquery.cloudinary") %>
  <%= cloudinary_js_config %>
<% end %>

Any help is appreciated.

**Comment by graysonwright** [comment]
Hm... you may be able to copy [this file](https://github.com/thoughtbot/administrate/blob/master/app/assets/javascripts/administrate/application.js) into your app at `app/assets/javascripts/administrate/application.js`, and then add the `//= require` statement in there.

Does that solve the problem?

**Comment by nextekcarl** [comment]
Yes, I think that did, thanks!

**Comment by graysonwright** [comment]
Great! I'll work on a generator to make that process easier.

**Comment by nextekcarl** [comment]
We can generate the files used for views, but not for the layout. How do do we modify the favicon, or change the actual layout outside of the specific content_for blocks included already? I guess you could include content for blocks for each section, but that feels kind of clunky over just generating the layouts the same way we generate the views for resources, but I don't see a way to do that.

**Comment by graysonwright** [comment]
@nextekcarl I just merged in #269, which adds `rails generate administrate:views:layout`. It'll go out in version `0.1.3`, and until then you can get it by using `gem "administrate", github: "thoughtbot/administrate"`.

Cheers!

**Comment by nextekcarl** [comment]
Woohoo!
