### ISSUE TITLE
Cancel Search Issue

### ISSUE THREAD

**Issue by agnel** [thoughtbot/administrate#260]
After searching, say in Customers, there is no 'x' button in the search bar to cancel the search. The user has to again click on the Customers link in the left side bar to listing the customers or cancel the search.

Can the 'x' button be added ?

**Comment by graysonwright** [comment]
Yep! We're working on this in #127.

I'm going to close this, because we already have an issue for it at #121. Feel free to join the conversation on the other thread!

**Comment by agnel** [comment]
Sure. Thanks
