### ISSUE TITLE
RubyGems Metadata Issue

### ISSUE THREAD

**Issue by benverseman** [thoughtbot/administrate#2714]
* What were you trying to do?
   - Attempting to update from administrate 0.19.0 to greater version

* What did you end up with (logs, or, even better, example apps are great!)?
bundle update administrate
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Could not find compatible versions

Because administrate >= 0.20.0 depends on activerecord >= 6.0, < 8.0
  and Gemfile depends on activerecord >= 8.0.0,
  administrate >= 0.20.0 cannot be used.
So, because Gemfile depends on administrate ~> 0.20.1,
  version solving has failed.

* What versions are you running?
  - Rails 8
  - administrate 0.19

Looks like the issue lies with the dependencies listed on Rubygems.org. When I manually add the repo from Github, bundler installs administrate just fine.

**Comment by nickcharlton** [comment]
There's are a couple of things here, first is support for Rails 8 is merged, but not released yet: #2705.

I also saw an issue where you might end up with an older version (which amusingly it _will_ work), but it's worth being mindful of: https://github.com/thoughtbot/administrate/issues/2703#issuecomment-2489179119

You can work around this by bundling from `main` for now (or from the `sha` associated with the merged in Rails 8 support), but only if you're keen to be on the bleeding edge of the beta releases.

There will be a release soon, as everything for v1 is looking good to go.
