### ISSUE TITLE
Filters : feature request 

### ISSUE THREAD

**Issue by wolfieorama** [thoughtbot/administrate#277]
Hi, 

This is an awesome and super simplified admin dashboard gem, when do we expect filters to be integrated, apologies if this feature request is a repetition

**Comment by nando** [comment]
Hi John,

we've been talking about this in this issue: https://github.com/thoughtbot/administrate/issues/183

This is in the context of Smart Searching https://github.com/thoughtbot/administrate/issues/157

Using my fork's branch search_scopes is possible to filter using the model scopes just adding "name_of_the_scope:" at the beggining of the search query.

Let me know if it is helpful for you too.

Best,
-- nando

**Comment by graysonwright** [comment]
@wolfieorama Thanks for your interest! We're still trying to figure out the best way to support filtering. Let's move this conversation over to #183 - I'd love to hear your ideas.

**Comment by Ferrumofomega** [comment]
Hi @graysonwright Is there any suggested way of filtering then?
