### ISSUE TITLE
Allow administrate to be installed somewhere other than /admin

### ISSUE THREAD

**Issue by aaronrenner** [thoughtbot/administrate#281]
I have a project that already has an /admin namespace and I'd like to install administrate as a secondary admin interface (maybe at /administrate).This would allow me to manage CRUD operations on models that don't have a UI yet. When I run `rails g administrate:install` it would be nice if there was an option to change the namespace of where I want it installed, so it doesn't conflict with my existing controllers. Here is an example of what rails admin does: https://github.com/sferik/rails_admin/blob/master/lib/generators/rails_admin/install_generator.rb#L13

I really appreciate you building this gem and I'm looking forward to using it.

**Comment by graysonwright** [comment]
@aaronrenner thanks! We definitely want to allow custom namespaces. Rails Admin's install generators should be a good reference for implementing this ourselves.

**Comment by zamith** [comment]
What about having it as a config? It could be defined once per project, instead of every time you want to generate one.

**Comment by zamith** [comment]
@graysonwright What do you think of #330?

**Comment by graysonwright** [comment]
Commented on that issue. Also opened up #339 as an alternative solution.
