### ISSUE TITLE
Allows controllers to be defined and work properly without declaring them in the manifest

### ISSUE THREAD

**Issue by erickreutz** [thoughtbot/administrate#283]
We have some models that we only want to be accessed through other models and not listed in the menu on the side. The only way for the routes to be defined, etc is to list the model in the dashboard manifest. Any plans to not require listing the model in the manifest in order for the routes and everything else to be defined?

**Comment by graysonwright** [comment]
@erickreutz, great question! Sorry it took me a while to get back to you.

There are a couple ways to do this:

One way is to remove the models from your `DashboardManifewt`, and replace the generated routes with custom ones for your application. You're under no obligation to use the routes that administrate defined for you - those are merely a suggestion.

Another way to accomplish this would be to copy [the sidebar partial] into your application, at `app/views/admin/_sidebar.html.erb`. You can customize the sidebar to use only the models that you'd like to display, or rearrange the sidebar completely to fit your tastes.

If you go the second route, you'll likely want to keep the models in `DashboardManifest` so the routes get generated for them automatically.

Let me know if one of those options works for you!

[the sidebar partial]: https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/_sidebar.html.erb

**Comment by carlosramireziii** [comment]
@erickreutz Were you able to make one of the solutions outlined above work for you? If so, which route did you end up going?

I'm going to close up this issue, but it'd be great to hear back regarding the approach you took.
