### ISSUE TITLE
Views, little problem for all of you, big for me

### ISSUE THREAD

**Issue by djordje47** [thoughtbot/administrate#287]
Hi,
I am new to rails and I am learning all the time. So I need help with editing my form of my new Categories. I do not know how to connect _form.html & edit.html which I generated through terminal and this command: " rails generate administrate:views:edit Category "  with my dashboard. I do not need any special edditing just few forms and that's it.

Thanks in advance,
Best regards

**Comment by graysonwright** [comment]
Hello, @djordje47!

If you only want to add new form fields, you should be able to edit `_form.html.erb` and ignore `edit.html.erb`.

To make sure it's working, add `<h1>Test</h1>` to `_edit.html.erb`, and make sure you see it show up at http://localhost:3000/admin/categories/new .

You can find a good overview of how Rails views work here: http://guides.rubyonrails.org/layouts_and_rendering.html

**Comment by carlosramireziii** [comment]
@djordje47 Were you able to get this working? 

I'm going to close up this issue, but I hope you were able to figure it out. Cheers!
