### ISSUE TITLE
ActiveRecord enum types incorrectly interpreted by generator

### ISSUE THREAD

**Issue by schneidmaster** [thoughtbot/administrate#290]
[ActiveRecord enums](http://edgeapi.rubyonrails.org/classes/ActiveRecord/Enum.html) are integers in the database, but ActiveRecord translates them into the associated string value before returning them to Rails application code. The problem is that the administrate generator interprets them as integers by default, which means that any generated dashboards with enums error unless you manually change the attribute type to `Field::String` in each one.

**Comment by seanpdoyle** [comment]
It would also be nice if the outgoing `String` value had `#titleize` invoked on it.

**Comment by graysonwright** [comment]
Merged in #295.
