### ISSUE TITLE
Search crashing with uuids, any way to override search?

### ISSUE THREAD

**Issue by michaelimstepf** [thoughtbot/administrate#291]
Thanks for creating this awesome gem,

I have this table:

```ruby
  create_table "organizations", id: :uuid, default: "uuid_generate_v4()", force: :cascade do |t|
    t.string   "name",                  null: false
    # rest omitted
  end
```

And when I search I get this error:

```
PG::UndefinedFunction: ERROR:  operator does not exist: uuid ~~* unknown
LINE 1: ... "organizations".* FROM "organizations" WHERE (id ILIKE '%At...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT  "organizations".* FROM "organizations" WHERE (id ILIKE '%Atlassian%' OR name ILIKE '%Atlassian%' OR logo_url ILIKE '%Atlassian%' OR thumb_url ILIKE '%Atlassian%' OR long_description ILIKE '%Atlassian%' OR short_description ILIKE '%Atlassian%' OR organization_url ILIKE '%Atlassian%' OR twitter_url ILIKE '%Atlassian%' OR angellist_id ILIKE '%Atlassian%' OR angellist_url ILIKE '%Atlassian%' OR slug ILIKE '%Atlassian%' OR crunchbase_id ILIKE '%Atlassian%' OR crunchbase_url ILIKE '%Atlassian%' OR location_id ILIKE '%Atlassian%') LIMIT 20 OFFSET 0
```

Rather than overriding the index method with my own search implementation, is there a way I can override the search method so it ignores the ID field?

**Comment by tomgatzgates** [comment]
This is what i've done `id: Field::String.with_options(searchable: false)`

**Comment by michaelimstepf** [comment]
Thanks! Upgrading to v0.1.1 and re running the installer fixed it.

**Comment by graysonwright** [comment]
@tomgatzgates thanks for your solution!

@michaelimstepf glad it's working for you. Let us know if you have any other issues!

**Comment by erickreutz** [comment]
What is we are wanting to search by UUIDs though?

**Comment by graysonwright** [comment]
@erickreutz we're planning to do a big overhaul of search, as discussed in #157 and #322. When we do that, it will add support for UUID columns.

**Comment by qume** [comment]
If anyone is using postgres, you can run this function in PSQL which makes searching work with UUIDs. 

This is the first time I've created a function in a database like this, so don't assume this doesn't have nasty side-effects:
```
create or replace function lower(uuid) returns text
    as 'select $1::text;'
    language sql
    immutable
    returns null on null input;
```
Where it says lower(uuid), you can replace uuid with other types, and as long as they can be converted to text with ::text, which most can, it should work.
