### ISSUE TITLE
with_options(title: '...') not setting field titles in dashboards

### ISSUE THREAD

**Issue by alexkrolick** [thoughtbot/administrate#292]
It seems like the default stringifier cuts off anything that ends with `_id` when it generates the labels for fields. I tried making a custom title for the fields like this:

``` ruby
thing_id: Field::String.with_options(title: "Thing ID")
```

But the labels throughout the dashboard are still the same.

**Comment by graysonwright** [comment]
@whokilledtheelectricmonk, thanks for pointing this out.

We'd absolutely like to support custom labels, but this feature isn't in place yet. I'm going to assign this to the `0.1.3` milestone, and we'll take a look at it as soon as we've ironed out more pressing bug fixes.

**Comment by janklimo** [comment]
As a temporary solution, see how the title is being set [right now](https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/show.html.erb#L36). For instance, I wanted to rename `item_total` attribute of `Order` to `Subtotal`, so I have the following in my `locales/en.yml`:

``` ruby
en:
  helpers:
    label:
      order:
        item_total: Subtotal
```

**Comment by pablobm** [comment]
I wasn't aware of that `title` option. I don't think it exists anymore? I can't find it in the code.

In any case @janklimo's approach is preferred: use the locale file to provide names for fields.
