### ISSUE TITLE
Environment setup issues

### ISSUE THREAD

**Issue by latortuga** [thoughtbot/administrate#296]
I'm on Ubuntu 14.04 LTS and running `bin/setup` gives me issues with the default configuration:

```sh
Couldn't create database for {"adapter"=>"postgresql", "database"=>"administrate-prototype_development", "encoding"=>"utf8", "host"=>"localhost", "min_messages"=>"warning", "pool"=>2, "timeout"=>5000}
fe_sendauth: no password supplied
/home/drew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `initialize'
/home/drew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `new'
/home/drew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
/home/drew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
/home/drew/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.2/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
```

...with a bunch more output. I commented out the `host` portion in `database.yml` and all works perfectly. Would you be amenable to accepting a PR where I modify the setup script to copy a `database.yml.example` to `database.yml` and add `database.yml` to `.gitignore`?

**Comment by graysonwright** [comment]
@latortuga interesting. Does Ubuntu not recognize `localhost`?

I wonder if we can remove the `host` argument altogether. It looks like doing so still works on OS X.

@croaky & @geoffharcourt, thoughts?

**Comment by geoffharcourt** [comment]
I've always avoided declaring the `host` parameter, but I assumed it was needed for folks on *nix/BSD systems. If it works across both OS categories I'm happy to drop it.

I'm a little nervous about moving to a `database.yml.example` world just because it's one more subtle thing a user could miss when they are tweaking their application setup.

**Comment by latortuga** [comment]
I don't really have a horse in either race. I will say that the `bin/setup` script was very straightforward and a pleasant surprise as most projects do not have a similar setup script. Adding a copy command along with a helpful message could be the ticket. However, it does work fine without the `host` argument so that way is fine with me too.

**Comment by graysonwright** [comment]
I'm :+1: on dropping the `host` key. Will create a PR before 0.1.3.
