### ISSUE TITLE
Allow Easier Editing of Labels For HasMany Field

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/administrate#303]
I have a user with many Roles, and on the edit page, I see a label saying `Role ids` when I would rather see the label say `Roles` instead. The only way I see to make this minor edit is by creating my own custom field which would duplicate most of Field::HasMany. Is there an easier way, am I missing something?

**Comment by sockmonk** [comment]
In the role_dashboard.rb at the bottom, overwrite the "display_resource" method. It will override what's displayed on the User page, too.

**Comment by graysonwright** [comment]
@sockmonk I'm not sure that solves @coneybeare's problem - maybe I'm misunderstanding though.

@coneybeare, I'd like to support custom labels by passing in an argument in the dashboard, like:

```ruby
  ATTRIBUTE_TYPES = {
    roles: Field::HasMany.with_options(label: "Roles"),
  }
```

Passing in the `label` option would change the table heading on the `index` page, as well as the left-side labels on the `show`, `edit`, and `new` pages.

Would that solve your problem?

**Comment by coneybeare** [comment]
The solution by @sockmonk does not solve the problem. That method is for when a Role is displayed on another form or field.

@graysonwright has the right approach here of editing it as part of the dashboard data. I actually tried doing that first by passing in `:name`, `:label` and other values, but could't find any documentation on it and the code wasn't clear, at least to me.

**Comment by graysonwright** [comment]
@coneybeare yeah, at the moment it's not supported.

It's a bit strange though - I thought we were already removing `_ids` from `has_many` fields. I may be getting it mixed up with the `_id` suffix on `belongs_to` relationships.

Let me dig in a little bit and see if I can remove the `_ids` suffix - I think we'll want to do that for all `HasMany` relationships. After that we can break out the custom labels into their own PR.

**Comment by graysonwright** [comment]
@coneybeare #315 should take care of this. Thanks for pointing it out!

**Comment by graysonwright** [comment]
@coneybeare If you set your administrate version to `~> 0.1.2`, this should be fixed.
