### ISSUE TITLE
Search is ambiguously displayed when nothing is searchable

### ISSUE THREAD

**Issue by latortuga** [thoughtbot/administrate#314]
Example: https://administrate-prototype.herokuapp.com/admin/line_items

None of the fields are searchable yet there is a search box. What do you think about removing it in this case? The problem is that using the search _appears_ to do something but really does nothing.

**Comment by carlosramireziii** [comment]
@latortuga I believe this may have been by #730. Could you please confirm. Thanks!!

**Comment by latortuga** [comment]
@carlosramireziii would you believe I don't even remember filing this issue? Fun. Anyway, LGTM on the demo site!
