### ISSUE TITLE
#to_s on models not working reliably

### ISSUE THREAD

**Issue by nextekcarl** [thoughtbot/administrate#329]
I've updated to 1.2.0 and to_s doesn't seem to be reliably working to display titles/names for models:

![to_s](https://monosnap.com/file/q0R2xKqV9DCU3YWrjkkr5YdE2osbRU.png)

There was talking about changing this in another issue, but I don't see anything saying the method changed, and I can't find anything documented anywhere, plus it is still working in at least one area shown.

**Comment by graysonwright** [comment]
@nextekcarl, we changed up the rendering behavior in #191 - that change went out in version `0.1.1`.

You can fix the behavior by adding this to your `ProductDashboard`:

```ruby
def display_resource(product)
  product.to_s
end
```

As for the "Show Shampoo" button that is using `#to_s`, that was an oversight that was fixed up in #243. If you update to version `~> 0.1.2`, that fix should be in place.

If that solves your problem, feel free to close the issue. Cheers!

**Comment by nextekcarl** [comment]
Thanks, though I'm already updated to 0.1.2 in that screenshot, so I think that button code must still be using the old code. I had just updated Administrate to 0.1.2 about 20 mins before posting that screenshot.

**Comment by nextekcarl** [comment]
And just to verify that I tried to update the gem again (already updated) and then changed the new display_resource method to reverse the text as shown here:

![edit oopmahs](https://cloud.githubusercontent.com/assets/16820/11821921/c92e6f84-a320-11e5-9ddc-cc9eb101f0ac.png)

The button must still be using the model's #to_s method.

**Comment by graysonwright** [comment]
Interesting. @nextekcarl, do you have `app/views/admin/application/edit.html.erb` or `app/views/admin/products/edit.html.erb` in your application?

**Comment by nextekcarl** [comment]
D'Oh! That was it, thanks.
