### ISSUE TITLE
Customizing `candidate_resources` per Dashboard

### ISSUE THREAD

**Issue by zamith** [thoughtbot/administrate#331]
Is it possible to define in a per dashboard basis, the queries to be done to get the `candidate_resources`, instead of using `all` all the time.

Example: A user can have multiple roles, and depending on the role we might (or not) want to show that user in the list of users to select from.

**Comment by zamith** [comment]
What about something like:

```ruby
def candidate_resources
  query = options.fetch(:scope, -> { associated_class.all })
  query.call
end
```

**Comment by pablobm** [comment]
Associated PR https://github.com/thoughtbot/administrate/pull/333 was closed.
