### ISSUE TITLE
Best way to include main app helper modules in administrate?

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/administrate#334]
In making a custom field, I have the need to reuse an `image_srcset_tag` I created outside of the app inside a helper. Administrate does not seem to know about my main app's helpers, so it appears that I would either have to duplicate the methods, or find someway to easily import the modules into administrate. What would you recommend?

**Comment by graysonwright** [comment]
Interesting question. I don't know an easy way to do this off the top of my head, but I'll ask my teammates and see if anyone knows a way.

**Comment by coneybeare** [comment]
I think the only way is for you to load it into the engine: http://stackoverflow.com/a/21792041/69634

It makes sense because you expect the fields to be defined in the same place as the main app views, so they should have access to the main app helpers as well. With routing you can use `main_app.xxxx`, but nothing like that exists for the helpers.

**Comment by graysonwright** [comment]
@coneybeare did that solve the problem for you?

**Comment by coneybeare** [comment]
I haven't tried yet, but I am also researching the best way, and trying to wrap my head around potential pitfalls. It appears as though the library purposely tries to be as isolated as possible, and this would add a major hook into the main app. It would be better if a solution could be found in a line to add to the main app instead.

**Comment by graysonwright** [comment]
Alright, let me know if you find anything that works well. Thanks for your help!

**Comment by coneybeare** [comment]
I haven't found anything that works yet unfortunately, but still hope to keep this DRY

**Comment by coneybeare** [comment]
It's not ideal, but I created my own `app/helpers/administrate/application_helper.rb` file which included a copy/paste of the 2 repo methods and `include ::ApplicationHelper`, `include ::ImagesHelper` and whatever other helpers I wanted to inject from the main app into the engine.

I have to monitor changes to the engines application helper and edit those as needed, but at least it works for the time being without having to overwrite any engine code.

**Comment by sophiedeziel** [comment]
The solution I found is very simple. `MontrealRb` is the name of my main app. 
```
#  config/application.rb
module MontrealRb
  class Application < Rails::Application
    # other configs

     config.to_prepare do
      Administrate::ApplicationController.helper MontrealRb::Application.helpers
    end
  end
end
```

**Comment by graysonwright** [comment]
@sophiedeziel that looks great. Thanks!

@coneybeare, does that work? Is that something that we should include in the documentation?

**Comment by coneybeare** [comment]
Unfortunately I have moved away from Administrate in my project, but it looks viable.

**Comment by graysonwright** [comment]
Ah, too bad. Sorry to hear that.

I'll close this issue for now; if we get some :+1:'s on this thread, I'll add it to the documentation. Thanks, @sophiedeziel!

**Comment by alvaroemmanuel** [comment]
I've just needed to use some helpers from main app in Administrate, first tried to create a helpers/administrate/application_helper.rb, just like @coneybeare.

Although it worked, I think it's not an elegant nor maintainable solution in the long term, so I tried @sophiedeziel suggestion and it worked like a charm :+1: 

I really think this should be added to the docs.

Thanks @sophiedeziel!!

**Comment by sophiedeziel** [comment]
Yay!

Happy to help!

And that solution works with any other engine your Rails app is using.

**Comment by jameswilliamiii** [comment]
I really like @sophiedeziel's solution.  Worked like a charm!

**Comment by FerPerales** [comment]
@sophiedeziel Nice solution! The only disadvantage is that app must be restarted in order to get the helpers updates when I change them. Any idea on how to auto reload? Thanks in advance

**Comment by fogshot** [comment]
@sophiedeziel can you tell me how to use your solution to call a helper from a custom field in Administrate?

**Comment by sophiedeziel** [comment]
I did that months ago, I have to go back to my project to remember if there is something else to do after editing `config/application.rb`.

@graysonwright did you add it to the documentation? Where can I find that part in the docs?

**Comment by sophiedeziel** [comment]
@fogshot Here is a commit where edited `config/application.rb` to make my own helpers (in `app/helpers`) available in Administrate's views.

I created a custom field called `MarkdownField`. In its `show` view (`app/views/fields/markdown_field/_show.html.erb`), I simply used my app's helper (`render_markdown_as_html `) and it worked. Nothing else to do.

**Comment by fogshot** [comment]
@sophiedeziel This is exactly what I'm trying to do myself, thanks a lot!

It seems like I went wrong in trying to use the helper inside the MarkdownField class. Using it directly from the view works like a charm though.

**Comment by kiramclean** [comment]
👍 thanks @sophiedeziel , awesome solution!

**Comment by FanaHOVA** [comment]
Sorry to bump an old issue, but did something change in the Administrate architecture that makes this throw this error?

`A copy of xxxxHelper has been removed from the module tree but is still active!`

I've seen this before with ActiveAdmin and it had something to do with requiring helpers in non-reloadable classes. Just trying to figure out if I need to debug this on my app's end or on Administrate. I don't think I have any config change that would break @sophiedeziel's solution.

**Comment by nickcharlton** [comment]
@FanaHOVA Do you know which version you were running when it _was_ working? It's possible something had changed between the `0.8.0` and `0.9.0` release and it'd be good to get this working again!

**Comment by fr33z3** [comment]
Any news about that issue?

**Comment by FanaHOVA** [comment]
@nickcharlton Sorry I didn't get a notification for your comment. I'm running 0.8.1 actually.

**Comment by juanmanuelramallo** [comment]
> The solution I found is very simple.
> 
> Basically, I tell the engine to load all the main app's helpers in the config of my app.
> 
> `MontrealRb` is the name of my main app.
> 
> ```
> #  config/application.rb
> 
> module MontrealRb
>   class Application < Rails::Application
>     # other configs
> 
>     config.to_prepare do
>       Administrate::ApplicationController.helper MontrealRb::Application.helpers
>     end
>   end
> end
> ```

It doesn't autoload the code when file has changed 😢 
So you'll see something like `A copy of SomeHelper has been removed from the module tree but is still active!`

**Comment by nealshepherd** [comment]
I found a solution that appears to be working as needed:

Add `helper all_helpers_from_path "app/helpers"` to your `Admin::ApplicationController`
Reference: https://api.rubyonrails.org/classes/ActionController/Helpers/ClassMethods.html#method-i-all_helpers_from_path

Unless I'm overlooking an important consideration, the helper modules are reloaded per-request with any changes.

**Comment by jpaulomotta** [comment]
Woow

@nealshepherd solutions worked for me on Rails 5.2 and Administrate 0.11.0

The solution proposed by @sophiedeziel also worked, but once in a while I would hit strange errors like: ```A copy of xxxxHelper has been removed from the module tree but is still active!```.

Using @nealshepherd  solution my ```Admin::ApplicationController``` looks as follow:
```ruby
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin_user!
    helper all_helpers_from_path "app/helpers"
  end
end
```
