### ISSUE TITLE
Custom JavaScript problem

### ISSUE THREAD

**Issue by kzazarashvili** [thoughtbot/administrate#343]
I tried to add custom JavaScript to the view that the gem generated for me, but it didn't work. The gem didn't load the assets from my application. Is there any solution for such situation?

**Comment by graysonwright** [comment]
@kzazarashvili, which file did you try to add your javascript to?

We just added a new generator, `rails generate administrate:assets:javascripts`, in #326. If you update your Gemfile to use:

```ruby
gem "administrate", github: "thoughtbot/administrate"
```

...then you should have access to that generator. After you run it, Administrate should pick up any javascript you add to `app/assets/javascripts/administrate/application.js`.

**Comment by kzazarashvili** [comment]
Thank you very much! it worked.

**Comment by causztic** [comment]
I did ```ruby rails generate administrate:assets:stylesheets``` instead and imported my stylesheets there.
