### ISSUE TITLE
Belongs_to form NoMethodError when association uses different foreign_key

### ISSUE THREAD

**Issue by coneybeare** [thoughtbot/administrate#354]
**Setup**

``` ruby
class AuthorLink < ActiveRecord::Base
  belongs_to :author
  belongs_to :link_type, class_name: 'AuthorLinkType', foreign_key: :author_link_type_id
  ...
end

class AuthorLinkDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    link_type: Field::BelongsTo.with_options(class_name: "AuthorLinkType"),
    ...
  }
...
end
```

**Problem**

Visiting `/admin/author_links/2/edit` results in

![NoMethodError](http://cloud.coneybeare.me/e8hy/Screen%20Shot%202015-12-18%20at%2010.34.17%20PM.jpg)

The `NoMethodError` stems from [`Field::BelongsTo.permitted_attribute`](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/fields/belongs_to.rb#L6), where you assume a standard association and hardcode `_id` accordingly.

``` ruby
def self.permitted_attribute(attr)
  :"#{attr}_id"
end
```

**Solution**

There needs to be more intelligence here to detect `foreign_key` variances amongst others. Agreed?

**Comment by zamith** [comment]
Since we are passing the `class_name` as an option, we can pass the `foreign_key` as well, no?

Or we can try to be a bit more clever and do something like:

```ruby
AuthorLink.reflect_on_association(:link_type).foreign_key
=> :author_link_type_id
```
which right now is not possible, since the field does not know about the `AuthorLink` class.

**Comment by coneybeare** [comment]
I would prefer passing the option in the dashboard, but I know that the goal of administrate is to avoid DSL and keeping the `with_options` as limited as possible. This could be problematic because if you allow `foreign_key` in the options, then you also should allow the other options for associations like `:conditions`, `:through`, `:polymorphic` etc...

**Comment by ACPK** [comment]
Any update or monkey patch for this so we can use Administrative?

**Comment by buren** [comment]
@ACPK, @coneybeare I ran in into the same problem I fixed by adding those methods to the ActiveRecord model.

Here is something that code work in your case:

```ruby
class AuthorLink < ActiveRecord::Base
  # ... 

  def link_type_id
  end

  def link_type_id=(id)
    self.link_type = AuthorLinkType.find(id)
  end
end
```

**Comment by angusfretwell** [comment]
Any update on this?

I found a slightly nicer workaround:

```ruby
class Lister < User
  belongs_to :company, foreign_key: :organisation_id

  alias_attribute :company_id, :organisation_id
end
```

**Comment by dduqueti** [comment]
@angusfretwell Thank you!

**Comment by pablobm** [comment]
I think this was fixed with https://github.com/thoughtbot/administrate/pull/807. I'm closing, but please reopen if you think differently.
