### ISSUE TITLE
Date Time Select Layout Issue and Responsive Layout

### ISSUE THREAD

**Issue by james05** [thoughtbot/administrate#360]
The layout when using Rails date_time_select looks terrible. The bigger issue this shows is the layout falls apart horribly on mobile devices. See the 2nd attached screenshot on a 5" smartphone screen.

![election_ui_bug](https://cloud.githubusercontent.com/assets/13721630/11939031/13504116-a7ed-11e5-8eea-c1d6041a8f50.jpeg)

![screenshot_2015-12-21-14-18-32](https://cloud.githubusercontent.com/assets/13721630/11939149/085cbe00-a7ee-11e5-80c8-43c3f9b2814b.png)

**Comment by graysonwright** [comment]
@james05 that's interesting. The default look for `DateTime` fields is a bit different - you can see it in action at https://administrate-prototype.herokuapp.com/admin/orders/312/edit.

![edit_order__312___administrate_prototype](https://cloud.githubusercontent.com/assets/829576/11949127/d53f5d0a-a849-11e5-957c-132570c4ccbb.png)

Have you customized the `DateTime` fields in your application?

As for a responsive layout, you're right - we currently don't support small screen sizes. This is something we'd like to do in the future, though. @tysongach would probably be able to speak the most about that.

**Comment by james05** [comment]
I changed the DateTime field intentionally as it's important for my application to work without JavaScript in text based browsers. The behaviour above is the behaviour for Rails form helper date_time_select.

**Comment by ACPK** [comment]
@geoffharcourt @james05  - To fix the responsiveness issue temporarily, what about keeping the screen width the same so the administrative area doesn't try to be responsive? Hence, you'll be able to use it on mobile but just have to zoom in.

**Comment by salimane** [comment]
any update of the responsiveness?

**Comment by nickcharlton** [comment]
I'm going to close this issue as it's quite old and there's other issues documenting the lack of responsiveness (e.g.: #128). This is important and we'll address it in the future.
