### ISSUE TITLE
[SCSS] FIX - appearence none

### ISSUE THREAD

**Issue by nicovak** [thoughtbot/administrate#366]
There is an issue with select and `appearance` css property. The dropdown 'icon' is displayed twice (tested on chrome).
A mixin should be used (It's SASS), Bourbon is imported, you could used it like this:

Eg: administrate/app/assets/stylesheets/administrate/base/_forms.scss

```
select {
@include appearance(none);
}
```

It will generates all browser's prefix for the property.

IE is the bad kid but Opera seems to be also : [W3C](http://www.w3schools.com/cssref/css3_pr_appearance.asp)

The best way to hanlde It would be to include a javascript library for a better customization.

**Comment by tysongach** [comment]
Definitely an issue many people are seeing. There’s some chatter and a possible fix over on #372, but Autoprefixer _should_ be running and take care of this for us (using Bourbon for prefixing is no longer the best solution). So if this is a prefixing issue, maybe it’s a bug with Autoprefixer.

**Comment by tysongach** [comment]
I’ve confirmed that Autoprefixer is not actually running and outputting any prefixes, including the ones required here for these styles.

**Comment by carlosramireziii** [comment]
As per #372, the solution to this issue is to fix Autoprefixer to make sure it's running on the CSS. I'm going to close this ticket in favor of that and will link the associated pull request when it's created.
