### ISSUE TITLE
Change has_many or belongs_to display title

### ISSUE THREAD

**Issue by cameronbarker** [thoughtbot/administrate#367]
Is there currently a way to choose which attribute will be displayed in a has many and belongs to  relationship form field? 

Be happy to take a crack at it if not.

i.e. Change the text "Line Item #1001" to the Line Item's product attribute (see photo below).

![product](https://cloud.githubusercontent.com/assets/6642141/12039968/e38ea552-ae32-11e5-950c-141457e4e1a1.jpg)

**Comment by coneybeare** [comment]
You just need to change the value returned for the `display_resource` method in your `LineItemDashboard`

**Comment by j-dexx** [comment]
Thanks @coneybeare been trying to find out how to do that.

**Comment by robinvdijk** [comment]
@j-dexx 

I think you can do the following to display a `LineItem name`
```
def display_resource(line_item)
  "#{line_item.name}"
end
```

**Comment by carlosramireziii** [comment]
@cameronbarker The commenters above are correct-- changing `display_resource` is the way to go.

**Comment by cameronbarker** [comment]
👍
