### ISSUE TITLE
"Rails generate administrate:install" interferes with the existing app/controllers/admin" folder.

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#374]
How can I mount / install administrative in a different folder, so it doesn't conflict with a custom admin dashboard? We'd like to gently launch a new administrative dashboard, rather than completely remove the old one.

**Comment by aguynamedben** [comment]
+1. Following the README to quickly try out administrate to see if it might be a good fit, I discovered the install generator was colliding with my existing admin functionality on a legacy app.

**Comment by aguynamedben** [comment]
Some history in this PR https://github.com/thoughtbot/administrate/pull/339

> Next Steps: Change generators to accept (or read from some configuration file) an optional namespace argument instead of always using the admin namespace.
