### ISSUE TITLE
undefined method `class_name' for nil:NilClass

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#375]
/Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/reflection.rb:883:in `derive_class_name': undefined method `class_name' for nil:NilClass (NoMethodError)
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/reflection.rb:157:in `class_name'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:92:in `relationship_options_string'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:79:in `association_type'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:55:in `redundant_attributes_for'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:50:in `block in redundant_attributes'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `each'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `flat_map'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:49:in `redundant_attributes'
        from /Users/andrewcharleskelley/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/administrate-0.1.2/lib/generators/administrate/dashboard/dashboard_generator.rb:41:in `attributes'
        from (erb):11:in `template'

**Comment by kenlane33** [comment]
I'm having this problem as well. Any findings?

**Comment by erichummel** [comment]
@kenlane33 i got this when I had a broken has_many :through in my models

**Comment by kenlane33** [comment]
Thanks, Eric. That was my trouble exactly.
