### ISSUE TITLE
Always go to show page

### ISSUE THREAD

**Issue by samnang** [thoughtbot/administrate#388]
When I tried to add another column in index page to show links which contain thumbnail like:

``` ruby
<%= link_to main_app.facebook_profile_url(resource.fb_id), target: "_blank" do  %>
  <%= image_tag resource.avatar.thumbnail.url %>
<% end %>
```

So whenever users click on thumbnail, it opens the url and as well as go to show page. We don't want to user go to show page. I notice it's always go to show page if event's target is not a link:
https://github.com/thoughtbot/administrate/blob/5f444611164a0b0494ee76fa30e6b577b93decef/app/assets/javascripts/administrate/components/table.js#L9-L10

Do you have any ideas or suggestion to address it? I could work on PR on those ideas.

**Comment by pablobm** [comment]
Associated PR https://github.com/thoughtbot/administrate/pull/392 was closed.
