### ISSUE TITLE
undefined local variable or method `namespace'

### ISSUE THREAD

**Issue by alejandropereira** [thoughtbot/administrate#403]
Hello, I'm trying to override the sidebar template, i copied [this template](https://raw.githubusercontent.com/thoughtbot/administrate/master/app/views/administrate/application/_sidebar.html.erb) into "app/views/admin/application/_sidebar.html.erb" and i'm getting this error.

![captura de pantalla 2016-01-11 a las 10 14 03 pm](https://cloud.githubusercontent.com/assets/3091982/12254686/f5c835fc-b8b0-11e5-9a9a-884221a17603.png)

I can hardcode `[:admin, resource]` but i think there must be a better option.

Thanks!!

**Comment by carlosramireziii** [comment]
@alejandropereira I see that you were using version `0.1.2`. I was able to reproduce the issue with that version, but it seems to be fixed if you upgrade to `0.1.5`. Will you try that and let me know if this issue is resolved? Thanks!

**Comment by carlosramireziii** [comment]
Closing this as it's been inactive for a while. Please re-open if you feel it's still an issue. Thanks!
