### ISSUE TITLE
Controller Generator Pagination

### ISSUE THREAD

**Issue by j-dexx** [thoughtbot/administrate#406]
In the controller generator you have the following example.

```
# def index
#   super
#   @resources = <%= class_name %>.all.paginate(10, params[:page])
# end
```

Paginate is a method for `will_paginate` though and administrate uses kaminari, so this should be

`@resources = <%= class_name %>.all.page(params[:page]).per(10)`

I don't know if this is because you're planning on switching to `will_paginate`?

Happy to submit a PR if it helps.

**Comment by onlymejosh** [comment]
I'm running into the same issues. It looks like this has been removed in the last few versions. Any news as to why?

**Comment by carlosramireziii** [comment]
@j-dexx @onlymejosh Is this a similar issue to #483?

If so, it looks like the generated controller template has been updated to use the proper Kaminari syntax in [this commit](https://github.com/thoughtbot/administrate/commit/077f6d370b3d0eff325a3de0509aeaa21b47b632) which was merged into the current `master` branch. 

That being the case, is this issue resolved?

**Comment by onlymejosh** [comment]
Yep that'll fix it for me!

**Comment by carlosramireziii** [comment]
@tysongach You may be able to close up this issue.

**Comment by nickcharlton** [comment]
Thanks for pulling this up! Going to close.

**Comment by lukelove** [comment]
Dropping this for the next person who comes looking for how to paginate

https://administrate-prototype.herokuapp.com/customizing_dashboards

```
  ATTRIBUTE_TYPES = {
    playlists: Field::HasMany.with_options(limit: 20), # this is how you set the pagination
    id: Field::Number,
    name: Field::String,
    created_at: Field::DateTime,
    updated_at: Field::DateTime,
  }.freeze
```
