### ISSUE TITLE
Override single method of a field

### ISSUE THREAD

**Issue by michaelimstepf** [thoughtbot/administrate#412]
On the show action of a resource, where there is a has many relationship with more than 5 associated records, I want to show all associated records (not just the first 5).

Instead of creating a custom field and copy / paste everything from the default has many field, I just want to change one method. Is this possible? I tried the following, which didn't work:

``` ruby
# app/fields/has_many.rb
module Administrate
  module Field
    class HasMany < Associative
      def resources
        data #.limit(limit)
      end
    end
  end
end
```

**Comment by ericgross** [comment]
👍

**Comment by twist900** [comment]
👍

**Comment by fraz017** [comment]
Hi any suggestions on this issue?

**Comment by carlosramireziii** [comment]
@michaelimstepf I've seen similar questions pop up in #300 and #131. 

The approach that I have used is creating a custom field that inherits from the default field and updating the options as you need in the custom field. You can use the templates of the default field (and avoid having to copy/paste them) by overriding `to_partial_path` in the custom field and pointing it to the parent. 

Something like this

```
class HasManyFieldWithoutLimits < Administrate::Field::HasMany
   def resources
      data
   end

   def to_partial_path
      "/fields/has_many/#{page}"
   end
end
```

Then just be sure to use that new field type when specifying associations in `ATTRIBUTE_TYPES` for the dashboard in question. 

WDYT?

**Comment by michaelimstepf** [comment]
Thanks @carlosramireziii, this looks like a good approach. Would be great to document the ability to override the partials path.
