### ISSUE TITLE
uninitialized constant Administrate::NAMESPACE

### ISSUE THREAD

**Issue by ACPK** [thoughtbot/administrate#413]
The latest update, which I'm using to have access to the sidebar, has a breaking change which causes "uninitialized constant Administrate::NAMESPACE".

The issue is with:       [:new, Administrate::NAMESPACE, page.resource_name],

**Comment by wiegand** [comment]
@ACPK looking at the [`_sidebar` template's diff](https://github.com/thoughtbot/administrate/commit/2aca8bbf1bba8978a8dcb2748208c982e26a50b9#diff-916841b0d3fdb0de4da867c71e7b3ab5L15) cleared this up for me:

```diff
- Administrate::NAMESPACE
+ namespace
```

**Comment by BillyParadise** [comment]
I just upgraded to 0.1.4 and am running into this as well.  app/views/admin/XXX/_collection.html.erb

```
 data-url="<%= polymorphic_path([Administrate::NAMESPACE, resource]) -%>"
```

Changing Administrate::NAMESPACE to namespace seems to resolve the issue.  Problem in the generator?

**Comment by graysonwright** [comment]
@BillyParadise - it looks like one of the views you've generated has fallen behind the main library. Unfortunately, we didn't include the fix for that in the release notes - that's an oversight on my part.

In this case, the breaking change was in https://github.com/thoughtbot/administrate/pull/339. The recommended upgrade path is to change `Administrate::NAMESPACE` to `namespace`. I've added a note to [the release notes for v0.1.3](https://github.com/thoughtbot/administrate/releases/tag/v0.1.3).

**Comment by BillyParadise** [comment]
Again, thanks for looking at this quickly!

**Comment by dizo1** [comment]
i get uninitialized constant admin::viewscontroller what could be the issue, i tried cleaning the code but some how it still persists

**Comment by pablobm** [comment]
@dizo1 - That sounds like you have a model call `View`, for which you have a dashboard listed in the routes, but you don't have a controller at `admin/views_controller`. Could that be it?

**Comment by dizo1** [comment]
It may sound funny but that model got in there without it needing to be there, i tried to delete the routes and anything associated with it but that error persists which means there is a trace of it somewhere i dont seem to know where though i have looked for it.

**Comment by dizo1** [comment]
I deleted the controller and routes realising i didnt need that model and went as far as deleting the model as well

**Comment by dizo1** [comment]
And yes your right there isn't a views controller bcoz i deleted it.Is there somewhere am not looking?

**Comment by pablobm** [comment]
@dizo1 Can you share the following, please?

1. The URL you are visiting (so that I can see what you are trying to do).
2. The error message.
3. The error backtrace.

**Comment by dizo1** [comment]
![Uploading 16894214678811213592316079113733.jpg…]()

**Comment by pablobm** [comment]
@dizo1 - That didn't upload correct :thinking: Can you try again please?

Actually, if instead of a screenshot you could please copy&paste the error, that would be easier to read.
