### ISSUE TITLE
'permitted_attributes' method collides with pundit

### ISSUE THREAD

**Issue by kuboon** [thoughtbot/administrate#417]
if I include Pundit on my Administrate controller, it raises ArgumentError on create / update.

```
class ApplicationController < Administrate::ApplicationController
  include Pundit
  # ...
end
```

The problem is calling `permitted_attributes` actually calls the method in Pundit.
https://github.com/elabs/pundit/blob/master/lib/pundit.rb#L248
What is a better way to avoid this collision rather than monkey-patching on either of gems?

**Comment by lserman** [comment]
I ran into this as well, I ended up just overriding `resource_params` to call `dashboard.permitted_attributes` directly:

```
def resource_params
  params.require(:user).permit(dashboard.permitted_attributes)
end
```

Definitely not ideal. Luckily I only need Pundit on one of my Administrate controllers for now.

**Comment by wenweih** [comment]
👍

**Comment by jasonswett** [comment]
@lserman's solution worked for me.

In case anyone, like me, has trouble connecting the dots, what you need to do is add @lserman's code to `app/controllers/admin/application_controller.rb`.

**Comment by carlosramireziii** [comment]
There's a PR for this #465 that will be in review shortly.

**Comment by jaykilleen** [comment]
Thanks @lserman and @jasonswett I have followed your instructions and now have fixed the Administrate Pundit `wrong number of arguments (given 0, expected 1..2)` error. I have to slightly tweak the code so it referenced resource instead of user so that it worked across all the objects.

```
    def resource_params
      params.require(resource_name).permit(dashboard.permitted_attributes)
    end
```
