### ISSUE TITLE
clicking on resource results in wrong id lookup AR error 

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/administrate#419]
I have a password's resets resource with a id, user_id and a token. Clicking on the individual resource on the dashboard results in the following active record error:
`Couldn't find PasswordReset with 'id'=23932o9sdd`
It's trying to look up the resource by the token? 

I'm thinking about removing this for a custom reset action, bc this could be a security issue, but should still be working.

Auth Gem is Monban by Goose https://github.com/halogenandtoast/monban

**Comment by graysonwright** [comment]
@ChrisCPO sorry for the late response.

Can you try adding this to your `app/controllers/admin/password_resets_controller.rb`?

```ruby
def find_resource(param)
  PasswordReset.find_by!(token: param)
end
```

Your `PasswordReset` model may have `to_param` defined, which would change the way links get generated for that model.

**Comment by carlosramireziii** [comment]
Hi @ChrisCPO! :) 

Were you able to get this working using the steps described above? If so, would you consider this issue resolved? 

Let me know

**Comment by carlosramireziii** [comment]
Closing this as it's been inactive for a while. Please feel free to re-open if you think it's still an issue. Thanks!
