### ISSUE TITLE
Feature request: reading data attributes of a record

### ISSUE THREAD

**Issue by janklimo** [thoughtbot/administrate#421]
Assuming I have an `Event` that `has _many` attendees and a given `capacity`, is there any way I can have a column on the `Event` index page showing spots available? Something like:

    object.capacity - object.attendees.size

**Comment by andrewhamon** [comment]
Does this not work?

```ruby
class Event < ActiveRecord::Base
  # all your associations and whatnot

  def spots_available
    capacity - attendees.count
  end
end
```

```ruby

class EventDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = [
    # your other types here
    spots_available: Field::Number
  ]

  COLLECTION_ATTRIBUTES = [
    # your other collection attributes here
    :spots_available
  ]
end

**Comment by janklimo** [comment]
It most definitely does :+1:  Thanks, Andrew!

**Comment by andrewhamon** [comment]
My pleasure!

**Comment by graysonwright** [comment]
This is the solution I had in mind. If you have a setter method like

```ruby
def name=(value)
  self.first_name = value.split.first
  self.last_name = value.split.last
end
```

then you can use that in your form attributes, as well! woot. :smile:
