### ISSUE TITLE
SimpleForm + Foundation Style Conflict & Question

### ISSUE THREAD

**Issue by JoelBeasley** [thoughtbot/administrate#432]
_Conflict_
By default Simple form for foundation uses .collapse to structure form inputs layout.
In administrate .collapse = display: none.

_Result_
Forms are invisible. 

_Question_
What is the best way to add app specific CSS customization for administrate?

**Comment by graysonwright** [comment]
@JoelBeasley you can customize Administrate's styles by running `rails generate administrate:assets:stylesheets`, and customizing the generated styles. Does that help?

**Comment by JoelBeasley** [comment]
@graysonwright Yes, thank you. Love the project.

**Comment by carlosramireziii** [comment]
@JoelBeasley Glad you were able to get this one working! Since it looks like it's resolved, I'm going to close this issue.
