### ISSUE TITLE
Allow preloading records with `Field::HasMany`

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/administrate#433]
Let's say a User has_many Books.

`Field::HasMany` loads each Book record and calls `display_resource` on each one. If the `Book` dashboard defines `display_resource` to call `book.publisher.name`, N publisher records will be loaded, one for each book.

This can significantly slow down load time.

A possible fix would be to allow passing `includes` options to `Field::HasMany`, like so:

```diff
def candidate_resources
-  associated_class.all
+  includes = options.fetch(:includes, [])
+  associated_class.includes(*includes).all
end
```

Relevant bit of code is [here](https://github.com/thoughtbot/administrate/blob/1024283df83795be459f82aeafd45b982ed1ec6a/lib/administrate/fields/has_many.rb#L50).

**Comment by graysonwright** [comment]
:+1: go for it. :smile:

**Comment by gabebw** [comment]
Closing in favor of a real PR: https://github.com/thoughtbot/administrate/pull/466
