### ISSUE TITLE
Has many field renders (potentially) wrong partial

### ISSUE THREAD

**Issue by keithlayne** [thoughtbot/administrate#440]
If a dashboard has one or more has_many fields, then on that dashboard's show page the `collection` partial will be rendered for each has_many field:

https://github.com/thoughtbot/administrate/blob/master/app/views/fields/has_many/_show.html.erb#L22-L26

The problem has to do with the template lookup path.  Take for example a class `Alpha` that has many `Bravo`s.  On the `Alpha` show page, the `collection` partial will be rendered for each relation:
- If you have overridden the `collection` partial for `Bravo`, it will never be rendered for the `bravos` field.
- If you have overridden the `collection` partial for `Alpha`, it will be used to render the `bravos` collection.

Neither of these seem to be the intended behavior.  It would be easy to create a test exposing this bug.  I have successfully gotten my desired behavior by putting an ugly hack in `app/views/fields/has_many/_show.html.erb`.

It seems likely that similar bugs exist in this project in other places - I can't confirm or deny that right now.  It seems like to really fix this there needs to be support for resolving the correct administrate partial regardless of the view context while respecting template inheritance.

**Comment by graysonwright** [comment]
@keithlayne good catch! The partial lookup code is definitely a bit tricky.

I'm a bit backed up right now, but feel free to take a crack at this.

**Comment by pablobm** [comment]
Closing as associated PR #522 was also closed. Happy to reopen if there's activity.
