### ISSUE TITLE
Should being searchable really be defined in the fieldtype?

### ISSUE THREAD

**Issue by andrewhamon** [thoughtbot/administrate#445]
I tried adding `password` and `password_confirmation` as text fields in my user dashboard so that they can be updated. Things seemed to work great! Then I tried searching, which blew up. 

[In the search class](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/search.rb#l31-l39), it looks like the assumption is made that any searchable field type exists as a database column.

Perhaps it makes more sense for this to be configurable?

For example, my User dashboard could have

``` ruby
SEARCH_ATTRIBUTES = [
  :email
]
```

and the search code might look like:

``` ruby
def search_attributes
  attribute_types.keys.select do |attribute|
    attribute_types[attribute].searchable? && search_attributes.include?(attribute)
  end
end

def attribute_types
  resolver.dashboard_class::ATTRIBUTE_TYPES
end

def search_attributes
    resolver.dashboard_class::SEARCH_ATTRIBUTES
end
```

This may not be worth the trouble though [if searching is going to be overhauled eventually](https://github.com/thoughtbot/administrate/issues/157).

**Comment by thomascullen** [comment]
You should be able to specify searchable in the `with_options` method in your dashboard class.

```ruby
ATTRIBUTE_TYPES = {
    name: Field::String.with_options(searchable: false),
}
```

**Comment by andrewhamon** [comment]
Hi @thomascullen 

It would be nice if it worked that way, [but it seems to be hardcoded rather than based on options](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/fields/string.rb#l6-l8): 

```ruby
module Administrate
  module Field
    class String < Field::Base
      def self.searchable?
        true
      end
      # Truncated here for brevity
    end
  end
end
```

**Comment by andrewhamon** [comment]
But I do agree that `with_options` feels like a better way to configure this than a new array of searchable fields as I initially suggested.

**Comment by thomascullen** [comment]
The [with_options](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/fields/base.rb#L7) method creates a new instance of `Deferred` which allows searchable to be set with options in its [searchable?](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/fields/deferred.rb#L23) method.

Is using `with_options` not working for you?

**Comment by andrewhamon** [comment]
Oh my, I guess I didn't read the source closely enough. 😅 Ill give that a try and report back. Thanks!

**Comment by thomascullen** [comment]
Hah no worries! Glad to help :)

**Comment by carlosramireziii** [comment]
@andrewhamon Just wanted to check in on this. Were you able to get it working as @thomascullen suggested? If so, would you consider this issue resolved? Let me know, thanks!

**Comment by andrewhamon** [comment]
Hey Carlos, it's been a year and I don't even remember what my use case was. I'm gonna assume that I got things working. Let's go ahead and close.

**Comment by carlosramireziii** [comment]
Okay @andrewhamon sounds good. Thanks for getting back to me!
