### ISSUE TITLE
Generated custom page views, but app still tries to use the gem supplied views.

### ISSUE THREAD

**Issue by praveenangyan** [thoughtbot/administrate#452]
I followed the instructions here:
http://administrate-prototype.herokuapp.com/customizing_page_views

However when I run the rails app, the application still uses the gem supplied views. How do I change the app to use my copied views?

**Comment by minimul** [comment]
Most likely it made the directory `app/views/admin/applications` should be just `app/views/admin/application`.
That should be fixed one of these days now https://github.com/thoughtbot/administrate/issues/202
