### ISSUE TITLE
resources is overriden on the index page

### ISSUE THREAD

**Issue by steffenix** [thoughtbot/administrate#455]
Hello,

Trying the last version; I am using a custom request to get the @resources to display. It seems I still get all my database entries.
Tou can try with something like:

``` ruby
module Admin
  class PagesController < Admin::ApplicationController
    def index
      super
      @resources = []
    end
  end
end
```

**Comment by lenart** [comment]
I believe the problem is that super calls render before the `@resources = []`. Currently it's not really possible to easily override resources scope; you'll have to copy over the entire [index action](https://github.com/thoughtbot/administrate/blob/master/app/controllers/administrate/application_controller.rb#L3) and make the necessary changes.

**Comment by joshco** [comment]
+1 critical feature.  Here's how I worked around it based on what @lenart said.  

See attached image content. The brown highlight is where I put a conditional.  If there is an *order* param put in the URL by administrate, then just do the usual order.apply, but if not, then use my own default ordering. (created_at desc)

![image](https://cloud.githubusercontent.com/assets/290314/12935608/0f59315e-cf65-11e5-8a89-52f06ce153fc.png)

> YAAAASSSS RUBYMINE!

**Comment by megetron** [comment]
Maybe you should add a remark regarding this one, I have spent several hours trying to figure this out.

My solution was to copy the definition and overwrite the resources, but this is a temporary solution, as what will happens when you update the gem?

**Comment by carlosramireziii** [comment]
The [explanation and suggestion above](https://github.com/thoughtbot/administrate/issues/455#issuecomment-181756203) is exactly right.
