### ISSUE TITLE
how do I change belongs_to attribute displayed?

### ISSUE THREAD

**Issue by joshco** [thoughtbot/administrate#456]
How can I make a belongs_to show user.name instead of "User #1"
Is there a place where the  with_options() available options are documented?

**Comment by thomascullen** [comment]
You can edit the `display_resouce` method Inside your `UserDashboard` class.
e.g
```ruby
def display_resource(user)
  user.name
end
```

**Comment by joshco** [comment]
Thanks, I guess I should have seen that.  I kept looking on the docs site, but didn't see it.
I created a pull request with a doc update
>  https://github.com/thoughtbot/administrate/pull/457

I foolishly added a wiki page, which you can delete.

**Comment by gabebw** [comment]
Can this issue be closed now?

**Comment by joshco** [comment]
Whats the process here?  Are you going to merge the documentation update, or do you want me to make changes to the pull request?
