### ISSUE TITLE
Custom Fields, make a PR or a Gem

### ISSUE THREAD

**Issue by acrogenesis** [thoughtbot/administrate#468]
Hello,

For a project I'm working on I made a custom field that works with the file uploader gem [refile/refile](https://github.com/refile/refile). I want to share this to the OS community but I'm not sure what's best. To make a PR for it to be merged in administrate or to make a gem.

What should I do?

**Comment by onceatime** [comment]
why not put it into a gem? this way the eco systems grow and keeps the core slim

**Comment by acrogenesis** [comment]
I was thinking the same but I don't know what the owners of this project would prefer :stuck_out_tongue:

**Comment by minimul** [comment]
https://github.com/metova/administrate-refile-attachment_fields

**Comment by acrogenesis** [comment]
@minimul I didn't like that gem field structure... I think i'll make one :+1:

**Comment by graysonwright** [comment]
@acrogenesis and @minimul - I just created a template for packaging fields up into gems - check it out at https://github.com/graysonwright/administrate-field-image.

**Comment by acrogenesis** [comment]
for the record I've published the gem here https://github.com/DisruptiveAngels/administrate-field-refile
