### ISSUE TITLE
Static Pages

### ISSUE THREAD

**Issue by tomgatzgates** [thoughtbot/administrate#470]
Has anyone had any thought to how you might approach static pages (not backed by a model)?

**Comment by onceatime** [comment]
use https://github.com/thoughtbot/high_voltage
its from the same vendor and works perfect!

its also used by administrate: https://github.com/thoughtbot/administrate/blob/cdb1d50b58248e260a7ca9b08a8414968c45c1d8/Gemfile

**Comment by carlosramireziii** [comment]
@tomgatzgates Did @onceatime's suggestion of using High Voltage work for you?

If not, I'd love to learn a little bit more about the use case you had in mind. Could you describe it in more detail. Thanks!

**Comment by nickcharlton** [comment]
I'm going to close this as it's been two months since the last comment. If this is still an issue, please reopen!
