### ISSUE TITLE
Manifest for specific resource ?

### ISSUE THREAD

**Issue by checkraiser** [thoughtbot/administrate#472]
Hi all.

Say, i have an `Account` model, each account resource could have its own Admin to mange its own sub resources.
Imagine the url could be `/accounts/1/admin` 
How could this be done ?

**Comment by utkukaynar** [comment]
Is it possible ?

**Comment by checkraiser** [comment]
@utkukaynar  Yes, just do like this
```
resources :account do 
  # mount :administrate routes here
end
```

**Comment by graysonwright** [comment]
@checkraiser - great idea. Glad you got it working!

You should keep in mind that at the moment, the generators look at the `/admin` namespace to decide which dashboards to generate. It will probably be easiest to generate the dashboards in the default `/admin` namespace, and then modify the routes file afterwards.

In future versions I'd like to have the generators handle any namespace correctly, not just `/admin`.
