### ISSUE TITLE
Gemspec needs to list inline_svg gem as a dependency

### ISSUE THREAD

**Issue by brigneld** [thoughtbot/administrate#479]
On installing administrate 0.1.4, my system crashed with:
`NoMethodError in Admin::Children#index`
`Showing /home/damien/websites/rss_scraper/app/views/admin/children/index.html.erb where line #31 raised:`
`undefined method 'inline_svg' for #<#<Class:0x007f53606b81a8>:0x007f53606bdf68>`
`Extracted source (around line #31):`
 ` <form class="search">`
`    <span class="search__icon">`
`      <%= inline_svg "administrate/search.svg" %>`
`    </span>`
`    <input type="text"
`

Solution in https://gist.github.com/adamjmurray/463731 didn't work, but installing gem fixed the problem.

**Comment by graysonwright** [comment]
@brigneld, we removed `inline_svg` as a dependency in #365.

It looks like you have a generated view that still uses the `inline_svg` tag - you should be able to replace that with our custom helper, `svg_tag`.

To re-set your custom view to Administrate's new default, you can re-run:

```
rails generate administrate:views:index child
```

Let me know if that works - feel free to close the issue if it does.

**Comment by brigneld** [comment]
closed
