### ISSUE TITLE
Custom controller is assumed to have a related model

### ISSUE THREAD

**Issue by naps62** [thoughtbot/administrate#481]
I want to have an admin dashboard where I show some useful data. This is not necessarily tied to a single resource model

My first attempt was to create a `Admin::OverviewController` with an `index` action.
However, the sidebar calls `Administrate::Namespace.new(namespace).resources`, which, I eventually discovered, is computed by listing all controllers for which administrate has routes. So it would end up looking for an Overview model

I generated the sidebar template, and monkey patched it with this:

`(Administrate::Namespace.new(namespace).resources - [:overview]).each`
to explicitly remove the overview from the list of resources. This is ugly as hell though

Is there currently a better solution for this?

**Comment by sebbean** [comment]
I'm having this issue as well. commented on the commit: https://github.com/thoughtbot/administrate/commit/765d3ff0b1377fb6465df0251049b4ffff0d2965

**Comment by graysonwright** [comment]
@naps62, you're right - there should be a better way to define custom routes.

Would it make sense to add a helper method to the routes file? Something like `administrate_resources :customers`? Administrate could look for only those routes, and ignore any normal routes. It would be backwards-incompatible, though.

Any suggestions welcome.

**Comment by naps62** [comment]
@graysonwright maybe I misunderstood your sugestion, but I actually think the routes are perfect as they are right now, and they're not the issue here

The thing that caught me off guard was that `administrate` assumes that, for every controller under the `Admin` namespace, I'll have a corresponding ActiveRecord model

I tried several ways to add an `Admin::OverviewController`. My original goal was to have an extra "Overview" link in the navbar, which would show me a page (using the same administrate layout), where I could show whatever I want
But `Administrate::Namespace` looks for everything under `admin`, assumes I have a model for it, a dashboard for it, and then other stuff assumes the model is an ActiveRecord one.

So, the way I see it, a possible solution would be to make `Namespace` aware of what resources I actually want him to use.
This information is already present in `DashboardManifest::DASHBOARDS`, although I'm not sure about using that, since that belongs to the app, and is not in the gem itself. But I feel that `Namespace` is trying to compute information that's already present in that constant, but it ends up finding too much

**Comment by graysonwright** [comment]
Hm... I'm not sure if I understand.

I opened up https://github.com/thoughtbot/administrate/pull/514, with a potential solution to your problem. Can you tell me if that would work for you, or if you had something else in mind?

**Comment by naps62** [comment]
@graysonwright nevermind. I was talking based on my knowledge which was from an older version of the gem. Apparently the current one does not generate routes in the same way (I was testing on an older project)

**Comment by naps62** [comment]
I tested your branch, and it solves this problem (partially, I think)
One other thing I'd like to do is use the same layout for my other admin pages (so that the whole admin part looks consistent

Is that possible right now? I'm having a few problems attempting to do so

PS: I realize this is a completely different problem, although it's part of why I originally created the issue, so I can open a new issue for this if you feel it's better

**Comment by G-Rath** [comment]
I'm in this situation currently, but I'm finding that `(Administrate::Namespace.new(namespace).resources - [:publish]).each` doesn't work :/

Given what administrate is trying to do, I think it makes perfect sense to have some way to have routes ignored. Any chance for progress on this one?

**Comment by justmendes** [comment]
Hey @G-Rath , @naps62 

Can you take a lot at #1298 and see if it works for your use cases?

**Comment by nickcharlton** [comment]
Closing as #1579 (née #1298) was merged a while ago and should solve this.
