### ISSUE TITLE
List parameters on "Customizing attribute partials" docs page

### ISSUE THREAD

**Issue by djsegal** [thoughtbot/administrate#486]
[The docs](http://administrate-prototype.herokuapp.com/adding_custom_field_types) refer to custom field type partials, but they don't list them out.

Also, the command `rails generate administrate:views:field` without any parameters errors out. Maybe it should generate all the defined custom fields, which are:

---
- belongs_to
- boolean
- date_time
- email
- has_many
- has_one
- image
- number
- polymorphic
- string
- text

**Comment by graysonwright** [comment]
@djsegal, thanks! It may take me a while to get to this - feel free to open a pull request if you'd like to speed it up. All of the documentation lives in the `/docs` folder.

Otherwise, I'll take a look when my schedule frees up, after March 7.

**Comment by djsegal** [comment]
@graysonwright, just following up. are you still able to do this?

**Comment by thecalliopecrashed** [comment]
Seems related to #1108?

**Comment by nickcharlton** [comment]
Closing as we merged #992.
