### ISSUE TITLE
Broken custom fields and no 0.1.4 release documentation

### ISSUE THREAD

**Issue by alvaroemmanuel** [thoughtbot/administrate#489]
Hello!

I've been using Administrate for my latest project and I think it's awesome, even for it's early stages :)

That being said, I've found out that custom fields have been broken in the change from 0.1.3 to 0.1.4 and worst thing is there's no tag or release in github with the changelog for this version, so it took me a little bit to find out what was wrong in my app.

Fortunately it was solved by changing the line `require "administrate/fields/base"` to `require "administrate/field/base"`, because it seems that administrate 'fields' is now in singular.

Anyway, I think the release changelog should be written and, considering this is a backwards breaking change, maybe the version number should also be updated accordingly.

**Comment by graysonwright** [comment]
@alvaroemmanuel thanks for pointing this out! I'm really sorry we didn't have better documentation around 0.1.4.

I just published a release for the new version, along with release notes that identify your fix. For future releases, I'll make sure to streamline the process to get the release notes out as quickly as possible.

As for the version number, we're going to be using [Semantic versioning](http://semver.org/), starting once we hit version 1.0.0. Until then, the library is a bit in flux, and small breaking changes might occur. Let me know if there's a better way to make people aware of the breaking changes.

Thanks!

**Comment by graysonwright** [comment]
Oops - here's the link to the new release notes: https://github.com/thoughtbot/administrate/releases/tag/v0.1.4

**Comment by alvaroemmanuel** [comment]
Hi @graysonwright, thanks for the fast response!

I agree with you and understand that right now the library is under heavy development and sometimes changes will gonna break previous releases, but I believe it will be in order to improve it, so I think that till it reaches version 1.0.0, to keep the changelog up to date will suffice :)
