### ISSUE TITLE
Lost custom fields alignment on edit form after 0.1.3 update

### ISSUE THREAD

**Issue by alvaroemmanuel** [thoughtbot/administrate#490]
Hi,

I have a custom field in my app.

Previous to 0.1.3 update (i.e., with 0.1.2), the update form was showing like this:

![screen shot 2016-02-28 at 2 57 24 pm](https://cloud.githubusercontent.com/assets/126522/13382498/9bbc8620-de3b-11e5-8868-efa8d9cba362.png)

As you can see, all the field labels were correctly aligned and with a nice grey font style.

However, after 0.1.3 update (and also with 0.1.4), it now shows like this:

![screen shot 2016-02-28 at 2 56 07 pm](https://cloud.githubusercontent.com/assets/126522/13382508/c97b90ce-de3b-11e5-915d-1e60fd85578b.png)

Notice how all the fields are still aligned except for "Front cover" and "Back cover", which are my custom fields, that are now pulled all the way to the left.

Also notice how the "Update" button is pushed all the way down to the edge of the page and finally all the font styles (for the field's labels, the fields themselves and also the sidebar) seems to be gone.

**Comment by graysonwright** [comment]
@tysongach - are you able to take a look at this? Thanks!

**Comment by tysongach** [comment]
Hi @alvaroemmanuel! We majorly refactored the CSS in `0.1.3`. The relevant PR for these form changes can be found here: https://github.com/thoughtbot/administrate/pull/399

We now have a nice structure that we use for every form field, which looks like this:

```html
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.text_field field.attribute %>
</div>
```

Wrapping your custom field elements in these classes should resolve your layout issues.

**Comment by graysonwright** [comment]
@alvaroemmanuel - if that works, feel free to close this issue.

**Comment by alvaroemmanuel** [comment]
Thanks!

That resolved the alignment issue, however I think div containing "Update" button should have a margin-button set, just like pretty much all the other divs in the form, so it does not "touch" the edge of the screen in smaller resolutions. I think it is how it was working before.

Is there another PR or reason as to why this was changed?

Thanks again!

**Comment by tysongach** [comment]
@alvaroemmanuel Yeah, we need to fix the spacing below that button; it’s an artifact from all the style changes.

**Comment by tysongach** [comment]
@alvaroemmanuel FYI: I’ve put up a PR to resolved those form buttons butting up against the bottom viewport edge » https://github.com/thoughtbot/administrate/pull/519

**Comment by alvaroemmanuel** [comment]
Thanks @tysongach, sounds great!
