### ISSUE TITLE
Editing devise users requires password field to be filled in

### ISSUE THREAD

**Issue by chriscapetown** [thoughtbot/administrate#495]
Hi,

I'm looking for some advice on how to handle this situation.

I have my Devise users model loaded into Administrate, and I need to be able to edit user information without needing to change/fill their passwords.

The validation at the moment throws:

```
1 error prohibited this user from being saved:
Password can't be blank
```

Any ideas how I can overcome this?

**Comment by OddEssay** [comment]
I got around this by removing the fields from the `FORM_ATTRIBUTES` array in `app/dashboards/user_dashboard.rb` and then we add the users using Devise Invitable if needed from the admin side of things.

**Comment by sivicencio** [comment]
@chriscapetown This is not an Administrate issue. It can be solved overriding the `create` action in your users controller, as [Devise state](https://github.com/plataformatec/devise/wiki/How-To:-Manage-users-through-a-CRUD-interface):

```ruby
def update
  if params[:user][:password].blank?
    params[:user].delete(:password)
    params[:user].delete(:password_confirmation)
  end
  if requested_resource.update(resource_params)
    redirect_to(
      [namespace, requested_resource],
      notice: translate_with_resource("update.success"),
    )
  else
    render :edit, locals: {
      page: Administrate::Page::Form.new(dashboard, requested_resource),
    }
  end
end
```

Hope it helps.

**Comment by rmcsharry** [comment]
There are some 'same but different' ;) solutions to this problem here:
http://stackoverflow.com/questions/7083575/updating-user-attributes-without-requiring-password

**Comment by michelegera** [comment]
@sivicencio’s solution can be further simplified if we remember that our `UsersController` inherits from `Administrate::ApplicationController`: we get rid of the blank `password` values, and call `super`.

```ruby
def update
  if params[:user][:password].blank?
    params[:user].delete(:password)
    params[:user].delete(:password_confirmation)
  end
  super
end
```

**Comment by carlosramireziii** [comment]
Hey @chriscapetown! Did any of the solutions above help solve your issue?

**Comment by chriscapetown** [comment]
@carlosramireziii yeah the suggestion from @michelegera solved it.

**Comment by IJustDev** [comment]
Thank you very much for sharing. I think a lot of Rails projects utilize Devise for their authentication.

This code snippet should be documented in the Readme or at least be mentioned in some side note.

> @sivicencio’s solution can be further simplified if we remember that our `UsersController` inherits from `Administrate::ApplicationController`: we get rid of the blank `password` values, and call `super`.
> 
> ```ruby
> def update
>   if params[:user][:password].blank?
>     params[:user].delete(:password)
>     params[:user].delete(:password_confirmation)
>   end
>   super
> end
> ```

**Comment by pablobm** [comment]
@IJustDev - That's a good point. I have added it to the list of things to document at https://github.com/thoughtbot/administrate/issues/1778
