### ISSUE TITLE
newbie administrate questions

### ISSUE THREAD

**Issue by megetron** [thoughtbot/administrate#498]
Hi There, 
This one a nice project which I would love to test and evaluate. 

- Do you have a scheduled till you get a stable release?
- After install the last version I couldn't find the Manifest dashboard file. not sure why.
- I would like to add my own design to the main admin application page. how can you do so?
- and how do you add a new empty dashboard where I could add my own graphs and widgets?

**Comment by Davidzhu001** [comment]
I think this question cover so much. 
Have you read the docs?
And have you go through the code?

**Comment by fwolfst** [comment]
- Wrt "Manifest Dashboard", this got me confused for a second too. The *_dashboard.rb files are meant.
- About design: I guess you have to run the tasks that install the various views and start fiddling there.

**Comment by megetron** [comment]
thanks
