### ISSUE TITLE
Undefined method 'camelize' for nil:NilClass

### ISSUE THREAD

**Issue by coisnepe** [thoughtbot/administrate#502]
Hey,

I tried adding administrate to my project but I kept getting this error. Just to make sure it wasn't because of the project, I started a fresh new app, only added administrate to the Gemfile, bundled and ran `rails generate administrate:install`, to no avail: keep getting the same error.

```
rails generate administrate:install
Running via Spring preloader in process 30057
       route  namespace :admin do

    root to: "#index"
  end
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/_dashboard.rb
/Users/.../.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/generators/named_base.rb:102:in `block in class_name': undefined method `camelize' for nil:NilClass (NoMethodError)
    from /Users/.../.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/generators/named_base.rb:102:in `map!'
    from /Users/.../.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.5.2/lib/rails/generators/named_base.rb:102:in `class_name'
    from (erb):3:in `template'
```

Edit: I had installed administrate in another project earlier that day without running into any issues. Not sure what happened in between... I tried `gem uninstall administrate`, created a new app, added `gem "administrate", "~> 0.1.4"`, bundled etc, but no luck...

Edit2: Tried bundling with Ruby 2.3 / 2.2.4 / 2.2.3 and Rails 4.2.5 / 4.2.5.2 (every possible combination) , still no luck

**Comment by eirvandelden** [comment]
+1 I have the exact same issue for a fresh application

**Comment by Amandeepsinghghai** [comment]
+1 have the same issue here as well

**Comment by neves** [comment]
+1 same here

**Comment by neves** [comment]
The problem happens when it tries to install without any model.
It generates the follow route:
```ruby
Rails.application.routes.draw do
  namespace :admin do

    root to: "#index"
  end
end
```

The correct behaviour would be to alert the missing model.
But a quick fix is to replace this line with this code:
`~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/administrate-0.1.4/lib/generators/administrate/install/install_generator.rb:34`

```ruby
dashboard_resources.map(&:to_s).reject(&:empty?).map(&:singularize)
```

**Comment by coisnepe** [comment]
Well @neves I'll be damned. I did suspect that it had something to do with missing models/controllers, so I tried again this evening... Bundle, quick scaffold, db create/migrate, administrate:install... lo and behold, it worked!
I should have pushed my investigation a little further. Not a big fan of changing gems' source code though... Maybe someone over at Thoughtbot ( @graysonwright ?) will notify the issue and fix it, but in the meantime I'll try to look into it and submit a PR.
Thanks for your input though!

**Comment by Amandeepsinghghai** [comment]
@neves Thanks for the info. I thought this might be the issue when i added a model and tried again. 

BTW.. What would you people recommend using as an admin panel for a CMS.. active-admin or administrate?

**Comment by coisnepe** [comment]
@Amandeepsinghghai from my short experience with admin panels, I think the closest to administrate is [rails-admin](https://github.com/sferik/rails_admin). Similarly to administrate, a mere `rails g rails_admin:install` will set pretty much everything up -literally and figuratively- so you can end up with a lot of things you don't need. Meanwhile, you can tailor made active-admin to your exact needs: only display certain models, some or all of their attributes, make them editable or not, etc. But it takes a lot of work. I should also point out, as thoughtbot has done in administrate's readme, that both have their DSLs (Domain Specific Language), meaning that you might have to go through a lot of documentation and googling.

**Comment by nguyen7thai** [comment]
This problem is because of `root to: "#index"`, it will generate an empty string when replacing the namespace.
@neves: Your solution cannot work, because the element we want to remove is a symbol `:""` not an empty string, so we cannot reject it by checking empty?

My issue with PR for this: https://github.com/thoughtbot/administrate/issues/516

**Comment by grammakov** [comment]
You can sidestep this error by generating any model and running a generator again.

**Comment by glaucocustodio** [comment]
It's still happening on 0.3.0, steps to reproduce:

```
$ rails -v
# Rails 5.0.1

$ rails new foo
$ echo 'gem "administrate"' >> Gemfile
$ bundle
$ rails generate administrate:install
# .rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/generators/named_base.rb:106:in `map!': undefined method `camelize' for nil:NilClass (NoMethodError)
```

Ps: brand new rails app, there is any model.

cc @nickcharlton.

**Comment by thomas-profitt** [comment]
I was experiencing this problem, on Rails 5.0.1 and Ruby 2.4.0, as well.

I had no models. I ran `administrate:install`. It edited _config/routes.rb_, but then hit the error.

I generated a model, and ran the generator again. The same thing happened.

I removed administrate's boilerplate `namespace :admin` block from _config/routes.rb_, then ran the generator again, and everything worked.
