### ISSUE TITLE
README should point to the documentation (guides) in repository, not only online

### ISSUE THREAD

**Issue by fwolfst** [thoughtbot/administrate#503]
The README links to documentation at the heroku app, but does not mention that the guides are available as markdown files("offline") in the repository itself.

**Comment by carlosramireziii** [comment]
Thanks for the feedback @fwolfst!

I think the intention was that the hosted application would be the best place to view the documentation. Do you feel that the markdown files are more useful than the rendered version? Should we make the link to them in the README more conspicuous perhaps? Would love to hear your thoughts

cc @nickcharlton

**Comment by fwolfst** [comment]
@nickcharlton @carlosramireziii Great you guys dig this out. I think my want to advertise my PR as is - I am always happy if a gem and/or a git repository ships its own documentation (in contrast to hosted wiki, etc.pp). Reasons are manifold:

- I might want to check out documentation for the version AT HAND, not for the most up-to-date version (or vice versa)
- I might be working on the supersecret project where I am not allowed to access the internet (you guys know, this happens nearly on a daily basis)
- Due to other reasons I might not have internet access at the time I need the documentation (in contrast to the previous situation this never happens)
- The project might have gone belly-up, has a maintenance window that coincidentally is my working window, etc.pp.

Like, **right now at the time of writing** the link to administrate guides is basically dead: http://administrate-docs.herokuapp.com/ is down...

And I dont object - a rendered online version might in cases be the best presentation and the most useful installation. But right now every user might be superhappy to know that the guides that she (maybe, didnt check) read online yesterday and are gone today are actually installed locally, too.

Rethinking this, I'd also prefer if the README has an own "##Documentation" section, with link to the guide on the heroku app and a mention on the locally shipped ones

**Comment by nickcharlton** [comment]
I completely agree with all of this. We should do something like your referenced commit that points out it's available in both places.

@fwolfst Could you open this as a PR, instead of just an issue?

The link should be to: https://administrate-prototype.herokuapp.com. The root of the demo gives us the docs.

**Comment by fwolfst** [comment]
I didnt realize it was this issues's birthday yesterday! :)  Happy birthday, issue #503 ! :) Btw, the PR is #504 but I will rebase and re-PR.

**Comment by fwolfst** [comment]
Now, when this is merged, there is still a hotly debatable question open: Should the docs be included in the gem? Currently they are not (of course the ri/rdoc can be generated, but the guides live just in the git repository). My oppinion on this is: yes, docs should ship with the gem (basically same reasons as above), but I would leave that decision to the maintainer. I am happy to create an issue and PR for it (single line change in `*gemspec`).

**Comment by nickcharlton** [comment]
I agree that we should include the docs in the gem.

Do you think it's a problem that our current docs are in markdown, rather than `rdoc`?

**Comment by nickcharlton** [comment]
Closing as we solved this with the two referenced PRs.
