### ISSUE TITLE
No Search Bar

### ISSUE THREAD

**Issue by sayshay** [thoughtbot/administrate#526]
After Installing there is no search bar on the top.
Also filtering doesn't work when I click field names. 
Is it something I should customize?

**Comment by carlosramireziii** [comment]
Hey @sayshay! Just following up on this...

The search bar dynamically appears when fields are marked as `searchable`. The fields which are searchable by default are `Field::Select` and `Field::String`. Does your dashboard have any of those kinds of fields?

**Comment by carlosramireziii** [comment]
I'm closing this for now, but feel free to re-open if you think it's still an issue. Thanks!
