### ISSUE TITLE
gems/administrate-0.1.4/app/views/administrate/application/index.html.erb where line #31 raised:

### ISSUE THREAD

**Issue by S-COULIBALY** [thoughtbot/administrate#528]
Hi! friends
I need help, i can't get access to Administrate 0.1.4 views.
I have got this following error
i have also tried  the <ineline_svg and SVG> that someone have gave as solution, it doesn't run for me.
So need your help.

Administrate/application/index.html.erb within layouts/administrate/application (6136.4ms)
Completed 500 Internal Server Error in 7802ms (ActiveRecord: 0.0ms)

**ActionView::Template::Error (TypeError: Cet objet ne gère pas cette propriété ou cette méthode):
    28: <% content_for(:search) do %>
    29:   <form class="search">
    30:     <span class="search__icon">
    31:       <%= svg_tag "administrate/search.svg", "search", width: 16, height: 16 %>
    32:     </span>
    33:     <input
    34:       type="text"**
  execjs (2.6.0) lib/execjs/external_runtime.rb:39:in `exec'
  execjs (2.6.0) lib/execjs/external_runtime.rb:21:in`eval'
  execjs (2.6.0) lib/execjs/external_runtime.rb:46:in `call'
  coffee-script (2.4.1) lib/coffee_script.rb:78:in`compile'
  sprockets (3.5.2) lib/sprockets/coffee_script_processor.rb:21:in `block in call'
  sprockets (3.5.2) lib/sprockets/cache.rb:85:in`fetch'
  sprockets (3.5.2) lib/sprockets/coffee_script_processor.rb:20:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in`call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in`reverse_each'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in`load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in`fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in`block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (3.5.2) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.5.2) lib/sprockets/utils.rb:183:in`dfs'
  sprockets (3.5.2) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:75:in`call_processor'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in`reverse_each'
  sprockets (3.5.2) lib/sprockets/processor_utils.rb:56:in `call_processors'
  sprockets (3.5.2) lib/sprockets/loader.rb:134:in`load_from_unloaded'
  sprockets (3.5.2) lib/sprockets/loader.rb:60:in `block in load'
  sprockets (3.5.2) lib/sprockets/loader.rb:318:in`fetch_asset_from_dependency_cache'
  sprockets (3.5.2) lib/sprockets/loader.rb:44:in `load'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:20:in`block in initialize'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in `yield'
  sprockets (3.5.2) lib/sprockets/cached_environment.rb:47:in`load'
  sprockets (3.5.2) lib/sprockets/base.rb:66:in `find_asset'
  sprockets (3.5.2) lib/sprockets/base.rb:73:in`find_all_linked_assets'
  sprockets (3.5.2) lib/sprockets/manifest.rb:142:in `block in find'
  sprockets (3.5.2) lib/sprockets/legacy.rb:114:in`block (2 levels) in logical_paths'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:225:in `block in stat_tree'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:209:in`block in stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:206:in `each'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:206:in`stat_directory'
  sprockets (3.5.2) lib/sprockets/path_utils.rb:224:in `stat_tree'
  sprockets (3.5.2) lib/sprockets/legacy.rb:105:in`each'
  sprockets (3.5.2) lib/sprockets/legacy.rb:105:in `block in logical_paths'
  sprockets (3.5.2) lib/sprockets/legacy.rb:104:in`each'
  sprockets (3.5.2) lib/sprockets/legacy.rb:104:in `logical_paths'
  sprockets (3.5.2) lib/sprockets/manifest.rb:140:in`find'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `each'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in`map'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `precompiled_assets'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:34:in`asset_precompiled?'
  sprockets-rails (3.0.4) lib/sprockets/railtie.rb:214:in `block (3 levels) in <class:Railtie>'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345:in`call'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345:in `precompiled?'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:349:in`raise_unless_precompiled_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:323:in `digest_path'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:311:in`asset_path'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:89:in `block in resolve_asset_path'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:229:in`block in resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `each'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in`detect'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `resolve_asset'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:88:in`resolve_asset_path'
  sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:78:in `compute_asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:135:in`asset_path'
  actionview (4.2.5.1) lib/action_view/helpers/asset_url_helper.rb:162:in `asset_url'
  administrate (0.1.4) app/helpers/administrate/application_helper.rb:22:in`svg_tag'
  administrate (0.1.4) app/views/administrate/application/index.html.erb:31:in `block in _____uby___x___lib_ruby_gems_______gems_administrate_______app_views_administrate_application_index_html_erb___1799828248_68045540'
  actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in`block in capture'
  actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:38:in`capture'
  actionview (4.2.5.1) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
  administrate (0.1.4) app/views/administrate/application/index.html.erb:28:in`_____uby___x___lib_ruby_gems_______gems_administrate_______app_views_administrate_application_index_html_erb___1799828248_68045540'
  actionview (4.2.5.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:166:in`instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.5.1) lib/action_view/template.rb:143:in`render'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in`block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.5.1) lib/action_view/renderer/abstract_renderer.rb:39:in`instrument'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:61:in`render_with_layout'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/template_renderer.rb:14:in`render'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.5.1) lib/action_view/renderer/renderer.rb:23:in`render'
  actionview (4.2.5.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.5.1) lib/action_controller/metal/streaming.rb:217:in`_render_template'
  actionview (4.2.5.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:32:in`render_to_body'
  actionpack (4.2.5.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.5.1) lib/abstract_controller/rendering.rb:25:in`render'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in`block (2 levels) in render'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  C:/Ruby22-x64/lib/ruby/2.2.0/benchmark.rb:303:in`realtime'
  activesupport (4.2.5.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:44:in`block in render'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:25:in`cleanup_view_runtime'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  administrate (0.1.4) app/controllers/administrate/application_controller.rb:10:in`index'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in`process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in`block in process_action'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in`call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in`call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in`__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in`block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in`instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in`process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in`process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in`dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in`block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in`dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in`block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in`serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in`call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in`call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in`call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in`call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in`call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in`call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in`**run_callbacks**'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in`call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in`catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in`call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in`call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in`call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in`service'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/httpserver.rb:94:in`run'
  C:/Ruby22-x64/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (16.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb within rescues/layout (1435.5ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_markup.html.erb (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (1.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/console.js.erb within layouts/javascript (1143.3ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/main.js.erb within layouts/javascript (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.0ms)
  Rendered C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/web-console-2.3.0/lib/web_console/templates/index.html.erb (2665.4ms)

**Comment by cooltk** [comment]
+1

**Comment by cooltk** [comment]
Problem solved installing gem 'coffee-script-source'

In gem file :
`gem 'coffee-script-source', '1.8.0'`

and after bundle install

**Comment by carlosramireziii** [comment]
@S-COULIBALY Does the solution provided above by @cooltk work for you? If so, would you deem this issue as resolved?

**Comment by carlosramireziii** [comment]
I'm going to close this for now, but if the issue appears again please feel free to re-open.
