### ISSUE TITLE
Nested edit forms

### ISSUE THREAD

**Issue by amtamayo** [thoughtbot/administrate#529]
Is it possible to customize a dashboard to also edit a child record?  I want to create an edit for for orders for a customer where the edit fields for the customer's name is in the order edit form.  I know I can generate views but is this something I can configure in the Dashboard class for Orders?

**Comment by graysonwright** [comment]
@amtamayo good idea! Right now the best approach is in #192 - We're taking a look at pulling that in as an officially supported feature.

**Comment by graysonwright** [comment]
Also, this seems like a duplicate of #192 - I'll close this so we can keep the conversation in that thread. Thanks!

**Comment by amtamayo** [comment]
Thanks, I'll try the approach in #192
