### ISSUE TITLE
HasMany edit fields no longer working after upgrading from 0.1.2

### ISSUE THREAD

**Issue by michaelimstepf** [thoughtbot/administrate#531]
I've upgraded from 0.1.2 and have changed both the routes and `require "administrate/field/base"` on custom fields. HasMany fields are no longer a selectize field, making it very hard to select values from a long list.

``` ruby
require "administrate/base_dashboard"

class OrganizationDashboard < Administrate::BaseDashboard
  ATTRIBUTE_TYPES = {
    locations: Field::HasMany
  }

  FORM_ATTRIBUTES = [
    :locations
  ]
end
```

<img width="556" alt="screen shot 2016-03-28 at 3 37 04 pm" src="https://cloud.githubusercontent.com/assets/430682/14071170/ca01bfbe-f4fc-11e5-9aa9-5e517324d611.png">

**Comment by carlosramireziii** [comment]
Hey @michaelimstepf! Just wanted to follow up on this one...

Is this still an issue with the latest version? If so, what kind of behavior would you like to see here? 

Let us know! Thanks

**Comment by michaelimstepf** [comment]
Hey @carlosramireziii I'm not sure, I haven't used the gem for a year. I can post here if I use it again and let you know.

**Comment by carlosramireziii** [comment]
Ok sounds good @michaelimstepf. Thanks for getting back to me! I'll close this for now. Cheers!
