### ISSUE TITLE
Enum fields

### ISSUE THREAD

**Issue by hauleth** [thoughtbot/administrate#533]
It would be really useful to have some way to entry values for `has_entry`.

**Comment by stevenpetryk** [comment]
This took about 3 minutes. Didn't even have to change the generated class.

```
rails g administrate:field enum
```

_form.html.erb
```erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.select field.attribute, Wireframe.orientations.keys.map { |v| [v.titleize, v] } %>
</div>
```

(_show/_index).html.erb
```erb
<%= field.to_s.titleize %>
```

**Comment by carlosramireziii** [comment]
@hauleth Does the custom field that @stevenpetryk illustrated above work for your needs? If so, would you or he like to take a stab at creating it as a plugin? 

Here's an example: 
https://github.com/thoughtbot/administrate-field-image

**Comment by brndn4** [comment]
Worked for me. You might want to change EnumField#to_s to
```
def to_s
  data.to_s
end
```
In case the enum data is nil

**Comment by carsonbland** [comment]
@stevenpetryk what is the benefit over Field::Select.with_options(collection: Model::ENUM) ?

**Comment by stevenpetryk** [comment]
@carsonbland I'm not sure – it may very well be the case that that was undocumented/impossible back when I posted that response. If that works, then go for it!

**Comment by BenMorganIO** [comment]
Closing this, since a custom enum field with `bin/rails g administrate:field enum` solves the issue.

**Comment by fercreek** [comment]
@stevenpetryk great solution! Thanks!!

**Comment by joallard** [comment]
@BenMorganIO Sounds like this should be part of core
