### ISSUE TITLE
Quick question about combining Administrate and Devise. 

### ISSUE THREAD

**Issue by mattgaudio** [thoughtbot/administrate#534]
I keep getting errors every time i try to update a resource such as a user or article because it's trying to update every single value instead of just the one i changed. returning this error. PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_users_on_reset_password_token".

So simply every time I submit an update on a resource in Devise Model, it returns an error because it is trying to update every field instead of the one field I am attempting to change. Is this a simple solution possibly.

**Comment by geoffharcourt** [comment]
Hi @mattgaudio, can you confirm some details about the workflow that produces the exception? Are you in a Users dashboard, editing a single record, and then the save produces this exception? You're not editing the password token, but some other field?

**Comment by rob-murray** [comment]
Sounds like you're trying to update all the fields and probably setting an empty string in the the `reset_password_token` field.

If it helps, I remove most Devise model attributes from the form leaving only email and the "virtual attribute" password attributes. I see no reason to edit the attributes such as `reset_password_token`, `current_sign_in_ip`, etc

**Comment by geoffharcourt** [comment]
@rob-murray that makes a ton of sense.

**Comment by mattgaudio** [comment]
Yea I commented out the fields that were causing conflicts and was able to update the resources without a problem. However is there a solution to leave the fields but simply not have them update unless changed?

**Comment by geoffharcourt** [comment]
@mattgaudio not at the moment. I've handled this for user fields by creating a custom view just for password updates and separating everything that's not credentials into the default show/edit view.
