### ISSUE TITLE
Hide resources in sidebar | Pagination in ::HasMany

### ISSUE THREAD

**Issue by LePhil** [thoughtbot/administrate#536]
Is it possible to customize which resources are being shown in the sidebar? We have some assignment groups (many-to-many relation) which should not be accessible through the sidebar.

Also, there is an automatic limit on "sub-views" (HasMany-Fields), with "Showing X out of Y" - how would one disable/override that to show all related entries, or even better, offer pagination there as well as in the main (index) views?

**Comment by OddEssay** [comment]
You can generate a customizable version of the sidebar with the undocumented `administrate:views:sidebar` and modify that however you wish.

Depending on how you modify it, you might need to in future manually add new resources, but it'd be a solid starting point.

**Comment by LePhil** [comment]
Immediately after posting we found the generator you mentioned :smiley: 

Any ideas on the Pagination in :HasMany?

**Comment by LePhil** [comment]
Adding an example screenshot:
![Example](https://cloud.githubusercontent.com/assets/1488366/14427315/6830e398-fff4-11e5-9f81-bacac8385a41.png)

It's nice to see how many are being displayed out of how many total, but it would be even nicer if the pagination would work here too. I created a custom field for that (HasManyPaginated) but I can't seem to figure out how to work the pagination via Kaminari out.

**Comment by Xosmond** [comment]
That would be good to make a limit number of items showing, also there would be good to select what attributes should be show it there (parent view) and what attributes should be show it on the general view (model view). But that will break a lot of things.

**Comment by micapam** [comment]
I know this is not my repo so it's not exactly my business, but would be handy to keep issues in separate threads rather than combining ;)

**Comment by jasonswett** [comment]
You can hide resources by modifying your route configuration. For example, let's say your route file looks like this:

```ruby
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :authors
    resources :authors_books
    resources :books
    resources :books_tags
    resources :tags

    root to: "users#index"
  end

  resources :tags
  devise_for :users
  resources :authors
  resources :books
  root "books#index"
end
```

And let's say you want to remove `authors_books` and `books_tags` from your sidebar. You can simply remove those resources from the `:admin` namespace like this:

```ruby
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :authors
    resources :books
    resources :tags

    root to: "users#index"
  end

  resources :tags
  devise_for :users
  resources :authors
  resources :books
  root "books#index"
end
```

And those items will disappear from the sidebar.

**Comment by ArslanShakoor** [comment]
@jasonswett  no your method would throw any error?

**Comment by JoseMPena** [comment]
@jasonswett I don't recommend doing so as any dependent model would trigger errors.

**Comment by gabriel-cardoso** [comment]
Use `rails generate administrate:views:navigation` in latest versions
