### ISSUE TITLE
javascript should be decleared at the beginning of body

### ISSUE THREAD

**Issue by karlosmid** [thoughtbot/administrate#539]
Javascripts should be declared at the beginning of body, so code could be referenced in the html as needed.
Otherwise `ReferenceError` is thrown.

Code on line:
https://github.com/thoughtbot/administrate/blob/master/app/views/layouts/administrate/application.html.erb#L42

should be moved to line 27

**Comment by JIAZHEN** [comment]
By looking at [the source codes](https://github.com/thoughtbot/administrate/blob/master/lib/generators/administrate/views/layout_generator.rb) I find that you can customise the layout.
```
rails generate administrate:views:layout
```

**Comment by karlosmid** [comment]
Yes,
but generator should put javascript declaration at the beginning of body, not the end.

**Comment by JIAZHEN** [comment]
There probably a reason for that, am I correct @graysonwright ? If not yeah, JS renders at the top would be great.

**Comment by carlosramireziii** [comment]
JavaScript at the end of the body is pretty common I believe, although I understand your issue with being able to reference in the HTML.

The question is if we want to follow the common convention of having JS at the end of the body or change it. 

@nickcharlton Any thoughts?

**Comment by nickcharlton** [comment]
The usual reason for including JavaScript at the bottom of the page is to avoid blocking rendering if things aren't required by the page.

I feel like the right answer here is to split our JavaScript into those required for the page (which, I suppose this might all be) from those not required until the page has fully loaded.

I'd happily merge a PR which did either of those things!

**Comment by nickcharlton** [comment]
I'm going to close this as we also closed #996, which is related to this.

It's worth looking at this again once we support Webpacker (#1491).
