### ISSUE TITLE
Remove the FuuBar Gem

### ISSUE THREAD

**Issue by BenMorganIO** [thoughtbot/administrate#542]
I'm currently working through the project in my branch of `rails-5-support` and trying to get Rails 4.2 to load up RSpec 3.4 and rails 5 to load up RSpec 3.5. However, as the RSpec core version changes, this also changes the requirement of the FuuBar gem.

I'm sure that we can get the gem functional for Rails 5 and RSpec 3.5, but its extra work; especially in future upgrades of Rails and RSpec. Considering this, perhaps it would be OK to substitute a nice loading bar with smaller and easier to manage dependencies.

The FuuBar gem also has an open pull request (https://github.com/thekompanee/fuubar/pull/87) which was submitted back in February. This PR is for RSpec version 3.5.0.beta1, which will most likely conflict with 3.5.0.beta3 which was recently released last week.

FuuBar looks like a great gem though. Heck, I'm probably going to submit a few PRs to it and get it working with Rails 5 and RSpec 3.5 so that _I_ can use it my project. But, from a gem perspective that in the future will have to manage multiple versions of Rails and RSpec, it may not be the best option.

**Comment by jfelchner** [comment]
@BenMorganIO I'll be releasing a version of `fuubar` with RSpec 3.5 beta support in just a few minutes.

**Comment by jfelchner** [comment]
Unfortunately keeping up with beta versions of RSpec can be tricky.  I honestly wish Rubygems had an option for `~>` to accept beta versions. :/
