### ISSUE TITLE
key not found: :jsonb :inet

### ISSUE THREAD

**Issue by kgathi2** [thoughtbot/administrate#548]
Working with postgres which has field types like inet and jsonb. These produce a "Key not founf error" when searching though the key type array.

**Comment by BenMorganIO** [comment]
Can you provide a copy of the error? This would majorly help in getting a fix in. 

Also, if you can provide steps to reproduce, the version of rails, ruby, and administrate, that would also be super helpful :)

**Comment by kgathi2** [comment]
Settings are:
ruby 2.2.2
postgres  > 9.3

Gems
rails 4.2.2
devise 3.5.1
pg 0.18.4
adminstrate 0.2.0

To reproduce set up a rails app with devise. For pg devise uses inet for current_sign_in_ip and last_sign_in_ip instead of string, and possibly add a jsonb field too, say "details"

Once you install and set up adminstrate gem, going to the users list view will bring the error.

**Comment by jalberto** [comment]
@kgathi2 this may help: https://github.com/eddietejeda/administrate-field-json

**Comment by carlosramireziii** [comment]
@kgathi2 Did the plugin that @jalberto linked to help solve your issue? If so, would you consider this resolved?

**Comment by volkov-sergey** [comment]
Hello, @kgathi2 we have built this gem for working with PG jsonb https://github.com/codica2/administrate-field-jsonb.

**Comment by nickcharlton** [comment]
I'm going to close this issue as it's quite old and there's other solutions using `jsonb` fields, but if this isn't solved by any of those, please feel free to open a new issue!
