### ISSUE TITLE
Overriding the `_collection` template for a model affects `has_many` for other models.

### ISSUE THREAD

**Issue by hickscorp** [thoughtbot/administrate#549]
I'm trying to get the index listing for a specific model to show an extra link where the "Edit" and "Destroy" buttons are located. The model name being `Foo`, I've created a view within `app/views/admin/foos/_collection.erb`. It works great on the root `Foo` listing page.

However, an instance of `Foo` can have many of `Bar`. When I select a `Foo`, the detail page shows a list of `Bar` object there, and unfortunately the same collection template is used.

Is that a bug, or am I missing something?

**Comment by toobulkeh** [comment]
It's because the `render collection partial` looks for the partial via a relative path instead of fully qualified.

How did you solve this problem @hickscorp? I'm debating generalizing that functionality to all models

**Comment by hughfm** [comment]
there's a solution for this issue in #522, which has been working for me...

**Comment by hickscorp** [comment]
@toobulkeh no, and we ended up completely rewriting the view. We're thinking about abandoning Administrate for multiple reasons now, one of them being this, the other one being the fact that Administrate is super-confused when asked to sort on "virtual columns". There should be a flag to tell Administrate about those.

**Comment by pablobm** [comment]
A potential solution for this would be to pass an additional parameter to the `_collection` partial. I'll be happy to look into a PR providing this (or a different solution).
