### ISSUE TITLE
Generator for Application layout & partials

### ISSUE THREAD

**Issue by erdostom** [thoughtbot/administrate#556]
It would be nice to nice to have a generate create views for the overall layout and partials and like `sidebar` etc. I know I was looking for this.

Let me know if you think this is a good idea, and I'll take a crack at PR.

**Comment by wspurgin** [comment]
@erdostom there's already a generator for those! As of [v0.1.3](https://github.com/thoughtbot/administrate/releases/tag/v0.1.3).

**Comment by erdostom** [comment]
nice! just need to update the docs then

**Comment by wspurgin** [comment]
True that. If you still want to make a PR, you can make one that updates them.... but who likes writing docs? :shipit:
