### ISSUE TITLE
Application wide generators views don't seem to work

### ISSUE THREAD

**Issue by erdostom** [thoughtbot/administrate#557]
ran `rails generate administrate:views` and modified `show.html.erb` and `_collection.html.erb`. Neither change was reflected in my dashboards.

**Comment by misaghshakeri** [comment]
Same problem here

**Comment by davidalejandroaguilar** [comment]
:+1:

**Comment by mitjok** [comment]
https://github.com/thoughtbot/administrate/issues/484

**Comment by carlosramireziii** [comment]
This indeed appears to be a duplicate of #484. Closing this in favor of the original issue.
