### ISSUE TITLE
resource_class_name not working for every model name (Ie -> Y)

### ISSUE THREAD

**Issue by jalberto** [thoughtbot/administrate#558]
I have a model Ie, Administrate generate the controller (ies), routes, and dashboard properly, but when I visit 'admin/ies' I get:

```
uninitialized constant Y
```

I think the issue is located here:

https://github.com/thoughtbot/administrate/blob/master/lib/administrate/resource_resolver.rb#L15

"admin/ies".singularize #=> 'admin/y'
"ies".singularize #=> 'ie'

So #singularize must be call after split ant not before

**Comment by jalberto** [comment]
This still happens in 0.2.1

What is blocking this to  be merge?

**Comment by BenMorganIO** [comment]
@jalberto this looks like a nice fix :)

I have a feeling this is an ActiveSupport issue though. Will get the fix in though :)

**Comment by jalberto** [comment]
@BenMorganIO great :)

**Comment by BenMorganIO** [comment]
See: https://twitter.com/chancancode/status/735354787194150912
