### ISSUE TITLE
v0.2.0 is still requiring the image field

### ISSUE THREAD

**Issue by mathieul** [thoughtbot/administrate#561]
Thank you so much for *administrate*, it is such a pleasure to use after rails_admin and activeadmin.

I've just upgraded to `0.2.0` but my application can't start, getting the following `LoadError` exception message: `cannot load such file -- administrate/field/image`.

It appears that `administrate/base_dashboard.rb` is still requiring `administrate/field/image`.

**Comment by adamniedzielski** [comment]
I encountered the very same error. I confirm that adding ```gem "administrate-field-image"``` to the Gemfile fixes it.

**Comment by jkostolansky** [comment]
There's already a PR:
https://github.com/thoughtbot/administrate/pull/560

**Comment by HenryTimelessness** [comment]
https://github.com/thoughtbot/administrate/releases/tag/v0.2.0

**Comment by mathieul** [comment]
The breaking change is that if you use the image field, you need to include the new `administrate-field-image` gem.

The problem here is that if you don't use the image field, administrate still requires the image field, which breaks if you don't require the gem.

**Comment by dancinglightning** [comment]
For the average user (just using the administrative gem) this means the gem is effectively broken.

I'm not sure how the tests for the gem are still green. I would suggest a new version with the fix #560 quickly.

**Comment by BenMorganIO** [comment]
[0.2.2](https://rubygems.org/gems/administrate/versions/0.2.2) has been released. Closing this now :)

**Comment by BenMorganIO** [comment]
👏 @yujinakayama for the fix
