### ISSUE TITLE
DateTime template renders only date

### ISSUE THREAD

**Issue by ineu** [thoughtbot/administrate#562]
https://github.com/thoughtbot/administrate/blob/master/app/views/fields/date_time/_index.html.erb render field by calling `to_date` which returns Date instance. Instead it should render DateTime as explained in comments in this view.

**Comment by mcmire** [comment]
I'm guessing the reason why it's this way by default is that showing the full time on the index page produces a long column and uses up a lot of space that could be used for other columns. Do you find that you always need the full time when you are scanning through the list of records?

**Comment by ineu** [comment]
I usually do. But the real problem is that it's inconsistent. The component is called 'date_time' so it's expected to return datetime, not date.

**Comment by nickcharlton** [comment]
Perhaps we can switch this to `date_time`, but use a short rendering?

```ruby

**Comment by carlosramireziii** [comment]
Would anyone like to take a stab at implementing Nick's [suggestion](https://github.com/thoughtbot/administrate/issues/562#issuecomment-267996518) from above?

**Comment by mcmire** [comment]
I am wondering whether it would be a better idea to use a custom format name, such as `:administrate` or something. `:short` is a default format in Rails, and as such, people might already be using it for the public side. I think it would allow for more flexibility to keep the public side and admin side as separate as possible.

**Comment by ndrluis** [comment]
The format definition can be done via option on Model dashboard, so I think that this Issue could be closed.

https://github.com/thoughtbot/administrate/blob/d840e13da93c0a43fa1a47b883a724eb6e5344b3/lib/administrate/field/date_time.rb#L11

**Comment by nickcharlton** [comment]
Thanks @nando! I'm going to close this as that gives us a solution.
