### ISSUE TITLE
Using administrate over APIs

### ISSUE THREAD

**Issue by ahmgeek** [thoughtbot/administrate#565]
Hi, I was looking to use `administrate` over an RESTful APIs, is it doable ?
basically, I have a REST application at the back-end and angular client at the front-end.
I want to use administrate in a separate project to consume the APIs with it's own authorization of course.

**Comment by kieraneglin** [comment]
I'm in the exact same boat as you.  I touched on it in #404  and it works well enough for me.

**Comment by carlosramireziii** [comment]
@ahmgeek As @kieraneglin pointed out, there are some good tips on doing this in #404. 

I also outlined the steps [here](http://www.carlosramireziii.com/using-administrate-with-a-rails-5-api-application.html?utm_source=github) if you need them. 

Hope that helps!
