### ISSUE TITLE
Orders/Products listing - Destroy action triggers 500 error

### ISSUE THREAD

**Issue by juanroldan1989** [thoughtbot/administrate#571]
- Access Orders/Products listing
- Click on any item's link "Destroy"
- 500 error spotted

![screen shot 2016-05-09 at 11 56 07 am](https://cloud.githubusercontent.com/assets/2252229/15101166/359d0c0a-15dd-11e6-9b19-45ac36c428c3.png)

**Comment by carlosramireziii** [comment]
@juanroldan1989 Wasn't able to reproduce this on the latest version of the demo. Would you confirm and see if this is still an issue? If not, we'll close. Thanks!

**Comment by juanroldan1989** [comment]
Hello @carlosramireziii ! I can't replicate this issue anymore : ) Cheers !
