### ISSUE TITLE
Cross-Origin issues with SVGs when using CDN

### ISSUE THREAD

**Issue by hughfm** [thoughtbot/administrate#572]
I'm using a Cloudfront CDN distribution and have run into problems loading the SVGs (search icon, up/down arrows). As far as I can tell, browsers don't allow SVGs and the <use> tag to be loaded from another origin. 

I'd like to supply a :host option in the call to asset_url inside the svg_tag helper method. Does anyone have a suggestion on the best way to override this? 

Thanks, experience has been great with administrate by the way!

**Comment by aergonaut** [comment]
👍  I am also running into this with my app. Would love to see this fixed so I can use Cloudfront to serve assets with Administrate

**Comment by tysongach** [comment]
This is likely resolved with https://github.com/thoughtbot/administrate/pull/880.

**Comment by nickcharlton** [comment]
I'm going to close this as it should be solved with #880. If not, please reopen this issue!
