### ISSUE TITLE
Resource resolver and irregular table names

### ISSUE THREAD

**Issue by marcog** [thoughtbot/administrate#574]
Hi,
i have a table named shelves and everything worked fine in administrate up until i upgraded to 0.2.0

Now i'm getting 
`uninitialized constant Shelve`
when i try to access:
`admin/shelves`

i tried using an inflection initializer with no luck.

thanks
Marco

**Comment by jalberto** [comment]
@marcog #559 may help you

**Comment by marcog** [comment]
Thanks
I'll have a look at your PR
M

Il giovedì 12 maggio 2016, José Alberto <notifications@github.com> ha
scritto:

**Comment by carlosramireziii** [comment]
@marcog Just checking in on this one. Does #559 solve your issue?

**Comment by marcog** [comment]
Yes, it solves it.
thanks
M

On Thu, Mar 9, 2017 at 7:07 PM, Carlos Ramirez III <notifications@github.com

**Comment by cabe56** [comment]
Seems like this issue can be closed. #559 was merged and it seems to fix the issue according to OP.
