### ISSUE TITLE
Trying to visit admin_root page 

### ISSUE THREAD

**Issue by dmitriy-strukov** [thoughtbot/administrate#576]
When i trying to visit admin_root page it raise error: 
undefined local variable or method `page' for #<#Class:0x0000000d1790a0:0x0000000d210ec8>

**Comment by dancinglightning** [comment]
I have a similar issue, annoyingly only in production.
ruby 2.3 ,  administrate 0.1.5

error only on one class view, but same error

**Comment by dancinglightning** [comment]
I found mine: For some reason i don't remember my controller was namespaced into admin.

In other words it was my own controller responding to the request and that off course did not have the variables needed for the page. my bad

**Comment by jeffreyguenther** [comment]
@dmitriy-strukov Are you still having trouble? Or can we close this issue?

**Comment by dmitriy-strukov** [comment]
@jeffreyguenther Please close issue
