### ISSUE TITLE
(confused) Which version of ruby we are using?

### ISSUE THREAD

**Issue by WaKeMaTTa** [thoughtbot/administrate#586]
Hello team!

Why in [`Gemfile`](https://github.com/thoughtbot/administrate/blob/master/Gemfile#L3) file the version of ruby is `2.3.1` and in the [`.ruby-version`](https://github.com/thoughtbot/administrate/blob/master/.ruby-version) the version of ruby is `2.2.3` ?

Which version of ruby we are using?

:confused:

**Comment by BenMorganIO** [comment]
We should probably just remove both of the references. Administrate should really just pick a minimum version and let TravisCI handle things from there.

**Comment by BenMorganIO** [comment]
Closing as of #591
