### ISSUE TITLE
Demo Application

### ISSUE THREAD

**Issue by esparkman** [thoughtbot/administrate#587]
Is there a place to see the source for the demo application. I can't for the life of me get the strong params for Paperclip attributes working with Administrate.

**Comment by aeons** [comment]
https://github.com/thoughtbot/administrate/tree/master/spec/example_app

**Comment by halogenandtoast** [comment]
@esparkman does the example app provide you with the information you needed or is there a more specific issue that can be extracted?

**Comment by nickcharlton** [comment]
Closing this as it's been open with (hopefully) a solution for some time now. Please re-open if you're still seeing this!
