### ISSUE TITLE
Pagination broken w/ action_on_unpermitted_parameters = :raise

### ISSUE THREAD

**Issue by atwoodjw** [thoughtbot/administrate#589]
If you configure your application to raise an error on unpermitted parameters...

```
module MyApp
  class Application < Rails::Application
    ...

    config.action_controller.action_on_unpermitted_parameters = :raise
  end
end
```

... you get this error on any dashboard index page page that includes the `page` URL parameter: `found unpermitted parameter: page`.

Example: `http://localhost:3000/admin/users?page=2`

Looks like the culprit is `sanitized_params`, which doesn't include `page`.

```
def sanitized_params
  params.permit([:search, :id, :order, :per_page, :direction])
end
```

**Comment by halogenandtoast** [comment]
I've configured my application the same way, but I'm not seeing this issue. Have you configured your dashboard in any way. Additionally, what versions are you using. I'm using administrate 0.2.2 with rails 4.2.6

**Comment by atwoodjw** [comment]
Whoops, forgot I was on a fork that supports Rails 5.

`gem 'administrate', github: 'greetpoint/administrate', branch: 'rails5'`

Please close.
