### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by dmitriy-strukov** [thoughtbot/administrate#592]
How i can do something like this in my dashboard resource.owner.first_name?  Or how i can put in field custom value using resourse variable?

**Comment by ACPK** [comment]
@dmitriy-strukov - Did you figure it out?

**Comment by kuboon** [comment]
Adding getter/setter to your model will work.

**Comment by ACPK** [comment]
@kuboon - Didn't work as this is what I had tried.

**Comment by kuboon** [comment]
@ACPK You also need to add your column with field type. Did you do that?

```ruby
  ATTRIBUTE_TYPES = {
    id: Field::Number,
#...
    owner_first_name: Field::String
  }
  FORM_ATTRIBUTES = [
    #...
    :owner_first_name
   ]
```

**Comment by ACPK** [comment]
Yes.

**Comment by ACPK** [comment]
@kuboon - Yes, so we decided to create our own admin area instead.
