### ISSUE TITLE
Search box not fitting into page layout

### ISSUE THREAD

**Issue by shubhpatel108** [thoughtbot/administrate#595]
I updated all gems including administrate using `bundle update` command. Now, the search box is not fitting in the page layout properly.

<img width="1280" alt="screen shot 2016-05-27 at 10 26 26 am" src="https://cloud.githubusercontent.com/assets/4345133/15598307/52ea7e38-23f6-11e6-9616-a83574c559b9.png">

It seems that administrate has incorporated many changes which include replacing inline_svg with svg_tag. According to #173, sprockets is involved somewhere in this change. My Gemfile doesn't contain sprockets. [Here](https://github.com/berkmancenter/bookanook/blob/cancancan/Gemfile) is the content of my Gemfile.
Is it a global issue directly related to administrate or a cause of a dependency? Please help with fixing it. Thanks!

**Comment by carlosramireziii** [comment]
Hey @shubhpatel108, just checking up on this one...

Is this still an issue for you? Are you able to reproduce this on the current [demo](https://administrate-prototype.herokuapp.com/admin) app? If so, could you give some more details so we can look into it. 

Thanks!

**Comment by carlosramireziii** [comment]
Closing for now, but feel free to re-open if you feel this is still an issue. Thanks!
