### ISSUE TITLE
rails g administrate:install error

### ISSUE THREAD

**Issue by tengju** [thoughtbot/administrate#601]
Hi its my first time trying to use this gem but when i genereate it this error keeps popping up.

/gems/ruby-2.3.1@global/gems/railties-4.2.6/lib/rails/generators/named_base.rb:102:in `block in class_name': undefined method`camelize' for nil:NilClass (NoMethodError)

How can i fix this? or what is exactly the problem?

p.s im using rails 4.2.6 with ruby 2.3.1

**Comment by tengju** [comment]
fixed by making models first

see: https://github.com/thoughtbot/administrate/issues/516

**Comment by nickcharlton** [comment]
Closing as this should be fixed with #713. Please open an issue if that's not the case!
