### ISSUE TITLE
Gem 'administrate' is not available in SDK 'ruby-2.0.0-p596'

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [thoughtbot/administrate#604]
Anytime I try to use administrate, I get the error Gem 'administrate' is not available in SDK 'ruby-2.0.0-p596'. In other words, it doesn't want to install or not just available for Ruby 2.0.0.

How do I fix this problem without having to install another version of Ruby?

**Comment by j-dexx** [comment]
What is `SDK 'ruby-2.0.0-p596'`? Based on a quick google is this something to do with RubyMine?

This doesn't seem to be an issue to do with the gem.  Administrate has no required ruby version on rubygems either.  Essentially it sounds like you simply need to install the gem.

If it is RubyMine you're using this may help [https://www.jetbrains.com/help/ruby/2016.1/installing-and-uninstalling-gems.html](https://www.jetbrains.com/help/ruby/2016.1/installing-and-uninstalling-gems.html)

**Comment by BenMorganIO** [comment]
I would recommend using either rvm or rbenv to install ruby. We haven't set a minimum version yet, but I expect it to be at least ruby 2.2.
