### ISSUE TITLE
Updating causes unrelated NULL fields to become NOT NULL

### ISSUE THREAD

**Issue by seanfcarroll** [thoughtbot/administrate#605]
I'm not really sure what exactly is going on here. I am using the excellent Administrate engine, and I received an error on a Devise-based user record after updating a field. It turns out there were 2 users with the same unlock_token.

Upon further investigation, it seems the problem occurs after doing an update with administrate. Any empty fields are failing a NOT NULL test (and therefore failing unique constraints on indexes).

```
=> select id, reset_password_token, website, '>' || website || '<'  as website_empty from participants where id = 2 and website is not null;
-[ RECORD 1 ]--------+---
id                   | 2
reset_password_token |
website              |
website_empty        | ><
```

I'm not clear on what is happening here, as there does not seem to be a space in the field, yet it is also not null. I have verified every field on a table updated through the Administrate edit page is doing this.

Perhaps this is a related issue:  https://github.com/thoughtbot/administrate/issues/136

**Comment by pablobm** [comment]
The issue indicated as possibly related is now fixed. Also, could it be that this is more to do with ActiveRecord's behaviour, rather than Administrate's?

I'm going to close for now. Please reopen with more information if you think this is still a problem.
