### ISSUE TITLE
NoMethodError on Models with methods overriding their fields

### ISSUE THREAD

**Issue by davidalejandroaguilar** [thoughtbot/administrate#610]
I got a model like this:

```
class OrderItem < ActiveRecord::Base
 def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end
```

When I try to create a **New Order Item** (_/admin/order_items/new_), I get a NoMethodEerror: 

`undefined method "price" for nil:NilClass.`

When I remove the overriding method, it works.

**Comment by manuelmeurer** [comment]
Maybe the `product` of the `order_item` is `nil`?

**Comment by carlosramireziii** [comment]
@davidalejandroaguilar Were you able to get to the bottom of this issue? @manuelmeurer's suggestion that perhaps `product` is `nil` seems like something to investigate. 

Let me know if this is still an open issue for you. Thanks!

**Comment by carlosramireziii** [comment]
Closing for now but feel free to re-open if you think this is still an issue. Thanks!
