### ISSUE TITLE
How to pass current_user to Administrate::Field ?

### ISSUE THREAD

**Issue by twist900** [thoughtbot/administrate#618]
When I am creating/editing a Model, I want to see only those associated models in the select field for which I have permissions. I am using CanCan, how can I pass my current_user to the fields/belongs_to.rb to be able to have something like:

```
def candidate_resources
  current_user = options.fetch(:current_user, {})
  associated_class.all.accessible_by(Ability.new(current_user))
end
```

**Comment by alexey-chernikov** [comment]
+1, I have the same question.

**Comment by twist900** [comment]
@alexey-chernikov hi, I succeeded by passing the current_user to the field through the view, not through the dashboard. P.s. привет :)

**Comment by carlosramireziii** [comment]
Sounds like this one has been resolved. Feel free to re-open if there is further feedback or questions. Thanks!
