### ISSUE TITLE
How do I customize various admin messages?

### ISSUE THREAD

**Issue by avk** [thoughtbot/administrate#619]
After generating a view:
`rails generate administrate:views:index User`

How or where do I change messages such as this one?

``` ruby
data: { confirm: t("administrate.actions.confirm") }
```

**Comment by j-dexx** [comment]
You should be able to copy the locales file from [here](https://github.com/thoughtbot/administrate/blob/master/config/locales/administrate.en.yml) into your config/locales directory and amend as necessary

**Comment by carlosramireziii** [comment]
@avk Did the solution outlined by @j-dexx work for you? If so, would you consider this issue as resolved?

**Comment by avk** [comment]
I won't have an opportunity to test this any time soon. Feel free to close.

**Comment by nickcharlton** [comment]
Going to go ahead and close. Thanks, @carlosramireziii!
