### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by teoljungberg** [thoughtbot/administrate#623]
There seems to be a few blockers of upgrading administrate, and since Rails 5 was released yesterday - It'd be good to have administrate upgraded aswell.

@graysonwright Let me know if there's anything I can do to help out.

**Comment by clemensg** [comment]
Yes, please let's make `administrate` Rails 5 compatible :)

What about PR https://github.com/thoughtbot/administrate/pull/575 ?

**Comment by ID25** [comment]
Just remind that currently we can use this fork, it works well with rails 5
```ruby
gem 'administrate', github: 'greetpoint/administrate', branch: 'rails5'
gem 'bourbon', '~> 5.0.0.beta.5' 
```

**Comment by teoljungberg** [comment]
@ID25 Thanks for bringing that up!

I started incorporating your branch into Administrate itself and captured it here https://github.com/thoughtbot/administrate/tree/rails-5.

All though, I ran into issues with generators. But ran out of time, so if someone else wants to pick this up - feel more than welcome to do so.

**Comment by hwhelchel** [comment]
Looks like the `column_types` method no longer exists. I patched this method and had the generator run successfully. 

```ruby
      def column_type_for_attribute(attr)
        if enum_column?(attr)
          :enum
        else
          klass.column_types[attr].type
        end
      end
```
```ruby
      def column_type_for_attribute(attr)
        if enum_column?(attr)
          :enum
        else
          klass.columns.find {|c| c.name == attr }.try!(:type) # This line changed
        end
      end
```

**Comment by hauleth** [comment]
What is the status?

**Comment by cies** [comment]
I'm also really curious for the status.

**Comment by clemensg** [comment]
@graysonwright ?

**Comment by pablo-co** [comment]
Any news?

**Comment by J77J** [comment]
Soo... What is the state of play for Rails 5? I see a couple of different branches in this thread which I can use for Rails 5, which is the better one to use?

**Comment by pablo-co** [comment]
@J77J You can use the `rails5` branch from this [fork](https://github.com/pablo-co/administrate) I made. I've been using it on production for over a month without a problem. 

The Gemfile declaration would be:
`gem "administrate", github: "pablo-co/administrate", branch: "rails5"`

It's a temporary workaround while administrate officially supports Rails 5. 👍

**Comment by J77J** [comment]
Thanks @pablo-co

**Comment by preist** [comment]
I look forward to Rails 5 support. Thanks a lot for all the work going into making it happen. ❤️

**Comment by gbrl** [comment]
@pablo-co When I run the generator, I get this:

```
rails generate administrate:install                                                  15:14  01.10.16
Running via Spring preloader in process 41196
       route  namespace :admin do
    resources :users
resources :invites
resources :messages
resources :profiles

    root to: "users#index"
  end
WARNING: Unable to generate a dashboard for ApplicationRecord.
         It is not connected to a database table.
         Make sure your database migrations are up to date.
      create  app/controllers/admin/application_controller.rb
      create  app/dashboards/user_dashboard.rb
      create  app/controllers/admin/users_controller.rb
      create  app/dashboards/invite_dashboard.rb
      create  app/controllers/admin/invites_controller.rb
      create  app/dashboards/message_dashboard.rb
      create  app/controllers/admin/messages_controller.rb
      create  app/dashboards/profile_dashboard.rb
      create  app/controllers/admin/profiles_controller.rb
```

**Comment by gbrl** [comment]
@pablo-co I just installed your fork, and it worked only after I added bourbon to my Gemfile. Might want to add that to your instructions! Thanks for your work!!!

**Comment by zaiste** [comment]
Can we close this since https://github.com/thoughtbot/administrate/pull/636 has been just merged in ?

**Comment by teoljungberg** [comment]
With the merge of #636, I'm calling this closed.
