### ISSUE TITLE
Getting an Internal 500 Server Error when I visit my /admin route on heroku.

### ISSUE THREAD

**Issue by reissjohnson** [thoughtbot/administrate#624]
Runs locally all good just hits a 500 error on the heroku log when I visit /admin. I get the standard 'We're sorry but something  went wrong'. All migrations are up to date etc. Any ideas?

**Comment by Ivandureve** [comment]
Hello @reissjohnson, how did you fixed that? I do have the same error!

**Comment by nickcharlton** [comment]
@Ivandureve, can you open a new issue with some more details of what you're seeing?

**Comment by Ivandureve** [comment]
It's all good, ended up fixing it. I did not migrante my db on heroku... Sorry about that!
