### ISSUE TITLE
Generate administrate:views creates incorrect path

### ISSUE THREAD

**Issue by tehfailsafe** [thoughtbot/administrate#645]
Took a bit to figure out why customizing views wasn't working, but looks like it's appending an `s` to the end of `application` in the path.

![image](https://cloud.githubusercontent.com/assets/1388454/17723182/efeb43a8-63ec-11e6-96a3-c74e39305b31.png)

**Comment by ashchan** [comment]
Hit by this too. Thanks for the finding.

**Comment by jeffreyguenther** [comment]
@nickcharlton we need to fix this one in the next release.
