### ISSUE TITLE
with_options usage documentation

### ISSUE THREAD

**Issue by giuseb** [thoughtbot/administrate#647]
The "Customizing Dashboard" documentation page says:

> Each of the Field types take a different set of options, which are specified through the `.with_options` class method.

I seem unable to figure out what options are available for each field type. Any pointers? Reference documentation and/or relevant source code to inspect?

I have detailed my specific problem [here](http://stackoverflow.com/questions/39052135/customizing-fields-with-the-administrate-gem-for-rails).

**Comment by erose** [comment]
+1, I'm also looking for this documentation.

**Comment by ianagne** [comment]
@giuseb I just responded to your StackOverflow post.  It doesn't use the `.with_options` class method, but it does expose another area where we could expand the documentation (overwriting the BaseDashboard class to customize appearance).

**Comment by ianagne** [comment]
@giuseb @erose If you're still looking for documentation on .with_options, check out the PR referenced right above this comment.  I added all of the currently active options that I could find in the source.  If you are using an option that isn't listed, let me know what it is and what it does and I'll add it to the PR.

**Comment by erose** [comment]
@ianagne: Thank you!

**Comment by ianagne** [comment]
@JoelQ With #670 merged, it should be safe to close this issue.
