### ISSUE TITLE
How can I prefill a form with data I get from an external API ?

### ISSUE THREAD

**Issue by stanams** [thoughtbot/administrate#658]
On my administrate 'model_1 index view', I'm quering an external API and I would like the form of 'model_2 new' to be prefilled with the data I get from the API. Is there a way to do that ?

**Comment by buren** [comment]
There is currently no way of doing this using the out-of-the-box version of administrate. You could perhaps work around that, but nothing I've looked into personally (even though I have a similar use case myself).

**Comment by ianagne** [comment]
You may customize any of the Administrate controller actions by overwriting the methods in the respective controller.  In this case, it sounds like you'd like to customize the `#new` action.

In Administrate's default controller, the `#new` action takes the resource_class (Model2 in this case), instantiates an instance of that class (Model2.new), and passes it to a page object.

You can prefill the model withl data from your API by instantiating the class with that data.

For example, in `app/controllers/admin/model_2_controller.rb` you could write something like this:

```ruby
module Admin
  class Model2Controller < Admin::ApplicationController
    def new
      resource = Model2.new(params_from_api)
      render locals: {
        page: Administrate::Page::Form.new(dashboard, resource),
      }
    end
  end
end
```

**Comment by stanams** [comment]
Cool thanks, that's a great solution! Before testing that one, I used the data retrieved from the api to create a new record of the model2: Model2.create(formatted_data_from_the_external_api) that was enough in my case. But I like your elegant solution @ianagne :)
