### ISSUE TITLE
Feature Request: Support multiple select

### ISSUE THREAD

**Issue by joe11051105** [thoughtbot/administrate#659]
thanks.

**Comment by JoelQ** [comment]
@joe11051105 Thanks for your suggestion.

Administrate allows you to create any custom fields you like. See https://administrate-prototype.herokuapp.com/adding_custom_field_types.

For now, we're focusing the Rails 5 upgrade and some internal changes.

Long-term, we plan on supporting most of the common field types in core. We're thinking of having less commonly used fields and fancier stuff in their own gems (both our own and community maintained). I'm not sure yet where multi-select will fall.

**Comment by dan-klasson** [comment]
Here's how to do it in case somebody else needs this too: 

http://stackoverflow.com/questions/40692913/multiple-select-in-administrate/40701551#40701551

**Comment by aksharj** [comment]
Hi, I am trying to implement a way to select multiple records on the index page and bulk delete. Can you please guide me as to how i can implement it. Thanks.

**Comment by andreibondarev** [comment]
Multi-select and bulk actions: https://github.com/SourceLabsLLC/administrate_batch_actions
