### ISSUE TITLE
Fresh install of gem, cannot get past Invalid CSS Error

### ISSUE THREAD

**Issue by smkarber** [thoughtbot/administrate#660]
I am trying to install administrate into a rail application. 

```
#administrate
gem 'sass-rails', '~> 5.0'
gem "administrate", "~> 0.2.2"
```

Both of those are in my gemfile. 

```
bundle install
rails generate administrate:install
rails s
```

visit localhost:3000/admin

Get the error:

Invalid CSS after "  alert": expected ")", was ": $light-yellow,"
  (in /Users/shawnkarber/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/administrate-0.2.2/app/assets/stylesheets/administrate/application.scss:45)

**Comment by danbee** [comment]
Hi @smkarber, does this problem occur if you use the `master` branch of the gem?

```
gem 'administrate', github: 'thoughtbot/administrate', branch: :master
```

**Comment by carlosramireziii** [comment]
@smkarber Just following up on this...

Is this still an issue with you for the latest version? If so, feel free to re-open. 

Thanks!
