### ISSUE TITLE
"datetimepicker" not showing / responding in datetime field.

### ISSUE THREAD

**Issue by haikalhussein** [thoughtbot/administrate#661]
Im using ruby 2.3.0, rails 4.2.5 and foundation-rails for my app.. I have generated the fields view for DateTime by running the generator "rails generate administrate:views:field DateTime". Re-started my app but somehow datetimepicker doesn't show any respond. It just act as a normal text input.

**Comment by michelegera** [comment]
While waiting for the above `datetime_picker_rails` PR to be reviewed/merged, I ended up rolling my own custom field which integrates the gorgeous [Flatpickr](https://github.com/chmln/flatpickr) library.

Take a look at [`administrate-field-date_picker`](https://github.com/z-productions/administrate-field-date_picker). It lets you pick only a date for now, but I’m planning to add time support soon.

**Comment by carlosramireziii** [comment]
@haikalhussein Just following up on this...

It sounds like you've created a custom field for a date time picker, is that correct? If so, does it utilize any custom JavaScript to make it function? If it's acting like a regular text field and it's a JS plugin, my guess is that the JS is not included. 

Have a look at [this](https://github.com/thoughtbot/administrate/issues/600#issuecomment-225866678) and see if it helps. 

Let me know!
