### ISSUE TITLE
Sass::SyntaxError - File to import not found or unreadable: bourbon.

### ISSUE THREAD

**Issue by jersingh** [thoughtbot/administrate#664]
Upgraded a rails app from 4.1.16 to 4.2.7.1. Worked through the issues to get it up and running.

Added administrate to Gemfile, and after running the generator and a puma reboot, getting stated error.

I'm loathe to include Gemfile.lock but will provide if requested.

**Comment by JoelQ** [comment]
Could this be a duplicate of #615 ?

**Comment by pkoch** [comment]
Looks like it. Close?
