### ISSUE TITLE
Increase viewable instances of attributes with has_many relation on show pages

### ISSUE THREAD

**Issue by icstunna** [thoughtbot/administrate#666]
I've noticed that on show pages, attributes whose fields have a `has_many` relationship are limited to only being able to view 5 instances with no options for pagination or revealing all relations.

This is problem for me, my application is somewhat of a to-do list with multiple milestones and tasks. As an administrator I want to see all tasks associated with a specific milestone (this could be a few dozen). 

In an attempt to view all of the tasks, I've overwritten some of the gems default limitations. As seen in the code below:

```
module Administrate
  module Field
    class HasMany < Associative
      DEFAULT_LIMIT = 100
    end
  end
end
```

This does not seem like a clean implementation and I worry about it's dependency on the gem. Can anyone recommend a better solution for what I'm trying to achieve?

**Comment by avk** [comment]
I have this question too. Any ideas @JoelQ @danbee? 
Why are `has_many`s limited to 5?

**Comment by JoelQ** [comment]
You can pass in your own limit. Internally, the `HasMany` field implements limit as follows:

```ruby
def limit
  options.fetch(:limit, DEFAULT_LIMIT)
end
```

The constant `DEFAULT_LIMIT` is just a fallback if no limit option is given.

In your dashboard, you probably want to do something like:

```ruby
orders: Field::HasMany.with_options(limit: 100)
```

You can see an example of using `with_options` at the bottom of this page: https://administrate-prototype.herokuapp.com/customizing_dashboards.

Hopefully that answers your question?

**Comment by icstunna** [comment]
@JoelQ that was very helpful thank you! I didn't realize you can overwrite the limit value within the with_options method. thanks!
