### ISSUE TITLE
0.2.2 depends on rails ~4.2

### ISSUE THREAD

**Issue by drewtunney** [thoughtbot/administrate#668]
It appears that administrate should be working with rails 5 given #636 was recently merged. However when trying to run `bundle install` I'm receiving the following error:

```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.0.0.1)

    administrate (~> 0.2.2) was resolved to 0.2.2, which depends on
      rails (~> 4.2)
```

Is this a known issue? Should master be compatible with rails 5?

**Comment by danbee** [comment]
Hi @drewtunney, the PR was merged but we have not cut a release yet. You could directly specify the ref for now:

```
gem "administrate", git: "https://github.com/thoughtbot/administrate", ref: "84096ca0b90c91f3033d123ad4c2ff691123e73a"
```

**Comment by drewtunney** [comment]
@danbee understood, thanks. do you have a vague idea of when that release will be?

**Comment by danbee** [comment]
@drewtunney Version 0.3.0 was released last week which fixes this.
