### ISSUE TITLE
Clear search broken on rails 5

### ISSUE THREAD

**Issue by j-dexx** [thoughtbot/administrate#669]
https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/_search.html.erb#L17

Not checked on rails 4 but I'd suspect it's the same.

> Attempting to generate a URL from non-sanitized request parameters! An attacker can inject malicious data into the generated URL, such as changing the host. Whitelist and sanitize passed parameters to be secure.

A simple fix would be to just change to 
`params.permit.except(:search)`

**Comment by jmasson** [comment]
Using the commit from https://github.com/thoughtbot/administrate/pull/665 fixed this for me and got administrate running with Rails 5.0.0.1

**Comment by j-dexx** [comment]
Cool, given that I'll close this.

**Comment by jcmorrow** [comment]
@BenMorganIO did you mean to reopen this?

**Comment by BenMorganIO** [comment]
I think so. Reasoning: The issue was opened because there was a problem with the project and closed because the user found a workaround for their specific project. I think that's what it was. But if we've solved it in the project, this guy can totally be closed.

**Comment by j-dexx** [comment]
I had assumed it would be merged in with the pull request.
