### ISSUE TITLE
`add_route': Invalid route name, already in use: 'admin_root'

### ISSUE THREAD

**Issue by FlorianCEO** [thoughtbot/administrate#675]
Hi, 

After deploying my rails app on Heroku, I had the error : 
`Invalid route name, already in use: 'admin_root'`

I post the problem here : http://stackoverflow.com/questions/40222008/administrate-rails-4-add-route-invalid-route-name-already-in-use-admin?noredirect=1#comment67708019_40222008

Thanks guys

**Comment by FlorianCEO** [comment]
Finally find the solution !

**Comment by JoelQ** [comment]
I'm glad you figured it out
