### ISSUE TITLE
Demo app throws errors

### ISSUE THREAD

**Issue by gbrl** [thoughtbot/administrate#676]
I was testing out the demo app, and I clicked on "Edit" for one of the customers, and got this: https://administrate-prototype.herokuapp.com/admin/customers/6027/edit

**Comment by JoelQ** [comment]
The linked page gives a `404` error. I'm guessing someone deleted customer 6027. I did get a `500` error when clicking on "Edit" for another customer. Will investigate further. Thanks for bringing this up.

**Comment by nickcharlton** [comment]
I'd looked at this a few times, but I finally figured out what was wrong: The database schema had drifted from what was being reset nightly.

I dropped all of the tables and now this appears to be all solved.
