### ISSUE TITLE
Question: Does this gem allow adding children to parent object?

### ISSUE THREAD

**Issue by gbrl** [thoughtbot/administrate#678]
Let's say I have a Post model, that has many Comments.  Does this gem allow me to go to a Post and add a new Comment to that post from the Post "show" view? Right now it either lists the children, or says "NONE". I want to add a button to add a Comment to a Post. This gem doesn't have this feature built-in, correct?

**Comment by j-dexx** [comment]
No, it's not built in you'd have to override things to customise it to do that.

**Comment by nickcharlton** [comment]
I hope this answered your question. Closing for now, but please reopen an issue if it didn't!
