### ISSUE TITLE
Setting extra attributes on has_many join table?

### ISSUE THREAD

**Issue by akestner** [thoughtbot/administrate#685]
Definitely not an issue, just fishing for advice. 

Was wondering how one might go about setting extra attributes on the join table of a `has_many` association, but from one of the associated models' dashboard (i.e. _not_ the join table's dashboard)?

At the risk of oversharing, here's the specific issue I'm trying to solve:
![administrate_join_table_extra_attrs](https://cloud.githubusercontent.com/assets/3409228/19937628/64707778-a0f8-11e6-8ef3-64af42c84cac.gif)

**Comment by j-dexx** [comment]
I think you'd need to customise the view and use ajax.

**Comment by akestner** [comment]
Great, thanks for the tip.
