### ISSUE TITLE
Broken sort arrow in the resource table

### ISSUE THREAD

**Issue by hoangzinh** [thoughtbot/administrate#686]
When I navigate to a resource index page, then I saw the broken arrow in the column "Genre Name"

<img width="1160" alt="screen shot 2016-11-06 at 5 20 04 pm" src="https://cloud.githubusercontent.com/assets/9639873/20036905/7d94dd40-a448-11e6-8fcc-a53a2cb05a8b.png">

Is there anyone have same experiment with me? I'm using administrate 0.2.2.

**Comment by carlosramireziii** [comment]
Looks like this one was merged in #687. Closing
