### ISSUE TITLE
Search functionality issues

### ISSUE THREAD

**Issue by romanoff** [thoughtbot/administrate#690]
When searching on demo application, following link errors out:
```
https://administrate-prototype.herokuapp.com/admin?search=hilda
```

As well search itself doesn't seem to work. Example:
```
https://administrate-prototype.herokuapp.com/admin/line_items?search=sorry
```

**Comment by SerKnight** [comment]
Will dig in tomorrow and look for the fix, but just referencing bug again here. So far very customizable. Coming from lots of AA & RA. 


https://administrate-prototype.herokuapp.com/admin/customers?search=lexi

**Comment by carlosramireziii** [comment]
Thanks for reporting this!

It looks like it's fixed on the current version of the demo application, so I'm going to close this up.
