### ISSUE TITLE
Exclude certain attributes from search

### ISSUE THREAD

**Issue by trandoanhung1991** [thoughtbot/administrate#691]
Currently search seems to search on all fields under ATTRIBUTE_TYPES, which then breaks with writer-only attributes. Is there any way to mark certain attributes as not searchable?

```
Mysql2::Error: Unknown column 'password' in 'where clause': SELECT  `users`.* FROM `users` WHERE `users`.`type` IN ('Customer') AND (lower(email) LIKE '%test2%' OR lower(password) LIKE '%test2%' OR lower(password_confirmation) LIKE '%test2%') LIMIT 20 OFFSET 0
```

Devise uses 2 writer attributes, but the actual column is encrypted_password, which is meaningless for searching anyway.

**Comment by trandoanhung1991** [comment]
Managed to make this work by making a custom ```PasswordField``` that inherits from ```Field::String```, and override ```self.searchable?``` to return ```false```, and then use that.

**Comment by jarvisjohnson** [comment]
Anyone looking at this now, you can add options in the `ATTRIBUTE_TYPES` hash for the field, so to avoid trying to search the `password` field, just do:
`password: Field::String.with_options(searchable: false),`

From [this issue](https://github.com/thoughtbot/administrate/issues/445)

**Comment by BenMorganIO** [comment]
@jarvisjohnson would you like to make a PR for the docs?

**Comment by jarvisjohnson** [comment]
Hey @BenMorganIO  - Realised now that this [already is in the docs](https://github.com/ianagne/administrate/blob/master/docs/customizing_dashboards.md) thanks to @ianagne [here](https://github.com/thoughtbot/administrate/issues/647)
