### ISSUE TITLE
Ability to customize left sidebar

### ISSUE THREAD

**Issue by trandoanhung1991** [thoughtbot/administrate#692]
It would be nice if we can customize the left sidebar. I really want to be able to add a log out link at the bottom of the links.

**Comment by trandoanhung1991** [comment]
Managed to do this by copying the gem's ```_sidebar.html.erb``` and change that. IMO the generator should really include all the views.

**Comment by clthck** [comment]
You can either manually copy that view file or hit the following command:
```
bundle exec rails g administrate:views:sidebar
```

**Comment by einSelbst** [comment]
To whom it may concern, as per 0.7 the sidebar is called 'navigation'.
Now it would be 
```
bundle exec rails g administrate:views:navigation
```
