### ISSUE TITLE
Sorting arrows in wrong places

### ISSUE THREAD

**Issue by pmichna** [thoughtbot/administrate#695]
I have just installed adminsitrate and when I click a column to be sorted, the arrows appear in strange places. Example for a `Tasks` column:

![image](https://cloud.githubusercontent.com/assets/3777006/20427378/e814616a-ad83-11e6-8724-d7c4620dc7d3.png)

![image](https://cloud.githubusercontent.com/assets/3777006/20427407/11d2df7c-ad84-11e6-8a74-eb94412a434c.png)

**Comment by hoangzinh** [comment]
It has been solved in this PR https://github.com/thoughtbot/administrate/pull/687
