### ISSUE TITLE
Version 0.3.0 on rubygems makes resolving dependencies difficult

### ISSUE THREAD

**Issue by jeffreyguenther** [thoughtbot/administrate#697]
Version 0.3.0 is listed on rubygems, but there is no release tag on the repo for the version.

This causes issues with using the image field plugin and rails 5.0 together. I ended up having to fork so I could edit the gemspec to let me use rails 5 with the image field plugin.

**Comment by nickcharlton** [comment]
I've just added a tag and created a release for `0.3.0`, hopefully this helps!
