### ISSUE TITLE
Demo App Source Code

### ISSUE THREAD

**Issue by jk2081** [thoughtbot/administrate#700]
Is there a link to the source for the demo app?

**Comment by meganemura** [comment]
[Repository Structure](https://github.com/thoughtbot/administrate/blob/master/README.md#repository-structure) section in README.md provides you that.

**Comment by jk2081** [comment]
Thank you!

**Comment by meganemura** [comment]
Would you please close the issue?

**Comment by HHGB12** [comment]
Hi Is there a link today, to get the source code for the demo app ??
