### ISSUE TITLE
Issue with administrate-field-image

### ISSUE THREAD

**Issue by dts** [thoughtbot/administrate#717]
I'm trying to build off of the [administrate-field-image](https://github.com/thoughtbot/administrate-field-image) gem example (my gem is here: https://github.com/TheHumanEffort/administrate-field-refile/blob/master/administrate-field-refile.gemspec).  I am running into some problems with the basic structure.  When I add the gem to my Gemfile (`gem 'administrate-field-image', github: 'thoughtbot/administrate-field-image', branch: 'master'
`) and `bundle install`, I get the following error:

```
Fetching git://github.com/thoughtbot/administrate-field-image.git

[!] There was an error while loading `administrate-field-image.gemspec`: cannot load such file -- administrate/field/base
Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

 #  from /usr/local/bundle/bundler/gems/administrate-field-image-c7cd88ae8dc2/administrate-field-image.gemspec:3
 #  -------------------------------------------
 #
 >  require "administrate/field/image"
 #
 #  -------------------------------------------
 $ bin/bundle version
Bundler version 1.13.6
```

I'm not entirely sure how to proceed, as my usual google-fu is failing me.

**Comment by nickcharlton** [comment]
It's a recursive include …as far as I understand it.

I recently opened a PR which fixed this on another gem based on `administrate-field-image`: https://github.com/eddietejeda/administrate-field-json/pull/11

There's a few open PRs on Grayson's original `administrate-field-image` which should help you: https://github.com/graysonwright/administrate-field-image

A job for the future is to rationalise these two repos and pick one.

**Comment by dts** [comment]
Big ups for the <15min response time!  Wowee zowee.  https://github.com/graysonwright/administrate-field-image/pull/6/commits/7686c92229054b898c998fceeba43663115f7516 was the fix I needed.  Thanks!
