### ISSUE TITLE
undefined local variable or method `page'

### ISSUE THREAD

**Issue by stoge** [thoughtbot/administrate#718]
Hi there,

While all my other models work,
I have this issue with just one model, when I hit "New Gallery" is get this
"undefined local variable or method `page'" error.
All other models work fine when I click on "New model-name"
FYI I have generated the administrate:view:new view files
Thank you in advance :D

**Comment by nickcharlton** [comment]
Interesting! Can you show an example of the models? Perhaps one of them has a different requirement which Administrate doesn't like.

**Comment by carlosramireziii** [comment]
@stoge Just following up on this...

Would you be able to provide a Gist with the relevant files (routes, dashboard, controller)? That would help us figure out the source of the issue.

Thanks!

**Comment by stoge** [comment]
Hi there sorry for not responding earlier,

Unfortunately, I am no longer able to help you, since I've tried something else.
Sorry for any inconvenience caused
