### ISSUE TITLE
DashboardGenerator does not update routes

### ISSUE THREAD

**Issue by mcmire** [thoughtbot/administrate#720]
Apologies if someone else has already submitted this.

If you use `rails g administrate:dashboard` to create a new dashboard file, the new dashboard is not added to `config/routes.rb`, and thus it does not appear automatically in the sidebar. I realize this is probably on purpose; after all, how is the generator going to know where in the routes file it needs to add a new line, especially if you've rearranged things? If that's the case, then I feel like the generator needs to display some kind of instructions when you run it to inform the user that they need to do this manually. For instance, if you ran `rails g administrate:dashboard Foo`, you would see something like:

> As you can see above, Administrate created files for the new dashboard. However, right now you won't see a new item in the sidebar. To make that happen, you'll need to add a new line to your existing admin-related routes. For instance:
>
>     resources :foos

**Comment by rnice01** [comment]
Is this still open for PRs? I'm new to the Rails community is it common for the routes.rb file to be in a different folder? Seems like a lot of stuff in the install generator process relies on routes.rb to be in the config folder and not just the routes generator.

**Comment by nickcharlton** [comment]
Hi @rnice01!

Sure is!

It might be in a different place if you're using a lot of Rails Engines and so administrate (an Engine itself) might not be able to determine where to put things.

**Comment by rnicedep** [comment]
@nickcharlton Thanks for getting back to me, I'd love to work on something for this. After looking at the install and routes generator, it looks like both of them are looking directly at the /config directory from the Rails root for the routes.rb file. 

My idea for this PR is to create a generator helper method to first check where the routes.rb would be, like it is now, and if it can't find it then do a quick search through the project's directories from the Rails root for the routes.rb file.  This could then be used in any generator needing to find the routes.rb file like the install and routes generators. What are your thoughts for this?

**Comment by nickcharlton** [comment]
That sounds like a good idea! I look forward to seeing it.

**Comment by pablobm** [comment]
I'm going to close this one as there hasn't been any activity in a long time.
