### ISSUE TITLE
has_one nested form ?

### ISSUE THREAD

**Issue by qubitam** [thoughtbot/administrate#724]
Hello guys!

I am trying to use a has one nested form, The idea is I have two models user and profile, a user has_one :profile and the profile belongs_to :user, what I want to achieve is instead of creating a user first then go to the profiles and create one which belongs to a specific user, I want to create both from the users form so it show both user and profile attributes ?

I see I can achieve this by has_many nested form but any chance to get this working for has_one ?

and thanks in advance.

**Comment by stratigos** [comment]
@qubitam note that there is [currently no support for HasOne](https://github.com/thoughtbot/administrate/issues/443). You may need to use the workaround in #443 to meet your needs for now.

**Comment by carlosramireziii** [comment]
Closing this in favor of #443 which will be revisited soon.
