### ISSUE TITLE
Assets not loaded in production

### ISSUE THREAD

**Issue by bobbyworx** [thoughtbot/administrate#725]
Has anybody encountered problems with assets in production?

I ran `RAILS_ENV=production rake assets:precompile`, it did write the files, but no css appears to be loading in my app.

This is a part of my `production.log`:

`Rendered admin/application/_collection.html.erb (299.7ms)
D, [2017-01-05T14:04:35.104258 #17236] DEBUG -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]    (0.2ms)  SELECT COUNT(*) FROM `accounts`
I, [2017-01-05T14:04:35.120199 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]   Rendered admin/application/index.html.erb within layouts/administrate/application (390.2ms)
I, [2017-01-05T14:04:35.126552 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]   Rendered /usr/local/rvm/gems/ruby-2.2.2/gems/administrate-0.3.0/app/views/administrate/application/_stylesheet.html.erb (1.1ms)
I, [2017-01-05T14:04:35.133557 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]   Rendered /usr/local/rvm/gems/ruby-2.2.2/gems/administrate-0.3.0/app/views/administrate/application/_sidebar.html.erb (2.6ms)
I, [2017-01-05T14:04:35.138954 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]   Rendered /usr/local/rvm/gems/ruby-2.2.2/gems/administrate-0.3.0/app/views/administrate/application/_flashes.html.erb (0.7ms)
I, [2017-01-05T14:04:35.144039 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0]   Rendered /usr/local/rvm/gems/ruby-2.2.2/gems/administrate-0.3.0/app/views/administrate/application/_javascript.html.erb (1.0ms)
I, [2017-01-05T14:04:35.144489 #17236]  INFO -- : [67d946e0-e286-432f-ab5e-881ded8ea9b0] Completed 200 OK in 463ms (Views: 405.4ms | ActiveRecord: 39.5ms)
`

Cheers!

**Comment by kuboon** [comment]
Did you set '''config.serve_static_assets''' properly?

**Comment by bobbyworx** [comment]
I run it on Rails 5, so I've set `config.public_file_server.enabled = true` inside `production.rb`

**Comment by nickcharlton** [comment]
@bobbyworx: How are you getting on with this now?

**Comment by mbiang** [comment]
Getting this same issue.  @bobbyworx did you solve this? or had anyone else?

**Comment by BenMorganIO** [comment]
@bobbyworx Are you using Sprockets 4?

**Comment by bobbyworx** [comment]
Hi, I managed to load the assets by specifying a separate location inside nginx, called /assets with the http://127.0.0.1:3000/assets path.

Seems like the problem was not necessarily relating to the administrate gem.

Thanks!

**Comment by BenMorganIO** [comment]
You're welcome!
