### ISSUE TITLE
belongs_to with foreign_key not working

### ISSUE THREAD

**Issue by AkaiNNT** [thoughtbot/administrate#735]
#job.rb
`belongs_to :country, foreign_key: "country_code", class_name: "Country", primary_key: "cc_fips"`
`scope :country, ->(country_code) {where('jobs.country_code = ?', country_code)}`
#job_dashboard.rb
`country: Field::BelongsTo.with_options(class_name: "Country")`
When I chose a country in the drop-down list, it shows the error "Country  is required!"
Sorry i'm not good at english. Thanks for any help!

**Comment by BenMorganIO** [comment]
Hey @AkaiNNT,

What do your validations look like? You make be doing:

```ruby
validates :country, presence: true
```

If so, try switching it to:

```ruby
validates :country_id, presence: true
