### ISSUE TITLE
Date Field?

### ISSUE THREAD

**Issue by gregblass** [thoughtbot/administrate#741]
I defined an attribute in my schema with type "Date", but it is being defaulted to "DateTime". I tried to update this in ATTRIBUTE_TYPES and change it to Field::Date, but I'm getting: uninitialized constant Administrate::Field::Date.

Are date's without times not supported or am I doing something wrong? I would expect the 00:00:00 to not show up on the form and for the datepicker to not include the time control?

**Comment by gregblass** [comment]
I tried generating a field for type Date:

`rails generate administrate:views:field date`

The generator seemed to run fine, but I'm getting:

`uninitialized constant Administrate::Field::Date`

Anything I'm doing wrong here? Shouldn't there be fields for Date, Time, and DateTime individually? I use all 3 types typically depending if I need to store one, the other, or both.

**Comment by BenMorganIO** [comment]
Sorry, we've only got a field for `DateTime` ATM. If you'd like to do a PR and get a `Date` and `Time` field into this project, that'd be super appreciated! 👍

**Comment by gregblass** [comment]
Got it, thanks for the info!

**Comment by pablobm** [comment]
Implemented at https://github.com/thoughtbot/administrate/issues/741

**Comment by pablobm** [comment]
Implemented at https://github.com/thoughtbot/administrate/pull/1530
