### ISSUE TITLE
How to add custom CSS?

### ISSUE THREAD

**Issue by lauroengineer** [thoughtbot/administrate#748]
Hi :) How can I add custom css to the dashboard?

**Comment by klaseskilson** [comment]
I've managed to add custom stylesheets through these steps. Create an initializer like so:

```ruby
# config/initializers/administrate.rb
Administrate::Engine.add_stylesheet('your_stylesheet_name')
```

You might also have to add it to be compiled through the asset pipeline, which also can be done through an initializer:

```ruby
# config/initializers/assets.rb
Rails.application.config.assets.precompile += %w(your_stylesheet_name.css)
```

Don't forget to restart your Rails server after adding/editing these files.

**Comment by carlosramireziii** [comment]
@lauroengineer Does the method outlined by @klaseskilson work for you? If so, would you consider this issue as resolved?

**Comment by lauroengineer** [comment]
@carlosramireziii sorry about that. Yes, It worked! Thanks you @klaseskilson 👍

**Comment by causztic** [comment]
I did ```ruby rails generate administrate:assets:stylesheets``` instead and imported my stylesheets there.
