### ISSUE TITLE
Any release planned?

### ISSUE THREAD

**Issue by klaseskilson** [thoughtbot/administrate#749]
Hey,

Thanks for a great and powerful gem. Is there a release planned soon? There's been some [great additions](https://github.com/thoughtbot/administrate/compare/v0.3.0...master) since 0.3.0 and I'd love to use some of them in situations where a pre-release through git wont do.

Again, thanks for a great gem.

**Comment by nickcharlton** [comment]
Hi @klaseskilson!

Yes. I've been meaning to for a few weeks now, but I'd wanted to get a few things in before then ([this, for example](https://github.com/thoughtbot/administrate/issues/645)). We're good to go now, so I just need to sit down and do it.

**Comment by klaseskilson** [comment]
All right! Thanks for your answer. Sorry to bother you.
