### ISSUE TITLE
Feature Request: Alternate views to Grid

### ISSUE THREAD

**Issue by ckluis** [thoughtbot/administrate#751]
By default it appears that the admin functions are only in grid format.  

It would be nice to offer alternative views (when applicable)

- calendar
- column

Here is an example of alternate views being implemented on a grid: https://www.hubspot.com/hubfs/assets/hubspot.com/parrotdad/overview-pages/CRMOverview-2.png?t=1486691014704

**Comment by stevenmilton58** [comment]
IMHO, I believe administrate makes it quite easy to customize the views, and in the interest of keeping administrate lean and doing the basics really well, it would be detrimental to add an alternative view like you mentioned.

**Comment by nickcharlton** [comment]
I do like the idea of this, and would certainly welcome some example layouts that we could work with in a PR.

I wonder if extra layouts or just docs is the right approach here though? Maybe it could have an option in the generator for the type of layout?

**Comment by ckluis** [comment]
I'd love to do that for you but alas I'm not a Ruby developer.  If I were attempting to spec this out as a feature for the generator it would be nice to have options like:

layout options:
grid: yes
calendar: yes
column: yes
gallery: no
card: no
master/detail: no {email like layout with small amount of data on left and full data on right}

column options: 
column source: {field that is used to generate columns} opportunity stage

It seems like it does probably go beyond the intent of the project, but these types of layout options fulfill the majority of the use cases associated with an administrator backend.

**Comment by purinkle** [comment]
@ckluis, is this still a feature you want?

**Comment by ckluis** [comment]
I'm not in need of a new admin panel structure at this point, but the solution we did implement allows for alternative layout models (gantt, chart, table/grid, kanban board, calendar) - airtable has an extremely powerful representation of this for selecting between layouts on the fly based upon the data that is available.  Highly recommend trying airtable.
