### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by flavienhello** [thoughtbot/administrate#752]
Hello, 

Don't administrate has an export to CSV feature ?

I can't seem to find it ?

**Comment by bikramwp** [comment]
It would appear not -a grep shows the word 'csv' is not present in the source code?

**Comment by carlosramireziii** [comment]
@flavienhello As of now, Administrate does not have a CSV export feature. If you'd like to try your hand at creating one, a PR would be welcomed! Otherwise you can always add a custom action to your controller within your app to create one. 

Hope that helps!

**Comment by andreibondarev** [comment]
CSV exports available via this plugin: https://github.com/SourceLabsLLC/administrate_exportable
