### ISSUE TITLE
Last Commit Date 2 Years Ago, Project Looks Dead

### ISSUE THREAD

**Issue by pferdefleisch** [thoughtbot/administrate#753]
Sorry for the noise.

The last commit makes it look like the last commit to this repo was 2 years ago. I almost immediately picked ActiveAdmin for my new project until I read some issues and actually looked at the commit history.

It's been almost a week and it's hard to say how many people have skipped on using the project because of this.

Again, sorry for the noise. Cheers, Aaron

**Comment by nerdyglasses** [comment]
pferdefleisch 😂😂🐎🍽

**Comment by BenMorganIO** [comment]
lols :D

**Comment by tysongach** [comment]
@pferdefleisch The last commit was originally created in December 2015, but it was committed to `master` on February 10, 2017: about 10 days ago.

There’s been an uptick in work on Administrate recently and the team is actively making progress. 👍 

![screen shot 2017-02-21 at 08 41 32](https://cloud.githubusercontent.com/assets/903327/23167367/1f358b50-f812-11e6-89c8-75e536ae5212.png)

**Comment by pferdefleisch** [comment]
Hi @tysongach. Thank you.

As you can see above, I am aware of the commit history. I am happy that they have picked up on dev this year as well, it's a nice project.

It was just super confusing for me. Coming to the project that I swore was in active development in the middle of last year, only to see that there had been no development in over a year.

Then I read the commit history and thought I would give a heads up in case the maintainers cared that they might lose some folks because of this. Before I look at the code in a project, I always look at the last commit date first. And I don't think I'm alone in that.

Anyway, here's more noise, which I already apologized about.

**Comment by tysongach** [comment]
> only to see that there had been no development in over a year.

I think you might be confused, because there’s been 23 commits to `master` in 2017 alone: https://github.com/thoughtbot/administrate/commits/master
