### ISSUE TITLE
Administrate::Namespace#namespace_controller_paths

### ISSUE THREAD

**Issue by artificis** [thoughtbot/administrate#758]
I am trying to add devise for admin authentication. Here's a `routes.rb` file
```ruby
...
namespace :admin do
  resources :subscriptions
  root to: 'subscriptions#index'
end

devise_for :admin_users, controllers: {
  sessions: 'admin_users/sessions'
}
...
```

Now administrate throws a weird error saying `uninitialized constant AdminUsers::Session`.
So I decided to dig this gem source code and turns out that [this line](https://github.com/thoughtbot/administrate/blob/master/lib/administrate/namespace.rb#L19) causes this problem.
```ruby
def namespace_controller_paths
  all_controller_paths.select do |controller|
    controller.starts_with?(namespace.to_s)
  end
end
```

It should be `controller.starts_with?("#{namespace.to_s}/")` instead, no?

**Comment by omake43** [comment]
👍
