### ISSUE TITLE
Suggestion: Namespace controllers and dashboards under the "administrate" name

### ISSUE THREAD

**Issue by bikramwp** [thoughtbot/administrate#765]
For the sake of future-proofing, and in situations where the `admin` module/folder names are already using by an application using administrate, would it make sense to namespace files and constants that belong to administrate in this way?
```
app/controllers/administrate/foos_controller.rb
app/dashboards/administrate/foo_dashboard.rb
app/views/administrate/foo/index.html.erb
```

instead of the current:

```
app/controllers/admin/foos_controller.rb
app/dashboards/foo_dashboard.rb
```

I think that (might) also help in avoiding issues such as:

https://github.com/thoughtbot/administrate/issues/487
https://github.com/thoughtbot/administrate/issues/758

**Comment by cristianogregnanin** [comment]
Any updates about this problem?

**Comment by nickcharlton** [comment]
I'm going to close this as this problem should be solved [through namespacing](https://administrate-demo.herokuapp.com/getting_started). Please open a new issue if this isn't the case.
