### ISSUE TITLE
Has_many associations are nil

### ISSUE THREAD

**Issue by cw2908** [thoughtbot/administrate#768]
When a model contains `has_many` but there are no actual `has_many` relations, the related page can not be loaded.

The problem is within: `@data=nil,` and in  app/views/fields/has_many/index.html.erb:

`<%= pluralize(field.data.size, field.attribute.to_s.humanize.downcase) %>`

field.data.size fails because `.size` is not valid on `NilClass`.

**Comment by stevenmilton58** [comment]
I'm not seeing that error with Rails 5.0.2, administrate 0.3.0. Can you specify the versions you are using and add some context to reproduce the error?

**Comment by carlosramireziii** [comment]
@cw2908 I opened up a PR for this #771. Will that solve this issue?

**Comment by cw2908** [comment]
I actually figured out that this was caused by an unmigrated has_many when the table & database had been removed on another branch. The association was added to user_dashboard.rb because of the branch difference. Not sure if the pull request is still need it.

**Comment by carlosramireziii** [comment]
@cw2908 Got it. Thanks for the update! Going to close up this issue.
