### ISSUE TITLE
Suggestion: Disable click event on text selection in index tables

### ISSUE THREAD

**Issue by stevenmilton58** [thoughtbot/administrate#770]
Version: 0.4.0

On the index page of a give resource, it is currently not possible to select some information from the table without navigating away from the index page. 

Mouse down+drag to select text+mouse up causes navigation to occur when the intent was only to copy text, and not click. [Examples](https://www.google.ca/search?q=jquery+disable+click+event+when+selecting+text)

One fix would be to change the code in https://github.com/thoughtbot/administrate/blob/v0.4.0/app/assets/javascripts/administrate/components/table.js to:

```javascript
$(function() {
  var keycodes = { space: 32, enter: 13 };

  var visitDataUrl = function(event) {
    if (event.type=="click" ||
        event.keyCode == keycodes.space ||
        event.keyCode == keycodes.enter) {
      var selection = window.getSelection().toString(); // code added
      if (selection.length == 0) {  // code added
        if(!event.target.href) {
          window.location = $(event.target).closest("tr").data("url");
        }
      }
    }
  };

  $("table").on("click", ".table__row", visitDataUrl);
  $("table").on("keydown", ".table__row", visitDataUrl);
});

```

**Comment by carlosramireziii** [comment]
@stevenmilton58 Would you like to take a stab at a pull request for this?

**Comment by dsolomadin** [comment]
@stevenmilton58 Added PR to fix this
