### ISSUE TITLE
Error installing with Rails 5.1.0.rc1

### ISSUE THREAD

**Issue by heliostatic** [thoughtbot/administrate#802]
Tried installing with the source set to github:
`gem 'rails', '~> 5.1.0.rc1'`
`gem 'administrate', github: 'thoughtbot/administrate'`

```
Bundler could not find compatible versions for gem "sass-rails":
  In Gemfile:
    sass-rails

    administrate was resolved to 0.5.0, which depends on
      sass-rails (~> 5.0)
```

**Comment by nickcharlton** [comment]
Hi! Thanks for opening this. We've been working on Rails 5.1 support in #782, so I'm going to close this for now. I hope to have that merged reasonably soon, but we'd love to see any help on that PR if it fits!
