### ISSUE TITLE
Upgrading to 0.5.0 breaks because bourbon seems to be missing

### ISSUE THREAD

**Issue by AndrewVos** [thoughtbot/administrate#806]
```
ActionView::Template::Error (File to import not found or unreadable: bourbon.
Load paths:
```

I just bundle updated and I'm getting this. It seems bourbon has been upgraded, but I'm not sure why this error would be appearing? This is potentially broken on a fresh rails install?

**Comment by nickcharlton** [comment]
Hi @AndrewVos!

Yeah, unfortunately this happened. `0.5.0` upgraded Bourbon to `>= 5.0.0.beta.6`. Bourbon 5 removed the Rails/Rails::Engine path loading. This means that if we don't have Bourbon in the asset pipeline already, it doesn't get loaded.

You can see that in this commit on Bourbon: https://github.com/thoughtbot/bourbon/commit/73b09f618bd3189bf5af6f639e3df07680ed4fc7

We've been working on removing both Bourbon and Neat for the next release, as this has been causing some fun problems (see: #789, #798).

In the mean time, if you add bourbon to the top level Gemfile, this problem should go away.

**Comment by RavenXce** [comment]
Adding bourbon to the top level Gemfile does not make the problem go away for me:

```
gem 'administrate', '~> 0.5.0'
gem 'bourbon', '5.0.0.beta.6'
```

I had to add this to get it to work:

```
Rails.application.config.assets.paths << Bundler.load.specs.find { |s| s.name == 'bourbon' }.full_gem_path + '/core'
```

**Comment by BenMorganIO** [comment]
@RavenXce well, good news is that Bourbon will be going at some point :)

**Comment by ACPK** [comment]
@BenMorganIO - Any progress on removing Bourbon?
