### ISSUE TITLE
Using fields in a customized form

### ISSUE THREAD

**Issue by ilyapoz** [thoughtbot/administrate#811]
I'm trying to build a customized form layout (two columns, groups of fields etc etc).
I run into problems as there appears to be only `attributes` method accessible in `Administrate::Page::Form` and I cannot access `attribute_field` from `Page::Base`.
I tried adding a method along the lines of

    def attribute(attribute)
      attribute_field(dashboard, resource, attribute, :form)
    end

Somewhere here https://github.com/thoughtbot/administrate/blob/master/lib/administrate/page/form.rb#L18

It works for me but appears to be either an obviously lacking feature in administrate or me looking in the wrong direction.

Should I start a PR or is there another way to achieve this?

**Comment by purinkle** [comment]
@ilyapoz, is this still an issue for you?
