### ISSUE TITLE
Move the prototype/spec referenced images to a single, reliable source.

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#819]
It was pointed out by @BenMorganIO that we're loading a bunch of resources in from various places, when they saw a test failure:

```
Capybara::Poltergeist::StatusFailError:
  Request to 'http://127.0.0.1:37179/admin/products' failed to reach server, check DNS and/or server status - Timed out with the following resources still waiting https://cdn.recombu.com/mobile/images/news/M11370/1264769196_w670.jpg
  # ./spec/features/products_index_spec.rb:17:in `block (2 levels) in <top (required)>'
  # ./spec/support/background_jobs.rb:14:in `block (3 levels) in <top (required)>'
  # ./spec/support/background_jobs.rb:5:in `run_background_jobs_immediately'
  # ./spec/support/background_jobs.rb:13:in `block (2 levels) in <top (required)>'
```

We should move these to a single location, and maybe stub them out for tests to absolve us of remote dependencies.

**Comment by pustomytnyk** [comment]
@nickcharlton there is related option in docs for Capybara::Poltergeist::Driver:

> :phantomjs_options (Array) - Additional command line options to be passed to PhantomJS, e.g. ['--load-images=no', ...

but I didn't try it.
