### ISSUE TITLE
Getting a hash for name resources 

### ISSUE THREAD

**Issue by lauroengineer** [thoughtbot/administrate#831]
How do I go about changing hashes on my resources to their actual names or ids?

![pasted_image_at_2017_04_13_01_50_am](https://cloud.githubusercontent.com/assets/8277963/24993351/a24f123a-1feb-11e7-8693-d671f090c3b7.png)

**Comment by dsolomadin** [comment]
@lauroengineer You would need to edit Dashboard for that resource, just add this method:
```
def display_resource(project)
  project.title
end
```

**Comment by lauroengineer** [comment]
@dsolomadin that helped! Thanks! I was also able to show the users name instead of their ID. Which make displaying info a lot easier.
