### ISSUE TITLE
Question: Displaying image from Google Auth's URL image

### ISSUE THREAD

**Issue by lauroengineer** [thoughtbot/administrate#833]
I'm using Google Auth. And I am saving the URL image that google provides. I wan to display the image on my Administrate dashboard.  How can I take the URL and display it on the show page of the dashboard? 

`https://lh5.googleusercontent.com/AAAAAAAAOU/CNNT2cbSqoo/photo.jpg`

I manage to add Administrate Field Paperclip to my projects. But that only displays the image when Im using Paperclip. In this case, I only have the image URL. 

![pasted image at 2017_04_13 06_31    ###pm](https://cloud.githubusercontent.com/assets/8277963/25028207/5aef1696-2078-11e7-9368-3dc0df87c0cb.png)

Any thoughts? Appreciate a lot! 😄

**Comment by dsolomadin** [comment]
@lauroengineer 
You would need to create a new field to display the link. 
Use this command to generate a new field: `rails generate administrate:field gravatar`
Then edit the show partial so it would render an `img` tag instead of a string.

**Comment by dsolomadin** [comment]
@lauroengineer More info can be found here: 
https://administrate-prototype.herokuapp.com/adding_custom_field_types

**Comment by lauroengineer** [comment]
@dsolomadin I appreciate the help. Thanks! 👍 

If anyone else stumbles into this thread. Taking a look at this screencast was also very helpful in walking you through the process of adding custom fields types: https://gorails.com/episodes/administrate

We can go ahead and close this thread.

**Comment by BenMorganIO** [comment]
@lauroengineer have you checked out https://github.com/thoughtbot/administrate-field-image?

**Comment by BenMorganIO** [comment]
Closed since this is a question. Let me know if this repo helps you. If not, let me know what some of the shortcomings were or if it didn't actually solve your issue :)
