### ISSUE TITLE
UI/UX/Design style guide for contributors and plugin authors

### ISSUE THREAD

**Issue by jayroh** [thoughtbot/administrate#834]
As someone who would love to create a plugin, or several plugins, for administrate I would love to make sure I stay within the boundaries of the administrate style and visual direction. As a result - something like a style guide, or a series of suggestions regarding colors, type, spacing, state behavior, etc, would be extremely helpful.

**Comment by carlosramireziii** [comment]
Hey @jayroh -- is this similar (possibly a duplicate request) of #828?

**Comment by tysongach** [comment]
I see the architecture as explanation of class names, linting, etc. and this style guide as “here is how we typically build the UI for XYZ form field.”

**Comment by carlosramireziii** [comment]
Got it! Thanks for clarifying @tysongach

**Comment by jayroh** [comment]
I should have been more clear, so - great point, @carlosramireziii. I updated the title of the issue to be more specific.

👍

**Comment by kevinelliott** [comment]
I'm confused. Why should anyone add more plugins or additions to administrate when as far as I can tell very few pull requests are getting merged. There are tons of PRs that are open (about 74 currently), some dating as far back as 2015. So many of them are passing CI and have no reviews or comments from anyone working on the project.

As far as I can tell, this project has stalled out, and only major bugs are being addressed.

**Comment by jayroh** [comment]
@kevinelliott - I can assure you that that's not the case. That being said - you are entitled to your opinion.

However, please understand that the people working on this do their best with the limited time they have. Remember - this is free software. No one is required to do anything by any time, on any one person's arbitrary deadline, and everyone is allowed to use it how they see fit.

**Comment by kevinelliott** [comment]
@jayroh I meant no insult. I'm only reporting on what seems to be true.

There are so so so many PRs where there are no official replies about whether or not they are useful, acceptable, problematic, etc. All of those developers put time in to augment and add to the project, but yet they've received no feedback on whether or not their work is valued. So many of these PRs are from 2016 and some from 2015. Most with no feedback or mention.

Looking at the recently merged PRs, and you see that they are generally bug fixes, but not significant improvements to the codebase.

That's fine ... as all open source projects, the maintainers get to say how the project is run and what gets added and what doesn't. And it's all too common that people get busy and work on other things, shifting their attention away. That's ok too.

But usually this can be resolved by building some relationships with other key stakeholders and giving them some privileges to help manage the in-flow. If that doesn't happen, stuff just gets backed up. Like the 74 PRs waiting in the queue to be reviewed, and the 99 issues still hanging in the lurch.

It's your choice to expand or not... and I don't fault anyone for that either. But don't expect anyone to feel good about contributing if they know their issues or pull requests are going to get ignored for 2 years.

**Comment by BenMorganIO** [comment]
@kevinelliott 

There _was_ a time when the project was stalled. You can see from the open PRs, a lot of them are very recent. Then there's a gap, then you see all of the old PRs and issues that require triaging. It's deceptive, but no, this project isn't stalled ATM.

AFAIK Thoughtbot doesn't supply project management to a specific project. It's simply Fridays are days in which developers can choose to work on an open source project. With all of the changes happening to the project right now for maintenance and to remove dependencies and whatnot, it's difficult to get a Thoughtbot devs time. We have to wait for Friday.

**Comment by kevinelliott** [comment]
@BenMorganIO Thank you for the clarification. That's useful to know.

**Comment by nickcharlton** [comment]
I'm going to close this as there's no immediate move to create a style guide; I'd recommend copying what's already here if you're starting a project and by all means open an issue if you'd like to clarify something.
