### ISSUE TITLE
uninitialized constant Admin::Administrate

### ISSUE THREAD

**Issue by wcp12** [thoughtbot/administrate#847]
Hi, after I ran rails generate administrate:install 
I tried to access the admin through url by putting /admin at the end but it gave me an error saying 
uninitialized constant Admin::Administrate. 
Here is a screenshot of the error message.
<img width="492" alt="screenshot 2017-04-29 17 24 48" src="https://cloud.githubusercontent.com/assets/23250002/25559019/0158a1e8-2d01-11e7-8bd9-7c01e1c5d871.png">

Here is a screenshot of my workspace. 
<img width="200" alt="screenshot 2017-04-29 17 27 19" src="https://cloud.githubusercontent.com/assets/23250002/25559032/23c61b2a-2d01-11e7-93a0-ff78ffa19990.png">

What is the problem?

**Comment by BenMorganIO** [comment]
Can we see the offending code?

**Comment by wcp12** [comment]
This is my original ApplicationController

<img width="450" alt="screenshot 2017-04-29 17 49 09" src="https://cloud.githubusercontent.com/assets/23250002/25559171/29e82e32-2d04-11e7-9712-4476a28b8fde.png">

and this is my admin ApplicationController
<img width="642" alt="screenshot 2017-04-29 17 49 04" src="https://cloud.githubusercontent.com/assets/23250002/25559176/3d4eedf8-2d04-11e7-98eb-c69097d2e415.png">

**Comment by wcp12** [comment]
and this is what i have in my route.rb

Rails.application.routes.draw do
  
  namespace :admin do
    resources :users
    resources :posts

    root to: "posts#index"
  end
  
  devise_for :users
  resources :posts
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'application#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

**Comment by BenMorganIO** [comment]
I don't think your application is aware of the `Administrate` module. It looks like an issue that's possibly in your Gemfile. You'll need to make sure you have administrate in your Gemfile and everything has properly booted.

**Comment by observingly** [comment]
Put this on your application.rb `config.api_only = false`

**Comment by kaimantsch** [comment]
I have the identical issue and setup. Here is the result of running bundle install to confirm gem:

```
Using administrate 0.8.1
Bundle complete! 37 Gemfile dependencies, 155 gems now installed.
Bundled gems are installed into /usr/local/bundle.
```

**Comment by VitaliyAdamkov** [comment]
Look to your routes, I've got the same problem because of my custom routes inside :admin namespace

**Comment by shrugs** [comment]
(this can also happen if you forgot to include the `administrate` gem for some reason or another... happened to a friend of mine that definitely wasn't me)

**Comment by yiyuanc** [comment]
try restarting and run `bundle exec` again. that solved my problem.
