### ISSUE TITLE
Is it possible to specify sort order for related fields?

### ISSUE THREAD

**Issue by oowowaee** [thoughtbot/administrate#848]
I see https://github.com/thoughtbot/administrate/pull/750 was closed - I have BelongsTo fields that I would like to specify sort order for - is there any way to do it?

**Comment by BenMorganIO** [comment]
Why not use `sort_by` with the foreign key?

**Comment by oowowaee** [comment]
Is that possible?  I had tried that, as well as the merged PR, and the closed one, but it looked to me like
https://github.com/thoughtbot/administrate/blob/5ebdb1a47b53cb020db2a5ae75a6b797392c1690/lib/administrate/field/belongs_to.rb#L27 implies that there is no option.  For the moment I just added my own code to check for a passed option.

**Comment by oowowaee** [comment]
Seems like this was finally addressed in https://github.com/thoughtbot/administrate/pull/939

**Comment by nickcharlton** [comment]
I'm going to close this issue as it seems it was fixed in #939. Please open a new issue if this isn't quite the case!
