### ISSUE TITLE
Sorting HasMany fields on show page

### ISSUE THREAD

**Issue by pauldub** [thoughtbot/administrate#858]
It is currently not possible to sort an `HasMany` field on the model's show view such as http://administrate-prototype.herokuapp.com/admin/customers/9085?direction=asc&order=address_state. There was a similar issue with its pagination which was fixed with release `0.5.0`. 

I have implemented it on a fork but I think it would require a bit more work. My implementation is based on the work done in PR https://github.com/thoughtbot/administrate/pull/736 

I suggest that we use a convention of `#{attr_name}[param]`, for example `orders[page]` for the pagination and `orders[direction]` & `orders[order]` for sorting. But the issue is that there is currently no proper way to do this except by adding more arguments to the `Page::Collection` methods. Maybe a better solution would be to be able to propagate request parameters through `Page#attribute_field` overriding options for the field. It would be consistent with the `HasMany` field implementation and its pagination could be implemented that way too (having `page` as an option).

What are your thoughts about this? I am willing to push this (small) feature as it is a great quality of life improvement and follows the extensibility goals set by the project.

**Comment by nickcharlton** [comment]
Hi @pauldub! I just saw this after looking into some pagination changes. Assuming you haven't already, a PR would be the best thing to do from here. It sounds like something we should do!

I'm going to close this issue for now, as a PR would be a much better place to discuss it.
