### ISSUE TITLE
Improve error state visual design

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/administrate#860]
The flash messages could be improved to better fit within the layout, as well as group together multiple errors and their label/description.

![screen shot 2017-05-05 at 14 14 21](https://cloud.githubusercontent.com/assets/903327/25758592/2c951af8-319d-11e7-8303-35cb561c9dd4.png)

**Comment by PapePathe** [comment]
+1

**Comment by admir23** [comment]
Hey @tysongach ,
I've would like to tackle this please :)

Thanks
Admir
