### ISSUE TITLE
administrate:views:layout task doesn't generate stylesheet partial

### ISSUE THREAD

**Issue by apraditya** [thoughtbot/administrate#888]
I'm using 0.7.0. The `administrate:views:layout` task doesn't generate `app/views/admin/application/_stylesheet.html.erb` file.

**Comment by professorNim** [comment]
Additionally, the generator doesn't generate the search partial. Is this intended behavior?

**Comment by nickcharlton** [comment]
Nice catch! I've opened #916 to add this in.

**Comment by nickcharlton** [comment]
@professorNim It sounds like we're missing generators for it. Could you open an issue (or better) a PR?

**Comment by professorNim** [comment]
@nickcharlton I'm confused, didn't you do just that with #916?
