### ISSUE TITLE
Selectize.define is not a function

### ISSUE THREAD

**Issue by ghost** [thoughtbot/administrate#889]
Using Administrate 0.7.0 I have this error in the console.

<img width="1505" alt="screen shot 2017-05-15 at 7 32 15 pm" src="https://cloud.githubusercontent.com/assets/947968/26055866/4e1a2a78-39a5-11e7-8032-005f983e35fd.png">

**Comment by nickcharlton** [comment]
Hi @invulsion. Which browser versions are you seeing this with?

Can you see the same on the [public prototype app](http://administrate-prototype.herokuapp.com/admin/line_items)?

**Comment by invulsion** [comment]
@nickcharlton the public prototype seems to work fine.
I'm using Chrome Version 58.0.3029.110 (64-bit) on Mac OS X.

PS: The data search field is broken. When I click inside it, it doesn't focus the input field. It was working fine before the major redesign.

**Comment by purinkle** [comment]
User no longer exists.

Closing.
