### ISSUE TITLE
Entire search bar is not clickable

### ISSUE THREAD

**Issue by ianagne** [thoughtbot/administrate#895]
![customers - administrate prototype 2017-05-18 10-33-28](https://cloud.githubusercontent.com/assets/9160106/26210759/47a129fe-3bb6-11e7-8514-01d79f4d740b.png)

This was picked up during QA while testing v0.7.0.  The `.search__hint` blocks a portion of the search bar from being clicked.  Users attempting to activate the search input by clicking on the word "Search" are unable to.  The rest of the bar is clickable.

**Comment by nickcharlton** [comment]
Closing as we've merged #896.
