### ISSUE TITLE
Nested resources in admin namespace throwing errors

### ISSUE THREAD

**Issue by kennymkchan** [thoughtbot/administrate#899]
Can anyone help with this? I have a nested resource within the admin namespace, but it does not seem like administrate registers the path. 

routes.rb
```
  namespace :admin do
    resources :locales do
      resources :translations, constraints: { id: /[^\/]+/ }
    end
  end
```

Running `rake routes`:
![screen shot 2017-05-19 at 10 06 31 am](https://cloud.githubusercontent.com/assets/22083509/26251547/9fe5666e-3c7b-11e7-8059-aa4aaf989c71.png)

Error:
<img width="997" alt="screen shot 2017-05-19 at 10 10 27 am" src="https://cloud.githubusercontent.com/assets/22083509/26251567/aded774c-3c7b-11e7-8256-68edeff9ad53.png">

Has anyone had success with nested resources ?

**Comment by nickcharlton** [comment]
I _suspect_ this is related to the same stuff as we're seeing with namespaced models (see #871) , and so we'll need to do a bit of work so that it's supported.

Would you be up for exploring what we'd need to do?

**Comment by gnagno** [comment]
Hello,

I just came across this issue on a project I'm working on, is there any plan to fix it or you need some help for it?

**Comment by nickcharlton** [comment]
Hi @gnagno! I'd be more than happy to see a PR related to this, if you were able.

**Comment by lubc** [comment]
Same issue here. To fix it I generated the views that raise errors and manually fixed the path of the links. I also did something similar with the controller, since the redirect paths also raise errors so I tweaked the create, update, and destroy actions. Not sure if there's a better solution for this.

**Comment by dankmitchell** [comment]
I think I have a similar issue here, I get `uninitialized constant Event::Speaker` with the below setup

routes.rb
```
namespace :admin do
    resources :events do
      scope module: :events do
        resources :speakers, on: :member
      end
    end
end
```

dashboards/event/speaker_dashboard.rb
```
class Event::SpeakerDashboard < Administrate::BaseDashboard
    # normal
end
```

controllers/admin/events/speakers_controller.rb
```
module Admin
  class Events::SpeakersController < Admin::ApplicationController
    def scoped_resource
      @event = ::Event.find_by!(slug: params[:event_id])
      @event.speakers.all
    end
  end
end
```

Any ideas?

**Comment by nickcharlton** [comment]
Is anyone able to confirm if this is still an issue? We've made a bunch of changes around this in the past year, but replicating the data structure with nested models is a bit complex.

If someone can, would anyone then be able to extract a sample app we could take a look at?

**Comment by smgnworld** [comment]
Hey @nickcharlton,

Still getting this error.
In my case I have following routes:

> namespace :admin do
>   resources :users do
>      resources :email_addresses
>   end 
> end

![Screenshot from 2020-11-02 15-51-19](https://user-images.githubusercontent.com/29263710/97875740-86596b00-1d23-11eb-87ac-95db8218e79c.png)

**Comment by nickcharlton** [comment]
It's been a while since, but can you confirm which version of Administrate you're using?

**Comment by smgnworld** [comment]
> It's been a while since, but can you confirm which version of Administrate you're using?

Double-checked and now that works.
Thanks for your reply, going to close issue.

**Comment by nickcharlton** [comment]
Great thanks for reporting back! I guess we solved it between now and the realise the other day.

**Comment by JoeDupuis** [comment]
Do you know which commit fixed the issue? I still have it on `0.15.0`.

**Comment by smgnworld** [comment]
@JoeDupuis 

This way solved the problem in my case:

`resources :email_addresses`

`resources :users do`
 `resources :email_addresses`
 `end `

When I didn't specify **resources :email_addresses** separately(not only as nested resources) then it failed.

**Comment by JoeDupuis** [comment]
This removes the error, but it is not the behavior I want. Here's a simplified version of my use case:
```ruby
resources :events do
   resources :event_registrations, only: [:index, :show], shallow: true
end
```
This makes the index nested, but the show not nested.

In your route example, it would expose a root email_addresses#index route (`/admin/email_addresses`). I am not exposing a root index route (only a nested one) on purpose. I do not want the resource to show in the navigation.

Currently, administrate tries to hide a resource from the nav if it doesn't have an index route. Which is great. Though if you need a nested index route, the way it checks for index routes will also find nested index route and then it assume all those are root index routes (not nested).

That is why we get the error and why it disappear if you also have a non nested index route for the same resource.

The fix I have been using for ages:

is replacing :
https://github.com/thoughtbot/administrate/blob/master/app/views/administrate/application/_navigation.html.erb#L13

with 

```ruby
  <% nav_resources.each do |resource| %>
```

where `nav_resources` is an array of resources I want to expose in the nav.

It would be much more convenient if administrate was able to only return the routes with *root* index  in [resources_with_index_route](https://github.com/thoughtbot/administrate/blob/06a5a1f00992dbe715ed30e4df76bd8a58ce95c1/lib/administrate/namespace.rb#L21)

I tried to look into it briefly, but I think I was playing with Rails private API, which isn't safe to do and I don't have the time currently. I'll try to revisit some day.
