### ISSUE TITLE
I already have an /admin route

### ISSUE THREAD

**Issue by andreheijstek** [thoughtbot/administrate#900]
My app already has an admin route. Will administrate overwrite this? Is there a way to tell the generator to create another route?

**Comment by jondkinney** [comment]
I just started digging into this gem an hour ago, but it doesn't overwrite the admin route. In fact, it also doesn't set a root route for the admin namespace, so if you do have an admin namespace and users route, for example... when you try to load up /admin it will say no route found. If you go to /admin/users though it'll work. So I spun up a blank rails app to test this out and they add a root specification to fix that issue when they generate the initial admin route namespace block:

```ruby
  namespace :admin do
    resources :users

    root to: "users#index"
  end
```

So you can run the generator and it'll be fine / won't overwrite your existing route (from my limited 1-resource test), you'll just have to add the root line. Hope this helps.

**Comment by nickcharlton** [comment]
@jondkinney is correct. The administrate generator will inject code into the routes, but you'll be able to change them. I don't know of anything else that assumes the path.

I'm going to close this for now, but please reopen it if it doesn't solve your problem.
