### ISSUE TITLE
include FactoryGirl::Syntax::Methods breaks controller inheritance of create action

### ISSUE THREAD

**Issue by jondkinney** [thoughtbot/administrate#901]
I'm honestly amazed I was able to track it down to this...but including this line in development.rb `include FactoryGirl::Syntax::Methods` at the bottom, like so:

```ruby
Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded on
  # every request. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.cache_classes = false

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable/disable caching. By default caching is disabled.
  if Rails.root.join('tmp/caching-dev.txt').exist?
    config.action_controller.perform_caching = true

    config.cache_store = :memory_store
    config.public_file_server.headers = {
      'Cache-Control' => "public, max-age=#{2.days.seconds.to_i}"
    }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  config.action_mailer.perform_caching = false

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Debug mode disables concatenation and preprocessing of assets.
  # This option may cause significant delays in view rendering with a large
  # number of complex assets.
  config.assets.debug = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations
  # config.action_view.raise_on_missing_translations = true

  # Use an evented file watcher to asynchronously detect changes in source code,
  # routes, locales, etc. This feature depends on the listen gem.
  config.file_watcher = ActiveSupport::EventedFileUpdateChecker
end
include FactoryGirl::Syntax::Methods
```

...which I usually do for all my apps so that when I pull open the development console with `--sandbox` I can use `create(:user)` instead of `FactoryGirl.create(:user)` (or whatever resource I'm monkeying around with to troubleshoot something or generate some data to manually test with.).

Any idea why this would cause administrate to not be able to find the `create` action from the inherited controller?

The error that I get is `The action 'create' could not be found for Admin::UsersController` (it's not unique to the users controller though, all the resources can't create through administrate).

I know everything is wired up properly with the inheritance...

![image](https://cloud.githubusercontent.com/assets/4521/26278348/e69c4cde-3d5d-11e7-9c5f-8ef18d6df72b.png)

And all the other actions work fine, too (even when this above error is presenting), so I'm not sure why only `create` specifically breaks here.

I'll not include the syntax methods in development.rb for now to work around this, but I'd love to figure out what is going on...thoughts?

**Comment by pustomytnyk** [comment]
@jondkinney there is similar problem over github issues, eg. https://github.com/thoughtbot/factory_girl_rails/issues/69.
As I understand, the module pollutes namespace of base class `Object` which breaks Rails controller magic.

**Comment by jondkinney** [comment]
@pustomytnyk aaah, that makes a ton of sense. Thanks for that!
