### ISSUE TITLE
rails 5.1 Support .  

### ISSUE THREAD

**Issue by PapePathe** [thoughtbot/administrate#905]
Hello @team i have issue with the gem. I was using the allow-rails-5-1 branch according to the gem. I want to deploy it on production but bundler cannot install gems, it seems like the branch is deleted...

> 
**### Revision allow-rails-5-1 does not exist in the repository https://github.com/tiagoamaro/administrate.git. Maybe you misspelled it?**

**Comment by stevensona** [comment]
That branch was merged into master #856
