### ISSUE TITLE
A new release to support 5.1.1

### ISSUE THREAD

**Issue by ThisIsMissEm** [thoughtbot/administrate#907]
Hi!

It seems the gemspec for 0.7.0 of administrate excludes rails > 5.1, which means the latest stable rails is not compatible with Adminstrate. However, Adminstrate on master does allow up to 5.2; 

All that I'm looking for is a new release which supports 5.1.1

**Comment by chupa-cabras** [comment]
I am the waiting for too .

**Comment by harisadam** [comment]
@ThisIsMissEm looks like there is an unreleased a commit that solves that issue: https://github.com/thoughtbot/administrate/commit/396a31d4773776b2a366087877537d65c8ca254d

should be ok w/ `gem 'administrate', github: 'thoughtbot/administrate'`

**Comment by chupa-cabras** [comment]
It works for me . Thanks :-)

**Comment by ThisIsMissEm** [comment]
Unfortunately I can't use that as I'm having Administrate in a rails engine, where github ref'd gems don't work due to gemspec

**Comment by jslag** [comment]
See https://github.com/thoughtbot/administrate/milestone/8

**Comment by ThisIsMissEm** [comment]
Aha! I missed that when looking at the issues on the project.

Thanks for the update.

**Comment by AkaiNNT** [comment]
I just updated my app to 5.1.1 and use my gem: `gem 'administrate', github: 'thoughtbot/administrate'` but sass and js doesn't work. How can I fix it? Thanks for any help!

**Comment by azeemh** [comment]
Hi just a bump how can i help accelerate the availability of administrate for rails 5.1.1. i'd really like to use it in a project I am working on right for work?

**Comment by nickcharlton** [comment]
I'm planning a release tomorrow (14th July). It's been a little while and I've only been triaging incoming stuff, so I suspect I'll bump a bunch from that `0.8.0` milestone, but we'll see.

**Comment by nickcharlton** [comment]
We've done this, so I'm going to close this issue.
