### ISSUE TITLE
How to setting an association field and customize it with paperclip

### ISSUE THREAD

**Issue by oolzpishere** [thoughtbot/administrate#909]
I have a Gallery model, setting has_many association with Image model: 

`has_many :images, dependent: :destroy`

How can I set paperclip to Image model, and to be a field of gallery.

**Comment by nickcharlton** [comment]
Hi @oolzpishere! I'd recommend opening this on [paperclip](https://github.com/thoughtbot/paperclip) as you'll likely get a better answer there than on administrate. If you're trying to use paperclip with administrate, there's [a plugin which brings support for it](https://github.com/picandocodigo/administrate-field-paperclip).
