### ISSUE TITLE
Launching the sample app locally with rails s doesn't load ENV variables

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#929]
When launching the sample app locally, the `ENV` variables are not loaded, so you get this error:

```
DEPRECATION WARNING: You didn't set `secret_key_base`. Read the upgrade documentation to learn more about this new config option. (called from env_config at /Users/nickcharlton/.gem/ruby/2.4.1/gems/railties-5.1.1/lib/rails/application.rb:247)
[2017-07-11 17:08:16] ERROR RuntimeError: Missing `secret_key_base` for 'development' environment, set this value in `config/secrets.yml`
```

We should figure out how to ensure a `.env` is loaded when you do a `rails s`.

**Comment by znvPredatoR** [comment]
I think hardcoded `secret_key_base` for dev env would solve that problem. Is there any downside to hardcoding it for development environment?

**Comment by nickcharlton** [comment]
Yeah, that could work. I don't think we've got anything else we're concerned with loading locally and I don't feel like that'll change soon.
