### ISSUE TITLE
Normalize asset file not included in gem

### ISSUE THREAD

**Issue by gchaturvedi** [thoughtbot/administrate#932]
Since the change to put the normalize css file in the assets subdirectory, the asset isn't included in the gem.  It has to be manually added into your own Rails app under vendor.

**Comment by tysongach** [comment]
Yep, I’m seeing the same thing. This PR is relevant: https://github.com/thoughtbot/administrate/pull/882

![localhost-5000- laptop with hidpi screen](https://user-images.githubusercontent.com/903327/28217939-f9f97e94-6884-11e7-9f8b-14593a22261b.png)

**Comment by dsolomadin** [comment]
@nickcharlton would be really nice if you could follow up with new release

**Comment by tysongach** [comment]
@dsolomadin We will; only been 10 minutes ;)

**Comment by dsolomadin** [comment]
cool, no pressure guys 😄

**Comment by nickcharlton** [comment]
I released 0.8.1 which fixes this: https://github.com/thoughtbot/administrate/releases/tag/v0.8.1
