### ISSUE TITLE
Can custom field plugins reformat data on submit?

### ISSUE THREAD

**Issue by bryanbraun** [thoughtbot/administrate#937]
Hey there 👋 .

[An issue came up](https://github.com/eddietejeda/administrate-field-json/issues/12) for the administrate-field-json plugin, where making edits to json data would fail for sites using Postgresql's native `json` or `jsonb` datatypes.

This is because the json is being submitted as a string, but the database expects a native json object.

I can't find a way from within a custom field plugin to reformat this data on submit.

It seems like this would be a common need. Forms usually need stringifield values, but there are plenty of data-types where the database isn't expecting a string (like `hstore`, `xml`, or [others supported by rails](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L69)). Any thoughts on how we can handle these cases from within a custom field plugin?

**Comment by pustomytnyk** [comment]
I think you will need to add smth. like `def process_params(controller_params)` to a field and call it from `controller#update` > some new method `dashboard#process_params` > chain `process_params` of fields. It is not cool to share all controller params with a field, but I don't see another way.

**Comment by nickcharlton** [comment]
Hi @bryanbraun!

This sounds like a great idea, but I don't have any particular insight into what I think would work best.

Since you'd opened this issue, have you had any ideas?

**Comment by bryanbraun** [comment]
Yeah I haven't had any ideas on how to implement this yet. I was able to find a workaround by [using a before_save callback](https://github.com/eddietejeda/administrate-field-json/issues/12#issuecomment-317206428). That's not something you can implement in a field plugin, but it allowed me to move forward.

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time and I'm not sure if there's a good solution to this; it's something that would be good to revisit in the future though.
