### ISSUE TITLE
How to rename dashboard

### ISSUE THREAD

**Issue by rozhok** [thoughtbot/administrate#938]
By default it generates name from the model name, but I want to pass i18n'ed name here or whatever thing I like. Where could I do this?

Thanks.

**Comment by pustomytnyk** [comment]
@rozhok do you want to pass argument to the generator or to show different name in sidebar?

**Comment by rozhok** [comment]
I dunno what is generator.

I have name in the sidebar, name in the header and name in the searchbar. I want to localize them.

**Comment by pustomytnyk** [comment]
if you check gem's source, you'll see that it uses http://guides.rubyonrails.org/i18n.html#translations-for-active-record-models

**Comment by rozhok** [comment]
Cool, thanks.
The only lasting question is localizing of search string (it won't work with separate words in Russian for instance, I need to localize whole sentence)

**Comment by nickcharlton** [comment]
Could you provide an example of what that might look like?

**Comment by rozhok** [comment]
For instance, I have model named Cat, search string placeholder will be "Search cats"
If I localize it, it would look like "Кіт" (model name), "Шукати Коти" (search string placeholder), but it should be "Шукати Котів" because regular plural form can't be used here.

**Comment by nickcharlton** [comment]
I didn't really understand, so I asked one of the developers at the client I'm working with at the moment to try and explain (he speaks Russian and not Ukrainian, but that was close enough for us to figure it out!).

From what I now understand:

* Depending on context there are different kinds of pluralisation.
* This means that you can't do "cats" and "search for cats", as pluralising for the second one should be a different word.

This lead us to this issue: https://stackoverflow.com/questions/12488705/incorrect-pluralizing-of-model-in-rails  
And this commit: https://github.com/rails/rails/commit/c300dca9963bda78b8f358dbcb59cabcdc5e1dc9

Anyway. The recommendation I got was to hard code the translation (assuming that this is practical). If there's not an easy way to do this, we should look at changing the way we localise strings to make it possible. There may or may not already be some open issues and/or PRs for this. I'm not really sure as I didn't until today really understand it!

**Comment by rozhok** [comment]
I can't hardcode because it will change dashboard name.
So, what I'd like to do something like is:
Model – "Cat" (`activerecord.model.cat.one: Cat`)
Dashboard name – "Cats" (`activerecord.model.cat.other: Cats`)
Search string – "Search for kitties" <--- how do I hardcode this?

**Comment by rozhok** [comment]
Oh, I see – I could change `uk.administrate.search` to what I need. Is there way to use `%{resource}` method? Like `%{resource.name}`?

**Comment by nickcharlton** [comment]
Ah, I see, too.

I think you could override it in the locale:

```yaml
search:
  clear: Clear search
  label: Search %{resource}
```

See: https://github.com/thoughtbot/administrate/blob/190cfe5438a56a3021774c9bf98a05dabffba0e1/config/locales/administrate.en.yml#L28

**Comment by rozhok** [comment]
Yeah, that's right, but how do I localize placeholder strings across the different dashboards? Is there way to call some method on `%{resource}`?

**Comment by nickcharlton** [comment]
I'm really not sure. If this is something that'll help localisation, I think it'd be great to have it added (if it's not there).

**Comment by rozhok** [comment]
Another question – how to localize `New` button:
![image](https://user-images.githubusercontent.com/1721631/29074364-a9e241a2-7c57-11e7-81a5-4f6e96e332b4.png)

**Comment by nickcharlton** [comment]
@rozhok Could you open a new issue for that?

I think we're done with the original problem, so I'm going to close this for now.

**Comment by rozhok** [comment]
Thanks, opened #963
