### ISSUE TITLE
How to display column with object number?

### ISSUE THREAD

**Issue by rozhok** [thoughtbot/administrate#943]
I have a bunch of objects and I'd like to display sequenced number for them.
I can't rely on default model ids because I have some objects removed and id does not show real object number for me.

Is there way to add such field? I lurked around and founded only https://github.com/djreimer/sequenced but not sure if it will be suitable for my task.

**Comment by rozhok** [comment]
So I went to custom attribute `order_number` which was implemented like this:
```ruby
  def order_number
    previous = Registration.where('id < ?', id).last
    if previous.nil?
      1
    else
      previous.order_number + 1
    end
  end
```
I don't think it's good for performance, but I don't have many of records, so I'm fine with this tradeoff.

**Comment by pustomytnyk** [comment]
in current version of Administrate you probably need to override `index` action and do some calculations based on current page from paginator. Not sure.

**Comment by rozhok** [comment]
Yeah,  but it seems a bit heavy for me. Would be nice to have such column out-of-the-box.

**Comment by nickcharlton** [comment]
I think you’d need to override `index`, as far as I’m aware. It’s a bit of a pain, but this isn’t something I think we’d do before 1.0.

**Comment by purinkle** [comment]
@rozhok, is this still an issue for you?

**Comment by rozhok** [comment]
Nope. Let's close this :)
