### ISSUE TITLE
Support for isolated engines?

### ISSUE THREAD

**Issue by krzysiek1507** [thoughtbot/administrate#948]
Did you think about support for isolated engines?

I took a look at the code and it requires a lot of changes because namespaced classes drop namespace. E.g. class `Blog::Post` drops `blog` everywhere (routes, params key, URL helpers etc).

Should I try to add support for it?

**Comment by nickcharlton** [comment]
I don’t think I’m quite sure on what you mean by “isolated engines”, but it sounds like it’d open up support for more types of usage.

If you’d be up for trying out a PR, I’d be happy to look at it!

**Comment by krzysiek1507** [comment]
I mean: `Isolated Engine` [here](http://edgeapi.rubyonrails.org/classes/Rails/Engine.html)

**Comment by nickcharlton** [comment]
Oh, I see. It’s been a while since I’ve done such a thing.

It sounds like it’s something we should consider, so if you’d be up to contributing a PR, that’d be great.

**Comment by nickcharlton** [comment]
I'm going to close this issue as the last activity was a while ago and this is not something that's come up often.
