### ISSUE TITLE
Name Error with generate dashboard command

### ISSUE THREAD

**Issue by compostbrain** [thoughtbot/administrate#949]
I created a test app with Rails 5.1.2 and ruby 2.4.1. Followed the doc instructions and when I generated the administrate:install it created `app/controllers/admin/application_controller.rb` but did nothing else then I tried generating a dashboard and got this error: 
``` rails generate administrate:dashboard Foo
Running via Spring preloader in process 9657
/Users/compost/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/administrate-8b51445b9251/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant Foo (NameError)```

**Comment by nickcharlton** [comment]
Did you create a model before running the install command? This has commonly caused such helpful errors!

**Comment by nickcharlton** [comment]
I'm going to close this as it's old and with no recent responses.
