### ISSUE TITLE
Feature Request: has_many relationships in edit page are clickable and can scope

### ISSUE THREAD

**Issue by simonnim** [thoughtbot/administrate#950]
I would like to request a feature. Currently going to the edit page allows you to see your Has_many relationships, however, clicking on them does nothing.

I think allowing you to click on the object should go to scope has_many object.

**Comment by nickcharlton** [comment]
This sounds like a good idea!

Would you be interested in contributing a PR for this?

**Comment by simonnim** [comment]
Sure!

**Comment by nickcharlton** [comment]
I'm not sure if we ever did do this, but I'm going to close it because it's been a long time since the last activity.
