### ISSUE TITLE
has_one with options class_name burns in agony

### ISSUE THREAD

**Issue by dan-ding** [thoughtbot/administrate#951]
```ruby
class PhoneDashboard < Administrate::BaseDashboard
ATTRIBUTE_TYPES = {
  owner: Field::HasOne,
  ...
} ...

class OwnerDashboard < Administrate::BaseDashboard
ATTRIBUTE_TYPES = {
  account: Field::HasOne,
  cat: Field::HasOne.with_options(class_name: 'Pet')
  ...
}...
```

trying to edit Phone dies with a message such as:

> uninitialized constant CatDashboard
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/resource_resolver.rb:8:in 'const_get'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/resource_resolver.rb:8:in 'dashboard_class'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/field/has_one.rb:9:in 'initialize'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/field/deferred.rb:15:in 'new'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/field/deferred.rb:15:in 'new'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/page/base.rb:23:in 'attribute_field'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/page/form.rb:15:in 'block in attributes'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/page/form.rb:14:in 'map'
/stark_tower/gems/administrate-8b51445b9251/lib/administrate/page/form.rb:14:in 'attributes'
/stark_tower/gems/administrate-8b51445b9251/app/views/fields/has_one/_form.html.erb:17:in 'block in app_views_fields_has_one__form_html_erb'
...
>

**Comment by nickcharlton** [comment]
* Which version of administrate do you see this with?
* What do your models look like?
* Could you provide an example project where this happens?

**Comment by dan-ding** [comment]
version - 8.0/8.1
models - have seen no common pattern -- has_one straight, has_one through
example - no, but should be reproducible with the above snippets.

**Comment by dan-ding** [comment]
The issue seems to be in the initialize method of administrate/field/has_one.rb
```ruby
      def initialize(attribute, data, page, options = {})
        resolver = Administrate::ResourceResolver.new("admin/#{attribute}")
        @nested_form = Administrate::Page::Form.new(
          resolver.dashboard_class.new,
          data || resolver.resource_class.new,
        )

        super
      end
```
with the first dashboard snippet, this initialize is called like with params similar to:
('cat', #<Pet...>, :form, {:class_name=>"Pet", :resource=>#<Owner...>}
Which makes it look for a CatDashboard with the ResourceResolver.new method and there is no Cat -- it's a Pet

The model we can suppose would be something like:
```ruby
class Owner < ApplicationRecord
  has_one :cat, class_name: 'Pet'
```

This seems to fix the issue, however the nested forms are a bit ugly and don't end up labelled correctly (that is they get labelled "Pet", not "Cat", when editing).
```ruby
      def initialize(attribute, data, page, options = {})
        super
        cain = (options[:class_name] || attribute).downcase
        resolver = Administrate::ResourceResolver.new("admin/#{cain}")
        @nested_form = Administrate::Page::Form.new(
          resolver.dashboard_class.new,
          data || resolver.resource_class.new,
        )
      end
```

**Comment by dan-ding** [comment]
Thoughts?

**Comment by tkbky** [comment]
I'm having this issue too with `0.8.1`.

Fix suggested by @dan-ding works! Another *sketchy* improvement for it to support **namespace resource** could be done like so:

```ruby
cain = (options[:class_name] || attribute.to_s).underscore
```

**Comment by dsolomadin** [comment]
Hi guys, as a temporary fix you can do this:
```
associated_class_name =
  options.fetch(:class_name, attribute.to_s.singularize.camelcase)
resolver = Administrate::ResourceResolver.new("admin/#{associated_class_name}")
```

You would also need to change `permitted_attribute`  method, otherwise you won't be able save HasOne form.

I'm thinking that I could refactor the way we initialize HasOne relationship and make use of `field/associative.rb`.

Unless you already have a PR on this, I could take a look next week.

**Comment by andmej** [comment]
+1

**Comment by kesha-antonov** [comment]
+1

**Comment by kesha-antonov** [comment]
@kavehsajjadi
@dsolomadin 

Guys do you plan to do PR?

**Comment by znvPredatoR** [comment]
Working on this, should have a PR on today/Monday.
