### ISSUE TITLE
Time zone select?

### ISSUE THREAD

**Issue by zachrose** [thoughtbot/administrate#952]
I have a field on class inheriting from ActiveRecord called "time_zone" that persists as a string.

Rails has a time zone form helper that works like so: http://railscasts.com/episodes/106-time-zones-revised?view=asciicast

How might I go about getting the select menu provided by the form helper into my Administrate dashboard?

**Comment by nickcharlton** [comment]
Yeah, you should create a new field. We’ve been working on adding a few more `Date` and `DateTime` fields which should come soon, but it sounds like you’ve got a special case.

I’d recommend basing something of what @pustomytnyk linked to.

I’m going to close this for now, but please open another issue if you need some specific help with your implementation.
