### ISSUE TITLE
run rails generate administrate:install

### ISSUE THREAD

**Issue by kfn8dkodemonkey** [thoughtbot/administrate#953]
I am trying to run this on new rails install using PostgreSQL as my DB on Rails 5.1.2.

I start out with:
rails new proj_name --database=postgesql
then I add the gem to my gem file
then run rake db:create:all to create my DB
then run bundle install 
then run rails generate administrate:install
at this point, my terminal just hangs for 5 min and nothing happens.

So I removed my application and started over, however, this time I did not run rake db:create:all to create my DB I went straight into the run rails generate administrate:install Now it will run but I have not routed...

What am I doing wrong or missing?

**Comment by nickcharlton** [comment]
Do you get any error message at all when you do this?

Have you found it does the same thing if you first create a model?

**Comment by kfn8dkodemonkey** [comment]
There was no error message the terminal just hung and finally I did ctrl z
to kill it. Have not first created a model. I will try that today and let
you know.

**Comment by kfn8dkodemonkey** [comment]
Okay so I was thinking maybe it was something other than Administrate. So I ran rails_admin and it would not install either. did a search and found that spring may have something to do with this. so I stopped spring and then gave it a try. It worked.. kind of. Ran rails generate administrate:install and it did set up the app/controllers/admin/application_controller.rb but did not set the routes.

**Comment by nickcharlton** [comment]
Oh, curious.

I’ve seen issues with `spring` not finding generators previously. It seems sometimes that `spring` doesn’t pick up the presence of those files. I don’t use `spring` on projects myself, but I feel that we shouldn’t stop others from being able to use it.

Which version of Ruby and Rails are you working with? Are you installing the current version of administrate?

**Comment by kfn8dkodemonkey** [comment]
I am using ruby 2.3.1 and rails 5.1.2. I can remove spring and give it a
try if you think that would fix things.

**Comment by kfn8dkodemonkey** [comment]
So I rand it with out spring and it just installs the controller, not the routes.

**Comment by nickcharlton** [comment]
Do you have any models?

**Comment by kfn8dkodemonkey** [comment]
No this is just a clean install have not ran or installed anything else.

**Comment by kfn8dkodemonkey** [comment]
I am following the githun repo for this.

**Comment by bepinekim** [comment]
I also get the same error messages and doing nothing above this.

In the first try, rails version was 5.1.2 but I downgraded below this.
bash-4.2$ rails -v
Rails 5.0.4
bash-4.2$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
bash-4.2$ rails generate administrate:install
WARNING: Unable to generate a dashboard for ApplicationRecord.
         It is not connected to a database table.
         Make sure your database migrations are up to date.
      create  app/controllers/admin/application_controller.rb

I can create a table with rake:migrate after scalffolding.
I don't know what can I do to solve the warning.

**Comment by nickcharlton** [comment]
I'd expect you to see no dashboards if there's no models, as there's nothing to generate. What happens if you create a model first?

**Comment by kfn8dkodemonkey** [comment]
So created a model and here is what I got:
rails g model Administrate
      invoke  active_record
The name 'Administrate' is either already used in your application or reserved by Ruby on Rails. Please choose an alternative and run this generator again.

**Comment by bepinekim** [comment]
Thank you so much.
I solved the problem after I got your advice.
I did below this and I could generate administrate without any problem.
　⇨　bundle exec rails g model user name:string body:text email:string

**Comment by nickcharlton** [comment]
@kfn8dkodemonkey You'd not be able to create a model called `Administrate` as that constant will exist inside your Rails app. Try creating something like `User` which won't already exist.

**Comment by kfn8dkodemonkey** [comment]
okay just did not see it in the list of rails reserve words. I ran a user model. Looks like it is working now.
Is this just something that is assumed in the how to that I would know need?  I did not have to create any models first to use rails_admin.

**Comment by nickcharlton** [comment]
If you're running the generator when there's no models, it'll pretty much do nothing. Apart from bootstrapping the administrate controllers, there's nothing else it can really do.

If you then add a model, you can generate a dashboard for that new model.

The most common use case is adding administrate _after_ you've got a bunch of models and there the initial generator run can do a bunch of things to get you going.

**Comment by andybluey** [comment]
I got the same problem and running "spring stop" in the command line worked for me.

**Comment by nickcharlton** [comment]
I'm going to close this issue as the last activity was a while ago and it seems to be mostly application specific issues.
