### ISSUE TITLE
how to disable nested forms or restrict to a certain number of levels

### ISSUE THREAD

**Issue by dan-ding** [thoughtbot/administrate#954]
nested forms can get ugly, quickly, particularly with has_one. If there isn't a way to disable generating nested forms, perhaps there should be one.

alternatively, a way to restrict how deep nested forms will go.

**Comment by nickcharlton** [comment]
Do you mean inside the generator? So if you're creating a deep structure, it could ask what you'd like to do?

My assumption would be that you'd just delete the offending areas after you'd run the otherwise simple generator. What do you think?

**Comment by nickcharlton** [comment]
I'm going to close this as it's been open for a long time without a response — I think the best answer right now is to just delete them and if that's hard going I have questions about how nested your models are!
