### ISSUE TITLE
Couldn't find the New button

### ISSUE THREAD

**Issue by ianzitow** [thoughtbot/administrate#958]
So, I created a new Rails 5.1 project with the --api option and then installed Administrate gem. However, for all resources, there's no way to create items, because the button is not being placed. What's wrong?

**Comment by banotraore** [comment]
Hi I'm facing the same issue. 
I created a regular rails app and I got all the regular buttons (new, edit, destroys).
But if I created a rails api only I only got the destroy button.

Did someone faced the same issue(s) or did you found a solution @ianzitow ?

<img width="1428" alt="Capture d’écran 2021-03-15 à 20 19 30" src="https://user-images.githubusercontent.com/47910631/111209679-9edc6a80-85cc-11eb-8c46-1640b3fa44ba.png">
<img width="1050" alt="Capture d’écran 2021-03-15 à 20 19 41" src="https://user-images.githubusercontent.com/47910631/111209687-a0a62e00-85cc-11eb-9e29-b564b5f8124f.png">
<img width="1417" alt="Capture d’écran 2021-03-15 à 20 21 00" src="https://user-images.githubusercontent.com/47910631/111209689-a13ec480-85cc-11eb-982f-ea4d15eacceb.png">

**Comment by pablobm** [comment]
I think that API apps don't provide `:new` and `:edit` routes by default. I'm not 100% sure but, if this is the case, then it may be solved by explicitly saying `resources :foos, only: [:index, :show, :new, :create, :edit, :update, :destroy]` for each separate route under the `:admin` namespace. See that I'm explicitly adding `:new` and `:edit`.

**Comment by AkaishiHayato** [comment]
@pablobm 
Thanks to you we were able to solve the problem!!💕

**Comment by pablobm** [comment]
For future readers, it may be useful to read the documentation on Rails API-only apps: https://guides.rubyonrails.org/api_app.html, in particular the [section on configuration](https://guides.rubyonrails.org/api_app.html#the-basic-configuration).

This is one of the things that happens when you generate an API-only app, according to the docs:

> Make `ApplicationController` inherit from `ActionController::API` instead of `ActionController::Base`. As with middleware, this will leave out any Action Controller modules that provide functionalities primarily used by browser applications.

So you may be able to fix this issue by making sure that Admin controllers inherit from `ActionController::Base`
