### ISSUE TITLE
password field?

### ISSUE THREAD

**Issue by kwerle** [thoughtbot/administrate#959]
Seems like there is no password field type.  I'm just looking for a text field where the input type is password and the display when showing is 8 *'s.

If that seems reasonable I'm happy to do a pull request.

**Comment by nickcharlton** [comment]
There's a third-party plugin which provides a password field: https://github.com/DisruptiveAngels/administrate-field-password I'd recommend giving that a go!

**Comment by kwerle** [comment]
Looks good!  Seems like you could integrate it - or at least add a note in the docs.

In any case, thank you for your work!

**Comment by vedmant** [comment]
That's weird that password field is not included in the package by default, looks like raw and incomplete package.

**Comment by caitlinpb** [comment]
Looks like this has since been integrated - works for me using Field::Password without the extra gem
