### ISSUE TITLE
Dashboard file still created if errors occur

### ISSUE THREAD

**Issue by lun4i** [thoughtbot/administrate#960]
Tiny issue for you guys =)
Situation:
after
`rails g administrate:dashboard SomeModel`
I had an _'uninitialized constant SomeModel'_ error
However, it was my fault, becouse i named my model like this: 'Somemodel'

The dashboard files were created no mater what errors occurred in generator, IMO this should be fixed

**Comment by nickcharlton** [comment]
That sounds like a good idea. Do you think you'd be able to contribute a PR for this?

**Comment by lun4i** [comment]
@nickcharlton Sounds great! I think I'll handle this

**Comment by nickcharlton** [comment]
Wonderful! I look forward to seeing your PR!

**Comment by das3in** [comment]
Took a stab at this as my first non-documentation open source contribution - wrote about it in the commit message but was having some trouble with the test. Unsure about how to properly test for raising a `NameError`

**Comment by nickcharlton** [comment]
Hi @das3in! That's off to a good start!

You should be able to do something like:

```ruby
expect { ... }.to raise_error(NameError)
```

Or, if there's a message with it:

```ruby
expect { ... }.to raise_error(NameError, "The name was invalid…")
```

**Comment by das3in** [comment]
@nickcharlton - Yeah I thought that'd work too and it's still not passing that test. The spec is in the PR I linked if you could see if maybe I was doing something else wrong.

**Comment by nickcharlton** [comment]
Ah, I see what you need to do. You need to wrap your `run_generator` call around the `expect` block so that it can catch the exception, a bit like this:

```ruby
expect do
  run_generator ["invalid_model"]
end.to raise_error(NameError)
```

**Comment by purinkle** [comment]
@lun4i, is this still an issue for you?
