### ISSUE TITLE
Unable to localize model name in 'create' button

### ISSUE THREAD

**Issue by rozhok** [thoughtbot/administrate#963]
Hey, I want to localize to only action name ('create') but also model name in the button caption.
Now it looks like
![image](https://user-images.githubusercontent.com/1721631/29187269-c8718a6c-7e17-11e7-836e-3fdbde7e3ae8.png)
("create pet")

According to this template
https://github.com/thoughtbot/administrate/blob/736266dd81f0a1b5ded6a268b93bd7de5c6c1a6f/app/views/administrate/application/index.html.erb#L45
Model name cannot be localized:
```erb
    <%= link_to(
      "#{t("administrate.actions.new")} #{page.resource_name.titleize.downcase}",
      [:new, namespace, page.resource_path],
      class: "button",
    ) if valid_action? :new %>
```

**Comment by nickcharlton** [comment]
Do you think we should add a translation option for the whole string, or a way to override when you can't reliably get this from the `resource_name`?

**Comment by rozhok** [comment]
I'd like to translate the whole string and fallback to default `resource_name` if translation isn't provided. It's completely up to you.

**Comment by nickcharlton** [comment]
Would you be able to open a PR for that?

My main concern with expanding localisations is the burden it puts on everyone for keeping up with it, but in this case it seems important.

**Comment by rozhok** [comment]
I've already launched my project where I've used administrate, but I'm planning to use it in near future, so possibly yes.

**Comment by tysongach** [comment]
Is this a duplicate of https://github.com/thoughtbot/administrate/issues/699, which has a potential solution by way of https://github.com/thoughtbot/administrate/pull/707?

**Comment by rozhok** [comment]
Yes, exactly.
