### ISSUE TITLE
Using Administrate with an API app

### ISSUE THREAD

**Issue by lesliev** [thoughtbot/administrate#965]
I know the docs say to set `config.api_only = false` in `config/application.rb` but for those that want to keep API mode turned on, I was able to get `Administrate` to properly add and update records with the following workarounds:

1. Add these to `config/application.rb`
```
    # Enable Flash, Cookies, MethodOverride for Administrate Gem
    config.middleware.use ActionDispatch::Flash
    config.session_store :cookie_store
    config.middleware.use ActionDispatch::Cookies
    config.middleware.use ActionDispatch::Session::CookieStore, config.session_options
    config.middleware.use ::Rack::MethodOverride
```
2. Make sure routes in `routes.rb` generate routes for all 7 controller actions. Example:
```
  namespace :admin do
    %i(
      attachments
      assets
      posts
    ).each do |name|
      resources name, only: %i(index show new create edit update destroy)
    end
```

**Comment by oyeanuj** [comment]
@lesliev Thanks for sharing your solution! Wouldn't enabling the extra middleware impact performance for the APIs? Wondering if there are any other possible solution.

**Comment by lesliev** [comment]
@oyeanuj not that I know of - you need these middlewares to work properly with forms. Perhaps there's a way to exclude them for the API paths: https://stackoverflow.com/questions/920719/how-do-i-use-a-rack-middleware-only-for-certain-paths - but those replies are pretty old so I'm not sure it's possible any more.

**Comment by oyeanuj** [comment]
@lesliev Thanks for the quick response!

@nickcharlton Do you recommend any other way to integrate this library with API-only Rails apps?

**Comment by michaelfich** [comment]
@lesliev Thank you very much for this!  It was very helpful.

I was having an issue with the routing, but I'm curious why certain RESTful routes stopped working without explicitly specifying them as you did in step #2.  Do you happen to know why?

**Comment by lesliev** [comment]
@michaelfich because of this: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb#L1142

I assume it's because the New and Edit actions are typically not needed in an API app because all New does is show an empty form, and Edit will also show a form with data that a front-end will likely have retrieved with a Show action. The commit message isn't much help.

**Comment by michaelfich** [comment]
@lesliev ahh very interesting.  thank you!

**Comment by nickcharlton** [comment]
Nice! This looks good!

@lesliev Do you think you'd be able to contribute a docs PR for this?

@oyeanuj This is probably the best I've seen yet, but I've not tried to do it myself.

**Comment by oyeanuj** [comment]
@lesliev @nickcharlton On trying the above, I am getting the following errors at `rails generate administrate:install` step:
```rb
→ rails generate administrate:install
Running via Spring preloader in process 64286
   identical  app/controllers/admin/application_controller.rb
/Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `const_get': uninitialized constant Attachment (NameError)
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:111:in `klass'
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/dashboard_generator.rb:47:in `attributes'
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/administrate-0.8.1/lib/generators/administrate/dashboard/templates/dashboard.rb.erb:11:in `template'
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/2.4.0/erb.rb:896:in `eval'
	from /Users/anuj/.rbenv/versions/2.4.2/lib/ruby/2.4.0/erb.rb:896:in `result'
```

Am I missing some middleware or configuration?

**Comment by nickcharlton** [comment]
Hi @oyeanuj!

Could you try without `spring`? It's possible that it's not reloading correctly (it does this sometimes!).

Your main error is: `uninitialized constant Attachment (NameError)`, which suggests that your `Attachment` model isn't loaded, or doesn't exist. Could you check that that's all there?

**Comment by oyeanuj** [comment]
@nickcharlton thank you for taking a look! From the docs, I didn't realize that I was supposed to first create an `Attachment` model - I thought `administrate` would do that. 

Could you provide more details, as that clearly might be the issue?

**Comment by nickcharlton** [comment]
You do need to have a model before Administrate can build and load a Dashboard for it as it pulls attributes out of that model.

If you're still having an issue after you've done that, could you create a new issue with a stacktrace so we can take a closer look at it?

**Comment by oyeanuj** [comment]
@nickcharlton Sorry for the false alarm, I got myself all confused. I took the code from the top comment, not realizing that the routes code there referred to the model that @lesliev had in his app. I assumed it was something that `administrate` needed - my bad, sorry for wasting your time there.

Moving forward though, I ran into two things worth bringing up:

1. I encountered the following error when going to `/admin` route:
```sh
ArgumentError - unknown firstpos: NilClass:
  actionpack (5.1.4) lib/action_dispatch/journey/gtg/builder.rb:99:in `firstpos'
  actionpack (5.1.4) lib/action_dispatch/journey/gtg/builder.rb:22:in `transition_table'
```
I fixed it as per [the solution mentioned here on SO](https://stackoverflow.com/questions/44465118/rails-5-1-unknown-firstpos-nilclass-issue-reloading-application) but wanted to bring it up since the solution seems like it'd often be a conflict with other people's code.

2. After fixing that problem, when I go to `/admin`, I see a routing error for route not existing. `/admin/posts` works thought. But it was unclear from the 'Getting Started' guide, if I should expect to see a admin homepage or not? Could you clarify? (I'd be happy to PR to the docs if needed as well).

**Comment by nickcharlton** [comment]
Ooh, interesting! I've not yet seen the `unknown firstpos` anywhere else.

When you go to `/admin`, you should see the "first" Dashboard. [You can see that on the prototype app here](http://administrate-prototype.herokuapp.com/admin)

**Comment by oyeanuj** [comment]
@nickcharlton Ah, I now see the [root route added here](https://github.com/thoughtbot/administrate/blob/master/spec/example_app/config/routes.rb#L15). Should this be part of the 'Getting Started' instructions?

Also, created a separate ticket for the `unknown firstpos` issue at #986.

Thanks for all your help!

**Comment by lesliev** [comment]
@nickcharlton I'd love to contribute to the docs but I'm totally snowed under at the moment, so I don't know when I'll get to it. Sorry!

**Comment by nickcharlton** [comment]
I'm going to close this as we solve the intention of this issue and got that merged a while back.
