### ISSUE TITLE
STI model names not being rendered correctly

### ISSUE THREAD

**Issue by ghost** [thoughtbot/administrate#968]
I'm having a problem with the dashboard and two of my models. One of the models is the default User model generated by Devise, and the other one is a simple STI model which, at the moment, doesn't have any custom functionality.

Below are the models code, as you can see they're defaults and nothing has been added yet. Schema wise, only the User model has a custom :type field which is required for STI.

_User Model_
```
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end
```
_AdminUser Model_
```
class AdminUser < User
end
```
The dashboard works 'fine', the only problem is that on the headers, or any text as a matter of fact, that were supposed to write Users or AdminUsers it says "User", I've added a picture so this makes a bit more sense.

![Dashboard](https://i.stack.imgur.com/HV51H.png)

I did notice the the urls were fine, for example the Users page url is /admin/users and the AdminUsers page url is /admin/admin_users, and so I can't really understand where this problem could be coming from.

**Comment by nickcharlton** [comment]
We've been seeing a couple of problems with STI models, and whilst we don't have a fix yet, does these help you?

https://github.com/thoughtbot/administrate/issues/703#issuecomment-329980874
https://github.com/thoughtbot/administrate/issues/951#issuecomment-328384743

**Comment by slickepinne** [comment]
Although the user left, I may have a solution for handling STI (devise) user model names. Just change the `devise.en.yml`:
```
models:
 user: User 
 admin_user: Admin User
...
```

**Comment by nickcharlton** [comment]
I'm going to close this as it's been a long time and there's a potential solution above. Please open a new issue if you see the same thing again, though.
