### ISSUE TITLE
Custom view for a specific action not overriding default

### ISSUE THREAD

**Issue by michaelfich** [thoughtbot/administrate#970]
Hi there,

I just started using administrate for the first time today and it's been a pleasure so far!  Very nice alternative to the other admin panel rails engines options out there.

I ran into an issue that I wanted to bring to your attention, or perhaps get some help with if I've done something wrong.

I've tried to add a custom view for one specific action associated with with one admin dashboard called `Product`.

I ran the generator as follows:

```
rails generate administrate:views:show Product
```

It generated the view just fine, however when I make an edit to the page, and then view it in my browser, it is still showing the original and not my changes.

Is there any steps I am missing other than using the generator to create the view in order to use the new template?

**Comment by nickcharlton** [comment]
Oh, that doesn't sound right.

My first thought is that there's some load order issue going on, but that's probably not right. Would you be able to provide a sample app where you can isolate it?

**Comment by 8vius** [comment]
Also having this problem, seems it's not solved.

**Comment by jkcchan** [comment]
Having this issue too

**Comment by purinkle** [comment]
@michaelfich, is this still an issue for you?

**Comment by michaelfich** [comment]
@purinkle This was an issue from a couple of years ago but I haven't checked back recently.  It can be closed if it's not an issue for others.
