### ISSUE TITLE
Order option for belongs_to field doesn't work consistently

### ISSUE THREAD

**Issue by kcorrigan86** [thoughtbot/administrate#974]
I tried using the code from [this commit](https://github.com/thoughtbot/administrate/commit/190cfe5438a56a3021774c9bf98a05dabffba0e1) (not released yet) in a custom field and found that it didn't always work. If I hit 'New Customer', then the back button, then 'New Customer' again, for example, I got the unordered dropdown the second time. To make it work every time, I replaced ```order = options.delete(:order)``` with ```order = options[:order]``` (from the candidate_resources method in lib/administrate/field/belongs_to.rb)

**Comment by kcorrigan86** [comment]
I gave it a try, but I had a hard time setting up a test that would fail with the current code and pass after the change. I may have some more time to look at it next week.

**Comment by nickcharlton** [comment]
How did you get on with this? Is there anything I can do to help?

**Comment by kcorrigan86** [comment]
Sorry, didn't have a chance to look at this again until now. It turns out I was using a pretty old version of administrate. Once I updated to the latest version, it fixed the problem with the order option on the belongs_to field.
