### ISSUE TITLE
has_and_belongs_to_many association

### ISSUE THREAD

**Issue by nishant1890** [thoughtbot/administrate#978]
How can one setup *has_and_belongs_to_many* linkage in two model in administrate

**Comment by nickcharlton** [comment]
Hi @nishant1890!

You should be able to create dashboards for your two models in the normal way: http://administrate-prototype.herokuapp.com/getting_started

Here's two issues which talk about HABTM relationships which help you: #124, #259.

I think we could definitely do with some improved documentation which talks about this. I'd love to see a PR relating to it!

**Comment by nickcharlton** [comment]
I'm going to close this as it's been inactive for a while. Please open another issue if you're still having problems with this.
