### ISSUE TITLE
Documentation doesn't describe views customisation

### ISSUE THREAD

**Issue by deashay** [thoughtbot/administrate#983]
Hi, 
I've checked your gem, looks really nice, but I've just lost like 15 minutes trying to find out how can I customise edit page for my model. Could you please add note to the section "Customising Page Views" that you have to actually modify ModelDashboard in order to change displayed fields? It was really frustrating not being able to do such a trivial thing. It's not really described anywhere, people in google just talk about FORM_ATTRIBUTES(and adding those to controller doesn't work) and stuff in dashboard, but no one seems to care that connection dashboard-model_views isn't really the first thing that comes to ones mind. Dashboard sounds like some additional panel, independent from standard model actions, so I wasn't even looking at it. Please save other people some time in the future : )

**Comment by nickcharlton** [comment]
Hi @deashay! Would you be up for contributing a PR for this?

**Comment by deashay** [comment]
sure, will do that tomorrow : )

**Comment by nickcharlton** [comment]
I'm going to close this as we now have this in [Customising Page Views](https://administrate-demo.herokuapp.com/customizing_page_views).
