### ISSUE TITLE
ArgumentError - unknown firstpos: NilClass:

### ISSUE THREAD

**Issue by oyeanuj** [thoughtbot/administrate#986]
Hi @nickcharlton, moving our conversation from [the comment](https://github.com/thoughtbot/administrate/issues/965#issuecomment-332594460) in #965 to a separate issue.

I encountered the following error when going to `/admin` route:
```sh
ArgumentError - unknown firstpos: NilClass:
  actionpack (5.1.4) lib/action_dispatch/journey/gtg/builder.rb:99:in `firstpos'
  actionpack (5.1.4) lib/action_dispatch/journey/gtg/builder.rb:22:in `transition_table'
```

I fixed it as per [the solution mentioned here on SO](https://stackoverflow.com/questions/44465118/rails-5-1-unknown-firstpos-nilclass-issue-reloading-application) but wanted to bring it up since the solution seems like it'd often be a conflict with other people's code, and SO solution seems like a band-aid.

FWIW, I am trying to get this to work in a Rails 5.1 API-only app.

**Comment by nickcharlton** [comment]
Thank you for documenting this so far and your solution to it. I hope this helps some people!

I'm not really sure what to do about this issue, so if you're reading this and have seen something similar and have come up with a different solution, I'd like to hear about it!

**Comment by devpolish** [comment]
@cmendla Thank you! I was struggling with this issue and, after removing Active Storage from my application.rb everything got to work again.

**Comment by pablobm** [comment]
I'm not sure that this is an issue any more. I'm going to close, but please let us know here if you think otherwise.
