### ISSUE TITLE
Pagination broken on `show` pages

### ISSUE THREAD

**Issue by pablobm** [thoughtbot/administrate#989]
### Reproduction

Given resource classes `R` and `A` such that "`R` has_many `A`".
Given `r`, an instance of `R`, with many associated instances of `A`, enough to trigger pagination.

1. Visit the `show` page for `r`.
2. Press "Next >" to see the next page of instances of `A`.

An exception `ActionController::UnpermittedParameters` will be raised, complaining of an unpermitted parameter `as`.

### The problem

When the ability to paginate within `show` pages was introduced (#736), a bug slipped in. Pagination would only work if the associated resource class `A` had the name `Order`. The value `:orders` was hard-coded as a valid param name, making the relevant spec pass but any other usage broken.

Also see this conversation: https://github.com/thoughtbot/administrate/pull/736#pullrequestreview-65906248

### Possible fix

Merging https://github.com/thoughtbot/administrate/pull/945 would fix this, so I suggest that we just wait until then.

**Comment by jamiefolsom** [comment]
Any update on this issue? Thanks!

**Comment by pablobm** [comment]
@jamiefolsom Could you please test now? #945 has just been merged, which I think should provide a fix.

**Comment by pablobm** [comment]
@jamiefolsom - Re: NestedHasMany, I just had a look. It has custom forms that are not compatible with the new way of handling things. I fixed some of it, but came across a completely different bug after that. I will continue looking into it next Friday, as well as the issue you mention about unpermitted params.

**Comment by jamiefolsom** [comment]
Great, thanks @pablobm!

**Comment by pablobm** [comment]
For reference, these two PRs are steps towards solving these problems:

* https://github.com/nickcharlton/administrate-field-nested_has_many/pull/18
* https://github.com/thoughtbot/administrate/pull/1176

**Comment by jonsgreen** [comment]
Just wondering if there has been progress in figuring out the unpermitted param issue for a has_many association on show page view?

**Comment by pablobm** [comment]
@jonsgreen: what issue are you having? What version of Administrate? I just tried the reproduction above and it works for me.

**Comment by jonsgreen** [comment]
@pablobm My apologies, it seems like somehow I must not have tested on 0.11.0 in the end. This does appear to be working.

**Comment by jonsgreen** [comment]
@pablobm I think I figured out what has been giving me problems. Sometimes we have a has_many association listed on a show page that is not in the COLLECTION_ATTRIBUTES because we don't want them listed on the index view. That breaks the pagination. I can get around this by overriding `#association_includes` in the dashboard and adding the additional missing associations to super. Is that advisable? Do you recommend something else?

**Comment by jonsgreen** [comment]
@pablobm overriding association_includes did have some unfortunate side-effects. It added includes to the database queries on the index view and that loaded so many objects that we started getting memory problems on Heroku. We don't need those objects on the index views. I will probably need to monkey patch this or live with the pagination not working on the show page. I would be willing to help with a fix but don't know enough about the code base so I would want some input on a direction for a pull request that would be more likely to be accepted.

**Comment by jonsgreen** [comment]
Hey @pablobm thanks for looking back into this. All you would need to do to reproduce the problems is this: 
```
@@ -21,7 +21,7 @@ class CustomerDashboard < Administrate::BaseDashboard
     password: Field::Password,
   }

-  COLLECTION_ATTRIBUTES = ATTRIBUTE_TYPES.keys - %i[created_at updated_at]
+  COLLECTION_ATTRIBUTES = ATTRIBUTE_TYPES.keys - %i[created_at updated_at orders]
   SHOW_PAGE_ATTRIBUTES = ATTRIBUTE_TYPES.keys - [:name]
   FORM_ATTRIBUTES = [
     :name,
```
and then on a customer show page you try to use the pagination. Basically the issue is when you don't want to show a has many in the index view but you do want it on the show view. 

We found a hack to get around this that I am happy to share though I suspect you might have a cleaner solution if you decide it is something that should be fixed in the main codebase.

**Comment by pablobm** [comment]
@jonsgreen - Thank you for the reproduction. It was really useful. Would you be able to test out the branch `fix-multiple-association-pagination` and see if it fixes your problems? See https://github.com/thoughtbot/administrate/pull/1268 for more info.

**Comment by pablobm** [comment]
Well, I think we can close this one now. Thank you all for your feedback!

**Comment by HHGB12** [comment]
Hi i did that Screenshots

 to know if someone Has succeeded to fix it.
using `gem "administrate-field-nested_has_many"` Works perfectly just this internal issue of pagination.

I think that https://github.com/nickcharlton/administrate-field-nested_has_many/pull/19 will fix it.
But still working on. Is there a temporary tricks or something that I misunderstood ?
 
If I add this line to the concern dashboard pagination is broken .
`tasks: Field::NestedHasMany.with_options(skip: :project,limit: 3, sort_by: :id),`

Then if I use the initial Field syntax (and give up the Nested form...) i got :
`tasks: Field::HasMany.with_options(skip: :project),`

![capture d ecran 2019-01-12 a 19 42 34](https://user-images.githubusercontent.com/24680535/51077146-839b0b00-16a2-11e9-9bca-91b2765a680f.jpg)
![capture d ecran 2019-01-12 a 19 43 40](https://user-images.githubusercontent.com/24680535/51077147-839b0b00-16a2-11e9-8cf4-9c24087870ec.jpg)
