### ISSUE TITLE
Search no longer retuning partial match results

### ISSUE THREAD

**Issue by complinggirl** [thoughtbot/administrate#997]
Forgive me if this has been raised elsewhere (or if this is not the correct forum)
We just upgraded to the most recent version of the gem but the behavior of search has changed. 
The following test (which correctly represents the UI behavior) used to pass but now fails on the second expectation.

```ruby
query = 'some experience' 
fill_in :search, with: query
submit_search
expect(page).to have_content('some experience' )
expect(page).to have_content('extensive experience')
```

**Comment by nickcharlton** [comment]
This is definitely the right place, and I wouldn't worry about raising things again!

Would you be able to provide a cut down example of how this is happening?

**Comment by complinggirl** [comment]
Hi @nickcharlton,

The problem that we encountered was a change in the behavior of the search feature. 

In the previous version, given a model with a text field "reason", a search for 'Insufficient experience' in that dashboard would return records with 'Insufficient experience' and 'Wrong experience'.  Since the update, 'Insufficient experience'  returns only records with 'Insufficient experience'. 

So the behavior has changed for partial matches. 

This is curious because our tests were based on your examples
https://github.com/thoughtbot/administrate/blob/master/spec/features/search_spec.rb
so I don't understand why your tests would still be passing but not ours.

I was away for most of October but my lead resolved the problem by modifying the tests for the new behavior but the previous search function was decidedly more powerful. 

Thanks for any insight you may have

**Comment by nickcharlton** [comment]
Ah, bummer! That's not very good.

Do you know which version you were using before you upgraded to `0.8.1`? It'd be good to track down where this stopped working.

**Comment by ACPK** [comment]
@complinggirl - Is this still an issue? I'm also having search issues.

**Comment by pablobm** [comment]
Closing due to lack of feedback. Happy to reopen if someone else experiences this.
